### ISSUE TITLE
Confusion between edge identifier of a shortcut and path termination of a path on the contracted graph

### ISSUE THREAD

**Issue by iamrohith94** [pgRouting/pgrouting#1003]
Let us consider the following graph to demonstrate the issue.

```
SELECT id, source, target, cost, reverse_cost FROM edge_table WHERE id = 2 or id = 3;
 id | source | target | cost | reverse_cost 
-----+--------+--------+------+--------------
   2 |      2 |      3 |   -1 |            1
   3 |      3 |      4 |   -1 |            1
(2 rows)

```
On applying linear contraction to the above graph, we get the following result.
```
SELECT * FROM pgr_contractGraph(
    'SELECT id, source, target, cost, reverse_cost FROM edge_table
    WHERE id = 2 OR id = 3',
    ARRAY[2]::integer[], 1, ARRAY[]::BIGINT[], true);
 seq | type | id | contracted_vertices | source | target | cost
-----+------+----+---------------------+--------+--------+------
   1 | e    | -1 | {3}                 |      4 |      2 |    2
``` 
Let us store this result in a separate table.
```
SELECT * INTO contraction_results FROM pgr_contractGraph(
    'SELECT id, source, target, cost, reverse_cost FROM edge_table
    WHERE id = 2 OR id = 3',
    ARRAY[2]::integer[], 1, ARRAY[]::BIGINT[], true);
```

By using the above result of contraction, we can generate the contracted graph in **three** steps. Let us store the contracted graph in a separate Table named **contracted_edge_table**.
1. Copy the original graph table
```
SELECT * INTO contracted_edge_table FROM edge_table WHERE id = 2 OR id = 3;
```
2. Removal of the contracted vertices
```
DELETE FROM contracted_edge_table WHERE source = ANY(SELECT unnest(contracted_vertices) FROM contraction_results) OR target = ANY(SELECT unnest(contracted_vertices) FROM contraction_results);
```
3. Addition of shortcuts
```
INSERT INTO contracted_edge_table(id, source, target, cost, reverse_cost)
SELECT id, source, target, cost, -1 FROM contraction_results WHERE type = 'e';
```

Now the contracted graph table is as follows
```
SELECT id, source, target, cost, reverse_cost FROM contracted_edge_table;
 id | source | target | cost | reverse_cost 
----+--------+--------+------+--------------
 -1 |      4 |      2 |    2 |           -1
(1 row)
```
Let us say we want to compute shortest path from vertex **4** to vertex **2**.
The result when we compute the path on the original graph is as follows
```
SELECT * FROM pgr_dijkstra('SELECT id, source, target, cost, reverse_cost FROM edge_table WHERE id = 2 or id = 3', 4, 2);
 seq | path_seq | node | edge | cost | agg_cost 
-----+----------+------+------+------+----------
   1 |        1 |    4 |    3 |    1 |        0
   2 |        2 |    3 |    2 |    1 |        1
   3 |        3 |    2 |   -1 |    0 |        2
(3 rows)

```
The result when we compute the path on the contracted graph is as follows
```
SELECT * FROM pgr_dijkstra('SELECT id, source, target, cost, reverse_cost FROM contracted_edge_table', 4, 2);
 seq | path_seq | node | edge | cost | agg_cost 
-----+----------+------+------+------+----------
   1 |        1 |    4 |   -1 |    2 |        0
   2 |        2 |    2 |   -1 |    0 |        2
(2 rows)

```
If we observe the above two paths, the **edge** column in the last line has a value **-1** which indicates the end of the path. But the path on the contracted graph has the **edge** column in the first row as **-1** though it does not indicate the end of the path. On examining the code I found out that this occurs due to numbering the ids of the contracted edges starting from **-1** thus leading to a confusion.

**Comment by cvvergara** [comment]
Related to #1002

**Comment by cvvergara** [comment]
You had it clear here on what to do:
http://docs.pgrouting.org/pickDeliver/en/contraction-family.html#construction-of-the-graph-in-the-database

**Comment by cvvergara** [comment]
Also here you can read: http://docs.pgrouting.org/pickDeliver/en/pgr_contractGraph.html#description-of-the-return-values


id  BIGINT  Identifier of:
* the  vertex when type = ‘v’.
  * The vertex belongs to the edge_table passed as a parameter.
*   the edge when type = ‘e’.
  * The id is a decreasing sequence starting from -1.  Representing a pseudo id as is not incorporated into the edge_table.

**Comment by cvvergara** [comment]
you can not give edge "1" because edge "1" already exists on the graph

**Comment by cvvergara** [comment]
I think the bug is that when inserting the contraction data into the edge_table it should get new numbering. So what is not correct is the post-processing of the contraction information
