### ISSUE TITLE
osm2pgrouting never finishes 

### ISSUE THREAD

**Issue by walpino** [pgRouting/pgrouting#1007]
### Expected behavior and actual behavior
it should do the import in x hours

### Steps to reproduce the problem
Connecting to the database
connection success

Dropping tables...
TABLE: hackways droped ... OK.
TABLE: hackways_vertices_pgr droped ... OK.
TABLE: hackpointsofinterest droped ... OK.
TABLE: configuration droped ... OK.
TABLE: osm_nodes droped ... OK.
TABLE: osm_ways droped ... OK.
TABLE: osm_relations droped ... OK.

Creating tables...
TABLE: hackways_vertices_pgr created ... OK.
TABLE: hackways created ... OK.
TABLE: hackpointsofinterest created ... OK.
TABLE: configuration created ... OK.
TABLE: osm_nodes created ... OK.
TABLE: osm_ways created ... OK.
TABLE: osm_relations created ... OK.
Opening configuration file: /usr/share/osm2pgrouting/mapconfig.xml
    Parsing configuration

Exporting configuration ...
  - Done
Counting lines ...
  - Done
Opening data file: planet_8.4572,47.3346_8.5867,47.4007.osm     total lines: 1542029
    Parsing data

Current osm_nodes:      400000
Final osm_nodes:        401143
Current osm_ways:       0
Final osm_ways: 65171

it stucks there for hours and hours and I dont see why and what it s doing
the osm file is just a small one 

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System
cnetos
SELECT version();
                                                 version
----------------------------------------------------------------------------------------------------------
 PostgreSQL 9.6.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16), 64-bit
(1 row)

# SELECT postgis_full_version();
                                                                              postgis_full_version
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 POSTGIS="2.4.3 r16312" PGSQL="96" GEOS="3.6.2-CAPI-1.10.2 4d2925d6" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 1.11.4, released 2016/01/25" LIBXML="2.9.1" LIBJSON="0.11" RASTER
(1 row)

# SELECT pgr_version();
              pgr_version
----------------------------------------
 (2.5.2,v2.5.2,60585f1f7,master,1.53.0)
(1 row)

Use the commands:
```
SELECT version();
SELECT postgis_full_version();
SELECT pgr_version();
```

any idea where it is stucked? or what takes so long?
the machine has 10 cpus and 50 gb of ram

**Comment by cayetanobv** [comment]
Hi @walpino , this issue is related to [osm2pgrouting](https://github.com/pgRouting/osm2pgrouting) repository. Could you close this issue here and you create a new one in https://github.com/pgRouting/osm2pgrouting/issues?
