### ISSUE TITLE
Experimental Flow Functions to legacy

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#1017]
The experimental flow functions were renamed on v2.5.0:

*    pgr_maxFlowPushRelabel - use pgr_pushRelabel instead
*    pgr_maxFlowEdmondsKarp -use pgr_edmondsKarp instead
*    pgr_maxFlowBoykovKolmogorov - use pgr_boykovKolmogorov instead
*    pgr_maximumCardinalityMatching - use pgr_maxCardinalityMatch instead

Move to legacy the original names.
Remove tests done to any of those functions

**Comment by dkastl** [comment]
Ah, probably this is the reason. They got a different name.

**Comment by cvvergara** [comment]
Done on PR #1018
