### ISSUE TITLE
Stop dijkstra when n destinations has being reached

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#1020]
Suppose you have a network A that connects to Network B (like a network of roads connecting to a network of public transportation) and want to find the shortest path to network B from a vertex `v ` in Network A.
Note: Network A and Network B have some vertices in common.

A possible way to do it is (in pseudo code):
```
v = vertex on network A
u = ARRAY[all the vertices on network B that are also in network A] 
results = SELECT * FROM pgr_dijkstra(
                        'SELECT * from network A
                                UNION
                         SELECT * from network B',
                         v, u);
best_result = get_the_one_with_lower_cost(results)"
```

Internally (C++),  to get the results it finds all `size(u)` paths, where `size(u) - 1` paths are going to be ignored on ` get_the_one_with_lower_cost(results)` function.

An alternate possible way to do it is (in pseudocode):
```
v = vertex on network A
u = ARRAY[all the vertices on network B that are also in network A] 
best_result = SELECT * FROM pgr_dijkstraNear(
                        'SELECT * from network A
                                UNION
                         SELECT * from network B',
                         v, u,
                         1);    --- additional parameter to stop on the "nth" shortest path found
```

Internally, C++ code needs to be modified,  so that it gets the `n` results requested
That way for `size(u)`, in the example, wants to stop once 1 path is found, which will be the one shortest from `v` to NETWORK B

**Comment by dkastl** [comment]
How do you know, that the right path in network A is part of your `n` requested ones?

Otherwise this looks like a very good new functionality, that can apply to several use cases.

**Comment by cvvergara** [comment]
Done with PR #1021
