### ISSUE TITLE
APSP Warshall sums up negative edge costs

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#105]
APSP Warshall returns a wrong result when there are negative edge weights. It sums up negative edge weights so idt decreases the costs to take that path.

See documentation graph and query:

```
SELECT seq, id1 AS from, id2 AS to, cost
    FROM pgr_apspWarshall(
        'SELECT id, source, target, cost FROM edge_table',
        false, false
    );
```

**Comment by cvvergara** [comment]
I don't think its actually returning paths, its returning distance matrix.
so apsp acronym is badly suited, the same applies to pgr_aspsJohnson.

**Comment by dkastl** [comment]
Oh, I see.
Btw., I'm not sure it brings so much value to the users, if we offer them two APSP functions, if both return the same. It's similar with Dijkstra and A*, where you have the same result with pretty much the same performance. 
Is there anything that makes either "Warshall" or "Jonson" better? 
Do we need to maintain them both? ... just asking without knowing much details about them.

**Comment by cvvergara** [comment]
FloydWarshall  is used for sparse graphs
Johnson for dense graphs
They return "distance matrices" aka "Cost Matrices" in our terminology in form of a table, and there are algorithms that use cost matrices, like tsp and vrp which read the cost matrix in form of a matrix.
This cost matrices they generate are all points to all points.
The way I would use them, is, generating the cost matrix in table form and store it in a permanent table, from there I would choose the appropriate sub-matrix data to be used as input of the algorithms that need a matrix table.
The interesting thing is if variations of it can be generated. (like with restrictions)

The difference with for example: (not implemented yet, but its on my mind)
```
pgr_dijkstraCost('select * from edge_table', array[5,10,7], array[5,10,7])
```
and
```
pgr_floydWarsahll('select * from edge_table');
```
floydWarshall will return the complete matrix, in form of a table, and the dijkstraCost would only return the matrix for 5, 7, 10 , also in form of a table.

for the sample data of the documentation:
```
pgr_floydWarsahll('select * from edge_table');
```
would be equivalent to 
```
pgr_dijkstraCost('select * from edge_table', array[1,2,3,4,5,6,7,8,9....18], array[1,2,3,4,5,6,7....18))
```

**Comment by dkastl** [comment]
How would you define a graph as "sparse" or "dense"?
Are there certain criteria or would a user need to try both and compare later?

**Comment by cvvergara** [comment]
Street's graphs are sparse.
Given `G(V,E)`
for sake of simplification (directed)
Graph density  `D = |E| / |V|²`
if D = 1 the graph is complete, form each vertex you have an edge from from that vertex to every other vertex.
if D = 0 that happens when there are no edges.
The closer the number is to 1 the denser is the graph, the closer is to 0 the sparser it is.
If we take the example data of the documentation as example:
there are 28 edges total, including the non negative  (source,target) and the (target,source), and 17 vertices
So:
`D = 28 / 17²  = 0.0622`
which is sparse

**Comment by Zia-** [comment]
For dense graphs, |E| = |V|^2 (approximately), according to http://www.amazon.com/The-Boost-Graph-Library-Reference/dp/0201729148

**Comment by cvvergara** [comment]
Deprecating pgr_apspWarshall please use pgr_floydWarshall
pgr_apspWarshall Its being fixed by wrapping it with the results of pgr_floydWarshall
