### ISSUE TITLE
APSP Johnson missing results

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#106]
It seems that APSP Johnson does not return all shortest path pairs, at least not with the documentation example: http://docs.pgrouting.org/dev/src/apsp_johnson/doc/index.html

It also returns a different number of results than APSP Floyd-Warshall algorithm, which has a similar issue #107.

**Comment by cvvergara** [comment]
Deprecating pgr_apspJohnson please use pgr_Johnson
pgr_apspJohnson Its being fixed by wrapping it with the results of pgr_Johnson
