### ISSUE TITLE
APSP Floyd-Warshall missing results

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#107]
It seems that APSP Floyd-Warshall does not return all shortest path pairs, at least not with the documentation example: http://docs.pgrouting.org/dev/src/apsp_warshall/doc/index.html

It also returns a different number of results than APSP Johnson algorithm, which has a similar issue #106.

**Comment by dkastl** [comment]
What about opening a new issue instead with a reference to this one?
Might be easier to understand.

**Comment by cvvergara** [comment]
Its already referenced by the #421, but test regarding this issue needs to be done.
Note that, "missing values" in he implementation mean that the distance is infinity. I am not returning a value for "infinity" so not to deal with particular machine "max" value.
Here is the [documentation](http://docs.pgrouting.org/dev/src/allpairs/doc/floydWarshall.html) of the implementation I am making.

**Comment by cvvergara** [comment]
Deprecating pgr_apspWarshall please use pgr_floydWarshall
pgr_apspWarshall Its being fixed by wrapping it with the results of pgr_floydWarshall
