### ISSUE TITLE
postgres-xl

### ISSUE THREAD

**Issue by leodc** [pgRouting/pgrouting#1083]
Hello team and thanks for all the work you made to create this library  !

I'm trying to make work pgRouting with [postgres-xl](https://www.postgres-xl.org/) but I'm running in some issues. I have all ready installed a cluster with the PostGIS and pgRouting libraries, I also inserted osm data using the `osm2pgrouting` tool (to create the topology I used a normal PostgreSQL installation because on postgres-xl the Internal subtransactions are not supported).

I will try to give a solution for this issue and make a PR but I couldn't find a good place to start after checking the logs, so I'm open to any suggestion of what part should I start looking. Thank you in advance for the help :)!

### Expected behavior and actual behavior
**Expected behavior**
Get a correct response for the query `SELECT * FROM pgr_dijkstra('SELECT gid AS id, source, target, length AS cost FROM ways', 2146, 22737, directed := false);`

**Actual behavior**
Server crashes giving the next response:
```
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```
Coordinator log:
```
STATEMENT:  SELECT * FROM pgr_dijkstra('SELECT gid AS id, source, target, length AS cost FROM ways', 2146, 22737, directed := false);
LOG:  Getting relation statistics for public.ways
LOG:  Getting detailed statistics for public.ways
LOG:  server process (PID 2398) was terminated by signal 11: Segmentation fault
DETAIL:  Failed process was running: SELECT * FROM pgr_dijkstra('SELECT gid AS id, source, target, length AS cost FROM ways', 2146, 22737, directed := false);
LOG:  terminating any other active server processes
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
```

### Steps to reproduce the problem
1. Create a cluster with postgres-xl, PostGIS and pgRouting.
2. Create a db `createdb routing` and install the extensions:
   - `CREATE EXTENSION postgis;`
   - `CREATE EXTENSION pgRouting;`
3. Fill the database using `osm2pgrouting`
4. Create the topology (using a PostgreSQL installation)
5. Test pgr_dijkstra

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System

Use the commands:

SELECT version();
```
                                                                version
----------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.5.8 (Postgres-XL 9.5r1.6) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609, 64-bit
```

SELECT postgis_version();
```
            postgis_version
---------------------------------------
 2.3 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
```

SELECT pgr_version();
```
             pgr_version
--------------------------------------
 (2.3.1,v2.3.1,963f95d,master,1.58.0)
```

**Comment by cayetanobv** [comment]
Hi @leodc ,

You are using an outdated (from 2016) version of pgRouting (v2.3.1): https://github.com/pgRouting/pgrouting/tree/v2.3.1
Could you install pgRouting v2.6 (latest stable) and test it again?

Thanks,

**Comment by cvvergara** [comment]
The question has become invalid as it refers to 2.6 and it is not supported any more
