### ISSUE TITLE
Is there any way to store the graph?

### ISSUE THREAD

**Issue by ArtistZhou** [pgRouting/pgrouting#1084]
### Expected behavior and actual behavior
when i use pgr_dijkstra(); the data grow million,the  function cost about 10 seconds to calculate.
I want ti know how to improve this. How about store the graph?

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System

Use the commands:
```
SELECT version();
SELECT postgis_full_version();
SELECT pgr_version();
```

**Comment by cvvergara** [comment]
The database stores the graph
We have new functionality on 3.1  `pgr_dijkstra(combinatins)` usable to make may queries in one graph load.
Also, you can use postgis functions to reduce the size of the graph
