### ISSUE TITLE
Support NUMERIC type on Inner queries

### ISSUE THREAD

**Issue by robe2** [pgRouting/pgrouting#1086]
### Expected behavior and actual behavior
I saw this in pgr_vrpOneDepot, I think it exists in other functions

If my x and y are of type numeric I get error:

ERROR:  Unexpected Column 'p_x' type. Expected ANY-NUMERICAL

To fix I have to change my query to :  
`SELECT id, x::float, y::float ...`

The functions should be changed to accept numeric (as a numerical).
or the errors should be changed to note that Numeric is not considered a numerical type.

   
### Steps to reproduce the problem
Use a vrp_orders table where x and y are of type numeric (not float).

`SELECT 
*
FROM 
    pgr_vrpOneDepot(
        'SELECT * FROM vrp_orders', 
        'SELECT id AS vehicle_id, capacity FROM vrp_vehicles',
        'SELECT * FROM vrp_cost_matrix', 
        0
    ) AS X
    INNER JOIN 
    vrp_orders AS Y ON X.oid = Y.id
ORDER BY vid, opos;`

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System

Use the commands:
```
SELECT version();
SELECT postgis_full_version();
SELECT pgr_version();
```
PostgreSQL 10.4, compiled by Visual C++ build 1800, 64-bit
POSTGIS="2.5.0rc1 r16697" [EXTENSION] PGSQL="100" GEOS="3.7.0-CAPI-1.11.0 3.7.0beta2-12-g49f6621" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.2.4, released 2018/03/19" LIBXML="2.7.8" LIBJSON="0.12" LIBPROTOBUF="1.2.1" RASTER

(2.6.0,v2.6.0,a6226c4,release/2.6,1.59.0)

**Comment by cvvergara** [comment]
right now `ANY-NUMERICAL` only has SMALLINT, INTEGER, BIGINT, REAL, FLOAT
 https://docs.pgrouting.org/2.6/en/pgRouting-concepts.html#inner-queries

We don't support postgreSQL `NUMERIC` type yet on the inner queries on any of our functions.
Once we figure out how to support that on the C++ internal code we can support that type.

So maybe we can generalize the title for this issue:
"Support NUMERIC type on Inner queries"
And the example is the pgr_vrpOneDepot experimental function

Can you make the title change please.
