### ISSUE TITLE
Unorganized Documentation Version 3.0-dev

### ISSUE THREAD

**Issue by MarPetra** [pgRouting/pgrouting#1100]
Yesterday I was about to translate pgRouting documentation for develop branch when I found a disaster with the sections in the contents, and I took the liberty of making a table about it with a list that Vicky gave me…  (Thanks a lot Vicky!)

This is the link to the table:

https://docs.google.com/spreadsheets/d/132BudOAI1EAsZTEs1zra21MiOdmyaBtORcYTQhLPiTE/edit?usp=sharing

**Comment by cvvergara** [comment]
@dkastl @woodbri @cayetanobv @robe2 @iamrohith94 
We need to set up a standard for the sections of the functions.

After lloking at the list I am think of:
* Synopsis
* Characteristics (or Description)
* Signatures
* Parameters
* Inner query (or "Inner queries" when there is more than one)
* Return Columns (or "Return Value" for functions returning one value) (Result?)
* Additional examples (when needed)
* See also (on all pages)

**Comment by cvvergara** [comment]
Also define precisely family & category to each function

**Comment by SunveerSingh** [comment]
Can I help with this issue, I would love to do it!

**Comment by cvvergara** [comment]
@SunveerSingh 
Sure see you on https://gitter.im/pgRouting/pgrouting 
I need to teach you how to build the documentation
And @MarPetra has already started working on it,
Then we need to discuss the way we can work without disrupting the other's work.

**Comment by cvvergara** [comment]
I think there has being a lot of work on this issue.
further cleanup, open new issue
