### ISSUE TITLE
pgr_directedChPP -> pgr_chinesePostman

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#1101]
`pgr_directedChPP` was developed by GSoC student @XJTUmg  we never discussed the name, as for me more important is the code.

But now its time that if we want the function to be part of official/proposed or experimental, try to give it the best name we can.

I have two problems with the current name: `pgr_directedChPP`

*directed*
By default pgRouting functions work on a directed graph, unless the algorithm is for an undirected graph only.

*ChPP*
I googled ChPP acronym
https://www.abbreviations.com/CHPP
I did not find anywhere that it means Chinese Postman Problem

So I would like the name to be:
`pgr_chinesePostman`

The documentation should mention that works on a directed graph

**Comment by cayetanobv** [comment]
Hi Vicky,

I'm totally agree with your proposal. By the way I think most used acronym
for Chinese Postman Problem is CPP.

Thanks,

*Cayetano Benavent*Head of Data

+34 954 095 876
www.geographica.gs

**Comment by cvvergara** [comment]
@XJTUmg 

You have priority to do that change

**Comment by cvvergara** [comment]
PR #1228
