### ISSUE TITLE
There are xx.c and xx_driver.cpp in each of the function folders in the file of 'src',  what's the relationship between them,and what are their respective roles?

### ISSUE THREAD

**Issue by zsc1220** [pgRouting/pgrouting#1118]
There are xx.c and xx_driver.cpp in each of  the function folders in the file of 'src',   what's the relationship between them,and what are their respective roles?
Thank you so much!

**Comment by cvvergara** [comment]
- xx.c connects is the C code needed to connect with postgres, it reads the data coming from [postgres](https://www.postgresql.org/docs/current/static/xfunc-c.html)
- The xx_driver.h  is compiled/linked as external C that way ..
- The function on xx_driver.cpp can be called on the xx.c code
- The function on xx_driver.cpp gets the data that was read on xx.c and converts the C arrays to C++ containers, process the info, converts the result to a C array giving postgres control to the memory where the C array was created (remember that C arrays are all pointers)

**Comment by zsc1220** [comment]
It's  so great,Thank you very much!
