### ISSUE TITLE
Wrong spelling for "euclidean"

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#1153]
There is at least one place, where "euclidean" is spelled wrong:
https://docs.pgrouting.org/2.6/en/pgr_eucledianTSP.html#pgr-euclediantsp

Since this is also in the URL of the function, the URL will change, when the name changes, so we could add a warning message in `v2.7`, that the function will change its name in `v3.0`:

- [ ] Add deprecation notice in `v2.7`(or `v2.6` bug-fix release)
- [ ] Rename the function (and other occurrences) in `v3.0`

**Comment by cvvergara** [comment]
My dyslexia showed up, I apologize

**Comment by SunveerSingh** [comment]
Hey, I would like to help in this issue, please let me know if I can help.

**Comment by dkastl** [comment]
@SunveerSingh , thank you for your offer to help! This task goes beyond just fixing text in the documentation, so it requires quite some coordination with release, because the function name will change, too.

@cvvergara will let you know, when she will make the internal changes. It would be definitly good to have some people testing it and give feedback.

**Comment by cvvergara** [comment]
@SunveerSingh 
This fix needs a new release, like I mentioned above
But you can inspect all the steps that were needed to make a release, for example

#1095

**Comment by dkastl** [comment]
Option B sounds also good for me as a start.

**Comment by cvvergara** [comment]
I have ready
Option A, B, & D in PR so we can decide

**Comment by dkastl** [comment]
Where is Option C? ;-)

I somehow find the solution without `euclidean`or `annealing` to be part of the function name the best looking one.

**Comment by cvvergara** [comment]
Because that is the least of my preferences I didnt make one  :(

> Leave for the future the implementation of other algorithms that approximate a solution to TSP
Internally figure out if the query gives (id,x,y) or if it gives (start_vid, end_vid, agg_cost) as data
Then the name euclidean can be avoided.

I prefer to work it out in the present.

**Comment by cvvergara** [comment]
As the start option B I will merge

**Comment by cvvergara** [comment]
PR was merged, the name change iwith correct spelling is done
