### ISSUE TITLE
Improve APSP for more complex networks

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#116]
This ticket continues 2 previous ones, closed for version 2.0:

* #106 
* #107 

To see if negative costs cause the missing pairs in the distance matrix I updated the [Sample Data](http://docs.pgrouting.org/dev/doc/src/developer/sampledata.html) to have only positive values:

```
UPDATE edge_table SET cost = 1;
UPDATE edge_table SET reverse_cost = 1;
```

But still distance pairs are missing and it'S not clear to me why these are missing.

**Comment by cvvergara** [comment]
Deprecating pgr_apspJohnson please use pgr_johnson
pgr_apspJohnson Its being fixed by wrapping it with the results of pgr_johnson
 Deprecating pgr_apspWarshall please use pgr_floydWarshall
pgr_apspWarshall Its being fixed by wrapping it with the results of pgr_floydWarshall
