### ISSUE TITLE
libpgrouting-2.6.so: undefined symbol: _ZN4CGAL18postcondition_failEPKcS1_iS1_

### ISSUE THREAD

**Issue by FreeGIS** [pgRouting/pgrouting#1160]
1 PostGIS2.5,PgRouting2.6 make install success.
2 
test=# create extension pgrouting;
ERROR:  could not load library "/home/postgres/lib/libpgrouting-2.6.so": /home/postgres/lib/libpgrouting-2.6.so: undefined symbol: _ZN4CGAL18postcondition_failEPKcS1_iS1_
test=# \q
[postgres@izm5edacof3axjh1mp7syzz ~]$ ldd  /home/postgres/lib/libpgrouting-2.6.so
	linux-vdso.so.1 =>  (0x00007fff75c2f000)
	libgmp.so.10 => /lib64/libgmp.so.10 (0x00007fcbbd3e1000)
	libboost_thread.so.1.65.0 => /lib/libboost_thread.so.1.65.0 (0x00007fcbbd1b8000)
	libboost_system.so.1.65.0 => /lib/libboost_system.so.1.65.0 (0x00007fcbbcfb4000)
	libboost_chrono.so.1.65.0 => /lib/libboost_chrono.so.1.65.0 (0x00007fcbbcdac000)
	libboost_date_time.so.1.65.0 => /lib/libboost_date_time.so.1.65.0 (0x00007fcbbcb9a000)
	libboost_atomic.so.1.65.0 => /lib/libboost_atomic.so.1.65.0 (0x00007fcbbc998000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fcbbc61d000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fcbbc31b000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fcbbc105000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fcbbbd37000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fcbbbb2f000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fcbbb913000)
	/lib64/ld-linux-x86-64.so.2 (0x0000559f2d3f1000)
I tried my best to solve it,but error still exist...

**Comment by dkastl** [comment]
Couldyou tell us more about your operating system?

**Comment by FreeGIS** [comment]
@dkastl Centos7 x86_64。
![image](https://user-images.githubusercontent.com/8785843/48711727-ee057100-ec46-11e8-8e34-2c9095934987.png)
All the libraries workes fine except pgrouting...

**Comment by FreeGIS** [comment]
I solved this problem, perhaps because of multiple versions of gcc conflicts.

**Comment by FreeGIS** [comment]
I made a few mistakes.
The first one is “gcc conflicts”，i uninstalled the gcc-5.4.0(/usr/local/gcc-5.4.0)and used the default gcc-4.8.5(yum install). 
The secord one is "boost conflicts",i uninstalled the boost-1.65.0(/usr/local/boost-1.65.0)and used the default boost-1.53.0(yum install boost-devel). 
The third one is "cgal".
error:
`[root@VM_0_4_centos include]# ldd /home/postgres/lib/libpgrouting-2.6.so
	linux-vdso.so.1 =>  (0x00007ffc671c5000)
	libgmp.so.10 => /lib64/libgmp.so.10 (0x00007fe32f9f5000)
	libboost_thread-mt.so.1.53.0 => /lib64/libboost_thread-mt.so.1.53.0 (0x00007fe32f7de000)
	libboost_system-mt.so.1.53.0 => /lib64/libboost_system-mt.so.1.53.0 (0x00007fe32f5da000)
	libboost_chrono-mt.so.1.53.0 => /lib64/libboost_chrono-mt.so.1.53.0 (0x00007fe32f3d1000)
	libboost_date_time-mt.so.1.53.0 => /lib64/libboost_date_time-mt.so.1.53.0 (0x00007fe32f1c0000)
	libboost_atomic-mt.so.1.53.0 => /lib64/libboost_atomic-mt.so.1.53.0 (0x00007fe32efbe000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fe32ecb6000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fe32e9b4000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fe32e79e000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fe32e3da000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fe32df76000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe32dd5a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe33087e000)
`
correct:
`
[root@VM_0_4_centos include]# ldd /home/postgres/lib/libpgrouting-2.6.so
	linux-vdso.so.1 =>  (0x00007ffc671c5000)
	libCGAL.so.13 => /usr/local/lib64/libCGAL.so.13 (0x00007fe32fc6e000)
	libgmp.so.10 => /lib64/libgmp.so.10 (0x00007fe32f9f5000)
	libboost_thread-mt.so.1.53.0 => /lib64/libboost_thread-mt.so.1.53.0 (0x00007fe32f7de000)
	libboost_system-mt.so.1.53.0 => /lib64/libboost_system-mt.so.1.53.0 (0x00007fe32f5da000)
	libboost_chrono-mt.so.1.53.0 => /lib64/libboost_chrono-mt.so.1.53.0 (0x00007fe32f3d1000)
	libboost_date_time-mt.so.1.53.0 => /lib64/libboost_date_time-mt.so.1.53.0 (0x00007fe32f1c0000)
	libboost_atomic-mt.so.1.53.0 => /lib64/libboost_atomic-mt.so.1.53.0 (0x00007fe32efbe000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fe32ecb6000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fe32e9b4000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fe32e79e000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fe32e3da000)
	libmpfr.so.4 => /lib64/libmpfr.so.4 (0x00007fe32e17f000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fe32df76000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe32dd5a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe33087e000)
`
"libCGAL.so.13，libmpfr.so.4" did not been showed，if i had not installed cgal,it should prompt "libCGAL.so.13 (not found)". but all it right.

i had no good idea,i ,i uninstalled the cgal-4.13.0(/usr/local/cgal-4.13.0) and used "cmake .." without "-DCMAKE_INSTALL_PREFIX=/usr/local/cgal-4.13" to re_install in default folder(/usr/lib...)

all it right!

before（error,pgrouting.so can not be load）:
`
--cgal
cmake -DCMAKE_INSTALL_PREFIX=/usr/local/cgal-4.13 -DBoost_INCLUDE_DIR="/usr/local/boost-1.65.0/include" ..
make
make install
--pgrouting
cmake -DCGAL_INCLUDE_DIR=/usr/local/cgal-4.13/include -DCGAL_LIBRARIES=/usr/local/cgal-4.13/lib64 ..
make 
make istall
`
after(right，pgrouting.so can be load):
`
rm -rf  /usr/local/boost-1.65.0
yum install boost-devel
--cgal
cmake -DBoost_INCLUDE_DIR="/usr/include" ..
--pgrouting
cmake ..
`
