### ISSUE TITLE
using the function of pgr_SPI_getText to read the Chinese datas were garbled words

### ISSUE THREAD

**Issue by zsc1220** [pgRouting/pgrouting#1171]
I have used the following function to read the Chinese datas ,but the result of return was garbled words

```c++
char *pgr_SPI_getText(HeapTuple *tuple, TupleDesc *tupdesc, Column_info_t info) {
	const char *a = SPI_getvalue(*tuple, *tupdesc, info.colNumber);
	return DatumGetCString(SPI_getvalue(*tuple, *tupdesc, info.colNumber));
}
```

How should I solve this problem , thank you very much !

**Comment by cvvergara** [comment]
Hi @zsc1220 
The question is more related to postgreSQL
https://doxygen.postgresql.org/spi_8c.html#ae53c12ff90592f67e4e40ad0af24205b
https://doxygen.postgresql.org/postgres_8h.html#ae401c8476d1a12b420e3061823a206a7
maybe you can ask in postgres hackers mailing list

btw: 

https://github.com/pgRouting/pgrouting/blob/ed6432f35846ca1a9f79cf9d5b2fd9517fea6dff/src/common/get_check_data.c#L286

Is an attempt to read text, internally we are not using it, I couldn't figure it out to make it work :(

**Comment by zsc1220** [comment]
@cvvergara Thank you very much ! Although the problem remains unresolved ,We sidestepped the problem in another way，just not to read Chinese datas.
