### ISSUE TITLE
could not access file "$libdir/libpgrouting-2.3"

### ISSUE THREAD

**Issue by kateallen1** [pgRouting/pgrouting#1182]
### Expected behavior and actual behavior
SELECT * FROM pgr_drivingDistance(
        'SELECT id, source, target, cost, reverse_cost FROM edge_table',
        2, 3
      );
#### Expected behaviour: 

 seq | node | edge | cost | agg_cost 
-----+------+------+------+----------
   1 |    2 |   -1 |    0 |        0
   2 |    1 |    1 |    1 |        1
   3 |    5 |    4 |    1 |        1
   4 |    6 |    8 |    1 |        2
   5 |    8 |    7 |    1 |        2
   6 |   10 |   10 |    1 |        2
   7 |    7 |    6 |    1 |        3
   8 |    9 |    9 |    1 |        3
   9 |   11 |   12 |    1 |        3
  10 |   13 |   14 |    1 |        3
(10 rows)

#### Actual behaviour: 
OperationalError: could not access file "$libdir/libpgrouting-2.3": No such file or directory
CONTEXT:  PL/pgSQL function pgr_drivingdistance(text,bigint,double precision,boolean) line 4 at RETURN QUERY

### Steps to reproduce the problem
I used the sample data to reproduce the error I was getting in my own project

I created the edge_table here: https://docs.pgrouting.org/2.3/en/doc/src/developer/sampledata.html#fig1 and then used the top example here - https://docs.pgrouting.org/2.3/en/src/driving_distance/doc/pgr_drivingDistance.html 

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System

```
SELECT version(); -  PostgreSQL 9.6.4, compiled by Visual C++ build 1800, 64-bit
SELECT postgis_full_version(); -  POSTGIS="2.3.3 r15473" GEOS="3.6.1-CAPI-1.10.1 r4317" PROJ="Rel. 4.9.1, 04 March 2015" GDAL="GDAL 2.2.1, released 2017/06/23" LIBXML="2.7.8" LIBJSON="0.12" (core procs from "2.3.1 r15264" need upgrade) RASTER (raster procs from "2.3.1 r15264" need upgrade)
SELECT pgr_version(); - (2.3.1,v2.3.1,963f95d,master,1.59.0)

```

Thank you for your help!

**Comment by cvvergara** [comment]
I dont recall fixing issues of pgRouting version 2.3 for postgreSQL 9.6
Can you try using a more recent version of pgRouting please.

**Comment by cvvergara** [comment]
We do not support:
- PostgreSQL 9.6, 
- pgRouting 2.3
