### ISSUE TITLE
  Selection of postgres-xl and postgres-xc

### ISSUE THREAD

**Issue by wangzuotang** [pgRouting/pgrouting#1189]
.

**Comment by wangzuotang** [comment]
Hello, I want to build a PG distributed architecture here. I want to choose postgres-xl or postgres-xc, but the information on our network is very abstract, which makes me confused. I would like to ask you to give some advice on the choice.

**Comment by cvvergara** [comment]
You can ask into the pgrouting mailing lists, maybe some user knows
