### ISSUE TITLE
pgrouting

### ISSUE THREAD

**Issue by godali645** [pgRouting/pgrouting#1196]
hi , i write pgrouting instruction in postgis and my pgrouting version is 2.6.
i using this algoritm 👍 

	SELECT dijkstra.*, ways.name, ways.the_geom
FROM pgr_dijkstra(
    'SELECT gid AS id, * FROM ways',
      59699, 61641,true
    ) AS dijkstra
LEFT JOIN ways
ON (edge = gid) ORDER BY seq;

then my routing is false because it calcuting brigde overpassing in driving rout.
why?
thx

**Comment by robe2** [comment]
Please ask this question in pgrouting-users  list https://lists.osgeo.org/mailman/listinfo/pgrouting-users  or GIS Stack Exchange  https://gis.stackexchange.com/  

This ticket tracker is only for bug reporting and not help with using functions
