### ISSUE TITLE
Passing too many edges to pgr_dijkstra causes it to return no route.

### ISSUE THREAD

**Issue by benglass** [pgRouting/pgrouting#1239]
### Expected behavior and actual behavior

I expect the number of edges provided to pgr_dijkstra to have no impact on the ability of it to find a route.

What I am seeing is that if there are too many edges (20k in my case) then sometimes it can't find a route.

I suspect there is some limit on the number of paths it will try or the amount of resources (memory?) it will consume before giving up but I can't find any documentation of this.

### Steps to reproduce the problem

Load the edge table with 100 edges
Attempt to route
It works

Add an additional 20k edges that are not related to the route in question
Attempt to route with pgr_dijkstra
It returns no rows

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System

PostgreSQL
10.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9), 64-bit

POSTGIS="2.4.4 r16526" PGSQL="100" GEOS="3.6.2-CAPI-1.10.2 4d2925d6" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.1.4, released 2017/06/23" LIBXML="2.9.1" LIBJSON="0.12" LIBPROTOBUF="1.3.0" RASTER

PGR Version
(2.5.2,v2.5.2,60585f1f7,master,1.65.0)
```

**Comment by dkastl** [comment]
pgRouting is known to work with very large networks, 20k edges is a very small number actually.

Would you be able to share the data you're using with the the query, that does not work?
