### ISSUE TITLE
pgr_pointtoedgenode

### ISSUE THREAD

**Issue by marcusyoung** [pgRouting/pgrouting#1257]
I see that `pgr_pointtoedgenode` has been removed from v3.0. I seem to recall this was being deprecated but can't recall why now. Presumably I can just take the function from an earlier version?

**Comment by cvvergara** [comment]
The code can be found on this legacy file:

https://github.com/pgRouting/pgrouting/blob/cd560142b48d92742d4fbf82e60326d91d1d1b30/sql/legacy/legacy-developers.sql#L430
