### ISSUE TITLE
FreeBSD 12 64-bit crashes on pgr_vrOneDepot tests Experimental Function

### ISSUE THREAD

**Issue by robe2** [pgRouting/pgrouting#1304]
### Expected behavior and actual behavior
No crash,
Crashes on FreeBSD 12 64 but not on FreeBSD 12 32-bit
### Steps to reproduce the problem
Both bessie and bessie32 freebsd fail -- load scripts in ci/bessie/regress.sh, ci/bessie32/regress.sh

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System

Use the commands:
```
SELECT version();
SELECT postgis_full_version();
SELECT pgr_version();
```

Output from CMake

> CMake suite maintained and supported by Kitware (kitware.com/cmake).
> -- Setting build type to 'Debug' as none was specified.
> -- CMAKE_BUILD_TYPE Debug
> -- The C compiler identification is Clang 6.0.1
> -- The CXX compiler identification is Clang 6.0.1
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- DOXYGEN_MINIMUM_VERSION=1.7
> -- SPHINX_MINIMUM_VERSION=1.1
> -- POSTGRESQL_MINIMUM_VERSION=9.2.0
> -- POSTGIS_MINIMUM_VERSION=2.0.0
> -- GNU_CXX_MINIMUM_VERSION=4.6
> -- CLANG_CXX_MINIMUM_VERSION=
> -- MSVC_CXX_MINIMUM_VERSION=18.0
> -- dir='/usr/home/jenkins/workspace/pgRouting_GitHubHook_Push/label/bessie32/c2f4b0caa491a4bbf68d396743628bab69fbf537/cmake'
> -- Performing Test COMPILER_SUPPORTS_CXX0X
> -- Performing Test COMPILER_SUPPORTS_CXX0X - Success
> -- Performing Test COMPILER_SUPPORTS_CXX11
> -- Performing Test COMPILER_SUPPORTS_CXX11 - Success
> -- Unknown compiler minimum version for Clang
> -- Using  -std=c++11.
> -- Found Perl: /usr/local/bin/perl (found version "5.28.2") 
> -- POSTGRESQL_PG_CONFIG is /usr/local/bin/pg_config
> -- POSTGRESQL_EXECUTABLE is /usr/local/bin/postgres
> -- POSTGRESQL_VERSION_STRING in FindPostgreSQL.cmake is PostgreSQL 11.5
> -- POSTGRESQL_INCLUDE_DIR: /usr/local/include/postgresql/server
> -- POSTGRESQL_LIBRARIES: /usr/local/lib
> -- PGSQL_VERSION=115
> -- Boost version: 1.70.0
> -- Boost headers were found here: /usr/local/include
> -- Boost VERSION 1.70.0
> -- BOOST_VERSION_OK 1
> -- BOOST_Geometry_VERSION_OK 1
> -- Performing Test C_COMPILER_SUPPORTS_FPIC
> -- Performing Test C_COMPILER_SUPPORTS_FPIC - Success
> -- Performing Test CXX_COMPILER_SUPPORTS_FPIC
> -- Performing Test CXX_COMPILER_SUPPORTS_FPIC - Success
> -- Performing Test C_COMPILER_SUPPORTS_ROUNDING_MATH
> -- Performing Test C_COMPILER_SUPPORTS_ROUNDING_MATH - Success
> -- Performing Test CXX_COMPILER_SUPPORTS_ROUNDING_MATH
> -- Performing Test CXX_COMPILER_SUPPORTS_ROUNDING_MATH - Failed
> -- Configuring done
> -- Generating done

>  3.0.0-rc1 | Debug      | 2019/10/28   | pgrouting-3.0 | FreeBSD-12.0-RELEASE-p10 | PostgreSQL 11.5 | Clang-6.0.1 | 1.70.0 | c2f4b0c',

error that shows:

> Processing test: docqueries/vrp_basic/doc-pgr_vrpOneDepotCRASHED SERVER: 'docqueries/vrp_basic/doc-pgr_vrpOneDepot.test.sql', sleeping 5 ...
>     test run time: 142.604254
> Processing test: docqueries/withPoints/doc-pgr_withPoints	 PASS
>     test run time: 0.392057
> Processing test: docqueries/withPoints/doc-pgr_withPointsCost	 PASS
>     test run time: 0.283035
> Processing test: docqueries/withPoints/doc-pgr_withPointsCostMatrix	 PASS
>     test run time: 0.621401
> Processing test: docqueries/withPoints/doc-pgr_withPointsDD	 PASS
>     test run time: 0.203146
> Processing test: docqueries/withPoints/doc-pgr_withPointsKSP	 PASS
>     test run time: 0.337488
> Processing test: docqueries/withPoints/doc-pgr_withPointsKSP	 PASS
>     test run time: 0.263803
>

**Comment by cvvergara** [comment]
Related to #1725 
This function calls calls `pgr_pickDeliver` so both are related
