### ISSUE TITLE
Incorrect query in the documentation of bdDijkstraCost

### ISSUE THREAD

**Issue by TanvirSingh007** [pgRouting/pgrouting#1325]
### Expected Query
- In one-to-one
```
SELECT * FROM pgr_bdDijkstraCost(
    'SELECT id, source, target, cost, reverse_cost FROM edge_table',
    2, 3,
    false
);
```
- In many-to-many
```
SELECT * FROM pgr_bdDijkstraCost(
    'SELECT id, source, target, cost, reverse_cost FROM edge_table',
    ARRAY[2, 7], ARRAY[3, 11]);
```

### Written Query
- In one-to-one
```
SELECT * FROM pgr_bdDijkstra(
    'SELECT id, source, target, cost, reverse_cost FROM edge_table',
    2, 3,
    false
);
```
- In many-to-many
```
SELECT * FROM pgr_bdDijkstra(
    'SELECT id, source, target, cost, reverse_cost FROM edge_table',
    ARRAY[2, 7], ARRAY[3, 11]);
```

It needs to be corrected on its webpage.
https://docs.pgrouting.org/latest/en/pgr_bdDijkstraCost.html#one-to-one

**Comment by cvvergara** [comment]
Thanks for your report

The error is in this file:
https://github.com/pgRouting/pgrouting/blob/master/doc/bdDijkstra/pgr_bdDijkstraCost.rst
Please let me know, as soon as possible, if you want to do a Pull Request with the fix

**Comment by TanvirSingh007** [comment]
Yes sure 
I will do a pull request with the fix

**Comment by TanvirSingh007** [comment]
Do I need to edit the sql file in this case?

**Comment by cvvergara** [comment]
I dont think so
https://github.com/pgRouting/pgrouting/blob/master/docqueries/bdDijkstra/doc-pgr_bdDijkstraCost.result

**Comment by TanvirSingh007** [comment]
Do i need to edit the queries?
Also are the results automatic or we need to edit those manually?

**Comment by cvvergara** [comment]
Results are automatic
