### ISSUE TITLE
Incorrect description of examples on bdAstarCost

### ISSUE THREAD

**Issue by ShivamRai2003** [pgRouting/pgrouting#1329]
###  Expected Description of Example

  
- Using Defaults
**Example:** From vertex 2 to vertex 3 on a directed graph.

- In one-to-one
**Example:** From vertex 2 to vertex 3 on an directed graph using heuristic 2

- one-to-many
**Example:** From vertex 2 to vertices {3,11} on a directed graph using heuristic 3 and factor=3.5

- many-to-one

   **Example:** From vertices {2,7} to vertex 3 on a undirected graph using heuristic 4

- many-to-many

  **Example:**  From vertices {2,7} to vertices {3,11} on a directed using heuristic 5 and factor=0.5

### Written Description of Examples

- Using Defaults
**Example:** From vertex 2 to vertex 12 on a directed graph.

- In one-to-one
**Example:** From vertex 2 to vertex 12 on an undirected graph using heuristic 2

- one-to-many
**Example:** From vertex 2 to vertices {3,12} on a directed graph using heuristic 2

- many-to-one

  **Example:** From vertices {7,2} to vertex 12 on a directed graph using heuristic 0

- many-to-many

  **Example:** From vertices {7,2} to vertices {3,12} on a directed using heuristic 2

**It needs to be corrected on its webpage:**  https://docs.pgrouting.org/latest/en/pgr_bdAstarCost.html

**Comment by cvvergara** [comment]
@ShivamRai2003 can you chnge the title to:
Incorrect description of examples on bdAstarCost
you will be fixing the description, not the queries

**Comment by cvvergara** [comment]
Will close the issue until you get the comment about the problem fixed

**Comment by ShivamRai2003** [comment]
@cvvergara Done the Changes !

**Comment by pranayteaches** [comment]
I guess we should elaborate the explanation a little bit.
Lets suppose (In few words) that:
For Many to Many have:
instead of
From vertices {7,2} to vertices {3,11} on a directed using heuristic 5
have:
From vertices {7,2} to vertices {3,11} on a directed using heuristic 5 (default) with factor 0.5
