### ISSUE TITLE
bdAstarCost (Many To Many) || Incorrect Explanation

### ISSUE THREAD

**Issue by pranayteaches** [pgRouting/pgrouting#1330]
The explanation of the the bdAstar(Many To Many) is incorrect
# Expected behavior
1. Example: From vertices {2, 7} to vertices {3,11} on a directed using heuristic 0.5(a/c to the bdAstarCost Explaination)
OR
2. Example: From vertices {2, 7} to vertices {3,11} on a directed using Factor 0.5(a/c to the query)

# Actual behavior
Example: From vertices {7,2} to vertices {3,11} on a directed using heuristic 5

# Steps to remove
![Capture](https://user-images.githubusercontent.com/35572191/71350724-e7f36980-2597-11ea-8c64-d428935b2074.PNG)
 the problem

the thing which is creating the problem is the factor in the statement either the explanation or the code.
Because in the viewing doc of bdAstar ( https://github.com/pgRouting/pgrouting/blob/master/doc/bdAstar/pgr_bdAstarCost.rst ) it showing the following explanation:-

Example: | From vertices \{7, 2\} to vertices \{3, 12\} on a directed using heuristic 2
-- | --
### problem 1 (no. 1 in the image above)
* but the main thing is the vertices should be { 2, 7} and {3, 11}
* and the other thing is that in bdAstarCost pgRouting manual, in the query in place of heuristic it is given factor. If it is factor only than the explaination is to be
### problem 2 (no. 2 in the image above)
"Example: From vertices {2, 7} to vertices {3,11} on a directed using factor 0.5"
* or if it is heuristic than the explaination should be
"Example: From vertices {2, 7} to vertices {3,11} on a directed using heuristic 0.5"
* also the the heuristic should be 0.5 in the explaination or 5 in the query.

**Comment by cvvergara** [comment]
This issue was reported previously on: #1329
