### ISSUE TITLE
pgr_dijkstra not exist postgresql 12

### ISSUE THREAD

**Issue by larscsg** [pgRouting/pgrouting#1334]
### Expected behavior and actual behavior
Dear pgrouting staff,

I have trouble with Postgresql 12 and pgrouting 3.0.1dev. I've installed the extension in database but I get the following error.

function pgr_dijkstra(unknown, integer, integer, boolean, boolean) does not exist

What is wrong? I see the function in the "\df" command line of pgsql.

There was no problem with pgsql 10 and pgrouting version 2.6.0.

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System

# SELECT version();
                                                         version
-------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 12.1 (Debian 12.1-1.pgdg80+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 4.9.2-10+deb8u2) 4.9.2, 64-bit
(1 Zeile)

# SELECT postgis_full_version();
                                                                    postgis_full_version
-------------------------------------------------------------------------------------------------------------------------------------------------------------
 POSTGIS="3.0.1dev" [EXTENSION] PGSQL="120" GEOS="3.7.0beta1-CAPI-1.11.0 5bf8baee" PROJ="Rel. 4.8.0, 6 March 2012" LIBXML="2.9.1" LIBJSON="0.11.99" TOPOLOGY
(1 Zeile)

# SELECT pgr_version();
 pgr_version
-------------
 3.0.0-rc1
(1 Zeile)

# \df pgr_dijkstra

Schema |     Name     | Ergebnisdatentyp |                                                                                                          Argumentdatentypen                                                                                                          | Typ
--------+--------------+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------
 public | pgr_dijkstra | SETOF record     | text, anyarray, anyarray, directed boolean DEFAULT true, OUT seq integer, OUT path_seq integer, OUT start_vid bigint, OUT end_vid bigint, OUT node bigint, OUT edge bigint, OUT cost double precision, OUT agg_cost double precision | Funk
 public | pgr_dijkstra | SETOF record     | text, anyarray, bigint, directed boolean DEFAULT true, OUT seq integer, OUT path_seq integer, OUT start_vid bigint, OUT node bigint, OUT edge bigint, OUT cost double precision, OUT agg_cost double precision                       | Funk
 public | pgr_dijkstra | SETOF record     | text, bigint, anyarray, directed boolean DEFAULT true, OUT seq integer, OUT path_seq integer, OUT end_vid bigint, OUT node bigint, OUT edge bigint, OUT cost double precision, OUT agg_cost double precision                         | Funk
 public | pgr_dijkstra | SETOF record     | text, bigint, bigint, directed boolean DEFAULT true, OUT seq integer, OUT path_seq integer, OUT node bigint, OUT edge bigint, OUT cost double precision, OUT agg_cost double precision                                               | Funk
(4 Zeilen)

**Comment by dkastl** [comment]
Do you get this error, when you run an SQL query with `pgr_dijkstra` function? 
In this case, could you post your query?

Looking at the output of `df pgr_routing` it seems that pgRouting is installed.

**Comment by maamolina** [comment]
Hi,

I have the same error larscsg bumped into. 
I am running dwmorley -  Minor_Roads method to estimate minor roads and one of the sql files uses pgRouting extension. We are able to run it with version pgRouting V2.6.3 but not with pgRouting V3.0.0. I tried installing pgRouting V2.6.3 in PostgreSQL 12 with no success:
 
CREATE EXTENSION pgrouting WITH VERSION "2.6.3";
ERROR:  extension "pgrouting" has no installation script nor update path for version "2.6.3"

How can I install version 2.6.3 in PostgreSQL 12?

PostgreSQL V11 runs pgRouting V2.6.3 and the Minor_Roads method runs without problem. 

Link to David Morley sql:
Master:
https://github.com/dwmorley/Minor_Roads

sql with error:
https://github.com/dwmorley/Minor_Roads/blob/master/minor_assignment_routing.sql

**Comment by cvvergara** [comment]
The signature is with BIGINT 
```
\dx+ pgrouting
....
 function pgr_dijkstra(text,anyarray,anyarray,boolean)
 function _pgr_dijkstra(text,anyarray,anyarray,boolean,boolean,boolean,bigint)
 function pgr_dijkstra(text,anyarray,bigint,boolean)
 function pgr_dijkstra(text,bigint,anyarray,boolean)
 function pgr_dijkstra(text,bigint,bigint,boolean)
...
```
