### ISSUE TITLE
Add newer PostgreSQL to CI

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#1335]
It seems that currently Travis CI does not test for newer PostgreSQL/PostGIS

- [x] Remove PostgreSQL 9.4
- [x] Add PostgreSQL 11
- [x] Add PostgreSQL 12
- [x] Test against newer versions of PostGIS

**Comment by dkastl** [comment]
@cvvergara , I wanted to try Github Actions, which could replace Travis and Appevyor, so I created the following branch and CI workflow script with a build matrix for different PostgreSQL/PostGIS versions: 
https://github.com/pgRouting/pgrouting/blob/ftr/gh-actions/.github/workflows/ubuntu.yml#L21-L24

In #1334 there is a report about problems with PostgreSQL 12, and I found out that Travis only tests until PostgreSQL 10.

The build and installation works for all PostgreSQL versions, but tests start failing from PostgreSQL 11. This is the successful build and test, but it only has tests until PostgreSQL 10: https://github.com/pgRouting/pgrouting/commit/9266a2e097664a39d8006adcd57766c2135cca8d/checks?check_suite_id=398177730

**Comment by dkastl** [comment]
I would suggest to use Github Actions and retire Travis. It was easier to setup, and it eventually can also build for Macos and Windows.

**Comment by cvvergara** [comment]
The set up is fine, but the tests are not performed.

**Comment by cvvergara** [comment]
Verified, tests are working, so we will open new issues for other operative systems different than linux.

**Comment by dkastl** [comment]
Actually in MacOS and Windows CI files everything is commented out at the moment.
But if Ubuntu tests work on Github Actions now, shall we drop Travis first?

**Comment by cvvergara** [comment]
Lets keep travis until I test everything I need to test on actions
