### ISSUE TITLE
Postgres not found when installing pgrouting extension.

### ISSUE THREAD

**Issue by brunre01** [pgRouting/pgrouting#1341]
cmake version 2.8.18
postgres 10.11
postgis 2.5.3
pgrouting 2.4.2

### Expected behavior and actual behavior

-- CMAKE_BUILD_TYPE
-- CMAKE_BUILD_TYPE
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- DOXYGEN_MINIMUM_VERSION=1.7
-- SPHINX_MINIMUM_VERSION=1.1
-- POSTGRESQL_MINIMUM_VERSION=9.2.0
-- POSTGIS_MINIMUM_VERSION=2.0.0
-- GNU_CXX_MINIMUM_VERSION=4.6
-- CLANG_CXX_MINIMUM_VERSION=
-- MSVC_CXX_MINIMUM_VERSION=18.0
-- dir='/home/postgres/software/pgrouting-2.4.2/cmake'
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Found Perl: /usr/bin/perl (found version "5.16.3")
-- POSTGRESQL_PG_CONFIG is /usr/pgsql-10/bin/pg_config
-- POSTGRESQL_EXECUTABLE is /usr/pgsql-10/bin/postgres
-- POSTGRESQL_VERSION_STRING in FindPostgreSQL.cmake is PostgreSQL 10.11
-- PostgreSQL not found.
CMake Error at CMakeLists.txt:313 (message):
   Please check your PostgreSQL installation.
-- Configuring incomplete, errors occurred!
See also "/home/postgres/software/pgrouting-2.4.2/build/CMakeFiles/CMakeOutput.log".

### Steps to reproduce the problem
cd  /home/postgres/software/pgrouting-2.4.2/build
cmake ..

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System

Redhat 7.4

Use the commands:
```
PostgreSQL 10.11 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit

POSTGIS="2.5.3 r17699" [EXTENSION] PGSQL="100" GEOS="3.8.0-CAPI-1.13.1 " SFCGAL="1.3.1" PROJ="Rel. 6.2.1, November 1st, 2019" GDAL="GDAL 3.0.2, released 2019/10/28" LIBXML="2.9.1" LIBJSON="0
.11" LIBPROTOBUF="1.0.2" TOPOLOGY RASTER

ERROR:  function pgr_version() does not exist
```

**Comment by ShivamRai2003** [comment]
Try this : CREATE EXTENSION pgrouting;

SELECT pgr_version();

**Comment by brunre01** [comment]
postgres=# create extension pgrouting;
ERROR:  could not open extension control file "/usr/pgsql-10/share/extension/pgrouting.control": No such file or directory

When trying to complie pgrouting from source i get the following error when running cmake

-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Found Perl: /usr/bin/perl (found version "5.16.3")
-- POSTGRESQL_PG_CONFIG is /usr/pgsql-10/bin/pg_config
-- POSTGRESQL_EXECUTABLE is /usr/pgsql-10/bin/postgres
-- POSTGRESQL_VERSION_STRING in FindPostgreSQL.cmake is PostgreSQL 10.11
-- PostgreSQL not found.



I'm including the cmakeoutput.log file
[CMakeOutput.log](https://github.com/pgRouting/pgrouting/files/4117730/CMakeOutput.log)

**Comment by cvvergara** [comment]
I dont have RedHat so I have no way to reproduce. But:

Make sure you installed postgres server and that client and server match:

```
psql --version
psql -c 'SELECT version()' 
```

you can also use the cmake flag: `-DPOSTGRESQL_BIN=/usr/pgsql-10/bin`

keep me posted.

**Comment by cvvergara** [comment]
Example of how to install postgreSQL server can be found in:
https://docs.pgrouting.org/3.0/en/pgRouting-installation.html#dependencies
