### ISSUE TITLE
pgr_createTopology get an error

### ISSUE THREAD

**Issue by Leijiawei** [pgRouting/pgrouting#1347]
**Describe the bug**
when I use 'select pgr_createTopology('total_road',0.000001, 'geom', 'id');' with 480K geographic data，I will get An I/O error occurred while sending to the backend.

![image](https://user-images.githubusercontent.com/11434308/80557311-1632fb00-8a09-11ea-96a2-53bdb1617174.png)

```
I hope to get help.
Thank you.

**Comment by dkastl** [comment]
pgRouting does not have any dependency to Java, but your error gives a java.io exception error. Can you explain why? 

Please try to post the actual error returned by PostgreSQL/pgRouting.

**Comment by guyanf** [comment]
Maybe he used the Jave code reference pgr_createTopology function.
