### ISSUE TITLE
GSoC 2020: Signature of new functions to be added in pgRouting

### ISSUE THREAD

**Issue by prakashupes** [pgRouting/pgrouting#1355]
**New Functions to be added are:**  
  - Lengauer Tarjan Dominator Tree
  - Two Graphs Common Spanning Trees

**The signature I would like to add:**
- Directory name for : 
   - Lengauer Tarjan Dominator Tree: **LTDTree**
   - Two Graphs Common Spanning Trees: **TGCSTrees**
- File Names:
 (These names will be used in all files including C, C++, Doc, Docquaries etc. by adding some prefix or a suffix like _, doc, pgr...Cost etc for added functionalities )
**Examples:**
   - LTDTree.sql, _LTDTree.sql, doc_pgr_LTDTree etc.
   - TGCSTrees.sql, _TGCSTrees.sql, doc_pgr_TGCSTrees etc.
- Signature
   -  ```pgr_LTDTree(edges_sql,root ) RETURNS SET OF (id,vid, sdom, idom)) OR EMPTY SET```
   -  ```pgr_TGCSTrees(edges_sql_G1,edges_sql_G2) RETURNS SET OF  (seq, edge, cost) OR EMPTY SET ```

**Proposed Alternatives 1**
- Directory name for : 
   - Lengauer Tarjan Dominator Tree: **LTDT**
   - Two Graphs Common Spanning Trees: **TGCST**

- Signature
   -  ```pgr_LTDT(edges_sql,root ) RETURNS SET OF (id,vid, sdom, idom)) OR EMPTY SET```
   -  ```pgr_TGCST(edges_sql_G1,edges_sql_G2) RETURNS SET OF  (seq, edge, cost) OR EMPTY SET ```

**Proposed Alternatives 2**
- Directory name for : 
   - Lengauer Tarjan Dominator Tree: **LTDominatorTree**
   - Two Graphs Common Spanning Trees: **2GCSpanningTree**

- Signature
   -  ```pgr_LTDominatorTree(edges_sql,root ) RETURNS SET OF (id,vid, sdom, idom)) OR EMPTY SET```
   -  ```pgr_2GCSpanningTree(edges_sql_G1,edges_sql_G2) RETURNS SET OF  (seq, edge, cost) OR EMPTY SET ```

**Comment by cvvergara** [comment]
We can not discuss to different function in one issue, please open an issue per function
Marking as invalid please open an issue per function
