### ISSUE TITLE
pgr_trspViaVertices ignores restriction at query vertex

### ISSUE THREAD

**Issue by crosspolar** [pgRouting/pgrouting#1357]
In case you use function `pgr_trspViaVertices` or `pgr_trspViaEdges` with a query vertex between two edges, for which a restriction applies, it will ignore this restriction.
**Example:** The [example query](http://docs.pgrouting.org/latest/en/pgr_trsp.html) from the documentation wants to find the routes connecting the vertices `2,7,11`. The resulting route crosses among others vertex 5 in sequence 2 and 6:
```
SELECT * FROM pgr_trspViaVertices(
        'SELECT id::INTEGER, source::INTEGER, target::INTEGER, cost FROM edge_table',
        ARRAY[2,7,11]::INTEGER[],
        false,  false,
        'SELECT to_cost, target_id::int4, from_edge ||
        coalesce('',''||via_path,'''') AS via_path FROM restrictions');
```
gives the expected:
```
╔═════╦═════╦═════╦═════╦══════╗
║ seq ║ id1 ║ id2 ║ id3 ║ cost ║
╠═════╬═════╬═════╬═════╬══════╣
║   1 ║   1 ║   2 ║   4 ║    1 ║
║   2 ║   1 ║   5 ║  10 ║    1 ║
║   3 ║   1 ║  10 ║  12 ║    1 ║
║   4 ║   1 ║  11 ║  11 ║    1 ║
║   5 ║   1 ║   6 ║   8 ║    1 ║
║   6 ║   1 ║   5 ║   7 ║    1 ║
║   7 ║   1 ║   8 ║   6 ║    1 ║
║   8 ║   2 ║   7 ║   6 ║    1 ║
║   9 ║   2 ║   8 ║   7 ║    1 ║
║  10 ║   2 ║   5 ║   8 ║    1 ║
║  11 ║   2 ║   6 ║   9 ║    1 ║
║  12 ║   2 ║   9 ║  15 ║    1 ║
║  13 ║   2 ║  12 ║  13 ║    1 ║
║  14 ║   2 ║  11 ║  -1 ║    0 ║
╚═════╩═════╩═════╩═════╩══════╝
```
**To reproduce** the problem, calculate the route via the vertices `2,5,7,11`, it will ignore the restriction between the edges 4 and 7.
```
SELECT * FROM pgr_trspViaVertices(
        'SELECT id::INTEGER, source::INTEGER, target::INTEGER, cost FROM edge_table',
        ARRAY[2,5,7,11]::INTEGER[],
        false,  false,
        'SELECT to_cost, target_id::int4, from_edge ||
        coalesce('',''||via_path,'''') AS via_path FROM restrictions');
```
The output is
```
╔═════╦═════╦═════╦═════╦══════╗
║ seq ║ id1 ║ id2 ║ id3 ║ cost ║
╠═════╬═════╬═════╬═════╬══════╣
║   1 ║   1 ║   2 ║   4 ║    1 ║
║   2 ║   2 ║   5 ║   7 ║    1 ║
║   3 ║   2 ║   8 ║   6 ║    1 ║
║   4 ║   3 ║   7 ║   6 ║    1 ║
║   5 ║   3 ║   8 ║   7 ║    1 ║
║   6 ║   3 ║   5 ║   8 ║    1 ║
║   7 ║   3 ║   6 ║   9 ║    1 ║
║   8 ║   3 ║   9 ║  15 ║    1 ║
║   9 ║   3 ║  12 ║  13 ║    1 ║
║  10 ║   3 ║  11 ║  -1 ║    0 ║
╚═════╩═════╩═════╩═════╩══════╝
```
My specification is 

- `version() = PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by gcc (Arch Linux 9.3.0-1) 9.3.0, 64-bit`
- `postgis_full_version() = POSTGIS="3.0.1 ec2a9aa" [EXTENSION] PGSQL="120" GEOS="3.8.0-CAPI-1.13.1 " PROJ="6.3.1" LIBXML="2.9.10" LIBJSON="0.14" LIBPROTOBUF="1.3.3" WAGYU="0.4.3 (Internal)"` 
- `pgr_version() = 3.0.0` 

Maybe this behavior is already known or wanted, but it I couldn't find any further note on that.

**Comment by cvvergara** [comment]
https://docs.pgrouting.org/latest/en/pgr_trsp.html#known-issues

**Comment by cvvergara** [comment]
Work has been done for TRSP on develop branch for version 3.4 (due to be released on September/October 2022:
https://github.com/pgRouting/pgrouting/issues/2238
Please check the documentation
https://docs.pgrouting.org/dev/en/TRSP-family.html
and the migration guide:
https://docs.pgrouting.org/dev/en/trsp_migration.html

For further similar problems with TRSP functions please open a new issue with the specific function name.
