### ISSUE TITLE
pgrouting-3.0.0 make error

### ISSUE THREAD

**Issue by Cenergy** [pgRouting/pgrouting#1363]
**Describe the bug**
### cmake success
![image](https://user-images.githubusercontent.com/22636178/85189554-a7746e80-b2e2-11ea-8495-e3f0e26e669a.png)
### but make error
![image](https://user-images.githubusercontent.com/22636178/85190226-a8a89a00-b2e8-11ea-9d22-b66d2ab66ceb.png)

![微信截图_20200620112537](https://user-images.githubusercontent.com/22636178/85190239-e3123700-b2e8-11ea-8883-fe5ef05306cc.png)

**Comment by Cenergy** [comment]
please help me,thanks!

**Comment by Cenergy** [comment]
boost version 1.53.0

**Comment by ImreSamu** [comment]
@Cenergy :
* How you installed the ["The Boost Graph Library (BGL) >= 1.53"](https://github.com/pgRouting/pgrouting#building-requirements) ?
* on ubuntu try `sudo apt-get install libboost-graph-dev`
   * see https://docs.pgrouting.org/latest/en/pgRouting-installation.html?highlight=libboost%20graph%20dev

**Comment by Cenergy** [comment]
@ImreSamu ,thanks

- My system is centos7.7,I used `yum install boost boost-devel` install,It shows that the version of boost is 1.53.0。So I suspect it's not about boost

**Comment by ImreSamu** [comment]
@Cenergy : 

> So I suspect it's not about boost

maybe you need to upgrade to 1.56 ;   see :  https://github.com/pgRouting/pgrouting/issues/1243#issuecomment-606484909

**Comment by Cenergy** [comment]
@ImreSamu  all right ,thanks

**Comment by Cenergy** [comment]
i  upgrade boost  to 1.68 and then install pgrouting-3.0.2 successfully
