### ISSUE TITLE
documentation : "Wikipedia: Prim's algorithm link"  typo

### ISSUE THREAD

**Issue by ImreSamu** [pgRouting/pgrouting#1365]
**Describe the bug**

imho - the "Wikipedia: Prim's algorithm" link is incorrect in the documentation.

| status | wiki link  |
| ------------- | ------------- |
| now | https://en.wikipedia.org/wiki/Prim'_algorithm |
| suggested | https://en.wikipedia.org/wiki/Prim's_algorithm |

references  ( 24 code results in  the repo ) :
*  https://github.com/pgRouting/pgrouting/search?q=%22https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FPrim%27_algorithm%22

**To Reproduce**
* go https://docs.pgrouting.org/latest/en/prim-family.html#see-also and try **"Wikipedia: Prim’s algorithm"** links.

my result:   "Wikipedia does not have an article with this exact name. "
![image](https://user-images.githubusercontent.com/2217320/85529585-85922900-b60d-11ea-85c0-89c7876e1412.png)

**Expected**

![image](https://user-images.githubusercontent.com/2217320/85530803-837c9a00-b60e-11ea-9e97-6be96c1ec6ca.png)

**Comment by cvvergara** [comment]
In PR #1393
```
* `Wikipedia: Prim's algorithm <https://en.wikipedia.org/wiki/Prim%27s_algorithm>`__
```
