### ISSUE TITLE
driving distance wrapper is not correctly formed

### ISSUE THREAD

**Issue by antonpa** [pgRouting/pgrouting#15]
the distance argument is the max cost cut-off from the Dijkstra's search, but it is also being used to create the BBOX() for selecting which edges to construct the graph with. This is wrong! Cost is not related to or in the same units as the vertex coordinates.

The simplest fix for this would be to pass two arguments to the driving distance function:

distance === maximum cost cut-off for the search buffer === maximum spatial units to expand the source x,y by.

**Comment by woodbri** [comment]
Closing - Wont fix.
