### ISSUE TITLE
Path evaluation on C++ not updated before the results go back to C

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#1616]
**Describe the bug**
While developing I found that there is a small bug on the Path class, and the total cost is not updated properly
As far as I can see affects some functions:
* bellman_ford_driver.cpp
* dijkstra_driver.cpp
* pgr_ksp.hpp

**To Reproduce**
Very difficult to reproduce, but from this test execution:
```
"SELECT  seq, path_seq, node, edge, cost, agg_cost FROM pgr_turnrestrictedpath($$SELECT id, source, target, cost, reverse_cost FROM edge_table$$, $$SELECT * FROM new_restrictions WHERE id > 10$$, 12, 13, 3, false)"
#     Extra records:
#         (2,2,11,12,1.144,1.1689999999999998)
#     Missing records:
#         (2,2,11,12,1.144,1.169)
```
``(2,2,11,12,1.144,1.169)`` ss expected as result of dijkstra
But this is obtained: ``(2,2,11,12,1.144,1.1689999999999998)``
and 1.169 compared with 1689999999999998 is "almost" the same value so there is floating point arithmetic issue.

**Expected behavior**
```
"SELECT  seq, path_seq, node, edge, cost, agg_cost FROM pgr_turnrestrictedpath($$SELECT id, source, target, cost, reverse_cost FROM edge_table$$, $$SELECT * FROM new_restrictions WHERE id > 10$$, 12, 13, 3, false)"
#     Extra records:
#         (2,2,11,12,1.144,1.169)
#     Missing records:
#         (2,2,11,12,1.144,1.169)
```
To get the expected results

**Sample Data**
Using the sample data of the documentation

**Specifications (please complete the following information):**
Fix & release:
* 3.0.3 version
* 3.1.1 version
and fix:
* 3.2.0-dev

**Comment by dkastl** [comment]
This issue is mentioned in https://github.com/pgRouting/admin/wiki/MOTION-2:-Stop-2.x-series-support
