### ISSUE TITLE
Build from source fails on Ubuntu 12.04 LTS 

### ISSUE THREAD

**Issue by elpaso** [pgRouting/pgrouting#168]
There is clearly a problem with paths:

xxx@darkstar ~/tmp/pgrouting/build: sudo make install
[sudo] password for xxx: 
[ 40%] Built target routing_dd
[100%] Built target routing
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/sh: 1: POSTGRESQL_EXECUTABLE-NOTFOUND/pg_config: not found/librouting.so

There is an error in FindPostgreSQL.cmake:

 FIND_PROGRAM(POSTGRESQL_EXECUTABLE postgres)

there is no such "postgres" program in ubuntu.

the correct location to install libs (in my case) was:

/usr/lib/postgresql/8.4/lib/

**Comment by woodbri** [comment]
Closing - Wont Fix.
