### ISSUE TITLE
small improvement suggestion for pgr_nodenetwork function in 2.0 RC

### ISSUE THREAD

**Issue by szalkatamas** [pgRouting/pgrouting#172]
Dear pgRouting Team!
I was trying to use the pgr_NodeNetwork() function to set up noded network from an OSM database in pgRouting 2.0 RC1
I realized that the function ignores the intersection points (or lines) if they are multipoints. This causes for example that a petrol station by a motorway cannot be routed, because the road segment has two intersections with the motorway linestring, its entry and exit point. These MULTIPOINT intersection (in the "intergeom" temporary table) should be exploded to single point as they also should used for splitting the network. 

I put a small improvement in the function, just after creating the "intergeom" table: 

-- Explode multipoints and multilines to handle them as single geometries
    EXECUTE 'insert into intergeom (l1id, l2id, geom)
        select l1id, l2id, (st_dump(geom)).geom
        from intergeom where geometryType(geom) in  (''MULTILINESTRING'' , ''MULTIPOINT'') ';

	GET DIAGNOSTICS p_num = ROW_COUNT;
	raise notice 'Inserted % MULTI* geometries', p_num;

I hope that its useful to others also.

gist link: https://gist.github.com/szalkatamas/9cbb77ff926b9165782b

Cheers,
Tamas

**Comment by cvvergara** [comment]
I'll reopen the issue because pgr_nodeNetwork has several issues and it might need a general redesign and this has to be considered also.

**Comment by cvvergara** [comment]
Main discussion in #419

**Comment by cvvergara** [comment]
@robe2 
I wonder if the modifications to nodeNetwork you made considered this.
Also quoting from original post:
"This causes for example that a petrol station by a motorway cannot be routed"
I created a withPoints family of functions to be in the 2.2 release, that adds additional temporary points to the graph, so the petrol station can be used to route now.
