### ISSUE TITLE
Add PostGIS 3.1 to CI

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#1821]
PostGIS 3.1 got release, so we may want to add it to our CI build matrix.

**Comment by cvvergara** [comment]
For ${PGVER} This exist
```
postgresql-${PGVER}-postgis-3
```
This does not exist
```
postgresql-${PGVER}-postgis-3.1
```
So
postgresql-${PGVER}-postgis-3
has the latest version of postgis regardless of the minor

You can see that it is actually happening here
https://github.com/pgRouting/pgrouting/runs/1766888491?check_suite_focus=true#step:9:60

Almost the same happens with pgRouting (at least on ubuntu)
postgresql-${PGVER}-pgrouting
with no version number

As you can see in this experiment here
https://github.com/cvvergara/experimentvrp/runs/1771282193?check_suite_focus=true#step:5:10
