### ISSUE TITLE
TSP on OSM data: bigint id issue

### ISSUE THREAD

**Issue by rocknrollnerd** [pgRouting/pgrouting#184]
I'm trying to run tsp on some test data from OpenStreetMap. After parsing it by osm2pgrouting, I've got a nodes table (columns id(bigint), lat(double), lon(double)).

After running the query, here's what I get:

    SELECT dmatrix, ids from pgr_makeDistanceMatrix('SELECT id, lon as x, lat as y FROM nodes');
    ERROR:  operator does not exist: integer[] || bigint[]
    LINE 1: SELECT ids || array[r.i]
                       ^
    HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
    QUERY:  SELECT ids || array[r.i]
    CONTEXT:  PL/pgSQL function "pgr_makedistancematrix" line 19 at assignment

Here's the code from pgrouting.sql:

    ids := array[]::integer[];

    sql := 'with nodes as (' || sqlin || ')
        select i, array_agg(dist) as arow from (
            select a.id as i, b.id as j, st_distance(st_makepoint(a.x, a.y), st_makepoint(b.x, b.y)) as dist
              from nodes a, nodes b
             order by a.id, b.id
           ) as foo group by i order by i';

    for r in execute sql loop
        dmatrix := array_cat(dmatrix, array[r.arow]);
        ids := || array[r.i];
    end loop;

Could you also suggest a possible workaround? I tried to edit pgrouting.sql directly,  but couldn't get the changes to apply (not sure if I'm doing it right with postgres)
Thanks.

**Comment by cvvergara** [comment]
This could be related to #140

**Comment by cvvergara** [comment]
I think this is not a bug, becuase everythng in 2.0 is for INTEGER data types not for BIGINT
so I am removing the bug, and keeping the feature request
