### ISSUE TITLE
Change Boost min version to 1.56

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#1850]
**Problem**
1. Due to 1.53, 1.54, 1.55 Boost's geometry lack of some functionality,
Code from boost had to be ported to pgRouting repository [here](https://github.com/pgRouting/pgrouting/tree/master/include/boost)
2. Boost Graph which is used intensively evolves rapidly with new functions that can be added to pgRouting. Normally GSoC students choose which functions from Boost Graph to implement which might not be on the minimum version.

**Improvement**

As the continuation of #1817 (which is porting the changes from #1831)
For 3.2:
- Change Boost min version to 1.56
- If a Boost version 1.X does not have provide the requirements of a pgRouting function `pgr_foo` then:
  - The `pgr_foo` SQL code needs to return an error message stating which minimum version of Boost is needed to work
  - functions that exist and work on pgRouting 3.1should continue working on 3.2
- While Boost min version is less than 1.75
  - C++ standard to be the same minimum as required in Boost graph / geometry
    - C++ standard for pgRouting = max(BoostMin_Graph, BoostMin_Geometry)
    - example, for 1.75, boost graph needs c++03 and boost Geometry needs c++14, so C++14 is the version to use for Boost1.75
  - see this [discussion](https://github.com/boostorg/geometry/issues/590)
  - see this deprecation [PR](https://github.com/boostorg/geometry/pull/689)

- TODO (what I can think as global things at this moment in time)
  - [x] set actions for Boost min version to start from 1.56
  - [x] remove boost code copy of the repository
  - [x] Set conditional testing on functions based on Boost versions
  - [x] Set code to be compiled based on Boost version
  - [x] Make functions to return error when the needed boost version does not exist
  - [x] Document changes

**Comment by chenrui333** [comment]
👋 just heads up, due to the boost compatibility issue, I have closed the [pgrouting 3.1.2 upgrade](https://github.com/Homebrew/homebrew-core/pull/67421) in the homebrew side.

**Comment by sanak** [comment]
@chenrui333 
Thanks for information and sorry for closing the following issue on the Homebrew/homebrew-core repository...
- https://github.com/Homebrew/homebrew-core/pull/67260

@dkastl @cvvergara (CC: @chenrui333)  
Could you check whether pgRouting license is `GPL-2.0-only` or `GPL-2.0-or-later` ? 
(Related with https://github.com/Homebrew/homebrew-core/pull/69231.)
> Well, about pgRouting Homebrew update, `brew audit --strict pgrouting` reported the following, but should we apply `GPL-2.0-only` or `GPL-2.0-or-later` ?
```
$ brew audit --strict pgrouting
:
pgrouting:
  * Formula pgrouting contains deprecated SPDX licenses: ["GPL-2.0"].
    You may need to add `-only` or `-or-later` for GNU licenses (e.g. `GPL`, `LGPL`, `AGPL`, `GFDL`).
    For a list of valid licenses check: https://spdx.org/licenses/
Error: 1 problem in 1 formula detected
```

**Comment by chenrui333** [comment]
yeah, the licensing thing is based on my interpretation with the license header declarations.

**Comment by chenrui333** [comment]
@sanak regarding closing the PR (I am not quite sure what would be the boost library that I can use with for pgrouting 3.1.2)

**Comment by sanak** [comment]
@chenrui333 
Well, latest (=current) boost 1.75.0 is not compatible with current released pgRouting 3.1.2, so I think that the followings are possible.
- **Quick:** depends not boost (latest), but boost@1.60
- **Not quick but quite soon:** wait for next pgRouting 3.1.3

The fix was already merged, so we can build it without changes by `brew install --HEAD pgrouting`.
- https://github.com/pgRouting/pgrouting/issues/795#issuecomment-712990007

**Comment by chenrui333** [comment]
yeah, I can give a try with `boost@1.60` and then wait for the next release for pgrouting 3.1.3. :)

**Comment by chenrui333** [comment]
`boost@1.60` is disabled, so i have to wait for the next release.

**Comment by cvvergara** [comment]
Changes done:
```
if the boost version >= "1.75.0"
   Use c++14 standard
else   
    Set to use c++11 if the compiler supports it
    else Set to use c++0x if the compiler supports it
    else Use the compiler as is. For example on MSVC 
```

**Comment by chenrui333** [comment]
> yeah, I can give a try with `boost@1.60` and then wait for the next release for pgrouting 3.1.3. :)

3.1.3 works for me and merged in https://github.com/Homebrew/homebrew-core/pull/69644
