### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by chenrui333** [pgRouting/pgrouting#1851]
per discussion in [here](https://github.com/pgRouting/pgrouting/issues/1850#issuecomment-761731492)

Can I assume the license should be `GPL-2.0-or-later` for the project (as GPL-2.0 is deprecated)?

cc @dkastl @cvvergara @sanak 

---

relates to https://github.com/Homebrew/homebrew-core/pull/69231

**Comment by cvvergara** [comment]
With this comment I confirm that:
Due to the fact that GPL-2.0 is deprecated we are moving to GPL-2.0-or-later

Administrative issue opened here:
https://github.com/pgRouting/admin/issues/40

**Comment by dkastl** [comment]
I think by making this change, we will prevent anyone using pgRouting code when their project is licensed under "GPLv3 or later". I'm not sure this is our intention and as far as I understand this would be a restriction that was not intended and exactly the reason why "GPL-2.0-or-later" sounded like the right thing.

**Comment by dkastl** [comment]
Confusing ...
- https://spdx.org/licenses/GPL-2.0-or-later.html -> valid
- https://spdx.org/licenses/GPL-2.0-only.html -> valid
- https://spdx.org/licenses/GPL-2.0.html -> deprecated
- https://spdx.org/licenses/GPL-2.0+.html -> deprecated

... because the titles of the license files read the same.
So both still exist, but looking at the URL schema they maybe have seen some clarifications.

**Comment by dkastl** [comment]
So we eventually just use an outdated license text, but with the original intent to also apply to "later" versions of GPL
https://github.com/pgRouting/pgrouting/blob/master/LICENSE#L296-L299

**Comment by sanak** [comment]
@dkastl (CC: @cvvergara, @chenrui333)
Okay, thanks for details.
By the way, I compared spdx license site contents difference between [GPL-2.0-only](https://spdx.org/licenses/GPL-2.0-only.html) and [GPL-2.0-or-later](https://spdx.org/licenses/GPL-2.0-or-later.html) and there seems to be no difference about the description part which you mentioned, but the difference is just quote part.
```diff
-Copyright (C) yyyy name of author
-This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; version 2.
+<one line to give the program's name and an idea of what it does.>
+Copyright (C) <yyyy> <name of author>
+
+This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
```

And current code search result of the quote was latter (`-or-later`) one, so I think that that current license is already `GPL-2.0-or-later` and no need to do quick license update.
- `; either version 2 of the License, or` search result:
   - https://github.com/pgRouting/pgrouting/search?q=%3B+either+version+2+of+the+License%2C+or
   - => Code: 545

**Comment by dkastl** [comment]
Thanks for comparing! I also wanted to do this, and I also didn't expect much changes. Good to see that there isn't any change in the content at all. I guess this was just a change in the name (and URL) for clarification. So this isn't a change of the license on our side I would say.

**Comment by sanak** [comment]
@dkastl Okay, thanks for confirmation.

@chenrui333 
> Can I assume the license should be GPL-2.0-or-later for the project (as GPL-2.0 is deprecated)?

From the above discussion, we can say that the license is `GPL-2.0-or-later` already.

**Comment by chenrui333** [comment]
The license body btw GPL-2.0-only and GPL-2.0-or-later are the same, the difference resides in the header declaration. It would be either applied to every license header in the source files (some projects have inconsistent licenses across the projects, like some source code are from other projects, or some code wants to be dual-licensed) or applied in the README on the project level.

With that being said, it would be preferred to add something in the README (I think this is the easiest way to add license header declaration).

Let me know if that makes sense.

**Comment by sanak** [comment]
@chenrui333 (CC: @dkastl @cvvergara)  
Oh, yes, sure.

My original misunderstanding came from the following README.md line, so that should be updated like `Most features are available under GPL v2 or later`.
https://github.com/pgRouting/pgrouting#license
```markdown
* Most features are available under GPLv2.
```
