### ISSUE TITLE
Missing upgrade path from 3.0.3 to 3.1.0

### ISSUE THREAD

**Issue by homyoung** [pgRouting/pgrouting#1892]
Currently upgrade path from 3.0.3 to 3.1.0 is missing. Is this intentional? Could we add that upgrade path?

**Comment by cvvergara** [comment]
can you give me the set of instructions you used to do the upgrade please.
Include the results of:
```
SELECT * FROM pgr_full_version();
```
before and after trying doing the upgrade.
