### ISSUE TITLE
Making compilation faster include/c_types/geom_text_rt.h

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#1899]
Refer to #1893 for instructions and details.

**Comment by K-Kumar-01** [comment]
@cvvergara 
Can i work on this issue?

**Comment by cvvergara** [comment]
You have a week. starting from now

**Comment by pranavajitnair** [comment]
@cvvergara
Since no one has worked on the issue and it has been over a week, I am resolving this issue.

**Comment by pranavajitnair** [comment]
I have sent the pull request. Please review. #2088
