### ISSUE TITLE
Making compilation faster  include/c_types/graph_enum.h

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#1900]
Refer to #1893 for instructions and details.

**Comment by nishkakotian** [comment]
Working on this issue.

**Comment by nishkakotian** [comment]
The graph_enum.h file does not have any structure declaration in it, so no changes are needed.

**Comment by nishkakotian** [comment]
The graph_enum.h file does not have any structure defined in it.So, no changes are needed.

**Comment by cvvergara** [comment]
Thanks.
