### ISSUE TITLE
Librouting version incompatible

### ISSUE THREAD

**Issue by sercoin** [pgRouting/pgrouting#192]
Hi, I'm using "Centos" and "Postgresql 9.2". I build "pgrouting-master" successfully. I create "routing" database. When i use "routing_core.sql" i get this error 

"psql:/usr/share/postlbs/routing_core.sql:32: ERROR:  incompatible library "/usr/pgsql-9.2/lib/librouting.so": version mismatch
DETAIL:  Server is version 9.2, library is version 8.4."  
"routing_core_wrappers.sql" and "routing_topology.sql" works normal. I try to build different pgrouting versions but result is same. What can i do to fix this problem? Can you help me?

**Comment by woodbri** [comment]
Closing - Wont fix.
