### ISSUE TITLE
Making compilation faster  include/c_types/trsp_types.h

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#1930]
Refer to #1893 for instructions and details.

**Comment by PrachiAgarwal19** [comment]
I found this issue on ovio.org and would love to contribute! [If this is still assigned, kindly assign this to me. I am new to open source contributions, so this would be my first issue that I would be working on. Thankyou.

**Comment by cvvergara** [comment]
@PrachiAgarwal19 
Please be my guest ans solve the issue

**Comment by PrachiAgarwal19** [comment]
Thankyou!

**Comment by cvvergara** [comment]
Issue open to anyone

**Comment by cvvergara** [comment]
There has been no progress.
I am taking the issue now
