### ISSUE TITLE
Added Issue templates in the Issue Section

### ISSUE THREAD

**Issue by Ayush7614** [pgRouting/pgrouting#1969]
Like we have to add issue templates like bug report, feature request etc

**Comment by Ayush7614** [comment]
Please assign me this issue

**Comment by cvvergara** [comment]
I do not understand what is the goal you want to achieve.

**Comment by cvvergara** [comment]
Label as discussion until the issue is clear and we can make a decision

**Comment by ImreSamu** [comment]
@Ayush7614  :

> Issue templates in the Issue Section
> Like we have to add issue templates like bug report, feature request etc

IMHO:  check the current organization templates:
  *  https://github.com/pgRouting/.github/tree/master/.github/ISSUE_TEMPLATE

**Comment by cvvergara** [comment]
@ImreSamu 
Make a suggestion in form of a Pull Request (best way to show the specific ideas you have)
and we will discuss in the PR.

**Comment by Ayush7614** [comment]
Ok @cvvergara sir thanku for responding

**Comment by Ayush7614** [comment]
I will make PR soon

**Comment by dkastl** [comment]
@Ayush7614 I think there are already issue templates for all repositories in pgRouting organization. They are named more friendly/understandable, but they should do the job:
- note
- improvement
- problem

We do not intend to manage them seperately for every repository, if this is what you have in mind.

**Comment by cvvergara** [comment]
There has been no progress on this idea, will close the issue based on @dkastl comment.
