### ISSUE TITLE
Document the release process

### ISSUE THREAD

**Issue by woodbri** [pgRouting/pgrouting#197]
The release process is very complicated and has a lot of moving parts that all need to be coordinated. V2.0.0 had some pieces that were not done ans some that were probably done wrong.

TAGS: what is our standard for tags names
TAGS: when we change the tag, tests and doc-tests and doc files need to be updated. which files? do we need a script to bump the version?
What is the order of branches, tagging, pushing, etc so things are correct.
When does VERSION got editted and to what?

**Comment by cvvergara** [comment]
Doing it in issue #364
