### ISSUE TITLE
Unit test

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#20]
create automated tests to ensure all functions work properly when (or before) compiling the binaries

**Comment by dkastl** [comment]
It seems pgTap became the most popular framework for testing PostgreSQL databases. It also support performance testing.

So i would propose to look at this again for the next major release.

**Comment by cvvergara** [comment]
I am converting tests to use pgTap.
I will start with the already "fixed" functions.
Later I will make tests for the "non fixed functions".

**Comment by cvvergara** [comment]
Unit tests I think with over 20,000 using pgtap, we can close this.
We ask for unit tests to developers.
