### ISSUE TITLE
Translators issues

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#200]
Please check the Wiki page in 
https://github.com/pgRouting/pgrouting/wiki/Translation-Process
Use this issue to post your questions

**Comment by dkastl** [comment]
Let's check your instructions for the next release. (Renamed the title to actually make it a task/issue)

**Comment by cvvergara** [comment]
@dkastl 
given the fact that basically there is going to be a gradual refactoring to reach V3.0 and tht translations take time, What if I move translation issues to 3.0, and we provide the translation only on V3.0? in the meantime as we move towards 3.0, the translators have plenty of time to translate :)

**Comment by woodbri** [comment]
+1 I think this makes sense. Also if we get updated translations they can be posted in the interim on the website.

**Comment by cvvergara** [comment]
Milestone set to 3.0, and kept tag of work on progress, because that is what it should be happening.

**Comment by dkastl** [comment]
I agree, too.

**Comment by cvvergara** [comment]
We have Spanish translations going with transifex, and transifex makes PR each time a file is finished, so Closing.
