### ISSUE TITLE
Driving Distance function does not return a useful edge id

### ISSUE THREAD

**Issue by YenTheFirst** [pgRouting/pgrouting#203]
This is brought up tangentially in another issue (https://github.com/pgRouting/pgrouting/issues/51), 
and alluded to in the [2.0 documentation](http://docs.pgrouting.org/2.0/en/src/driving_distance/doc/dd_driving_distance.html#pgr-driving-distance) "id2: edge ID (this is probably not a useful item)",
 but this really needs to be documented as a specific issue.

The driving distance function should return the ids of edges actually traversed, and the cost to traverse those edges. i.e., the output of pgr_drivingDistance should describe a shortest path tree.

As it is currently, you can only get information on the cost to reach nodes, but not what edges are traversed in reaching those nodes. It returns an edge_id, but this is not actually related to anything.

demonstration of problem, using the [sample data network](http://docs.pgrouting.org/2.0/en/doc/src/developer/sampledata.html#sampledata):

the shortest path from node 1 to 6 is along edges 1,4,8:
````
select * from pgr_dijkstra('SELECT id, source, target, cost FROM edge_table', 1, 6, false, false);
 seq | id1 | id2 | cost 
-----+-----+-----+------
   0 |   1 |   1 |    1
   1 |   2 |   4 |    1
   2 |   5 |   8 |    1
   3 |   6 |  -1 |    0
````

however, doing a driving distance query from node 1:

```
select * from pgr_drivingdistance('SELECT id, source, target, cost FROM edge_table', 1, 3, false, false);
 seq | id1 | id2 | cost 
-----+-----+-----+------
   0 |   1 |   1 |    0
   1 |   2 |   4 |    1
   2 |   5 |  10 |    2
   3 |   6 |   9 |    3
   4 |   8 |   7 |    3
   5 |  10 |  10 |    3
```
you can see that it does not include edge 8. rather, it includes edge 9, which, while connected to node 6, would not actually be crossed if traveling only 3 distance units from node 1. the expected output should be:
```
 seq | id1 | id2 | cost 
-----+-----+-----+------
   0 |   1 |   ? |    0
   1 |   2 |   1 |    1
   2 |   5 |   4 |    2
   3 |   6 |   8 |    3
   4 |   8 |   7 |    3
   5 |  10 |  10 |    3
```

where the edge id associated with the starting node could be anything, possibly -1 as a marker.

**Comment by cvvergara** [comment]
Work in progress
See #278,  For the case where there is no edge to traverse, I am returning -1 as suggested, 
![issue278-1](https://cloud.githubusercontent.com/assets/5035290/7890160/c3030de0-0609-11e5-8dcb-12e05167831c.png)
I will have tests with sample data soon.
