### ISSUE TITLE
Missing support files for documentation

### ISSUE THREAD

**Issue by woodbri** [pgRouting/pgrouting#209]
Looking at my appache error.log I am seeing a the following files as 404:

```
pgr2-doc/2.0/en/_static/theme_extras.js
pgr2-doc/dev/en/_static/print.css
```

These should probably be added to github in the develop branch and may be the develop_2_0_1 branch.

Neither of these files are buried in our repository, so they probably need to be added and then copied appropriately to build and installed.

**Comment by cvvergara** [comment]
```
locate theme_extras
/usr/share/javascript/sphinxdoc/1.0/theme_extras.js
/usr/share/sphinx/themes/scrolls/static/theme_extras.js
```

**Comment by woodbri** [comment]
files on newer os. closing.
