### ISSUE TITLE
Delete Appveyor project

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#2099]
On Appveyor the following project exists, which isn't necessary anymore thanks to GH Actions:

- https://ci.appveyor.com/project/Georepublic/pgrouting/
- https://github.com/pgRouting/pgrouting/pull/2097
 
@krashish8 @cvvergara , is it safe to delete the Appveyor project already, or do we need to wait until the next release?

**Comment by cvvergara** [comment]
@dkastl you can now remove appveyor service
