### ISSUE TITLE
Add a NEWS file 

### ISSUE THREAD

**Issue by strk** [pgRouting/pgrouting#212]
The file would be useful to see what changed between versions, from an high-level point of view.

See http://www.gnu.org/prep/standards/html_node/NEWS-File.html#NEWS-File

**Comment by cvvergara** [comment]
@strk 
It is on the checklist for 2.1 that I have to do, I did so many changes, do you have an idea on how to auto generate so that I simplify my life a little?

**Comment by woodbri** [comment]
Probably the best we can do at the moment is to do something like:
```
git log > news.tmp
```
and then edit news.tmp and delete useless lines. Then you might also list the bugs that have been closed against this release. Unfortunately, we do not have a real automated way to do this. In the future we might want to write a standard on how to annotate commit messages we want to later extract for the changelog or NEWS file.

**Comment by strk** [comment]
No way to automate NEWS, as the goal for that file is to be high-level
and not too much detailed. Only important things should be noted.

**Comment by cvvergara** [comment]
I made this one:
https://github.com/pgRouting/pgrouting/blob/develop/doc/src/changelog/2_1_0.rst
You think its enough?

**Comment by strk** [comment]
I filed the ticket specifically for a file called "NEWS" in the top-level directory.
The good thing of following standards is that you enable people expecting familiar things :)

**Comment by strk** [comment]
I'd have no problem with a NEWS file redirecting the reader deep under doc directories...

**Comment by cvvergara** [comment]
In this one you mean?
http://pgrouting.org/

**Comment by strk** [comment]
In the root directory of the source code tree.
See the link to the gnu standards in the original ticket submission.

**Comment by cvvergara** [comment]
peeking into postGIS
like this:
https://github.com/postgis/postgis/blob/svn-trunk/ChangeLog

**Comment by strk** [comment]
Are you deliberately trying to avoid the standard ?
https://github.com/postgis/postgis/blob/svn-trunk/NEWS

**Comment by cvvergara** [comment]
No, I am trying to understand.

**Comment by cvvergara** [comment]
I think I understood,
https://github.com/pgRouting/pgrouting/blob/develop_2_1_0/NEWS

**Comment by strk** [comment]
Sounds good to me, thanks ! :)

**Comment by cvvergara** [comment]
Added the task of updating NEWS in the check list.

**Comment by sanak** [comment]
I am checking both of pgRouting 2.0 and 2.1 on my Mac OSX Homebrew environment,
but the following installed files difference seems not to be mentioned in the NEWS file.
Also, "*_legacy.sql" seems to be removed, but if this is a new limitation, mentioning about it will be necessary.

pgRouting-2.0:
<pre>
/usr/local/Cellar/postgresql/9.4.4/lib/librouting_bd.so
/usr/local/Cellar/postgresql/9.4.4/lib/librouting.so
/usr/local/Cellar/postgresql/9.4.4/share/postgresql/extension/pgrouting--2.0.0.sql
/usr/local/Cellar/postgresql/9.4.4/share/postgresql/extension/pgrouting.control
/usr/local/Cellar/postgresql/9.4.4/share/postgresql/extension/pgrouting_legacy.sql
/usr/local/Cellar/postgresql/9.4.4/share/postgresql/contrib/pgrouting-2.0/pgrouting.sql
/usr/local/Cellar/postgresql/9.4.4/share/postgresql/contrib/pgrouting-2.0/pgrouting.control
/usr/local/Cellar/postgresql/9.4.4/share/postgresql/contrib/pgrouting-2.0/pgrouting_legacy.sql
/usr/local/Cellar/postgresql/9.4.4/share/postgresql/extension/pgrouting_dd_legacy.sql
/usr/local/Cellar/postgresql/9.4.4/share/postgresql/contrib/pgrouting-2.0/pgrouting_dd_legacy.sql
/usr/local/Cellar/postgresql/9.4.4/lib/librouting_tsp.so
/usr/local/Cellar/postgresql/9.4.4/lib/librouting_ksp.so
/usr/local/Cellar/postgresql/9.4.4/lib/librouting_dd.so
</pre>

pgRouting-2.1:
<pre>
/usr/local/Cellar/postgresql/9.4.4/lib/librouting-2.1.so
/usr/local/Cellar/postgresql/9.4.4/share/postgresql/extension/pgrouting--2.1.0.sql
/usr/local/Cellar/postgresql/9.4.4/share/postgresql/extension/pgrouting.control
/usr/local/Cellar/postgresql/9.4.4/share/postgresql/contrib/pgrouting-2.1/pgrouting.sql
/usr/local/Cellar/postgresql/9.4.4/share/postgresql/contrib/pgrouting-2.1/pgrouting.control
/usr/local/Cellar/postgresql/9.4.4/share/postgresql/contrib/pgrouting-2.1
</pre>

**Comment by strk** [comment]
+1, thanks for reviewing !

**Comment by cvvergara** [comment]
oh, yes!, now only one library is generated. Forgot to mention it.
About the legacy, shall 2.1 keep them? (they are legacy from 1.0)

**Comment by dkastl** [comment]
I would vote to drop the legacy files.
We could consult the mailing list, but I think it just adds more functions we need to look after.
Quite a long time has passed since 2.0 was released and not sure if someone still uses old PostgreSQL/PostGIS and doesn't want to upgrade. But then why should one upgrade pgRouting?

If someone really needs it, then it had to be funded.

About having the .so files all combined in one. I think that's something not relevant to users. Would there be any advantage of having them separate? I can't find any.

**Comment by woodbri** [comment]
+1 on dropping it from the release.

We do not need to delete the file from the repository, in case someone wants it, just don't include it in the release and note that it has been dropped as obsolete so user that were using it will need to update their code to use the released functions.

**Comment by sanak** [comment]
Okay, about dropping legacy files with some notes.
(Actually, I forget almost of pgRouting 1.x function syntax...)
Then, modifying the following document will be necessary also.
http://docs.pgrouting.org/v2.1.0-alpha/src/common/doc/legacy.html

And about combining all .so files to one, I think that just mentioning about it to the NEWS is enough.

**Comment by cvvergara** [comment]
I am reopening as NEWS documentation is being modified.

**Comment by cvvergara** [comment]
Note: All changes are being done to branch develop_2_1_0

- Modified [NEWS](https://github.com/pgRouting/pgrouting/blob/develop_2_1_0/NEWS)
- About legacy
  -  [Documentation](http://docs.pgrouting.org/v2.1.0-alpha/src/common/doc/legacy.html) is kept but not linked to the main index.
  -  [Code](https://github.com/pgRouting/pgrouting/blob/develop_2_1_0/src/common/sql/pgrouting_legacy.sql) is kept put not insalled

**Comment by cvvergara** [comment]
Now Develop  has the NEWS file
