### ISSUE TITLE
Add minimum dependencies for Boost, CGAL, and LaTeX to build documentation

### ISSUE THREAD

**Issue by smathermather** [pgRouting/pgrouting#218]
Add minimum dependencies for Boost, CGAL, and LaTeX to build documentation so users know, e.g. if they can use the versions in their package manager or need to compile from source for certain libraries.

**Comment by cvvergara** [comment]
Boost is OK, CGAl wont be used on V3.0 will close this one

**Comment by smathermather** [comment]
w00t!
