### ISSUE TITLE
pgrouting package not signed in Cent Os 7 repository

### ISSUE THREAD

**Issue by alessandroarmellini** [pgRouting/pgrouting#2204]
We're experiencing the following error in updating the package pgrouting with yum on CentOs 7

Package pgrouting_10-3.0.6-1.rhel7.x86_64.rpm is not signed

Should it be something involved with the repository (so we have to send the bug to the pgdg) or is something you can manage?

Thank you in advance

Alessandro

**Comment by dkastl** [comment]
Maybe @devrimgunduz can answer this question?

**Comment by robe2** [comment]
@alessandroarmellini  you should bring up the issue on the yum pgdg mailing list -- https://www.postgresql.org/list/pgsql-pkg-yum/

Details of sign up are here - https://lists.postgresql.org/

**Comment by alessandroarmellini** [comment]
Ok... issue submitted to pgdg mailing list. I'll let you know their reply.

Thank you again.

**Comment by alessandroarmellini** [comment]
The package is fixed now. 

Thank you all for the help!

**Comment by dkastl** [comment]
Great, and thanks a lot for caring about it! That's very appreciated!
