### ISSUE TITLE
Does it support the installation of Alpine version operating system?

### ISSUE THREAD

**Issue by wmabcde** [pgRouting/pgrouting#2218]
**Problem**

Does it support the installation of Alpine version operating system? Both Postgres and PostGIS support the installation of Alpine version operating system. If so, what do I need to do?
**To Reproduce**

**Expectation**

**Sample Data**

**Platform/versions**

```
SELECT version();
SELECT postgis_full_version();
SELECT pgr_version();
```

**Comment by dkastl** [comment]
This is a duplicate question of https://github.com/pgRouting/docker-pgrouting/issues/46
