### ISSUE TITLE
Error to build PgRouting 3.3.0: PostgreSQL not found

### ISSUE THREAD

**Issue by francot** [pgRouting/pgrouting#2243]
**Problem**
I need to upgrade PgRouting 3.0.0 to 3.3.0

I try to compile PgRouting 3.3.0 and get this error:
-- CMAKE_BUILD_TYPE Release
-- DOXYGEN_MINIMUM_VERSION=1.7
-- SPHINX_MINIMUM_VERSION=4.0
-- POSTGRESQL_MINIMUM_VERSION=9.2.0
-- BOOST_MINIMUM_VERSION=1.56.0
-- POSTGIS_MINIMUM_VERSION=2.0.0
-- POSTGRESQL_PG_CONFIG is /usr/bin/pg_config
-- POSTGRESQL_EXECUTABLE is /usr/lib/postgresql/12/bin/postgres
-- POSTGRESQL_VERSION_STRING in FindPostgreSQL.cmake is PostgreSQL 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
-- PostgreSQL not found.
CMake Error at CMakeLists.txt:168 (message):
  PostgreSQL not found - Please check your PostgreSQL installation.

But Postgresql installation is ok

dpkg --get-selections | grep postgres return:

postgresql					install
postgresql-12					install
postgresql-12-pgrouting				install
postgresql-12-pgrouting-scripts			install
postgresql-12-postgis-3				install
postgresql-12-postgis-3-scripts			install
postgresql-client-12				install
postgresql-client-common			install
postgresql-common				install
postgresql-contrib				install

**To Reproduce**
download from:
https://github.com/pgRouting/pgrouting/releases/download/v3.3.0/pgrouting-3.3.0.tar.gz

tar xvfz pgrouting-3.3.0.tar.gz
cd pgrouting-3.3.0

mkdir build
cd build
cmake  ..

**Platform/versions**

SELECT version();

PostgreSQL 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit

SELECT postgis_full_version();

POSTGIS="3.0.0 r17983" [EXTENSION] PGSQL="120" GEOS="3.8.0-CAPI-1.13.1 " SFCGAL="1.3.7" PROJ="6.3.1" GDAL="GDAL 3.0.4, released 2020/01/28" LIBXML="2.9.4" LIBJSON="0.13.1" LIBPROTOBUF="1.3.3" WAGYU="0.4.3 (Internal)" TOPOLOGY RASTER

SELECT pgr_version();

3.0.0-rc1

```

**Comment by francot** [comment]
Thanks a lot I solve with:

`sudo aptitude install postgresql-server-dev-12`

I use aptitude to manage all dependencies.

**Comment by ImreSamu** [comment]
> You think is necessary update documentation to specify that postgresql-server-dev-* is needed

see the "Database dependencies" https://docs.pgrouting.org/latest/en/pgRouting-installation.html#dependencies
```
sudo apt-get install
    postgresql-10 \
    postgresql-server-dev-10 \
    postgresql-10-postgis
```    

IMHO: if you can improve the documentation - please create a PR
