### ISSUE TITLE
Use parsed-literal instead of code-block on signatures

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#2244]
Using `code-block` does not allow links to sections on the documentation page

![image](https://user-images.githubusercontent.com/5035290/152012494-e09101f1-7a92-4bed-a429-e88a8f5e7c64.png)

Using `parsed-literal` allows links, specially useful for the inner queries

![image](https://user-images.githubusercontent.com/5035290/152012366-e5cfdda4-8cd5-4fdc-8adf-a2ace5909cad.png)

- [x] doc/allpairs/allpairs-family.rst
- [x] doc/allpairs/pgr_floydWarshall.rst
- [x] doc/allpairs/pgr_johnson.rst
- [x] doc/alpha_shape/pgr_alphaShape.rst
- [x] doc/astar/aStar-family.rst
- [x] doc/astar/pgr_aStar.rst
- [x] doc/astar/pgr_aStarCost.rst
- [x] doc/astar/pgr_aStarCostMatrix.rst
- [x] doc/bdAstar/bdAstar-family.rst
- [x] doc/bdAstar/pgr_bdAstar.rst
- [x] doc/bdAstar/pgr_bdAstarCost.rst
- [x] doc/bdAstar/pgr_bdAstarCostMatrix.rst
- [x] doc/bdDijkstra/bdDijkstra-family.rst
- [x] doc/bdDijkstra/pgr_bdDijkstra.rst
- [x] doc/bdDijkstra/pgr_bdDijkstraCost.rst
- [x] doc/bdDijkstra/pgr_bdDijkstraCostMatrix.rst
- [x] doc/bellman_ford/pgr_bellmanFord.rst
- [x] doc/bellman_ford/pgr_edwardMoore.rst
- [x] doc/breadthFirstSearch/pgr_binaryBreadthFirstSearch.rst
- [x] doc/breadthFirstSearch/pgr_breadthFirstSearch.rst
- [x] doc/chinese/chinesePostmanProblem-family.rst
- [x] doc/chinese/pgr_chinesePostman.rst
- [x] doc/chinese/pgr_chinesePostmanCost.rst
- [x] doc/coloring/coloring-family.rst
- [x] doc/coloring/pgr_bipartite.rst
- [x] doc/coloring/pgr_edgeColoring.rst
- [x] doc/coloring/pgr_sequentialVertexColoring.rst
- [x] doc/components/components-family.rst
- [x] doc/components/pgr_articulationPoints.rst
- [x] doc/components/pgr_biconnectedComponents.rst
- [x] doc/components/pgr_bridges.rst
- [x] doc/components/pgr_connectedComponents.rst
- [x] doc/components/pgr_makeConnected.rst
- [x] doc/components/pgr_strongComponents.rst
- [x] doc/contraction/contraction-family.rst
- [x] doc/contraction/pgr_contraction.rst
- [x] doc/dagShortestPath/pgr_dagShortestPath.rst
- [x] doc/dijkstra/dijkstra-family.rst
- [x] doc/dijkstra/pgr_dijkstra.rst
- [x] doc/dijkstra/pgr_dijkstraCost.rst
- [x] doc/dijkstra/pgr_dijkstraCostMatrix.rst
- [x] doc/dijkstra/pgr_dijkstraNear.rst
- [x] doc/dijkstra/pgr_dijkstraNearCost.rst
- [x] doc/dijkstra/pgr_dijkstraVia.rst
- [x] doc/dominator/pgr_lengauerTarjanDominatorTree.rst
- [x] doc/driving_distance/drivingDistance-category.rst
- [x] doc/driving_distance/pgr_drivingDistance.rst
- [x] doc/ksp/KSP-category.rst
- [x] doc/ksp/pgr_KSP.rst
- [x] doc/lineGraph/pgr_lineGraph.rst
- [x] doc/lineGraph/pgr_lineGraphFull.rst
- [x] doc/lineGraph/transformation-family.rst
- [x] doc/max_flow/flow-family.rst
- [x] doc/max_flow/pgr_boykovKolmogorov.rst
- [x] doc/max_flow/pgr_edgeDisjointPaths.rst
- [x] doc/max_flow/pgr_edmondsKarp.rst
- [x] doc/max_flow/pgr_maxCardinalityMatch.rst
- [x] doc/max_flow/pgr_maxFlow.rst
- [x] doc/max_flow/pgr_maxFlowMinCost.rst
- [x] doc/max_flow/pgr_maxFlowMinCost_Cost.rst
- [x] doc/max_flow/pgr_pushRelabel.rst
- [x] doc/mincut/pgr_stoerWagner.rst
- [x] doc/pickDeliver/VRP-category.rst
- [x] doc/pickDeliver/pgr_pickDeliver.rst
- [x] doc/pickDeliver/pgr_pickDeliverEuclidean.rst
- [x] doc/planar/pgr_isPlanar.rst
- [x] doc/spanningTree/kruskal-family.rst
- [x] doc/spanningTree/pgr_kruskal.rst
- [x] doc/spanningTree/pgr_kruskalBFS.rst
- [x] doc/spanningTree/pgr_kruskalDD.rst
- [x] doc/spanningTree/pgr_kruskalDFS.rst
- [x] doc/spanningTree/pgr_prim.rst
- [x] doc/spanningTree/pgr_primBFS.rst
- [x] doc/spanningTree/pgr_primDD.rst
- [x] doc/spanningTree/pgr_primDFS.rst
- [x] doc/spanningTree/pgr_randomSpanTree.rst
- [x] doc/spanningTree/prim-family.rst
- [x] doc/spanningTree/spanningTree-family.rst
- [x] doc/src/cost-category.rst
- [x] doc/src/costMatrix-category.rst
- [x] doc/src/experimental.rst
- [x] doc/src/index.rst
- [x] doc/src/pgRouting-concepts.rst
- [x] doc/src/pgRouting-installation.rst
- [x] doc/src/pgRouting-introduction.rst
- [x] doc/src/proposed.rst
- [x] doc/src/release_notes.rst
- [x] doc/src/routingFunctions.rst
- [x] doc/src/sampledata.rst
- [x] doc/src/support.rst
- [x] doc/topologicalSort/pgr_topologicalSort.rst
- [x] doc/topology/pgr_analyzeOneWay.rst
- [x] doc/topology/pgr_createTopology.rst
- [x] doc/topology/pgr_createVerticesTable.rst
- [x] doc/topology/pgr_analyzeGraph.rst
- [x] doc/topology/pgr_extractVertices.rst
- [x] doc/topology/pgr_nodeNetwork.rst
- [x] doc/topology/topology-functions.rst
- [x] doc/transitiveClosure/pgr_transitiveClosure.rst
- [x] doc/traversal/pgr_depthFirstSearch.rst
- [x] doc/traversal/traversal-family.rst
- [x] doc/trsp/TRSP-family.rst
- [x] doc/trsp/pgr_trsp.rst
- [x] doc/trsp/pgr_trsp_withPoints.rst
- [x] doc/trsp/pgr_trspVia.rst
- [x] doc/trsp/pgr_trspVia_withPoints.rst
- [x] doc/trsp/pgr_trspviaedges.rst
- [x] doc/trsp/pgr_trspviavertices.rst
- [x] doc/trsp/pgr_turnRestrictedPath.rst
- [x] doc/tsp/TSP-family.rst
- [x] doc/tsp/pgr_TSP.rst
- [x] doc/tsp/pgr_TSPeuclidean.rst
- [x] doc/version/pgr_full_version.rst
- [x] doc/version/pgr_version.rst
- [x] doc/vrp_basic/pgr_vrpOneDepot.rst
- [x] doc/withPoints/pgr_withPoints.rst
- [x] doc/withPoints/pgr_withPointsCost.rst
- [x] doc/withPoints/pgr_withPointsCostMatrix.rst
- [x] doc/withPoints/pgr_withPointsDD.rst
- [x] doc/withPoints/pgr_withPointsKSP.rst
- [x] doc/withPoints/pgr_withPointsVia.rst
- [x] doc/withPoints/withPoints-family.rst

**Comment by cvvergara** [comment]
Please write in a comment your intended changes.
Example:
I am working on these:
- doc/trsp/pgr_trsp.rst
- doc/trsp/TRSP-family.rst
- doc/trsp/pgr_turnRestrictedPath.rst

**Comment by cvvergara** [comment]
If needed, to make it standard (and shorter) using SQL

This is a link to the title
```
`Edges SQL`_
```
This is the title
```
Edges SQL
---------------------------------------------------------
```
They should match.
If needed change `Query` to `SQL`

**Comment by cvvergara** [comment]
Will be using bold font on unnamed parameters

**Comment by nitishchauhan0022** [comment]
Hello Everyone, I also want to work on this issue. I am starting with experimental functions

- doc/bellman_ford/pgr_bellmanFord.rst
- doc/bellman_ford/pgr_edwardMoore.rst

**Comment by cvvergara** [comment]
I will be doing maxflow functions

**Comment by nitishchauhan0022** [comment]
I will work on
- doc/breadthFirstSearch/pgr_binaryBreadthFirstSearch.rst
-  doc/breadthFirstSearch/pgr_breadthFirstSearch.rst

**Comment by sbdtu5498** [comment]
@cvvergara @nitishchauhan0022 I will be working on the following experimental functions:-
- doc/coloring/coloring-family.rst
- doc/coloring/pgr_bipartite.rst
- doc/coloring/pgr_edgeColoring.rst
- doc/coloring/pgr_sequentialVertexColoring.rst

**Comment by shobhit162** [comment]
@cvvergara, @nitishchauhan0022 @sbdtu5498  I will be working on the following functions:-

- doc/components/pgr_articulationPoints.rst
-  doc/components/pgr_biconnectedComponents.rst
-  doc/components/pgr_bridges.rst

**Comment by cvvergara** [comment]
I am working on topology

**Comment by shobhit162** [comment]
> @cvvergara, @nitishchauhan0022 @sbdtu5498 I will be working on the following functions:-
> 
> * doc/components/pgr_articulationPoints.rst
> * doc/components/pgr_biconnectedComponents.rst
> * doc/components/pgr_bridges.rst

This is to inform that I will submit a PR on 19 May, currently I'm finishing all my academics work

**Comment by cvvergara** [comment]
I am also working on ksp

**Comment by cvvergara** [comment]
ksp is finished PR is pending
