### ISSUE TITLE
pgRouting and PostgreSQL 9.2 installation errors RHEL 5.3 Issue

### ISSUE THREAD

**Issue by ahid** [pgRouting/pgrouting#231]
Hello,

I have a problem in installing pgRouting 2 with PostgreSQL 9.2 on Linux (Red Hat Enterprise Linux Server release 5.3 (Tikanga) ). I’ve tried to install it using rpm, but it failed with missing dependences error, even all dependences are installed and available in /usr/lib64. Below is the error:

[root@quwic-s03-db ahide]# rpm -ivh pgRouting-2.0.0-1.fc20.x86_64.rpm
error: Failed dependencies:
        libCGAL.so.10()(64bit) is needed by pgRouting-2.0.0-1.fc20.x86_64
        libboost_system.so.1.54.0()(64bit) is needed by pgRouting-2.0.0-1.fc20.x86_64
        libboost_thread.so.1.54.0()(64bit) is needed by pgRouting-2.0.0-1.fc20.x86_64
        libc.so.6(GLIBC_2.14)(64bit) is needed by pgRouting-2.0.0-1.fc20.x86_64
        libgmp.so.10()(64bit) is needed by pgRouting-2.0.0-1.fc20.x86_64
        libstdc++.so.6(GLIBCXX_3.4.11)(64bit) is needed by pgRouting-2.0.0-1.fc20.x86_64
        libstdc++.so.6(GLIBCXX_3.4.15)(64bit) is needed by pgRouting-2.0.0-1.fc20.x86_64
        libstdc++.so.6(GLIBCXX_3.4.9)(64bit) is needed by pgRouting-2.0.0-1.fc20.x86_64
        postgis is needed by pgRouting-2.0.0-1.fc20.x86_64
        postgresql-server is needed by pgRouting-2.0.0-1.fc20.x86_64
        rpmlib(FileDigests) <= 4.6.0-1 is needed by pgRouting-2.0.0-1.fc20.x86_64
        rpmlib(PayloadIsXz) <= 5.2-1 is needed by pgRouting-2.0.0-1.fc20.x86_64

After that I decided to build it from the source, but I couldn’t and it failed with errors, please see the below:

[root@quwic-s03-db build]# cmake -DWITH_DD=ON ..
-- The C compiler identification is GNU 4.1.2
-- The CXX compiler identification is GNU 4.1.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- PGROUTING_GIT_TAG: pgrouting-2.0.0
-- PGROUTING_GIT_BUILD: 0
-- PGROUTING_GIT_HASH: f26831f
-- PGROUTING_GIT_BRANCH: master
-- PGROUTING_VERSION_REVISION_NAME: f26831f master
-- PGROUTING_VERSION_REVISION_HASH: f26831f
-- UNIX=1
-- WIN32=
-- POSTGRESQL_EXECUTABLE is /opt/PostgreSQL/9.2/bin/postgres
-- POSTGRESQL_PG_CONFIG is /opt/PostgreSQL/9.2/bin/pg_config
-- POSTGRESQL_INCLUDE_DIR: /opt/PostgreSQL/9.2/include/postgresql/server
-- POSTGRESQL_LIBRARIES: /opt/PostgreSQL/9.2/lib
-- Boost version: 1.55.0
-- Boost headers were found here: /usr/local/include
-- POSTGRESQL_VERSION_STRING is PostgreSQL 9.2.4
-- POSTGRESQL_VERSION is 9.2.4
-- PGSQL_VERSION is 92
-- Install directory for libraries is set to /opt/PostgreSQL/9.2/lib/postgresql
-- Contrib directory for SQL files is set to /opt/PostgreSQL/9.2/share/postgresql/contrib/pgrouting-2.0
-- Extension directory for SQL files is set to /opt/PostgreSQL/9.2/share/postgresql/extension
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   thread
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   thread
--   system
-- CGAL_INCLUDE_DIR=/usr/local/include
-- CGAL_LIBRARIES=/usr/local/lib/libCGAL.so
-- BOOST_THREAD_LIBRARIES=/usr/local/lib/libboost_thread.so;/usr/local/lib/libboost_system.so
-- GMP_LIBRARIES=/usr/lib64/libgmp.so
-- Found CGAL: /usr/local/include, /usr/local/lib/libCGAL.so, /usr/local/lib/libboost_thread.so;/usr/local/lib/libboost_system.so, /usr/lib64/libgmp.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ahide/pgrouting-2.0.0/build
[root@quwic-s03-db build]# make
Scanning dependencies of target trsp
[  2%] Building C object src/trsp/src/CMakeFiles/trsp.dir/trsp.c.o
[  5%] Building CXX object src/trsp/src/CMakeFiles/trsp.dir/trsp_core.cpp.o
[  8%] Building CXX object src/trsp/src/CMakeFiles/trsp.dir/GraphDefinition.cpp.o
[  8%] Built target trsp
Scanning dependencies of target astar
[ 11%] Building C object src/astar/src/CMakeFiles/astar.dir/astar.c.o
[ 14%] Building CXX object src/astar/src/CMakeFiles/astar.dir/astar_boost_wrapper.cpp.o
/usr/include/libintl.h:40: error: expected unqualified-id before âconstâ
/usr/include/libintl.h:40: error: expected `)' before âconstâ
/usr/include/libintl.h:40: error: expected initializer before âconstâ
/usr/include/libintl.h:45: error: expected unqualified-id before âconstâ
/usr/include/libintl.h:45: error: expected `)' before âconstâ
/usr/include/libintl.h:45: error: expected initializer before âconstâ
/usr/include/libintl.h:62: error: expected unqualified-id before âunsignedâ
/usr/include/libintl.h:62: error: expected `)' before âunsignedâ
/usr/include/libintl.h:62: error: expected `)' before âunsignedâ
/usr/include/libintl.h:62: error: expected initializer before âunsignedâ
/usr/include/libintl.h:68: error: expected unqualified-id before âunsignedâ
/usr/include/libintl.h:68: error: expected `)' before âunsignedâ
/usr/include/libintl.h:68: error: expected `)' before âunsignedâ
/usr/include/libintl.h:68: error: expected initializer before âunsignedâ
make[2]: *** [src/astar/src/CMakeFiles/astar.dir/astar_boost_wrapper.cpp.o] Error 1
make[1]: *** [src/astar/src/CMakeFiles/astar.dir/all] Error 2
make: *** [all] Error 2

Please help me in this issue, it’s very urgent.

Thank you.

**Comment by robe2** [comment]
Is this still an issue?  I know when I treid a while ago using yum.postgresql.org  I had to first add epel repo to get teh boost dependencies.  Also CGAL wasn't being packaged.  I had complained about that to yum.postgresql.org folks and they started package CGAL too as I recall.  So haven't had issues lately.

Here are my instructions with reference to pgrouting 2.0 (ths was again 9.3), and I added a note about Devrim having started packaing CGAL as part of it to make the install smoother.


http://www.postgresonline.com/journal/archives/329-An-almost-idiots-guide-to-install-PostgreSQL-9.3,-PostGIS-2.1-and-pgRouting-with-Yum.html

**Comment by dkastl** [comment]
Well, I'm not a user of RPM packages, but CGAL package was also an issue with Debian/Ubuntu in the past. It has been resolved for Debian packages, so I guess the same applies for RPM's, because I can't remember to have heard about any problems in the past years.

So let's close this issue and reopen it or create a new one if necessary.
