### ISSUE TITLE
Honor client cancel requests in C /C++ code

### ISSUE THREAD

**Issue by woodbri** [pgRouting/pgrouting#232]
Currently our C/C++ code does not honor client cancel query requests. There is a macro CHECK_FOR_INTERRUPTS() defined in server/miscadmin.h and we should use that or more likely mimic it so we can check for a pending interrupt in any long running processes, then do clean up and finally call ProcessInterrupts().

We will need to look at how to do this from C++ it might be as simple as wrapping the include like:

```
extern "C" {
#include "server/miscadmin.h"
}
```

**Comment by cvvergara** [comment]
Fixed this issue for pgr_ksp with commit 5cdd106ebe.
TODO:
Make the code available to all functions
And each function, if required, should have to add where appropriate the catch

**Comment by woodbri** [comment]
In the cpp code where it is in a loop that takes a a lot of iterations you need to include THROW_ON_SIGINT

    while (lots_of_stuff_to_do) {
      ...
      THROW_ON_SIGINT
    }

and #include "signalhandler.h"

This is a very low cost asynchronous way to check if we got a ^C and the wrapper needs to catch this and inform the C code. You can freely put THROW_ON_SIGINT through out the code and you will get a faster terminate to the ^C

**Comment by cvvergara** [comment]
@woodbri 
I am trying the signal handler to honour the ctrl-c

The include:
https://github.com/cvvergara/pgrouting/blob/fix/issue232/src/internalQueryTests/src/testXYedges_driver.cpp#L42

The signal intialization:
https://github.com/cvvergara/pgrouting/blob/fix/issue232/src/internalQueryTests/src/testXYedges_driver.cpp#L60
the signal quit
https://github.com/cvvergara/pgrouting/blob/fix/issue232/src/internalQueryTests/src/testXYedges_driver.cpp#L196

The include:
https://github.com/cvvergara/pgrouting/blob/fix/issue232/src/dijkstra/src/pgr_dijkstra.hpp#L47

the throw:
https://github.com/cvvergara/pgrouting/blob/fix/issue232/src/dijkstra/src/pgr_dijkstra.hpp#L264

the cant compile:
https://travis-ci.org/cvvergara/pgrouting/jobs/156604195#L897

What am I doing wrong?

**Comment by woodbri** [comment]
I'm not sure, but maybe the compiler is not scoping the #define in 
https://github.com/cvvergara/pgrouting/blob/fix/issue232/src/common/src/signalhandler.h#L148

``sigint_handler`` is a reference to 
https://github.com/cvvergara/pgrouting/blob/fix/issue232/src/common/src/signalhandler.h#L142

you could try rewriting L148 to be something like:

```
#define THROW_ON_SIGINT do { \
    if (SignalHandler::instance()->registerHandler(SIGINT, &sigint_handler).gracefulQuit() == 1 ) \
        throw(UserQuitException("Abort on User Request!")); \
} while (0);
```
and see if that helps. Have the rules for scoping #define objects changed since C++98?

**Comment by cvvergara** [comment]
I dont think scoping rules changed.
I missed that. `SignalHandler::instance()->` I'll try again with it. (forgot its kind of a singleton)

**Comment by cvvergara** [comment]
could not make it work :(

**Comment by woodbri** [comment]
Thank you for following up on this. Its been too long for me to remember the details. Removing from 3.0 is fine. 

I think to diagnosis this issue in the future we need to trace where if anywhere the signal is getting handled. So for example:

0. is the signal handler getting installed correctly?
1. is the backend process getting the cancel request?
2. is our code checking for the the cancel request?
3. is our code handling the request?
4. etc

Once this is understood for one command, it should be easy to propagate, so maybe making a dummy command just for testing, that loop 30 times with a sleep(1sec) in the loop would be adequate for testing.
