### ISSUE TITLE
PgRouting/pgr_dijkstra: How to log output, i.e raising a notice message after every 100, 500, 0r 1.000 calculated routes or so.

### ISSUE THREAD

**Issue by adeways2000** [pgRouting/pgrouting#2338]
I am writing a code PL/pgSQL that processes both input layers (households[points] and network[linestrings]). 

**Expectation**
The processing should produce an output layer with all routes/connections from every household to every other household. Given an input layer with around 1.000 (n) households the resulting routes/connections layer should have around 1.000.000 routes/connections (n * n). 

**Problem**
 I want the procedure to produce some logging output, i.e raising a notice message after every 1.000 calculated routes or so.

**Sample Data**

set client_min_messages = default;
set search_path = working_schema, pg_default, public;

do 
$$ 
declare

	string1 varchar;
	
  
begin
	
	--Creates Source and Target columns if they are not existing
	ALTER TABLE roadlines
		ADD COLUMN if not exists source integer;
	
	ALTER TABLE roadlines
		ADD COLUMN if not exists target integer;
			
	--Create topology	
	SELECT pgr_createTopology INTO string1('roadlines', 0.001, 'geom', clean := 'true'); 
	RAISE notice '% - pgr_createTopology: %', substr(cast(clock_timestamp() as varchar), 12, 8), string1;
	
	--Create node network	
	SELECT pgr_nodeNetwork INTO string1('roadlines',0.001, 'id', 'geom');
	RAISE notice '% - pgr_nodeNetwork: %', substr(cast(clock_timestamp() as varchar), 12, 8), string1;
	
	--Create topology for the noded table
	SELECT pgr_createTopology INTO string1('roadlines_noded', 0.001, 'geom', clean := 'true'); 
	RAISE notice '% - pgr_createTopology: %', substr(cast(clock_timestamp() as varchar), 12, 8), string1;
	
	--Adds the length column
	ALTER TABLE roadlines_noded
		ADD COLUMN d_cost_length double precision;
	RAISE notice '% - the length column is Created: ', substr(cast(clock_timestamp() as varchar), 12, 8);
	
	--Fills the length column which will be considered as cost
	UPDATE roadlines_noded SET d_cost_length = ST_Length(ST_Transform(geom, 25832)::geometry);
	RAISE notice '% - the d_cost_length is Calculated: ', substr(cast(clock_timestamp() as varchar), 12, 8);
	
	--Identifies the potential problems on the graph
	SELECT pgr_analyzegraph INTO string1('roadlines_noded', 0.001, 'geom');
	RAISE notice '% - pgr_analyzegraph: %', substr(cast(clock_timestamp() as varchar), 12, 8), string1;
	
	--Creates a new Djikstira result table
	CREATE TABLE dijkstra_routing_table as
	SELECT *
		FROM pgr_dijkstra('SELECT id, source::INT4, target::INT4, d_cost_length AS cost FROM roadlines_noded',
		
			-- Collects the array of start_vid,  end_vid, only when the intersection between a roadlines layer and a point layer is true
			-- Buffer is applied to the point layer in order to facilitate the intersection of a point layer and a line layer.
			(	
				SELECT array_agg(distinct(case when st_intersects(ST_StartPoint(w_noded.geom), st_buffer(adr_pts.geom,0.1)) then source else target end))
				FROM roadlines_noded as w_noded
				INNER JOIN housepoints as adr_pts on st_intersects(w_noded.geom, st_buffer(adr_pts.geom))),
					  
			(	SELECT array_agg(distinct(case when st_intersects(ST_StartPoint(w_noded.geom), st_buffer(adr_pts.geom, 0.1)) then source else target end))
				FROM roadlines_noded as w_noded
				INNER JOIN housepoints as adr_pts on st_intersects(w_noded.geom, st_buffer(adr_pts.geom))))
				
		INNER JOIN roadlines_noded ON edge = id
		ORDER BY seq;
	
	RAISE notice '% - djikstra_routing_table is Created: ', substr(cast(clock_timestamp() as varchar), 12, 8);
	
			
	RAISE notice '% - Ende', substr(cast(clock_timestamp() as varchar), 12, 8);
	RAISE notice ' ';

end;
$$
language plpgsql;

**Platform/versions**
PostgreSQL 14.1, compiled by Visual C++ build 1914, 64-bit
POSTGIS="3.2.0 3.2.0" [EXTENSION] PGSQL="140" GEOS="3.10.1-CAPI-1.16.0" PROJ="7.2.1"
pgr_version: 3.3.0
PgAdmin 4

**Comment by robe2** [comment]
@adeways2000 this issue tracker is for bugs and enhancements and not for user help with a specific problem.

I think this question is better asked on the pgrouting mailing lists -  [https://lists.osgeo.org/mailman/listinfo/pgrouting-users](https://lists.osgeo.org/mailman/listinfo/pgrouting-users) or [gis.stackexchange.com](https://gis.stackexchange.com/) .
