### ISSUE TITLE
pgr_pointsaspolygon returns a self intersecting polygon which does not cover underlying points

### ISSUE THREAD

**Issue by nilguncelik** [pgRouting/pgrouting#235]
I am using pgrouting 2.0 library to create an alpha shape around my set of points. It works nearly perfect but I have a case where pgr_pointsaspolygon returns a self intersecting polygon which does not really cover the underlying points in the table:

![pgr_pointsaspolygon](https://f.cloud.github.com/assets/1549493/2177702/f0e004b8-9632-11e3-876b-c118c79dad9b.png)

This is how i call the pgr_pointsaspolygon function :
```
SELECT 1 as a,* FROM  pgr_pointsaspolygon('SELECT id, ST_X(the_geom) AS x, ST_Y(the_geom) AS y FROM test')
```

**Comment by woodbri** [comment]
This might need to get pushed out to the 2.2.0 Milestone.

**Comment by cvvergara** [comment]
@sanak 
I am revising all the issues that are to be handled in the 2.2 version, and I was wondering if this one was solved on the 2.1 version.

**Comment by dkastl** [comment]
Since it was merged it was probably resolved.
We may want to add a test case though ... new issue for that and close this one?

**Comment by cvvergara** [comment]
ok.
Marking as fixed on develop due to the fact that we milestone 2.1.0 has being closed.
Closing.
