### ISSUE TITLE
Where can I found 3.4-dev?

### ISSUE THREAD

**Issue by geohuz** [pgRouting/pgrouting#2360]
I'm tring to use the ``pgr_findCloseEdges`` in the 3.4-dev in my project, but I can't find the exact repository tag so I can pull and build myself. Hope somebody can answer the question.

**Comment by krashish8** [comment]
v3.4 is not yet released, so there is no tag for that yet. The function is present in the development version, so, if you want to use it, then you need to checkout the `develop` branch.

**Comment by geohuz** [comment]
Thanks! @krashish8
