### ISSUE TITLE
Extend DD docs with alpha argument 

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#238]
When issue #237 is merged, add additional arguments with description to the DD documentation.

**Comment by cvvergara** [comment]
@dkastl
I think it has the correct description now, please verify & close
http://docs.pgrouting.org/dev/src/alpha_shape/doc/pgr_alphaShape.html#pgr-alphashape

**Comment by dkastl** [comment]
In general good, but shouldn'T we maybe add at least into one example a value for `alpha`?
Just an idea.

**Comment by cvvergara** [comment]
Maybe, but I see that the id is int4, and eventually has to be rewritten to receive bigint, why dont we leave the example for when that is done?

**Comment by cvvergara** [comment]
The link above is outdated, it is documented in version 2.2, so I will close
http://docs.pgrouting.org/2.2/en/src/alpha_shape/doc/pgr_alphaShape.html#pgr-alphashape
