### ISSUE TITLE
 pgRouting 3.4 do not build docs when sphinx is too low or missing

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#2401]
#2399 on 3.4.0

**Comment by robe2** [comment]
I think that is fine and no need to try to get it to build in focal.
The docs are already part of the tagged release.  I'd just make sure doc building is disabled if sphinx < 4.0 since we have that set here as the minimum https://github.com/pgRouting/pgrouting/blob/main/CMakeLists.txt#L61

**Comment by df7cb** [comment]
Debian wants to be able to modify the source, so disabling the doc build isn't ideal. (But maybe acceptable if that's just in old distributions.)

**Comment by cvvergara** [comment]
Thanks, I am working on it for 3.4.1
