### ISSUE TITLE
PostGIS 2.5 will be reaching EOL soon, so no need to test it on develop

### ISSUE THREAD

**Issue by robe2** [pgRouting/pgrouting#2416]
In the next PostGIS micro release, I'm planning to EOL PostGIS 2.5.  It's long overdue.

That said, I don't expect PostGIS 2.5 to be supported for more than the next 2-3 months.

It makes sense to still keep it in main, but I'd get rid of it in develop and develop 4.0, in favor of something like PostGIS 3.3, our latest supported stable release.

**Comment by cvvergara** [comment]
Done on:
https://github.com/pgRouting/pgrouting/commit/bcc71a8fc4a099547c6f5ee93ab57f04f6e2b086
