### ISSUE TITLE
Licence check under sql directory

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#2423]
At least should be:

/*PGR-GNU*****************************************************************

Copyright (c) YEAR pgRouting developers
Mail: project@pgrouting.org

------
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 ********************************************************************PGR-GNU*/

* [x] sql/allpairs/_floydWarshall.sql
* [x] sql/allpairs/_johnson.sql
* [x] sql/allpairs/floydWarshall.sql
* [x] sql/allpairs/johnson.sql
* [x] sql/alpha_shape/_alphaShape.sql
* [x] sql/alpha_shape/alphaShape.sql
* [x] sql/astar/_astar.sql
* [x] sql/astar/astar.sql
* [x] sql/astar/astarCost.sql
* [x] sql/astar/astarCostMatrix.sql
* [x] sql/bdAstar/_bdAstar.sql
* [x] sql/bdAstar/bdAstar.sql
* [x] sql/bdAstar/bdAstarCost.sql
* [x] sql/bdAstar/bdAstarCostMatrix.sql
* [x] sql/bdDijkstra/_bdDijkstra.sql
* [x] sql/bdDijkstra/bdDijkstra.sql
* [x] sql/bdDijkstra/bdDijkstraCost.sql
* [x] sql/bdDijkstra/bdDijkstraCostMatrix.sql
* [x] sql/bellman_ford/_bellman_ford.sql
* [x] sql/bellman_ford/_bellman_ford_neg.sql
* [x] sql/bellman_ford/_edwardMoore.sql
* [x] sql/bellman_ford/bellman_ford.sql
* [x] sql/bellman_ford/bellman_ford_neg.sql
* [x] sql/bellman_ford/edwardMoore.sql
* [x] sql/breadthFirstSearch/_binaryBreadthFirstSearch.sql
* [x] sql/breadthFirstSearch/_breadthFirstSearch.sql
* [x] sql/breadthFirstSearch/binaryBreadthFirstSearch.sql
* [x] sql/breadthFirstSearch/breadthFirstSearch.sql
* [x] sql/chinese/_pgr_chinesePostman.sql
* [x] sql/chinese/pgr_chinesePostman.sql
* [x] sql/chinese/pgr_chinesePostmanCost.sql
* [x] sql/circuits/_hawickCircuits.sql
* [x] sql/circuits/hawickCircuits.sql
* [x] sql/coloring/_bipartite.sql
* [x] sql/coloring/_edgeColoring.sql
* [x] sql/coloring/_sequentialVertexColoring.sql
* [x] sql/coloring/bipartite.sql
* [x] sql/coloring/edgeColoring.sql
* [x] sql/coloring/sequentialVertexColoring.sql
* [x] sql/common/_checkcolumn.sql
* [x] sql/common/_checkquery.sql
* [x] sql/common/_endPoint.sql
* [x] sql/common/_point_toId.sql
* [x] sql/common/_startPoint.sql
* [x] sql/common/createIndex.sql
* [x] sql/common/pgRouting-header.sql
* [x] sql/common/pgr_parameter_check.sql
* [x] sql/common/pgrouting_utilities.sql
* [x] sql/common/utilities_pgr.sql
* [x] sql/components/_articulationPoints.sql
* [x] sql/components/_biconnectedComponents.sql
* [x] sql/components/_bridges.sql
* [x] sql/components/_connectedComponents.sql
* [x] sql/components/_makeConnected.sql
* [x] sql/components/_strongComponents.sql
* [x] sql/components/articulationPoints.sql
* [x] sql/components/biconnectedComponents.sql
* [x] sql/components/bridges.sql
* [x] sql/components/connectedComponents.sql
* [x] sql/components/makeConnected.sql
* [x] sql/components/strongComponents.sql
* [x] sql/contraction/_contraction.sql
* [x] sql/contraction/contraction.sql
* [x] sql/dagShortestPath/_dagShortestPath.sql
* [x] sql/dagShortestPath/dagShortestPath.sql
* [x] sql/dijkstra/_dijkstra.sql
* [x] sql/dijkstra/_dijkstraNear.sql
* [x] sql/dijkstra/_dijkstraVia.sql
* [x] sql/dijkstra/dijkstra.sql
* [x] sql/dijkstra/dijkstraCost.sql
* [x] sql/dijkstra/dijkstraCostMatrix.sql
* [x] sql/dijkstra/dijkstraNear.sql
* [x] sql/dijkstra/dijkstraNearCost.sql
* [x] sql/dijkstra/dijkstraVia.sql
* [x] sql/dominator/_lengauerTarjanDominatorTree.sql
* [x] sql/dominator/lengauerTarjanDominatorTree.sql
* [x] sql/driving_distance/_drivingDistance.sql
* [x] sql/driving_distance/_withPointsDD.sql
* [x] sql/driving_distance/drivingDistance.sql
* [x] sql/driving_distance/withPointsDD.sql
* [x] sql/ksp/_ksp.sql
* [x] sql/ksp/_turnRestrictedPath.sql
* [x] sql/ksp/_withPointsKSP.sql
* [x] sql/ksp/ksp.sql
* [x] sql/ksp/turnRestrictedPath.sql
* [x] sql/ksp/withPointsKSP.sql
* [x] sql/legacy/alpha_shape.sql
* [x] sql/legacy/legacy-developers.sql
* [x] sql/legacy/legacy_experimental.sql
* [x] sql/legacy/pgrouting_version.sql
* [x] sql/legacy/pointsAsPolygon.sql
* [x] sql/legacy/routing_legacy.sql
* [x] sql/legacy/tsp/TSPeucledian.sql
* [x] sql/legacy/tsp/_makeDistanceMatrix.sql
* [x] sql/legacy/tsp/tsp_v2.0_coordinates.sql
* [x] sql/legacy/tsp/tsp_v2.0_matrix.sql
* [x] sql/legacy/vrppdtw/_gsoc_vrppdtw.sql
* [x] sql/legacy/vrppdtw/gsoc_vrppdtw.sql
* [x] sql/lineGraph/_lineGraph.sql
* [x] sql/lineGraph/_lineGraphFull.sql
* [x] sql/lineGraph/lineGraph.sql
* [x] sql/lineGraph/lineGraphFull.sql
* [x] sql/max_flow/_edgeDisjointPaths.sql
* [x] sql/max_flow/_maxCardinalityMatch.sql
* [x] sql/max_flow/_maxFlowMinCost.sql
* [x] sql/max_flow/_maxflow.sql
* [x] sql/max_flow/boykovKolmogorov.sql
* [x] sql/max_flow/edgeDisjointPaths.sql
* [x] sql/max_flow/edmondsKarp.sql
* [x] sql/max_flow/maxCardinalityMatch.sql
* [x] sql/max_flow/maxFlow.sql
* [x] sql/max_flow/maxFlowMinCost.sql
* [x] sql/max_flow/maxFlowMinCost_Cost.sql
* [x] sql/max_flow/pushRelabel.sql
* [x] sql/mincut/_stoerWagner.sql
* [x] sql/mincut/stoerWagner.sql
* [x] sql/ordering/_cuthillMckeeOrdering.sql
* [x] sql/ordering/cuthillMckeeOrdering.sql
* [x] sql/pickDeliver/_pickDeliver.sql
* [x] sql/pickDeliver/_pickDeliverEuclidean.sql
* [x] sql/pickDeliver/pickDeliver.sql
* [x] sql/pickDeliver/pickDeliverEuclidean.sql
* [x] sql/planar/_boyerMyrvold.sql
* [x] sql/planar/_isPlanar.sql
* [x] sql/planar/boyerMyrvold.sql
* [x] sql/planar/isPlanar.sql
* [x] sql/spanningTree/_kruskal.sql
* [x] sql/spanningTree/_prim.sql
* [x] sql/spanningTree/_randomSpanTree.sql
* [x] sql/spanningTree/kruskal.sql
* [x] sql/spanningTree/kruskalBFS.sql
* [x] sql/spanningTree/kruskalDD.sql
* [x] sql/spanningTree/kruskalDFS.sql
* [x] sql/spanningTree/prim.sql
* [x] sql/spanningTree/primBFS.sql
* [x] sql/spanningTree/primDD.sql
* [x] sql/spanningTree/primDFS.sql
* [x] sql/spanningTree/randomSpanTree.sql
* [x] sql/topologicalSort/_topologicalSort.sql
* [x] sql/topologicalSort/topologicalSort.sql
* [x] sql/topology/analyzeOneway.sql
* [x] sql/topology/analyzegraph.sql
* [x] sql/topology/createtopology.sql
* [x] sql/topology/createverticestable.sql
* [x] sql/topology/degree.sql
* [x] sql/topology/extractVertices.sql
* [x] sql/topology/nodeNetwork.sql
* [x] sql/transitiveClosure/_transitiveClosure.sql
* [x] sql/transitiveClosure/transitiveClosure.sql
* [x] sql/traversal/_depthFirstSearch.sql
* [x] sql/traversal/depthFirstSearch.sql
* [x] sql/trsp/_array_reverse.sql
* [x] sql/trsp/_pgr_trsp.sql
* [x] sql/trsp/_pgr_trspViaVertices.sql
* [x] sql/trsp/_trsp.sql
* [x] sql/trsp/_trspVia.sql
* [x] sql/trsp/_trspVia_withPoints.sql
* [x] sql/trsp/_trsp_withPoints.sql
* [x] sql/trsp/pgr_trsp.sql
* [x] sql/trsp/pgr_trspViaEdges.sql
* [x] sql/trsp/pgr_trspViaVertices.sql
* [x] sql/trsp/trsp.sql
* [x] sql/trsp/trspVia.sql
* [x] sql/trsp/trspVia_withPoints.sql
* [x] sql/trsp/trsp_withPoints.sql
* [x] sql/tsp/TSP.sql
* [x] sql/tsp/TSPeuclidean.sql
* [x] sql/tsp/_TSP.sql
* [x] sql/tsp/_TSPeuclidean.sql
* [x] sql/utilities/findCloseEdges.sql
* [x] sql/version/_version.sql
* [x] sql/version/full_version.sql
* [x] sql/version/version.sql
* [x] sql/vrp_basic/_pgr_vrpOneDepot.sql
* [x] sql/vrp_basic/pgr_vrpOneDepot.sql
* [x] sql/withPoints/_withPoints.sql
* [x] sql/withPoints/_withPointsVia.sql
* [x] sql/withPoints/withPoints.sql
* [x] sql/withPoints/withPointsCost.sql
* [x] sql/withPoints/withPointsCostMatrix.sql
* [x] sql/withPoints/withPointsVia.sql

**Comment by iosefa** [comment]
FYI the following are licensed under MIT:
* sql/legacy/pgrouting_version.sql
* sql/legacy/tsp/_makeDistanceMatrix.sql
* sql/topology/analyzeOneway.sql
* sql/topology/analyzegraph.sql
