### ISSUE TITLE
Bug(?) with pgr_createVerticesTable and pgr_createtopology functions (v3.4+)

### ISSUE THREAD

**Issue by Nick-Nal** [pgRouting/pgrouting#2427]
Greetings.

**Problem**
Functions pgr_createVerticesTable and pgr_createtopology does not working properly in PGR 3.4.0 and 3.4.1 because of this:

DECLARE
       dummyRec TEXT;
...
        sql = 'SELECT * FROM '||_pgr_quote_ident(tabname)||' WHERE true'||rows_where ||' limit 1';
        EXECUTE sql INTO dummyRec;

Obviously, this variable should be of type Record.
Currently this problem blocks initial checks on tables when using these two functions, because it generates exception.
AFAIR, this bug wasn't present in 3.3.x versions earlier this year.

**Comment by cvvergara** [comment]
Thanks for reporting, will fix soon, on 3.4.2, but that micro will be released in 15 days aprox

**Comment by Nick-Nal** [comment]
Thank you
