### ISSUE TITLE
pgrouting crashes and restarts the postgresql server when searching for endpoints in 2 disjoints graphs

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#245]
I have

> apt-show-versions postgresql-9.1-pgrouting
postgresql-9.1-pgrouting/precise uptodate 2.0.0-release-ppa1~precise2

Whenever I do a search http://docs.pgrouting.org/dev/src/astar/doc/index.html between two end points in disjoint graphs, I get the error error sending I/O to backend and my postgresql server crashes and restarts. Why doesnt this simply return a no route found?

Source: http://gis.stackexchange.com/questions/91127/pgrouting-crashes-and-restarts-the-postgresql-server-when-searching-for-endpoint

**Comment by woodbri** [comment]
This is a crash it needs to be trapped in 2.1.0

**Comment by cvvergara** [comment]
Note to self:
Uses boost
It does have the try/catch block.
https://github.com/pgRouting/pgrouting/blob/develop/src/astar/src/astar_boost_wrapper.cpp#L130
and here
https://github.com/pgRouting/pgrouting/blob/develop/src/astar/src/astar_boost_wrapper.cpp#L201
By first glance on the current code, I can't see what is wrong.

**Comment by cvvergara** [comment]
Astars code has being rewritten, there is no sample test case to test if this issue was fixed, I tested on the sample data that has disjoint graphs with no crash.
If the problem persists, open a new issue
