### ISSUE TITLE
pgr_Dijkstra/pgr_kdijkstraPath/pgr_ksp differences

### ISSUE THREAD

**Issue by opessoa** [pgRouting/pgrouting#246]
I have a city roads data base witch is returning different values from this
'selects'.

select sum(cost) from pgr_Dijkstra('SELECT id, source, target, cost,
reverse_cost FROM ruas', 3423, 3839, true, true);

select sum(cost) from pgr_kdijkstraPath('SELECT id, source, target, cost,
reverse_cost FROM ruas', 3423, array[3839], true, true);

select sum(cost) from pgr_ksp('SELECT id, source, target, cost,
reverse_cost FROM ruas', 3423, 3839, 1, true);

Manually I have seen that the pgr_Dijkstra has the correct path.

And the others has passed from edges who is not the shortest path.

Is it an alghorithm error?

**Comment by opessoa** [comment]
Hi, after a long time, I've back to pgr_kdijkstraPath, and I find out that using sql text passed to function like 'SELECT  id2, id3, cost FROM pgr_kdijkstrapath('SELECT id, source, target, cost, reverse_cost FROM roads order by st_length(the_geom)' adding the order clause 'order st_length(the_geom)' they returns the same route than pgr_dijkstra.

**Comment by woodbri** [comment]
Yes, leave this open. The error is in the fact that if there are multiple paths to a node that the code finds the shortest path but extracts the first of the multiple paths in the list. We made a fix for this in dijkstra but must have missed kdijkstra. Thanks this is helpful.

**Comment by cvvergara** [comment]
@opessoa
Fixed pgr_ksp part of this issue
with  commit 5cdd106ebe
can you please check it works with your original problem pgr_ksp vs pgr_dijkstra with out the:
 order clause 'order st_length(the_geom)'

**Comment by opessoa** [comment]
Hello guys, I'm out of time to see it now. When I have more time, for sure, I'll do the tests.

**Comment by cvvergara** [comment]
pgr_Dijkstra pgr_ksp differences fixed in develop_2_1_0
but pgr_kdijkstraPath remains for 2.2

**Comment by cvvergara** [comment]
See #333 
As pgr_kdijkstraPath is going to be deprecated in favor of pgr_dijkstra 
This bug will disappear.

**Comment by cvvergara** [comment]
Deprecating pgr_kdijkstraPath please use pgr_dijkstra
pgr_kdijkstraPath Its being fixed by wrapping it with the results of pgr_dijkstra
