### ISSUE TITLE
VRP-basic does not optimize the results

### ISSUE THREAD

**Issue by woodbri** [pgRouting/pgrouting#249]
It appears that VRP tries to fill the trucks to capacity so lets say we have 10 orders 5 in each of two spatial clusters that are far apart and we can fit 6 orders in a truck. Rather than put 5 orders in each truck it will put 6 orders in the first truck and 4 in the second. This means that the first truck has to deliver its orders in cluster A and then drive all the way over to cluster B to deliver one package. It would be more efficient to do some additional constraint checking to see if moving an order to another truck or swapping orders between trucks improves the overall solution.

We might be able to add in this if we first check if orders are in spatial clusters and then assign them to trucks based on that.

**Comment by cvvergara** [comment]
vrp basic is renamed to pgr_vrpOneDepot.
as pgr_vrpOneDepot is a proposed function I am removing the milestone.
Related to #378

**Comment by cvvergara** [comment]
Work was done on experimental functions for version 3.0
pgr_pickDeliver
pgr_vrpOneDepot
Closing
if new issue araises please open a new issue
