### ISSUE TITLE
vrp_basic - get attemptFeasibleNodeExchange method working

### ISSUE THREAD

**Issue by woodbri** [pgRouting/pgrouting#250]
the vrp_basic code as some methods that are commented out. I presume these were planned methods that were never debugged or worked. I think the lack of these might be related to issue #249.

**Comment by cvvergara** [comment]
Work was done on experimental functions for version 3.0
pgr_pickDeliver
pgr_vrpOneDepot
Closing
if new issue araises please open a new issue
