### ISSUE TITLE
vrp_basic needs documentation written

### ISSUE THREAD

**Issue by woodbri** [pgRouting/pgrouting#251]
I have merged the gsoc-vrp branch into develop, but it needs documentation written for it.

**Comment by cvvergara** [comment]
vrp basic is renamed to pgr_vrpOneDepot.
as pgr_vrpOneDepot is a proposed function I am removing the milestone.
Related to #378

**Comment by cvvergara** [comment]
Rewriten with `pgr_pickDelivery` experimental function
