### ISSUE TITLE
Contributors before December 2016

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#2527]
# Introduction
The [CONTRIBUTING.md](https://github.com/pgRouting/pgrouting/blob/main/CONTRIBUTING.md) was created on December 8, 2016 on [this commit](https://github.com/pgRouting/pgrouting/commit/34b933f144cf6cab04de7055c7bc404590c8f6f1)

This incubation step only considers contributors that made contributions before the  [CONTRIBUTING.md](https://github.com/pgRouting/pgrouting/blob/main/CONTRIBUTING.md) was created. And the purpose is to reach out for those that made a substantial contribution.

- [x] Get the list of contributors before December 2016
- [x] Analyze the information
- [x] Determine who needs to be reached out.
- [x] Receive agreement from 3 contributors
- [x] Double check on code-sprint
  

## Complete list of contributors
https://github.com/pgRouting/pgrouting/graphs/contributors

## List of contributors before December 2016

The following command gives the following result (left column) on version 3.5
```
git log --pretty="format:user:%an date:%ad" --name-only --encoding=UTF-8 --before="2016-12-08" | \
grep user contributors.txt | \
awk -F"date" '{print $1}' contributors.txt | sort | uniq
```

| name | same as | Contributed After / PRs |
|---|---|---|
| = | | YES |
| Aaron W. Swenson | | YES |
| Alec Gosse | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Acgosse+is%3Amerged+) |
| anton | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Aantonpa++is%3Amerged+) and he wrote/fixed the [License](https://github.com/antonpa/pgrouting/commits/b58825dc0fbb66061cee1b08adbac51c09eb557a/COPYING), also (Inactive) PSC during the change|
| Bas Couwenberg | | YES |
| Clemens Werther | Clemens Werther| [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Aclashman+is%3Amerged+) |
| m3th0s |Clemens Werther | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Aclashman+is%3Amerged+) |
| daniel |Daniel Kastl | YES |
| Daniel Kastl |Daniel Kastl | YES |
| drnextgis | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Adrnextgis+is%3Amerged+)|
| guest | | [contributions](#guest)|
| Illedran | Andrea Nardelli | [GSoC student](https://github.com/pgRouting/pgrouting/wiki/Google-Summer-of-Code)|
| Andrea Nardelli | Andrea Nardelli | [GSoC student](https://github.com/pgRouting/pgrouting/wiki/Google-Summer-of-Code) |
| Jonathan Wakely | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Ajwakely) |
| J Smith | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Adark-panda+is%3Amerged+)|
| kiorky | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Akiorky+is%3Amerged+)|
| Kirill Müller | | [PRs](https://github.com/pgRouting/pgrouting/pull/242)|
| J Kishore kumar | J Kishore kumar| [GSoC student](https://github.com/pgRouting/pgrouting/wiki/Google-Summer-of-Code)|
| Kishore kumar J | J Kishore kumar| [GSoC student](https://github.com/pgRouting/pgrouting/wiki/Google-Summer-of-Code)|
| Ko Nagase | Ko Nagase | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Asanak++is%3Amerged+)|
| sanak |Ko Nagase | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Asanak++is%3Amerged+) |
| manikanta-kondeti | |[GSoC student](https://github.com/pgRouting/pgrouting/wiki/Google-Summer-of-Code) |
| michael skinner | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Amskinna++is%3Amerged+)|
| Mohammed Zia | |[PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Azia-++is%3Amerged+)|
| nbrinckm | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Anbrinckm++is%3Amerged+)|
| (no author) | | [contributions](#no-author)|
| Omar | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Aopessoa+is%3Amerged+) |
| petebp | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Apetebp+is%3Amerged+) |
| Regina Obe | Regina Obe | YES |
| robe2 |Regina Obe | YES |
| $R0h!tH | Rohith Reddy | YES |
| rohith | Rohith Reddy| YES |
| Rohith Reddy |Rohith Reddy | YES |
| root | | YES |
| Sandro Santilli | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Astrk+is%3Amerged+)|
| Stephen Mather | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Asmathermather+is%3Amerged+)|
| Stephen Woodbridge | | YES |
| takubo | | [contributions](#takubo)|
| The Gitter Badger | | [contributions](#gitter-badger)|
| Vadim Zhukov | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Agrayed+is%3Amerged+) |
| Varod | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Avalvin1+is%3Amerged+)|
| cvvergara | Vicky Vergara | YES |
| mapas de vicky | Vicky Vergara| YES |
| vicky |Vicky Vergara | YES |
| vicky vergara |Vicky Vergara | YES |
| Vicky Vergara |Vicky Vergara | YES |
| Vincent Picavet | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Avpicavet+is%3Amerged+) |
| yobiSource | | [PRs](https://github.com/pgRouting/pgrouting/pull/428) |
| zibon | | [GSoC student](https://github.com/pgRouting/pgrouting/wiki/Google-Summer-of-Code)|

## List of contributors that have agreed to the contribution agreement

To get the contributors that also contributed after the Contribution agreement 

```
git log --pretty="format:user:%an" --name-only --encoding=UTF-8 --before="2016-12-08" | \
grep user | \
awk -F"user:" '{print $2}' | sort | uniq > before.txt

git log --pretty="format:user:%an" --name-only --encoding=UTF-8 --after="2016-12-08" | \
grep user | \
awk -F"user:" '{print $2}' | sort | uniq > after.txt

comm -12 before.txt after.txt
```
The following table includes
* Contributors that make a PR after the Contibution.md file was created: marked with `YES`
* Contributors from Google Summer of Code students that followed contribution agreement of the program: with link "GSoC student"
* Participated creating the License and/or has been a PSC: with explanation

## List of contributors that have agreed to the contribution agreement

| name | same as | Contributed After / PRs |
|---|---|---|
| = | | YES |
| Aaron W. Swenson | | YES |
| anton | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Aantonpa++is%3Amerged+) and he wrote/fixed the [License](https://github.com/antonpa/pgrouting/commits/b58825dc0fbb66061cee1b08adbac51c09eb557a/COPYING), also (Inactive) PSC during the change|
| Bas Couwenberg | | YES |
| daniel |Daniel Kastl | YES |
| Daniel Kastl |Daniel Kastl | YES |
| Illedran | Andrea Nardelli | [GSoC student](https://github.com/pgRouting/pgrouting/wiki/Google-Summer-of-Code)|
| Andrea Nardelli | Andrea Nardelli | [GSoC student](https://github.com/pgRouting/pgrouting/wiki/Google-Summer-of-Code) |
| J Kishore kumar | J Kishore kumar| [GSoC student](https://github.com/pgRouting/pgrouting/wiki/Google-Summer-of-Code)|
| Kishore kumar J | J Kishore kumar| [GSoC student](https://github.com/pgRouting/pgrouting/wiki/Google-Summer-of-Code)|
| manikanta-kondeti | |[GSoC student](https://github.com/pgRouting/pgrouting/wiki/Google-Summer-of-Code) |
| Regina Obe | Regina Obe | YES |
| robe2 |Regina Obe | YES |
| $R0h!tH | Rohith Reddy | YES |
| rohith | Rohith Reddy| YES |
| Rohith Reddy |Rohith Reddy | YES |
| root | | YES |
| Stephen Woodbridge | | YES |
| cvvergara | Vicky Vergara | YES |
| mapas de vicky | Vicky Vergara| YES |
| vicky |Vicky Vergara | YES |
| vicky vergara |Vicky Vergara | YES |
| Vicky Vergara |Vicky Vergara | YES |
| zibon | | [GSoC student](https://github.com/pgRouting/pgrouting/wiki/Google-Summer-of-Code)|

## Contributors that are OSGeo charter members

[Charter members](https://www.osgeo.org/about/charter-members/)

| name | same as | PRs |
|---|---|---|
| Ko Nagase | Ko Nagase | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Asanak++is%3Amerged+)|
| Mohammed Zia | |[PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Azia-++is%3Amerged+)|
| sanak |Ko Nagase | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Asanak++is%3Amerged+)|
| Sandro Santilli | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Astrk+is%3Amerged+)|
| Stephen Mather | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Asmathermather+is%3Amerged+) small contributor|
| Vincent Picavet | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Avpicavet+is%3Amerged+) small contributor|

##  Unknown Contributors and robots

| name | same as | PRs |
|---|---|---|
| guest | | [contributions](#guest)|
| (no author) | | [contributions](#no-author)|
| The Gitter Badger | | [contributions](#gitter-badger)|

## Small Contributors

Contributors that participated on small bug fixes and typo fixes but not new development

| name | same as | PRs |
|---|---|---|
| Alec Gosse | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Acgosse+is%3Amerged+)|
| Clemens Werther | Clemens Werther| [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Aclashman+is%3Amerged+) |
| m3th0s |Clemens Werther | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Aclashman+is%3Amerged+) |
| drnextgis | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Adrnextgis+is%3Amerged+)|
| Jonathan Wakely | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Ajwakely) |
| J Smith | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Adark-panda+is%3Amerged+)|
| kiorky | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Akiorky+is%3Amerged+)|
| Kirill Müller | | [PRs](https://github.com/pgRouting/pgrouting/pull/242)|
| michael skinner | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Amskinna++is%3Amerged+)|
| nbrinckm | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Anbrinckm++is%3Amerged+)|
| Omar | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Aopessoa+is%3Amerged+) |
| petebp | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Apetebp+is%3Amerged+) |
| takubo | | [contributions](#takubo)|
| Vadim Zhukov | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Agrayed+is%3Amerged+) |
| Varod | | [PRs](https://github.com/pgRouting/pgrouting/pulls?q=is%3Apr+author%3Avalvin1+is%3Amerged+)|
| yobiSource | | [PRs](https://github.com/pgRouting/pgrouting/pull/428) |

## takubo
```
user:takubo Tue Jul 29 00:27:38 2008 +0000
 debian/changelog                                                              |  6 ++++++
 debian/control                                                                | 13 ++++++-------
 debian/postgresql-8.2-pgrouting.dirs                                          |  2 --
 debian/postgresql-8.3-pgrouting.dirs                                          |  2 ++
 debian/{postgresql-8.2-pgrouting.install => postgresql-8.3-pgrouting.install} |  2 +-
 debian/rules                                                                  | 10 ++++++----
 6 files changed, 21 insertions(+), 14 deletions(-)

user:takubo Mon Jan 14 23:02:48 2008 +0000
 debian/README.Debian                    | 18 ++++++++++++++++++
 debian/changelog                        |  6 ++++++
 debian/compat                           |  1 +
 debian/control                          | 23 +++++++++++++++++++++++
 debian/copyright                        | 38 ++++++++++++++++++++++++++++++++++++++
 debian/docs                             |  4 ++++
 debian/postgresql-8.2-pgrouting.dirs    |  2 ++
 debian/postgresql-8.2-pgrouting.install |  4 ++++
 debian/rules                            | 94 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 9 files changed, 190 insertions(+)

user:takubo Sun Jan 13 09:37:01 2008 +0000
 autors.txt | 15 ---------------
 1 file changed, 15 deletions(-)

user:takubo Sun Jan 13 08:28:52 2008 +0000
 CMakeLists.txt                            | 69 +++++++++++++++++++++++++++++++++++++++++----------------------------
 cmake/FindCGAL.cmake                      | 14 +++++++-------
 cmake/FindGAUL.cmake                      | 25 ++++++++++++++++---------
 core/CMakeLists.txt                       |  3 ++-
 core/sql/CMakeLists.txt                   |  3 +++
 core/src/CMakeLists.txt                   |  4 +++-
 extra/driving_distance/CMakeLists.txt     |  2 +-
 extra/driving_distance/sql/CMakeLists.txt |  3 +++
 extra/driving_distance/src/CMakeLists.txt | 23 ++---------------------
 extra/tsp/CMakeLists.txt                  |  2 +-
 extra/tsp/sql/CMakeLists.txt              |  3 +++
 extra/tsp/src/CMakeLists.txt              | 22 +++-------------------
 12 files changed, 85 insertions(+), 88 deletions(-)
```

**Comment by sanak** [comment]
@cvvergara Hey, I agree with contribution! 😄

**Comment by Zia-** [comment]
@cvvergara I agree to the contribution agreement
