### ISSUE TITLE
Vrp_basic: Terrible performance!

### ISSUE THREAD

**Issue by multiluca** [pgRouting/pgrouting#253]
Hi,
I'm trying to solve a vrp problem with vrp for pgrouting but it is terrible slow! In 10 hours of work it added to inizial solution just 800 orders of 3600 total orders.... For a complete vrp solution it will spend around a month!! It is possible? Please help me!
Thanks, 
Luca

**Comment by cvvergara** [comment]
Closing this issue in favor of #378
