### ISSUE TITLE
Add macos-14 to macos CI

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#2618]
Currently we only test on macos-latest
Add macos-14 to the CI

https://github.com/pgRouting/pgrouting/issues/2616#issuecomment-1941441178

@sanak do we have the problem on main?
we are about to make a new release

**Comment by sanak** [comment]
@cvvergara Thanks for creating this issue!

> @sanak do we have the problem on main?

`main` branch is no problem to build on my M1 MacBook (macOS 14) environment.
