### ISSUE TITLE
Fail building under window mingw64

### ISSUE THREAD

**Issue by robe2** [pgRouting/pgrouting#2648]
Just noticed that winnie has been failing for some time compiling develop.

https://winnie.postgis.net/job/pgRouting_PGVersionEDB/10537/console

Issue is repeated multiple times like below, but all errors seem to be around the new functionality betweennessCentrality

/src/metrics/betweennessCentrality_driver.cpp:37  (on line 32 or 37)

  In file included from E:/jenkins/postgresql/rel/pg16w64gcc81/include/server/port/win32_port.h:75,
                   from E:/jenkins/postgresql/rel/pg16w64gcc81/include/server/port.h:24,
                   from E:/jenkins/postgresql/rel/pg16w64gcc81/include/server/c.h:1375,
                   from E:/jenkins/postgresql/rel/pg16w64gcc81/include/server/postgres.h:45,
                   from E:/jenkins/pgrouting/branches/develop/include/cpp_common/pgdata_getters.hpp:42,
                   from E:/jenkins/pgrouting/branches/develop/src/metrics/betweennessCentrality_driver.cpp:37:
  C:/ming64gcc81/mingw64/x86_64-w64-mingw32/include/sys/stat.h: In function 'int microsoft_native_fstat(int, microsoft_native_stat*)':
  C:/ming64gcc81/mingw64/x86_64-w64-mingw32/include/sys/stat.h:226:38: error: invalid application of 'sizeof' to incomplete type 'microsoft_native_stat'
       memset(_Stat,0,sizeof(struct stat));
                                        ^

**Comment by cvvergara** [comment]
Found a similar problem in PostGIS
https://trac.osgeo.org/postgis/ticket/4877
Right now I am figuring out how it was fixed.

**Comment by robe2** [comment]
Winnie is green now for pgrouting develop except for the PG12 run, which we concluded is broken for all PG 12.  That doesn't need fixing if we release 3.7.0 after PG 12 reaches end of life this coming November 14th 2024 - https://www.postgresql.org/support/versioning/

**Comment by robe2** [comment]
since we are not supporting PG12 the PG12 error is moot.
