### ISSUE TITLE
OS X build error: undefined symbols when linking

### ISSUE THREAD

**Issue by neapel** [pgRouting/pgrouting#267]
The shared libraries fail to link when I'm trying to install using `brew install pgrouting`, see full logs at https://gist.github.com/neapel/826a1c295cc0922f1061
Cloning the repository directly and building fails with:

```
Linking CXX shared module lib/librouting.so
Undefined symbols for architecture x86_64:
  "_BlessTupleDesc", referenced from:
      _shortest_path_astar in astar.c.o
```

On top of the homebrew versions (that seem to be used here as far as I can see from the paths), I have Postgres.app installed and QGIS + dependencies.

**Comment by mtaptich** [comment]
I was able to undefined symbols when linking issue by changing the filepath in /pgrouting/build/CMakeCache.txt: 

<pre><code>
POSTGRESQL_EXECUTABLE:FILEPATH=/Applications/postgres.app/Contents/Versions/9.4/bin/postgres</code></pre>

I am also getting two warnings:
<pre><code>src/tsp/src/tsp2.c:57:5: warning: implicit declaration of function 'get_typlenbyvalalign' is invalid in C99
      [-Wimplicit-function-declaration]
    get_typlenbyvalalign(i_eltype, &i_typlen, &i_typbyval, &i_typalign);
    ^
src/tsp/src/tsplib.c:115:16: warning: implicit declaration of function 'Rand' is invalid in C99
      [-Wimplicit-function-declaration]
        last = Rand ();
               ^</code></pre>

**Comment by sanak** [comment]
@mtaptich
Which branch are you using?
If you are using `master` branch, please use `develop` branch.
Because I merged above fixes to `develop` branch.

**Comment by mtaptich** [comment]
@sanak I haven't pulled from the repo to make changes to the any branches. If I confirm this work around, I'll have someone who's more knowledgeable about submitting changes walk me through the update (e.g., I am a git beginner and basically am learning on the fly!).

**Comment by sanak** [comment]
@mtaptich Okay. You can download `develop` branch zip archive as follows.
![download_zip](https://cloud.githubusercontent.com/assets/629923/5787347/8a71d7a0-9e3e-11e4-96f6-4bce45258c02.png)
