### ISSUE TITLE
VRP/PNP resources for the wiki

### ISSUE THREAD

**Issue by bhack** [pgRouting/pgrouting#272]
Do you think that this two resources could be added in the wiki?

- [RinSim](https://github.com/rinde/rinsim/) is a multi-agent system simulator written in Java. It supports problems in the fields of transportation and logistics, most notably pickup-and-delivery problems (PDP).

- [Multi-agent Pickup and Delivery Planning with Transfers](https://www.ri.cmu.edu/publication_view.html?pub_id=7594)

Edit: also solvers in https://github.com/jsprit/jsprit

**Comment by dkastl** [comment]
Added here: https://github.com/pgRouting/pgrouting/wiki/VRP-Algorithms/_compare/93966436f206fbb474e4079646c23d6b5d691ca4...31e3632d120787d7757a31466e912f3ba615a910
