### ISSUE TITLE
pgr_drivingdistance vs pgr_dijkstra - delievering contradictionary results

### ISSUE THREAD

**Issue by Styp** [pgRouting/pgrouting#278]
I encountered an issue which is difficile to explain.

Starting with the same starting point both algorithms return different results. It is obvious that the 2 algorithms produce two total different things, but the details have to be similar if not equal. In my opinion the boostlib works with Dijkstras algorithm on both functions.

Lets give the start point an id, in my case: 915231
And the endpoint id, in my case: 1291686

The end point is within the pgr_drivingdistance result and gave me a result of: 1.72xxxx.
This means the point is in reach within 1.73minutes. As I made a selection of all points in reach under 2 minutes. So far I do not see or feel any issues, but...

I use the same 2 points as an input for the pgr_dijkstra routine, my summed up result returns me a value of 1.99. This means the point is in reach within almost 2 minutes.

As this is only the 'introduction' to the problem, we digged deeper...

![image](https://cloud.githubusercontent.com/assets/1202069/4231470/7e266a04-3991-11e4-8058-8dcbab844e6a.png)

This is an example of  what I described above. The point set and the blue line are the return set of a 2 minutes calculation starting at the same point. In my eyes something is completely off here!

![image](https://cloud.githubusercontent.com/assets/1202069/4231687/588f871e-3994-11e4-8f41-f4cefc53d236.png)

We analysed the 2 graphes and realized, that to a certain point the routing does the same, but than chooses another direction. In my opinion this is wrong. Although, the nodes do not need to have the same 'costs' the end point of the routing has to be equal to the drivingdistance node cost. This is obvious as otherwise there would be a better route!

Reverse_cost is turned off! In both cases!

Hope you understand my theory!

Thank you
Styp

**Comment by cvvergara** [comment]
Work in progress:
Upoladed the data with osm2po. instead of osm2pgrouting.
The image shows the edges that form a minimum spanning tree within the distance.
The area is what is generated by the points as polygon.

![issue278-1](https://cloud.githubusercontent.com/assets/5035290/7890160/c3030de0-0609-11e5-8dcb-12e05167831c.png)


There is no difference on the costs obtained using driving distance and using dijkstra.
```
select sum(cost) from pgr_dijkstra('select id, source, target, km as cost  from si_2po_4pgr', 8887, 2188);
     sum     
-------------
 0.886207587
(1 row)

select cost from pgr_drivingdistance('select id, source, target, km as cost  from si_2po_4pgr', 8887, 1) where id1 = 2188;
    cost     
-------------
 0.886207587
(1 row)
```
