### ISSUE TITLE
TRSP returned different result without "reverse_cost" attribute

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#286]
When I wrote a [TRSP Wiki page](https://github.com/pgRouting/pgrouting/wiki/TRSP-for-railroads) I experienced a strange result, which only occurred, when I removed `reverse_cost::float` from the SQL statement.
### Returned wrong result

```
SELECT seq, id1 AS node, id2 AS edge, cost
        FROM pgr_trsp(
                'SELECT id, source, target, cost::float FROM network',
                4, 1, false, false
        );
```

Result as screenshot:
![screenshot from 2015-02-06 13 22 37](https://cloud.githubusercontent.com/assets/227762/6074501/674ac03c-ae03-11e4-8593-30adaac92db6.png)
### Returned correct result

```
SELECT seq, id1 AS node, id2 AS edge, cost
        FROM pgr_trsp(
                'SELECT id, source, target, cost::float, reverse_cost::float FROM network',
                4, 1, false, false
        );

 seq | node | edge | cost 
-----+------+------+------
   0 |    4 |    3 |    0
   1 |    3 |    2 |    0
   2 |    2 |    1 |    0
   3 |    1 |   -1 |    0
(4 rows)
```

**Though this only happened with pgAdmin3!!!**
When I use command line to create output for this ticket, the result was correct (???).

Does the function has some (wrong) query plan caching?

**Comment by dkastl** [comment]
I tried to run:

```
VACUUM FULL;
VACUUM ANALYZE;
```
 And afterwards I also got strange result on command line:

```
 seq | node | edge |         cost          
-----+------+------+-----------------------
   0 |    4 |    3 | 6.91557725894232e-310
   1 |    3 |    9 |                     0
   2 |    8 |    8 |                     0
   3 |    7 |    7 | 6.91557717990091e-310
   4 |    2 |    1 | 3.16202013338398e-322
   5 |    1 |   -1 |                     0
```
... or another time ...
```
 seq | node | edge |         cost          
-----+------+------+-----------------------
   0 |    4 |    3 | 3.34250411018432e-308
   1 |    3 |    2 | 6.91537208318028e-310
   2 |    2 |    1 | 1.26480805335359e-321
   3 |    1 |   -1 |                     0
```
... where the costs are totally wrong.

**Comment by woodbri** [comment]
The cost are all essentially zero given some float8 rounding errors. Try:
```
SELECT seq, id1 AS node, id2 AS edge, round(cost::numeric, 1) as cost
        FROM pgr_trsp(
                'SELECT id, source, target, cost::float, reverse_cost::float FROM network',
                4, 1, false, false
        );
```
There might be some query caching happening, as I tend to set the function types to stable rather than volatile because the function are not change the data and if the inputs are the same they should given the same output.

**Comment by cvvergara** [comment]
the first query: 
```SELECT seq, id1 AS node, id2 AS edge, cost
        FROM pgr_trsp(
                'SELECT id, source, target, cost::float FROM network',
                4, 1, false, false
        );
```
has_rcost = false    OK, you dont have a reverse cost in the query
Directed= false       so:
for every source, target, cost the graph needs to have:
(source,target,cost)
(target,source,cost)
```
The second query:
SELECT seq, id1 AS node, id2 AS edge, cost
        FROM pgr_trsp(
                'SELECT id, source, target, cost::float, reverse_cost::float FROM network',
                4, 1, false, false
);
```
has_rcost = false    ????? you are saying that you don't have a reverse_cost column, but I can  clearly see it.
Directed= false   you want an undirected graph
for every source, target, cost the graph needs to have:
(source,target,cost)
(target,source,cost)
something like this: would prevent users contradictory input,  pseudo code
```has_reverse = inspect_the_query_string( sql );
if (has_reverse != has_rcost) then {
  if (has_reverse)  error ('has_reverse_cost set to false but reverse_cost column found'); quit;
  else error('has_reverse_cost set to true but reverse_cost not found'); quit;
  end if;
end if;
```
but then again, if this can be done:
```has_reverse = inspect_the_query_string( sql );```
(maybe that can't be done)
then what is the use for having that flag?

**Comment by cvvergara** [comment]
improvements on TRSP are not done yet

**Comment by cvvergara** [comment]
Work has been done for TRSP on develop branch for version 3.4 (due to be released on September/October 2022:
https://github.com/pgRouting/pgrouting/issues/2238
Please check the documentation
https://docs.pgrouting.org/dev/en/TRSP-family.html
and the migration guide:
https://docs.pgrouting.org/dev/en/trsp_migration.html

For further similar problems with TRSP functions please open a new issue with the specific function name.

**Comment by cvvergara** [comment]
@dkastl 
Based on the migration guide:
The following query does not have restrictions
```
SELECT seq, id1 AS node, id2 AS edge, cost
        FROM pgr_trsp(
                'SELECT id, source, target, cost::float FROM network',
                4, 1, false, false
        );
```        
Therefore its migrated as follows
```        
SELECT *
FROM pgr_dijkstra(
  'SELECT id, source, target, cost FROM network',
  4, 1
);
```
Giving the following resutls
```
 seq | path_seq | node | edge | cost | agg_cost 
-----+----------+------+------+------+----------
   1 |        1 |    4 |    4 |    5 |        0
   2 |        2 |    5 |    5 |    5 |        5
   3 |        3 |    6 |    6 |    5 |       10
   4 |        4 |    1 |   -1 |    0 |       15
(4 rows)
```
The graph used in this query is:
```
SELECT id, source, target, cost
FROM network;
 id | source | target |        cost        
----+--------+--------+--------------------
  1 |      1 |      2 |                  1
  2 |      2 |      3 |                  3
  3 |      3 |      4 |                  1
  4 |      4 |      5 |                  5
  5 |      5 |      6 |                  5
  6 |      6 |      1 |                  5
  7 |      2 |      7 | 1.4142135623730951
  8 |      7 |      8 |                  1
  9 |      8 |      3 | 1.4142135623730951
(9 rows)
```
