### ISSUE TITLE
pgr_ksp returns invalid one route when source and target are same

### ISSUE THREAD

**Issue by sanak** [pgRouting/pgrouting#287]
I used the following sample data.
http://docs.pgrouting.org/2.0/en/doc/src/developer/sampledata.html

<pre>
sampledata=# SELECT seq, id1 AS route, id2 AS node, id3 AS edge, cost
 FROM pgr_ksp(
   'SELECT id, source, target, cost FROM edge_table',
   1, 1, 4, false
 );
 seq | route | node |    edge     |         cost          
-----+-------+------+-------------+-----------------------
   0 |     0 |    1 | -2147483648 | 1.79769313486232e+308
   1 |     0 |    1 |          -1 |                     0
(2 rows)
</pre>

I think that the results should be as follows,
because in my understanding, K-Shortest Path should support round-trip pattern.
<pre>
 seq | route | node |    edge     |         cost          
-----+-------+------+-------------+-----------------------
   0 |     0 |    1 |           1 |                     1
   1 |     0 |    2 |           1 |                     1
   2 |     0 |    1 |          -1 |                     0
   3 |     1 |    1 |           1 |                     1
   : |     : |    : |           : |                     :
</pre>

**Comment by woodbri** [comment]
On 2/7/2015 2:44 AM, Ko Nagase wrote:
> I used the following sample data.
> http://docs.pgrouting.org/2.0/en/doc/src/developer/sampledata.html
>
> sampledata=# SELECT seq, id1 AS route, id2 AS node, id3 AS edge, cost
>   FROM pgr_ksp(
>     'SELECT id, source, target, cost FROM edge_table',
>     1, 1, 4, false
>   );
>   seq | route | node |    edge     |         cost
> -----+-------+------+-------------+-----------------------
>     0 |     0 |    1 | -2147483648 | 1.79769313486232e+308
>     1 |     0 |    1 |          -1 |                     0
> (2 rows)

Ok these results definitely look to be a problem.

> I think that the results should be as follows,
> because in my understanding, K-Shortest Path should support round-trip
> pattern.
>
>   seq | route | node |    edge     |         cost
> -----+-------+------+-------------+-----------------------
>     0 |     0 |    1 |           1 |                     1
>     1 |     0 |    2 |           1 |                     1
>     2 |     0 |    1 |          -1 |                     0
>     3 |     1 |    1 |           1 |                     1
>     : |     : |    : |           : |                     :


You are trying to do a round trip. I do not think this is supported. KSP 
is just a variant of Dijkstra shortest path. what it the short path from 
node 1 to node 1? It is obviously that you do not move from node one so 
the distance should be zero.

The only way you could do a shortest path that represents a round trip 
would be to make the code support a via node(s) that the path must go 
through. So if the Via node was 2 then a path 1-2-1 would be possible.

None of our basic solvers support via nodes. You might be able to write 
a wrapper that supports via nodes and breaks the routing into multiple 
results like start-v1, v1-v2, ..., vN-end and returns the results of 
each path.

I wrote something like that for TRSP that might be in the develop 
branch, but I don't remember. If that would be helpful I can look and 
see if I can find it.

-Steve

**Comment by sanak** [comment]
> You are trying to do a round trip. I do not think this is supported. KSP
> is just a variant of Dijkstra shortest path. what it the short path from
> node 1 to node 1? It is obviously that you do not move from node one so
> the distance should be zero.

Yes, sure.

> The only way you could do a shortest path that represents a round trip
> would be to make the code support a via node(s) that the path must go
> through. So if the Via node was 2 then a path 1-2-1 would be possible.

Okay.
I am asking our customer to provide such via node (round-trip edge) list.

> I wrote something like that for TRSP that might be in the develop
> branch, but I don't remember. If that would be helpful I can look and
> see if I can find it.

Okay, thanks.

**Comment by woodbri** [comment]
On 2/7/2015 10:15 AM, Ko Nagase wrote:
>     You are trying to do a round trip. I do not think this is supported. KSP
>     is just a variant of Dijkstra shortest path. what it the short path from
>     node 1 to node 1? It is obviously that you do not move from node one so
>     the distance should be zero.
>
> Yes, sure.
>
>     The only way you could do a shortest path that represents a round trip
>     would be to make the code support a via node(s) that the path must go
>     through. So if the Via node was 2 then a path 1-2-1 would be possible.
>
> Okay.
> I am asking our customer to provide such via node (round-trip edge) list.
>
>     I wrote something like that for TRSP that might be in the develop
>     branch, but I don't remember. If that would be helpful I can look and
>     see if I can find it.
>
> Okay, thanks.

It is in the develop branch, see:

diff --git a/src/trsp/doc/index.rst b/src/trsp/doc/index.rst
index cbee767..084e268 100644
--- a/src/trsp/doc/index.rst
+++ b/src/trsp/doc/index.rst
@@ -17,8 +17,6 @@ pgr_trsp - Turn Restriction Shortest Path (TRSP)
         single: pgr_trsp(text,integer,integer,boolean,boolean,text)
         single: pgr_trsp(text,integer,double precision,integer,double 
precision,
         single: pgr_trsp(text,integer,double precision,integer,double 
precision,
-    single: pgr_trsp(text,integer[],boolean,boolean,text)
-    single: pgr_trsp(text,integer[],float8[],boolean,boolean,text)
         module: trsp

Notice the last two signatures, where you can enter an array of 
locations. this will compute the paths between each successive pairs of 
nodes and return all the results as one path.

-Steve

**Comment by sanak** [comment]
Okay, thanks!

**Comment by cvvergara** [comment]
Please try vicky-develop to test this issue.
the following empty path will be given
together with a Notice: 
seq | route | node   |    edge     |         cost          
-----+-------+------+-------------+-----------------------
    1 |       0 |   sourceid  |          -1    |                     0
Returned message = NOTICE: Starting and Ending vertices are the same.

**Comment by cvvergara** [comment]
Fixed with  commit 5cdd106ebe
A route with invild edge as no route, is returned
-----+-------+------+-------------+-----------------------
1 | 0 | sourceid | -1 | 0
