### ISSUE TITLE
TRSP test case 

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#288]
Trying to find a solution for an uncommon use case, this might be an interesting test for TRSP, which returned a different result than I expected.

Based on the sample data of the following [Wiki page](https://github.com/pgRouting/pgrouting/wiki/TRSP-for-railroads) I made the following modifications:

![trsp for railroads pgrouting pgrouting wiki](https://cloud.githubusercontent.com/assets/227762/6107010/db076842-b0a9-11e4-9bec-6525701b0fb4.png)

The idea is to force going from node 1 to 4 with visiting node 7.

Here the SQL to modify the network (see the [Wiki page](https://github.com/pgRouting/pgrouting/wiki/TRSP-for-railroads) how to create the sample network):

```
DELETE FROM network WHERE id IN (8,9);
DELETE FROM restrictions;
INSERT INTO restrictions (to_cost,to_edge,from_edge) VALUES (100,2,1);
```

The SQL query, that should force visiting node 7 is then:

```
SELECT seq, id1 AS node, id2 AS edge, cost FROM pgr_trsp('
    SELECT id, source, target, cost::float, reverse_cost::float FROM network WHERE id < 5', 
    1, 4, true, true, 
    'SELECT to_cost, to_edge AS target_id, from_edge::text AS via_path FROM restrictions'
);
```

But instead it prefers the direct connection even if the costs are higher:

```
 seq | node | edge | cost 
-----+------+------+------
   0 |    1 |    1 |    1
   1 |    2 |    2 |  103
   2 |    3 |    3 |    1
   3 |    4 |   -1 |    0
(4 rows)
```

Interesting here is also the cost of `103` even if the restrictions cost was only `100`.
Eventually TRSP was not designed to handle this use case, and it might be even a case that is not, what a user wants to get around a restriction.

**Comment by woodbri** [comment]
The cost=103 is because the turn restriction cost =100 + 3 for the cost of edge=2.

And you route has NO option but to travel from 1 -> 2 -> 3 because edges 7-9 are not in your graph - - oops! ;)

**Comment by dkastl** [comment]
Oh, true. I forgot the cost of edge `2`.
Well, I wanted to force it to go through nodes `1 -> 2 -> 7 -> 2 -> 3 -> 4`.

**Comment by woodbri** [comment]
Then why NOT include those edges? ``FROM network WHERE id < 5``

**Comment by dkastl** [comment]
Oh, it seems my brain is not yet working this Momday ;)
You're right ... I excluded edge 7. Well, including it doesn't change anything though.

```
SELECT seq, id1 AS node, id2 AS edge, cost FROM pgr_trsp('
    SELECT id, source, target, cost::float, reverse_cost::float FROM network WHERE id != 7', 
    1, 4, true, true, 
    'SELECT to_cost, to_edge AS target_id, from_edge::text AS via_path FROM restrictions'
);
```

The result remains the same.

**Comment by woodbri** [comment]
Just remove the where cause, you still have it wrong. id != 7 excludes edge 7!

**Comment by woodbri** [comment]
oh: Well, I wanted to force it to go through nodes 1 -> 2 -> 7 -> 2 -> 3 -> 4. this is not possible. it violates the fundamentals of shortest path.

**Comment by dkastl** [comment]
Oh, today is really not a good day ...
But in my test query I actually had it already right, just made a mistake when I formatted on Github:

```
# SELECT seq, id1 AS node, id2 AS edge, cost FROM pgr_trsp(
    'SELECT id, source, target, cost::float, reverse_cost::float FROM network WHERE id != 6', 
    1, 4, true, true, 
    'SELECT to_cost, to_edge AS target_id, from_edge::text AS via_path FROM restrictions');
 seq | node | edge | cost 
-----+------+------+------
   0 |    1 |    1 |    1
   1 |    2 |    2 |  103
   2 |    3 |    3 |    1
   3 |    4 |   -1 |    0
(4 rows)

```
(Now copied the query right from my terminal window to be sure ;-)

**Comment by dkastl** [comment]
You mean the shortest path presumption for algorithms like Dijkstra, that a node cannot be visited twice, also applies for TRSP?

**Comment by woodbri** [comment]
Correct. TRSP is just Dijkstra with some additional code to handle the restrictions.

**Comment by woodbri** [comment]
Dijkstra's algorithm, converts the graph into a tree and a tree can not have any loops in it.

**Comment by dkastl** [comment]
OK, good to know. So handling [jughandle turns](http://en.wikipedia.org/wiki/Jughandle) would not work either, I guess.

**Comment by woodbri** [comment]
Hmmm, jughandles work because TRSP is edge based not node based.

**Comment by cvvergara** [comment]
improvements on trsp are not done yet.

**Comment by cvvergara** [comment]
Work has been done for TRSP on develop branch for version 3.4 (due to be released on September/October 2022:
https://github.com/pgRouting/pgrouting/issues/2238
Please check the documentation
https://docs.pgrouting.org/dev/en/TRSP-family.html
and the migration guide:
https://docs.pgrouting.org/dev/en/trsp_migration.html

For further similar problems with TRSP functions please open a new issue with the specific function name.
