### ISSUE TITLE
Cleanup KSP directory

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#293]
In branch "develop_ksp" the source has been updated with latest KSP modifications in the upstream project: https://github.com/pgRouting/pgrouting/commit/5fc9cff624778f4038e2658433acf9979e28ee8d

The "Basepath" files are not included in the `CMakeList.txt`, but it still compiles and seems to work.
There are also other files, which are not referenced in `CMakeList.txt`, so maybe they are not needed.

**Comment by dkastl** [comment]
Updating KSP from https://code.google.com/p/k-shortest-paths/ does not solve the issue #285

**Comment by woodbri** [comment]
Has anyone looked at the patch attached to #229? I think this is the same problem that many of the other algorithms have had.

**Comment by dkastl** [comment]
I sent the link to Dave but he didn't mention it.

**Comment by cvvergara** [comment]
Fixed with  commit 5cdd106ebe
