### ISSUE TITLE
Can't install pgrouting in non-public using extension

### ISSUE THREAD

**Issue by robe2** [pgRouting/pgrouting#298]
If I do this.  This is with 2.0.0

``` 
CREATE EXTENSION  pgrouting schema contrib;

```

I get this error:
```
ERROR:  function pgr_iscolumnindexed(text, text) does not exist
```

However I can do this to overcome:

```
CREATE EXTENSION  pgrouting schema public;
ALTER EXTENSION  pgrouting SET schema contrib;

```

**Comment by woodbri** [comment]
Any ideas on why this happens. I have run into other issues when installing into a schema and your workaround worked for me also. I have looked into it but I'm not seeing anything obvious.

**Comment by robe2** [comment]
There is a hard-coding in the extension script I think we just need to get rid of reference to public.

CREATE OR REPLACE FUNCTION public.pgr_isColumnIndexed(tab text, col text)

**Comment by robe2** [comment]
Yap just got rid of the public. in line 269 of the pgrouting-2.0.0.sql extension script and then it installs fine in a non-public schema.  But haven't looked to see how the file is generated.

**Comment by woodbri** [comment]
Ah, it is not in the develop branch so I must have fixed that.
