### ISSUE TITLE
Build system needs to be revised for how pgrouting-<version>.sql is generated

### ISSUE THREAD

**Issue by woodbri** [pgRouting/pgrouting#302]
Currently the build system assembles the pgrouting extension SQL during the cmake run and not during the make. This is counter intuitive because changes to SQL are not updated during make or make install. This should be fixed if we make any changes to the build system.

**Comment by cvvergara** [comment]
@woodbri 
Do you think that with the changes that were made for the installation process this might have being solved in this release?

**Comment by woodbri** [comment]
No. This should get pushed out to 2.2 or 3.0.
The current system creates the ``pgrouting--<version>.sql`` when cmake is run and not when make is run so there is no way to create dependency that gets checked and forces a new ``pgrouting--<version>.sql`` file to be created if any of the dependent files are changed.

Too extensive a change to the build system to deal with this now.

**Comment by cvvergara** [comment]
@woodbri 
```
I think I fixed this issue in develop, you might want to try.
cd build/
cmake  ..
make
vi ../sql/vrppdtw/gsoc_vrppdtw.sql  (add a blank line)
make
```

please verify that this is what you mean

**Comment by cvvergara** [comment]
@woodbri 
I verified my own work, So I will close the issue, if you think my interpretation is wrong open a new issue
