### ISSUE TITLE
Dijkstra, accepting anytype as id  (edge's id)

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#303]
```
select * from  pgr_dijkstra( 'select id* 10000000000::bigint as id, source , target,   
                      cost from edge_table',
                      1, 6 , true,false);
 seq | id1 |     id2     | cost 
-----+-----+-------------+------
   0 |   1 |  1410065408 |    1
   1 |   2 |  1345294336 |    1
   2 |   5 | -1604378624 |    1
   3 |   6 |          -1 |    0
```
I also added a new column "name" and gave different names to each edge
select pg_typeof(name),name from edge_table limit 1;

```
     pg_typeof     | name 
-------------------+------
 character varying | a
```
And ran the query
```
select * from  pgr_dijkstra( 'select name as id, source , target,   
                      cost  from edge_table',
                      1, 6 , true,false);
 seq | id1 |    id2     | cost 
-----+-----+------------+------
   0 |   1 | -822715968 |    1
   1 |   2 | -822715536 |    1
   2 |   5 | -822714960 |    1
   3 |   6 |         -1 |    0
```

**Comment by woodbri** [comment]
All the existing code should be checking column types and throwing an error if they are not correct. The current code expects node and edge ids to be integer type so its an error if they are not until we change the specification.

**Comment by cvvergara** [comment]
select * from  pgr_dijkstra( 'select id* 10000000000::bigint as id, source , target,   
                      cost from edge_table',
                      1, 6 , true,false);
ERROR:  Support for id only of type: integer
CONTEXT:  SQL statement "SELECT _pgr_4parameter_check(sql)"
PL/pgSQL function pgr_dijkstra(text,integer,integer,boolean,boolean) line 6 at PERFORM

**Comment by cvvergara** [comment]
select * from  pgr_dijkstra( 'select id::bigint as id, source , target,   
                      cost from edge_table',
                      1, 6 , true,false);
ERROR:  Support for id only of type: integer
