### ISSUE TITLE
Add .editorconfig file to root

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#304]
To unify configuration of editors let's use `editorconfig`: http://editorconfig.org

**Comment by cvvergara** [comment]
sounds like a tool why not in tools directory?

**Comment by dkastl** [comment]
It's not really a tool. It's more like `.gitignore`.
Nowadays many editors support `.editorconfig`, which helps developers to use the same settings for tabs/spaces, line ends, etc..

**Comment by cvvergara** [comment]
I use vi.
So maybe your concern is more of on "how the code looks"
Steve, for vrp, found a program that formats the code according to some configuration. It parses the code and modifies the indentations according to that configuration and much more. astyle is the name. But then again, the programmer can code as he wants and you parse it an read it as you want, it will change the code "looks".
I never liked it personally. for example, it changes the tabs to spaces at the beginning of the line. 

I am trying to adhere to this (not that I am doing a good job doing it):
http://google-styleguide.googlecode.com/svn/trunk/cppguide.html
ccplint.py points out some of the errors in the coding style mentioned above. (I did use it, but I modify afterwards and I forgot to re-use it) but it doesn't change the code looks. For example it points out where is the tab, and then the programmer replaces it to spaces.
example:
http://www.sw-engineering-candies.com/snippets/cpp/hello-world-google-cpp-style-guide-compliant

**Comment by dkastl** [comment]
Look at the source code and see, that some people use spaces, some tabs, some use length of 4 and some 2. And some don't care at all and just mix everything up.

Editorconfig doesn't prevent to create messy source code, but it provides the settings for editors, which support it. It's easy and simple and doesn't hurt. If someone wants to write ugly formatted source code, that's still possible ;-) 
I use it for my projects, because then I don't need to set editor configuration manually.

Btw., there is a plugin for Vim: https://github.com/editorconfig/editorconfig-vim#readme
And I like this editor: http://www.sublimetext.com/3 It's fast and has some nice features, and for "vi" addicts it also allows "vi mode": http://www.sublimetext.com/docs/3/vintage.html

Anyway, I'm just going to add and configure this file. Just created this ticket as a reminder, that I might also need to explain it somewhere.

**Comment by woodbri** [comment]
My 2 cents on this.

1. we run astyle on all the code once using the same setting as we used on our vrprepo to standardize the formatting and then we only run it when we are getting ready to release code or if a file gets really messed up.

2. Tabs should be spaces and indents 4 spaces

I'm fine with setting editorconfig to match these standards, but there is no assurance that people will use it. For example I already have vi setup for these standards.

**Comment by dkastl** [comment]
In the worst case scenario, the file will be just useful for myself ;-)

I will commit an initial version and we can then adjust it to match our "coding standard". 
The settings may differ by file type. Some like the Travis YAML files for example may be strict with tabs and spaces. Will check by then.

**Comment by dkastl** [comment]
When looking at source files I just saw that indents and tabs are a mess ;-)
