### ISSUE TITLE
Review branch gsoc-vrppdtw for possible inclusion in 2.1.0

### ISSUE THREAD

**Issue by woodbri** [pgRouting/pgrouting#307]
Review branch gsoc-vrppdtw for possible inclusion in 2.1.0. This is supposed to solve the pickup and delivery problem with time windows.

**Comment by cvvergara** [comment]
https://github.com/pgRouting/pgrouting/tree/merge-gsoc-vrppdtw

**Comment by cvvergara** [comment]
I just merged the branch into develop_2_1_0
@woodbri 
Thanks for generating the mergeable branch.

**Comment by cvvergara** [comment]
Sorry, forgot we are using the labels instead of closing
