### ISSUE TITLE
Append "_" to internal functions

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#309]
There are quite a few functions, which seem to be used only internally. 
It doesn't make sense to add them all to the documentation and maintain them. 

Instead we could follow the way PostGIS does and let internal (private) functions start with `_`.

To make sure that we don't break somebody's software, let's add a wrapper function add first which raises a notice that the function will be removed in upcoming releases.

**Comment by cvvergara** [comment]
as internal I understand developers use it.
What about the documentation for the _pgr_foo for developers, shall it be moved to the wiki?
The documentation on the pgRouting site, add a message that states the removal in future releases?

**Comment by dkastl** [comment]
I would pledge for documentation within the source code.
We should probably talk about some standardized format. Then we can also write a script, that automatically maintain Wiki pages or whatever else. But for the beginning I would prefer to keep source code and documentation together.

**Comment by cvvergara** [comment]
What about? :  in 1 and only 1 wiki page with list of all those functions with:
a link to the source code that has the documentations
a link to a place where its actually being used
That way the developer has a reference point to the source documentation and a working example of how its being used.

**Comment by dkastl** [comment]
Well, someone has to maintain this Wiki page manually?

**Comment by cvvergara** [comment]
If some one adds a "new" _ he just has to go and add the name and two links in the wiki page.
But as a start all the existing ones, its just a matter of doing it once.
I can do that....
actually I am asking, because I am almost finish with the underscoring of the ones that were original on V2.0

**Comment by cvvergara** [comment]
I made a demo of my idea here:
https://github.com/pgRouting/pgrouting/wiki/Developers-plpgsql-support-functions-demo

**Comment by woodbri** [comment]
I think we can use doxygen documentation is plpgsql use the /**  ... */ comment notation, then extract the internal doc using doxygen. It would also make sense as we work on existing C/C++ code to add doxygen comments.

**Comment by cvvergara** [comment]
The underscored version of the internal functions are ready for V2.1, the missing part is the internal documentation. doxigen does not support sql files, So, I will try to look for a way around.

**Comment by dkastl** [comment]
I think renaming these functions is a typical case for not being backwards compatible.

The question is now, if it's worth to keep the old function names as an alias and return a warning that the function name is deprecated. Then one or two releases later they could be removed.

But I'm not sure anyone is using them.

**Comment by cvvergara** [comment]
For pgRouting, I modified the code that uses them, basically are the topology functions, now they use the underscored version. Now, outside of pgRouting I don't know if anyone is using them in their developments.
They are intended to be used by developers, like @Zia-.
