### ISSUE TITLE
pgr_pointstovids

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#316]
Referring to #309 we should rename `pgr_pointstovids` to `_pgr_pointstovids` and provide a wrapper (returning a notice) to ensure backwards compatibility.

**Comment by cvvergara** [comment]
This is a front end driven function To make an example

This is a query to get the nearest vertex `id` to point x1, x2

```
SELECT id FROM ways_vertices_pgr
            ORDER BY the_geom <-> ST_SetSRID(ST_Point(x1,y1), 4326) LIMIT 1;
```

this is a query to get the nearest vertex `osm_id` to point x1, x2

```
SELECT osm_id FROM ways_vertices_pgr
            ORDER BY the_geom <-> ST_SetSRID(ST_Point(x1,y1), 4326) LIMIT 1;
```

this is a query to get the nearest vertex `my_id` to point x1, x2

```
SELECT my_id FROM ways_vertices_pgr
            ORDER BY the_geom <-> ST_SetSRID(ST_Point(x1,y1), 4326) LIMIT 1;
```

a pgRouting query may go

```
SELECT * pgr_foo('SELECT id .....', .....)
SELECT * pgr_foo('SELECT osm_id AS id .....', .....)
SELECT * pgr_foo('SELECT my_id AS id .....', .....)
```

**Comment by cvvergara** [comment]
with pull request #705 this functions has being deprecated
