### ISSUE TITLE
pgr_pointstodmatrix

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#317]
Referring to #309 we should rename `pgr_pointstodmatrix` to `_pgr_pointstodmatrix` and provide a wrapper (returning a notice) to ensure backwards compatibility.

**Comment by cvvergara** [comment]
I made some pgTap tessts made bsed on the documentation
../../src/convinience/test/pgtap/pointsToDMatrix-types-check.sql .. 1/3 
# Failed (TODO) test 1: "Function pgr_pointstodmatrix(geometry[]) should exist"
# Failed (TODO) test 2: "Function pgr_pointstodmatrix(geometry[], integer) should not exist"
# Failed (TODO) test 3: "Function pgr_pointstodmatrix(geometry[]) should return record"

**Comment by cvvergara** [comment]
The reason for this functions to exist is pgr_tsp V2.0, 2.1, 2.2 signatures as a preprocessing function where the results are given as a parameter to pgr_tsp.
This pgr_tsp signatures are going to be deprecated on V2.3 and for new different signatures where:

    pgr_eucledianTSP does not need a matrix
    pgr_tsp, the matrix is given as a postgres set query instead of an array (see #368 (comment) about large arrays)

So, this functions are being deprecated together with the pgr_tsp deprecated signatures.
They will remain on the project during the 2.x versions for backwards compatibility.
