### ISSUE TITLE
database crashes when a large number was entered as target id 

### ISSUE THREAD

**Issue by jaapdekker** [pgRouting/pgrouting#32]
with a normal number it's fast 4860887 152ms 
with a larger number it becomes slow  34860887 19435ms
with an even larger number it crashes the database 134860887 after 28 seconds it crashed the database 

I could reproduce it both under linux/postgres9 and windows/postgres8.4 
under windows the timings are different 300 ms ,1500 ms ,250 ms the first two gave a result and the third also caused the database to crash 

The SQL of the network used for testing is below. For the first two tests the number 134860887 is changed 

DROP TABLE IF EXISTS network;
CREATE TABLE network (id integer PRIMARY KEY, source integer, target integer, cost float);
INSERT INTO network(id,source,target,cost) VALUES
(134034453,4401484,4401467,1491.35562366006),
(134034463,4401489,4401485,12.1046145920234),
(134034458,4401487,4401477,177.374061187772),
(134095663,4401465,4401476,2014.71852797927),
(134034459,4401485,4401487,201.968135582698),
(134095834,4401478,4401465,293.089423713387),
(134034461,4401488,4401489,418.687894948968),
(629678698,4415069,134860887,3776.78929640359),
(134034456,4401477,4401481,491.242305990214),
(134095832,4401482,4401487,76.1157555542275),
(134034465,4401490,4401489,1956.98967514724),
(134034454,4401483,4401486,1356.25190452873),
(134034462,4401487,4401478,17.2205341642897),
(134095833,4401477,4401478,2014.66722340654),
(134034455,4401485,4401483,53.5613132396201),
(134034467,4401488,4417647,2597.20106449741),
(134034452,4401483,4401467,350.071683838508),
(134034446,4401481,4401476,568.270689073724),
(134072383,4416226,4401482,322.141177736713),
(134034447,4401482,4401481,1522.8331095897),
(134034466,4401486,4401490,610.880612548267),
(134034468,4417647,4401486,507.803184036552),
(134034464,4401490,4401485,149.914370088613);
DROP INDEX IF EXISTS idx_network_source;
DROP INDEX IF EXISTS idx_network_target;
CREATE INDEX idx_network_source ON network(source);
CREATE INDEX idx_network_target ON network(target);
SELECT * FROM shortest_path('SELECT id, source, target, cost FROM network', 4401489, 4401483, false, false)

**Comment by cvvergara** [comment]
pgr_dijstra, pgr_ksp and pgr_dirvingDistance should work with big numbers
Moving the issue to milestone 2.2 for the other functions

**Comment by cvvergara** [comment]
I was reading in detail this issue, it mentions functions that we do not support any more like:

- shortest_path
- turn_restrict_shortest_path
- driving_distance

Instead of shortest_path use pgr_dijkstra
```
SELECT * FROM pgr_dijkstra('SELECT id, source, target, cost FROM network', 4401489, 4401483, false) ;
 seq | path_seq |  node   |   edge    |       cost       |     agg_cost     
-----+----------+---------+-----------+------------------+------------------
   1 |        1 | 4401489 | 134034463 | 12.1046145920234 |                0
   2 |        2 | 4401485 | 134034455 | 53.5613132396201 | 12.1046145920234
   3 |        3 | 4401483 |        -1 |                0 | 65.6659278316435
```

Instead of driving_distance use pgr_drivingdistance
```
SELECT * from pgr_drivingdistance('select 1 as id, 1000000000 as source, 1000000001 as target, 0.9::float8 as cost, 0.8::float8 as reverse_cost', 1000000000, 0.5, True);
 seq |    node    | edge | cost | agg_cost 
-----+------------+------+------+----------
   1 | 1000000000 |   -1 |    0 |        0
```

Instead of turn_restrict_shortest_path use  pgr_trsp
```
SELECT * FROM pgr_trsp(
'SELECT id, source, target, cost FROM network', 
4401489, 4401483, false, false, null) ;
 seq |   id1   |    id2    |       cost       
-----+---------+-----------+------------------
   0 | 4401489 | 134034463 | 12.1046145920234
   1 | 4401485 | 134034455 | 53.5613132396201
   2 | 4401483 |        -1 |                0
(3 rows)
```

For the queries posted on this issue the functions in V2.1 work.
I am closing this issue.
