### ISSUE TITLE
apspWarshall

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#324]
From the documentation:
```
SELECT seq, id1 AS from, id2 AS to, cost
    FROM pgr_apspWarshall(
        'SELECT id, source, target, cost FROM edge_table',
        false, false
    );
```
So all edges in the following graph are undirected because Directed = false.
The meaning of a -1 in column cost in the data from the documentation, as far as I understand, mean that the edge doesn't exist.
And the graph looks like this, as far as my understanding:
![fig2-cost](https://cloud.githubusercontent.com/assets/5035290/6987715/72c5253a-da07-11e4-8f4a-a7972eb83347.png)
From the documentation tests:
```
SELECT seq, id1 AS FROM, id2 AS to, cost
    FROM pgr_apspWarshall(
        'SELECT id, source, target, cost FROM edge_table',
        false, false
    ) limit 10;
```
My intuition gives the following results: (seq,from,to,cost)
0 | 1 | 1   | 0
1 | 1 | 2   | 1
2 | 1 | 3   | 4
3 | 1 | 4   | 5
4 | 1 | 5   | 2
5 | 1 | 6   | 3
6 | 1 | 9   | 4
7 | 1 | 10 | 3
8 | 1 | 11 | 4
9 | 1 | 12 | 5
The documentation test's results are: (seq,from,to,cost)
0 | 1 | 1   | 0
1 | 1 | 2   | 1
2 | 1 | 3   | 0
3 | 1 | 4   | -1
4 | 1 | 5   | 2
5 | 1 | 6   | 1
6 | 1 | 9   | 0
7 | 1 | 10 | 3
8 | 1 | 11 | 2
9 | 1 | 12 | 1
The documentation mentions that cost is a positive value. If that is the case how can one get a negative value as a result?
Comparing: other functions state that negative values are being ignored, (edge not inserted).
Are edges with negative costs being inserted?
Non existing edges being inserted?
I can deduce the following:
to get a 0 from 1 to 3 is using the following route: edge costs in parenthesis.
1(1) 2 (-1) 3 total = 0
to get a -1 from 1 to 4:
1(1) 2 (-1) 3 (-1) 4 total = -1 
to get a 0 from 1 to 9
1(1) 2 (-1) 3 (-1) 4 (1) 9 total = 0

For me there is something that doesn't make sense.

**Comment by cvvergara** [comment]
I am revising my intuition.. and because its an undirected graph (Directed = false)
I missed the following
1 to 7 with cost 4
1 to 8 with cost 3
which in a directed graph would not be part of the solution.

**Comment by cvvergara** [comment]
related to this #105

**Comment by cvvergara** [comment]
Pseudocode sugested by Christoph Mayrhofer to actually generate the paths
```
function neighbors_list(links[])
	neighbors[][] := [][] // associative list containing lists of all neighbors for each node
	for link in links[]
		add link[node2] to neigbors[link[node1]]
		add link[node1] to neigbors[link[node2]]
	return neighbors[][]
	
function P_from_D(D[][], links[])
	neighbors[][] := neighbors_list(links[])
	P[][] := sizeof(D[][])
	for i from 1 to |V|
               for j from 1 to |V|
			min_dist := inf
			next := null
			for neighbor in neighbors[i] 
				dist := D[i][neighbor] + D[neighbor][j]
				if dist < min_dist
					min_dist := dist
					next := neighbor
			P[i][j] := next
```

**Comment by woodbri** [comment]
More stuff from Christoph Mayrhofer email that might be helpful:

```
let dist be a |V| × |V| array of minimum distances initialized to ∞ (infinity)
let next be a |V| × |V| array of vertex indices initialized to null

procedure FloydWarshallWithPathReconstruction ()
   for each edge (u,v)
      dist[u][v] ← w(u,v)  // the weight of the edge (u,v)
*     next[u][v] ← v   // << -- this line is needed to reconstruct the path later
   for k from 1 to |V| // standard Floyd-Warshall implementation
      for i from 1 to |V|
         for j from 1 to |V|
            if dist[i][k] + dist[k][j] < dist[i][j] then
               dist[i][j] ← dist[i][k] + dist[k][j]
*              next[i][j] ← next[i][k]   // << -- this line is needed to reconstruct the path later

// this function reconstructs the path from the "next" matrix
procedure Path(u, v)   
   if next[u][v] = null then
       return []
   path = [u]
   while u ≠ v
       u ← next[u][v]
       path.append(u)
   return path

```
This adaption requires the pgrouting source code to be changed. (the two lines marked with a * need to be added)
Since I already mentioned that I am not very much into that I came up with the following algorithm that allows to reconstruct the path from the resulting distance matrix as produced by the current pgr_apspWarshall
It does not require the matrix with the first node of the path (next[][]) as mentioned in the code snippet above, but uses the distance matrix in combination with the link list to build the path. 
So what I currently do: use pgrouting to get the distance matrix ... and then use the functions in the post above to extract the paths.

**Comment by cvvergara** [comment]
For the 2.2 version:
```
CREATE OR REPLACE FUNCTION pgr_floydWarshall(edges_sql TEXT, directed BOOLEAN)
RETURNS SET OF (seq bigint, from_vid bigint, to_vid bigint, cost float)
```

- The algorithms correct name is not Warshall, its floyd-Warshall
- As it does not returns an actual path, removing `apsp` will avoid people think of misleading functionality.
- It would be a mirror of [boost.graph](http://www.boost.org/doc/libs/1_59_0/libs/graph/doc/floyd_warshall_shortest.html) implementation except for:
  - As in the other functions, we insert only edges with positive weights so:
    - the call to boost::graph::`floyd_warshall_all_pairs_shortest_paths` it would be always return true. 
- Fixes the negative return values `pgr_apspWarshall` its giving.
- Returns meaningful names
- Also accepts in the sql: id, source, target types that are ANY-INTEGER.
- if there are V vertices:
  - Boost returns a VxV matrix. 
    - We would only return the non infinity values.
    - for the undirected graph, even that the matrix its symmetric. So we let to the users choice of deleting the upper or lower part of the matrix using a wrapper.
  - The time complexity is O(V^3).

To fix the issues of the current `pgr_apspWarshall`:
- It would be a wrapper to  `pgr_floydWarshall` where:
  - before calling `pgr_floydWarshall`:
    - raises a notice of 'Deprecated Function: Use pgr_floydWarshall instead'
    - enforces in the sql: id, source, target types that are integer
    - catches user contradiction about reverse_cost column and has_rcost 
      - stops if flag says it exists but it does not.
      - ignores reverse_column when it says it doesn't exist
   - the return values of  `pgr_floydWarshall` will be transformed to  `pgr_costresult` type:
     - (seq, id1, id2, cost)

**Comment by cvvergara** [comment]
Forgot to mention:
About Christoph Mayrhofer email:
I will not modify boost.graph implementation of Floyd-Warshall algorithm
When their implementation returns also the paths, we can then talk about getting them also.

**Comment by cvvergara** [comment]
So I will discuss what just came to mind...

# Is the `seq` needed for this function??

Let be the case the values returned are stored in a table, so the unique index that makes sense would be the pair:
`(from_vid, to_vid)`
that is, there is no relation between `seq` and the results
if the `edges_sql` is for exampĺe:
`SELECT id, source, target, cost FROM edges_table ORDER  BY id ASC`
vs
`SELECT id, source, target, cost FROM edges_table ORDER BY id DESC`
they both return the same `SET OF (from_vid, to_vid, cost)`
but different `SET OF (seq, from_vid, to_vid, cost)`
`seq` was thought of because of the misconception that is returning a path. But it is not returning a path!!!
comments?
# I plan to remove `seq`

**Comment by woodbri** [comment]
seq is probably not needed for this command. I'm +1 on removing it for this function.

The purpose of seq is to be able to force the correct ordering of results when order of the records matters, because RDBMS work on set theory and set theory does not consider worry about ordering of records. ie: the set 1,2,3 is the same as 3,1,2, etc. and when you join the results of a pgr_* function to another table the database does not enforce ordering on the join results unles you add an order by clause which is where seq comes is useful.

**Comment by cvvergara** [comment]
Another thing came to my mind:
For the 2.2 version:
-  agg_cost instead of cost

On a previous comment I posted
```
CREATE OR REPLACE FUNCTION pgr_floydWarshall(edges_sql TEXT, directed BOOLEAN)
RETURNS SET OF (seq bigint, from_vid bigint, to_vid bigint, cost float)
```
But... to match results found using the pgr_dijkstra family of functions, the returning column name should be agg_cost, like follows:
```
CREATE OR REPLACE FUNCTION pgr_floydWarshall(edges_sql TEXT, directed BOOLEAN)
RETURNS SET OF (from_vid bigint, to_vid bigint, agg_cost float)
```
(notice I am removing the `seq`)
comments?

**Comment by cvvergara** [comment]
Related to this is #421

**Comment by cvvergara** [comment]
The internal query will requiere only:
`source, target, cost, [reverse_cost]`
instead of 
`id, source, target, cost, [reverse_cost]`
as the `id` is not needed.

**Comment by cvvergara** [comment]
Proposed documentation for pgr-floydwarshall:
http://docs.pgrouting.org/dev/src/floydWarshall/doc/floydWarshall.html#pgr-floydwarshall

**Comment by Remi-C** [comment]
Hey,
the function should definitively not return 
(e,e,0), where e is any edge from the first argument query.
Those edges are easily added if necessary with a generate_series(),
and the output result is already big enough (v^2! ).
This function hard crashes my server when used with a sparse network of about 1000 edges 
(return result should be 1 million rows).
Iknow I'm dreaming, but an option to limit the computing and output to the cost below a parameter would be the perfect solution to make this function tractable with even moderate dataset.
Cheers,
Rémi-C

**Comment by cvvergara** [comment]
+1
I like your argument.
So functions that use a matrix as input, should consider the data:
when e = (v,v)  the cost is 0
when e = (v,u)  the cost is infinity
I like the idea.
Need another +1, so I proceed  to do the suggestion for the new functions:
pgr_johnson
pgr_floydWarshall
pgr_dijkstraCost family (one to one, one to many, many to one, many to many)

**Comment by woodbri** [comment]
I'm +0 as I have not used this function and I'm not clear on the use cases for it.

**Comment by cvvergara** [comment]
Deprecating pgr_apspWarshall please use pgr_floydWarshall
pgr_apspWarshall Its being fixed by wrapping it with the results of pgr_floydWarshall
