### ISSUE TITLE
pgr_createTopology that supports incremental build of the topology.

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#329]
The following came from a user:
 John Zabrenski wrote:

    Hello everyone,

    I have a question about pgr_createTopology...

    I am attempting to make a routable US street network table using
    pgRouting (pgRouting ver 2.0.0, postGIS 2.1.1, postgresql 9.2).
    It is running on localhost (32 bit windows, 4 gb RAM).

    I have a postgres table created originally from street shapefiles that
    now has about 43 million rows.

    As I expected, the create topology function faced an out of memory error
    about halfway through the creation, and gave me this message:

    My original statement:

    SELECT pgr_createTopology('usa_streets', 0.00001, 'geom', 'gid');

    Result:

    NOTICE:  out of memory
    NOTICE:  UPDATE public.usa_streets SET source = 22148149,target =
    22152619 WHERE gid =  9166028
    Total query runtime: 96149189 ms.
    1 row retrieved.

    The resulting vertices_pgr table has only about 22 million rows and I
    get errors for null sources when trying to run routing functions.

    Would it be possible to run another Create Topology for rows in the
    original edges table where source and target are null, or will this just
    create two conflicting networks?

    I am curious if anyone here is familiar or experienced with a workaround
    for this problem? Or is the only solution more RAM? If I'm leaving out
    any relevant information please let me know.

    Thank you for reading,
    John Zabrenski

**Comment by woodbri** [comment]
@cvvergara didn't you already create a version of pgr_createtopology that allow you to incrementally build the topology and/or to add to an existing table?

**Comment by cvvergara** [comment]
@woodbri  you never merged it

**Comment by woodbri** [comment]
Is this in a branch somewhere?
If you have code that needs to be merged, please create a ticket with the branch that needs to be merged referenced in it. and you can assign it to me.

**Comment by cvvergara** [comment]
@woodbri I will, as soon I as the default value for the flag "clean" is decided and I get to modify the documentation accordingly.
