### ISSUE TITLE
VRP module's Mac OSX build warnings

### ISSUE THREAD

**Issue by sanak** [pgRouting/pgrouting#331]
I confirmed it on "develop" branch.
VRP module build log is as follows.
<pre>
:
Scanning dependencies of target vrp_single
[ 56%] Building C object src/vrp_basic/src/CMakeFiles/vrp_single.dir/VRP.c.o
/Users/sanak/Build/cpp/pgrouting-git/src/vrp_basic/src/VRP.c:451:39: warning: use of GNU old-style field designator
      extension [-Wgnu-designator]
        vehicle_columns_t vehicle_columns = {vehicle_id: -1, capacity: -1};
                                             ^~~~~~~~~~~
                                             .vehicle_id = 
/Users/sanak/Build/cpp/pgrouting-git/src/vrp_basic/src/VRP.c:451:55: warning: use of GNU old-style field designator
      extension [-Wgnu-designator]
        vehicle_columns_t vehicle_columns = {vehicle_id: -1, capacity: -1};
                                                             ^~~~~~~~~
                                                             .capacity = 
/Users/sanak/Build/cpp/pgrouting-git/src/vrp_basic/src/VRP.c:454:35: warning: use of GNU old-style field designator
      extension [-Wgnu-designator]
        order_columns_t order_columns = {id: -1, order_unit: -1, open_time: -1, close_time: -1, service_time...
                                         ^~~
                                         .id = 
/Users/sanak/Build/cpp/pgrouting-git/src/vrp_basic/src/VRP.c:454:43: warning: use of GNU old-style field designator
      extension [-Wgnu-designator]
        order_columns_t order_columns = {id: -1, order_unit: -1, open_time: -1, close_time: -1, service_time...
                                                 ^~~~~~~~~~~
                                                 .order_unit = 
/Users/sanak/Build/cpp/pgrouting-git/src/vrp_basic/src/VRP.c:454:59: warning: use of GNU old-style field designator
      extension [-Wgnu-designator]
        order_columns_t order_columns = {id: -1, order_unit: -1, open_time: -1, close_time: -1, service_time...
                                                                 ^~~~~~~~~~
                                                                 .open_time = 
/Users/sanak/Build/cpp/pgrouting-git/src/vrp_basic/src/VRP.c:454:74: warning: use of GNU old-style field designator
      extension [-Wgnu-designator]
        order_columns_t order_columns = {id: -1, order_unit: -1, open_time: -1, close_time: -1, service_time...
                                                                                ^~~~~~~~~~~
                                                                                .close_time = 
/Users/sanak/Build/cpp/pgrouting-git/src/vrp_basic/src/VRP.c:454:90: warning: use of GNU old-style field designator
      extension [-Wgnu-designator]
  ...order_columns = {id: -1, order_unit: -1, open_time: -1, close_time: -1, service_time: -1, x: -1, y: -1};
                                                                             ^~~~~~~~~~~~~
                                                                             .service_time = 
/Users/sanak/Build/cpp/pgrouting-git/src/vrp_basic/src/VRP.c:454:108: warning: use of GNU old-style field designator
      extension [-Wgnu-designator]
  ...order_columns = {id: -1, order_unit: -1, open_time: -1, close_time: -1, service_time: -1, x: -1, y: -1};
                                                                                               ^~
                                                                                               .x = 
/Users/sanak/Build/cpp/pgrouting-git/src/vrp_basic/src/VRP.c:454:115: warning: use of GNU old-style field designator
      extension [-Wgnu-designator]
  ...order_columns = {id: -1, order_unit: -1, open_time: -1, close_time: -1, service_time: -1, x: -1, y: -1};
                                                                                                      ^~
                                                                                                      .y = 
/Users/sanak/Build/cpp/pgrouting-git/src/vrp_basic/src/VRP.c:457:41: warning: use of GNU old-style field designator
      extension [-Wgnu-designator]
        distance_columns_t distance_columns = {src_id: -1, dest_id: -1, cost: -1, distance: -1, traveltime: -1};
                                               ^~~~~~~
                                               .src_id = 
/Users/sanak/Build/cpp/pgrouting-git/src/vrp_basic/src/VRP.c:457:53: warning: use of GNU old-style field designator
      extension [-Wgnu-designator]
        distance_columns_t distance_columns = {src_id: -1, dest_id: -1, cost: -1, distance: -1, traveltime: -1};
                                                           ^~~~~~~~
                                                           .dest_id = 
/Users/sanak/Build/cpp/pgrouting-git/src/vrp_basic/src/VRP.c:457:66: warning: use of GNU old-style field designator
      extension [-Wgnu-designator]
        distance_columns_t distance_columns = {src_id: -1, dest_id: -1, cost: -1, distance: -1, traveltime: -1};
                                                                        ^~~~~
                                                                        .cost = 
/Users/sanak/Build/cpp/pgrouting-git/src/vrp_basic/src/VRP.c:457:76: warning: use of GNU old-style field designator
      extension [-Wgnu-designator]
        distance_columns_t distance_columns = {src_id: -1, dest_id: -1, cost: -1, distance: -1, traveltime: -1};
                                                                                  ^~~~~~~~~
                                                                                  .distance = 
/Users/sanak/Build/cpp/pgrouting-git/src/vrp_basic/src/VRP.c:457:90: warning: use of GNU old-style field designator
      extension [-Wgnu-designator]
        distance_columns_t distance_columns = {src_id: -1, dest_id: -1, cost: -1, distance: -1, traveltime: -1};
                                                                                                ^~~~~~~~~~~
                                                                                                .traveltime = 
/Users/sanak/Build/cpp/pgrouting-git/src/vrp_basic/src/VRP.c:761:1: warning: control may reach end of non-void
      function [-Wreturn-type]
}
^
15 warnings generated.
[ 59%] Building CXX object src/vrp_basic/src/CMakeFiles/vrp_single.dir/VRP_core.cpp.o
[ 62%] Building CXX object src/vrp_basic/src/CMakeFiles/vrp_single.dir/VRP_Solver.cpp.o
/Users/sanak/Build/cpp/pgrouting-git/src/vrp_basic/src/VRP_Solver.cpp:232:1: warning: control may reach end of
      non-void function [-Wreturn-type]
}
^
/Users/sanak/Build/cpp/pgrouting-git/src/vrp_basic/src/VRP_Solver.cpp:864:21: warning: self-comparison always
      evaluates to false [-Wtautological-compare]
                                curFreeCapacity > curFreeCapacity && curFreeCapacity > bestFreeCapacity )
                                                ^
2 warnings generated.
[ 62%] Built target vrp_single
Scanning dependencies of target routing_vrp
Linking CXX shared module lib/librouting_vrp.so
[ 62%] Built target routing_vrp
:
</pre>

Probably same fix as #138 is necessary.

**Comment by cvvergara** [comment]
Based on  @sanak latest test no longer the error shows on vrp_basic on develop 2_1_0 branch

```
Scanning dependencies of target vrp_basic
[ 23%] Building C object src/vrp_basic/src/CMakeFiles/vrp_basic.dir/VRP.c.o
[ 25%] Building CXX object src/vrp_basic/src/CMakeFiles/vrp_basic.dir/VRP_core.cpp.o
[ 28%] Building CXX object src/vrp_basic/src/CMakeFiles/vrp_basic.dir/VRP_Solver.cpp.o
[ 28%] Built target vrp_basic
```
