### ISSUE TITLE
Driving distance module's CGAL 4.5.2 and Boost 1.57.0 build warnings on Mac OSX

### ISSUE THREAD

**Issue by sanak** [pgRouting/pgrouting#332]
I confirmed it on "develop" branch.
Driving distance module build log is as follows.
<pre>
:
Scanning dependencies of target routing_dd
[ 91%] Building C object src/driving_distance/src/CMakeFiles/routing_dd.dir/alpha.c.o
[ 94%] Building CXX object src/driving_distance/src/CMakeFiles/routing_dd.dir/alpha_drivedist.cpp.o
In file included from /Users/sanak/Build/cpp/pgrouting-git/src/driving_distance/src/alpha_drivedist.cpp:53:
In file included from /opt/local/include/CGAL/Delaunay_triangulation_2.h:28:
In file included from /opt/local/include/CGAL/Triangulation_2.h:38:
In file included from /opt/local/include/CGAL/Triangulation_data_structure_2.h:38:
/opt/local/include/CGAL/Compact_container.h:1159:13: warning: reference cannot be bound to dereferenced null pointer
      in well-defined C++ code; comparison may be assumed to always evaluate to true
      [-Wtautological-undefined-compare]
    return &*rhs != NULL;
            ^~~~    ~~~~
/opt/local/include/CGAL/Alpha_shape_2.h:1322:47: note: in instantiation of function template specialization
      'CGAL::internal::operator!=<CGAL::Compact_container<CGAL::Alpha_shape_face_base_2<CGAL::Filtered_kernel<CGAL::Simple_cartesian<double>,
      true>, CGAL::Triangulation_face_base_2<CGAL::Filtered_kernel<CGAL::Simple_cartesian<double>, true>,
      CGAL::Triangulation_ds_face_base_2<CGAL::Triangulation_data_structure_2<CGAL::Triangulation_hierarchy_vertex_base_2<CGAL::Alpha_shape_vertex_base_2<CGAL::Filtered_kernel<CGAL::Simple_cartesian<double>,
      true>, CGAL::Default, CGAL::Boolean_tag<false> > >,
      CGAL::Alpha_shape_face_base_2<CGAL::Filtered_kernel<CGAL::Simple_cartesian<double>, true>,
      CGAL::Triangulation_face_base_2<CGAL::Filtered_kernel<CGAL::Simple_cartesian<double>, true>,
      CGAL::Triangulation_ds_face_base_2<void> >, CGAL::Boolean_tag<false> > > > >, CGAL::Boolean_tag<false> >,
      CGAL::Default, CGAL::Default, CGAL::Default>, false>' requested here
      CGAL_triangulation_postcondition( pFace != NULL);
                                              ^
/opt/local/include/CGAL/triangulation_assertions.h:213:20: note: expanded from macro
      'CGAL_triangulation_postcondition'
   (CGAL::possibly(EX)?(static_cast<void>(0)): ::CGAL::postcondition_fail( # EX , __FILE__, __LINE__))
                   ^
/opt/local/include/CGAL/Alpha_shape_2.h:1382:7: note: in instantiation of member function
      'CGAL::Alpha_shape_2<CGAL::Triangulation_hierarchy_2<CGAL::Delaunay_triangulation_2<CGAL::Filtered_kernel<CGAL::Simple_cartesian<double>,
      true>, CGAL::Triangulation_default_data_structure_2<CGAL::Filtered_kernel<CGAL::Simple_cartesian<double>,
      true>,
      CGAL::Triangulation_hierarchy_vertex_base_2<CGAL::Alpha_shape_vertex_base_2<CGAL::Filtered_kernel<CGAL::Simple_cartesian<double>,
      true>, CGAL::Default, CGAL::Boolean_tag<false> > >,
      CGAL::Alpha_shape_face_base_2<CGAL::Filtered_kernel<CGAL::Simple_cartesian<double>, true>,
      CGAL::Triangulation_face_base_2<CGAL::Filtered_kernel<CGAL::Simple_cartesian<double>, true>,
      CGAL::Triangulation_ds_face_base_2<void> >, CGAL::Boolean_tag<false> > > > >, CGAL::Boolean_tag<false>
      >::number_of_solid_components' requested here
  if (number_of_solid_components(alpha) == nb_components) 
      ^
/Users/sanak/Build/cpp/pgrouting-git/src/driving_distance/src/alpha_drivedist.cpp:214:16: note: in instantiation of
      member function
      'CGAL::Alpha_shape_2<CGAL::Triangulation_hierarchy_2<CGAL::Delaunay_triangulation_2<CGAL::Filtered_kernel<CGAL::Simple_cartesian<double>,
      true>, CGAL::Triangulation_default_data_structure_2<CGAL::Filtered_kernel<CGAL::Simple_cartesian<double>,
      true>,
      CGAL::Triangulation_hierarchy_vertex_base_2<CGAL::Alpha_shape_vertex_base_2<CGAL::Filtered_kernel<CGAL::Simple_cartesian<double>,
      true>, CGAL::Default, CGAL::Boolean_tag<false> > >,
      CGAL::Alpha_shape_face_base_2<CGAL::Filtered_kernel<CGAL::Simple_cartesian<double>, true>,
      CGAL::Triangulation_face_base_2<CGAL::Filtered_kernel<CGAL::Simple_cartesian<double>, true>,
      CGAL::Triangulation_ds_face_base_2<void> >, CGAL::Boolean_tag<false> > > > >, CGAL::Boolean_tag<false>
      >::find_optimal_alpha' requested here
    alpha = *A.find_optimal_alpha(1);
               ^
/opt/local/include/CGAL/Compact_container.h:1095:15: note: 'operator*' returns a reference
    reference operator*() const { return *(m_ptr.p); }
              ^
1 warning generated.
[ 97%] Building CXX object src/driving_distance/src/CMakeFiles/routing_dd.dir/boost_drivedist.cpp.o
[100%] Building C object src/driving_distance/src/CMakeFiles/routing_dd.dir/drivedist.c.o
Linking CXX shared module ../../../lib/librouting_dd.so
[100%] Built target routing_dd
:
</pre>

**Comment by cvvergara** [comment]
@sanak 
The last test you made uses boost 1.58 and it doesn't seem to have this problem, so I will tag this issue to fix documentation requirement for Mac OSX
