### ISSUE TITLE
Wrong edge selection in pgr_kDijkstraPath

### ISSUE THREAD

**Issue by ikgpcz** [pgRouting/pgrouting#333]
There may be an issue in the kDijkstraPath algorithm.

In the very basic example of:

Edge table
![bildschirmfoto vom 2015-04-22 16 09 55](https://cloud.githubusercontent.com/assets/12069169/7276475/154e9dfc-e90a-11e4-9dc5-67500475bfd0.png)

and the Query

SELECT * FROM pgr_kDijkstraPath(
'SELECT gid as id, source, target, v_tc_to as cost, v_tc_from as reverse_cost FROM edges',
1, array[2], false, true);

I get the following result:
![bildschirmfoto vom 2015-04-22 16 13 21](https://cloud.githubusercontent.com/assets/12069169/7276539/83e05a94-e90a-11e4-923f-05beec78412d.png)

...which is obviously wrong since the other edge is way cheaper. In fact, the pgr_dijkstra algorithm delivers the correct result in this example...

**Comment by masc** [comment]
I can confirm this behavior in the latest version (commit 40ad51f09f) for pgr_kDijkstra running PostgreSQL 9.3.6 / PostGIS 2.1 and above example:
```
SELECT *
FROM pgr_dijkstra(
  'SELECT gid as id, source, target, v_tc_to as cost, v_tc_from as reverse_cost FROM test_ways',
  2, 1, true, true
);
 
seq | id1 |  id2  | cost
-----+-----+-------+------
   0 |   2 | 25735 | 3.59
   1 |   1 |    -1 |    0
(2 rows)
```
```
SELECT *
FROM pgr_kDijkstraPath(
  'SELECT gid as id, source, target, v_tc_to as cost, v_tc_from as reverse_cost FROM test2_ways',
  2, array[1], true, true
);

 seq | id1 | id2 |  id3  | cost
-----+-----+-----+-------+-------
   0 |   1 |   2 | 15371 | 16.72
   1 |   1 |   1 |    -1 |     0
(2 rows)
```

**Comment by woodbri** [comment]
There are multiple issues for this problem and one patch that may fix it. See #227 #229 #246 #333

**Comment by ikgpcz** [comment]
You are right! The problem seems in fact to go backwards to 2011: #34 

Obviously, the problem has been fixed for the standard Dijkstra, but still not for kDijkstra (and maybe also others). 

Nevertheless, the workaround with the ORDER BY cost seems to works fine. Perhaps it should also be mentioned in the docs?

**Comment by woodbri** [comment]
We are review a lot of the code and plan to make some big changes so all the Dijkstra related functions share the same code base and will be consistent across all the related functions.

**Comment by cvvergara** [comment]
What about: 
deprecate  pgr_kDijkstraPath in favor of
```
pgr_dijkstra(TEXT,BIGINT,ARRAY[ANY-INTEGER],directed)
```
benefits:
 - bugs are fixed
 - no new function name is needed
 - auto detection of reverse_cost column
 - meaningful return names
 - The edges and vertices id's can be of ANY_INTEGER


```
doc_data=# select * from issue333;
select * from issue333;
 id | source | target | cost  | reverse_cost 
----+--------+--------+-------+--------------
  1 |      1 |      2 | 16.72 |        16.72
  2 |      2 |      1 |  3.59 |         3.59
(2 rows)

doc_data=# SELECT * FROM pgr_kDijkstraPath(
    'SELECT id, source, target, cost, reverse_cost FROM issue333',
    1, array[2], false, true);
 seq | id1 | id2 | id3 | cost  
-----+-----+-----+-----+-------
   0 |   2 |   1 |   1 | 16.72
   1 |   2 |   2 |  -1 |     0
(2 rows)

doc_data=# SELECT * FROM pgr_dijkstra(
    'SELECT id, source, target, cost, reverse_cost FROM issue333',
    1, array[2], false);
 seq | path_seq | end_vid | node | edge | cost | agg_cost 
-----+----------+---------+------+------+------+----------
   1 |        1 |       2 |    1 |    2 | 3.59 |        0
   2 |        2 |       2 |    2 |   -1 |    0 |     3.59
(2 rows)
```

for 2.x, in order not to break code
pgr_kDijkstraPath can be defined in terms of pgr_dijkstra
 - documentation of pgr_kDijkstraPath requires data to be integer. So only in this case pgr_kDijkstraPath can be defined.

**Comment by woodbri** [comment]
+1 sounds like a good idea.

**Comment by robe2** [comment]
+1 from me.  I actually thought we already deprecated.

**Comment by cvvergara** [comment]
@robe2 
Yes, we discussed so much about it but, wasn’t formally deprecated.

**Comment by cvvergara** [comment]
Deprecating pgr_kdijkstraPath please use pgr_dijkstra
pgr_kdijkstraPath Its being fixed by wrapping it with the results of pgr_dijkstra

 Deprecating pgr_kdijkstraCost please use pgr_dijkstraCost
pgr_kdijkstraCost Its being fixed by wrapping it with the results of pgr_dijkstraCost
