### ISSUE TITLE
routing over waypoints

### ISSUE THREAD

**Issue by MannusEtten** [pgRouting/pgrouting#334]
is there a possibility to calculate shortest path with some intermediate waypoints?

**Comment by dkastl** [comment]
No, not at the moment.
It's an interesting feature, so any contribution or funding to make it happen is highly welcome!

**Comment by Zia-** [comment]
Hi Guys!
I wrote this (https://github.com/Zia-/pgr_aStarFromAtoBviaC) SQL code few months ago for my own project. It's calculating routes using aStar algo via intermediate points. Although it's using pgRouting functions and not build on top of C or some other languages, it's working for me. Let me know if this is helpful.

**Comment by Tho77** [comment]
A non-perfect workaround is to calculate a separate path from start to A, A to B, B to finish and then stitch them together for a final path.

**Comment by woodbri** [comment]
Actually, we have code for this in the "develop" branch here.
https://github.com/pgRouting/pgrouting/blob/develop/src/trsp/sql/routing_trsp_vias.sql
you should be able to run this file and add the functionality without having to compile anything.

**Comment by cvvergara** [comment]
Closing based on last comment.
