### ISSUE TITLE
SELECT pgr_nodeNetwork query fails

### ISSUE THREAD

**Issue by woodbri** [pgRouting/pgrouting#335]
From stackoverflow post:
http://stackoverflow.com/questions/29864784/select-pgr-nodenetwork-query-fails

**Comment by ldeschaumes** [comment]
I got same error on
Ubuntu 14.04. LTS 64bits
Postgis 2.1.2
Postgres 9.3

**Comment by ldeschaumes** [comment]
it's a mistake , geom field was multistring , change it in linestring and it 's work

**Comment by gugacavalieri** [comment]
@ldeschaumes where can you change it to linestring? Can you change it in the query or you have to override the function?

**Comment by ldeschaumes** [comment]
Just make update geometry field
like this

ALTER TABLE road
 ALTER COLUMN geom TYPE geometry(LineString,3857)
  USING ST_LineMerge(geom);


----- Mail original -----
| 
| 
| @ldeschaumes where can you change it to linestring? Can you change it
| in the query or you have to override the function?
| 
| —
| Reply to this email directly or view it on GitHub .
| 
|
