### ISSUE TITLE
Topology

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#341]
I found this "old" document, (uses 1.0) but it relates potgis topology with pgrouting. I wonder, if instead of reinventing the wheel (aka use our topology) we can do stuff with postgis topology, hav any one seen that?
http://strk.keybit.net/projects/postgis/Paris2011_TopologyWithPostGIS_2_0.pdf

**Comment by woodbri** [comment]
Yes this has been discussed and it does not make sense to use postgis topology pgrouting. For example it does not support overpass underpass intersections that are not connected from a routing point of view. It is very complicated to use, and much slower than our our pgr_createTopology(). 

It is solving a geometrical topology and not a graph topology. These have a lot of similar components, but graph topology has concerns that are not covered by geographical topology, like intersection constraints like overpasses, one way and bi-directional edges, edge weights.

**Comment by cvvergara** [comment]
I don't think of pgRouting being used only for routing cars. It might so happen that the majority of our users think on routing cars. (like I got here because I wanted to make a route from my house to my dads house). But what about data routing, flow analysis, the network doesn't need to be car focus specific.
"Complicated" is a matter of point of view. I haven't gone into it yet, so I can't decide yet how I see postgis topology. (I will later on)
About overpass, underpass intersections that are not connected: you mean a disconnected graph (at least is what I understand with not connected?. 
What do you mean with "solving a geometrical topology"?
By geographical topology, you mean like streets. But a topology doesn't need to be street only, like in the paper, there are also topologies used for rivers.
I really should try to use pgRouting to find the relationships I have in my family tree.

**Comment by woodbri** [comment]
in postgis topology, you can not model two lines the cross one another without intersecting the lines and creating a node that connects the all four pieces of the two lines at a common node. In pgrouting you have to be able to model say a limited access highway that has a minor road the crosses under the highway but is not accessible from that highway. IE: you can not make a right turn from the highway onto the minor road that is 20 feet below the highway and not connected at the intersection to the highway. In postgis topology you can not model that. So be definition it is not suitable. 

Also Strk, the author of postgis topology as stated that it in not suitable networks:
http://strk.keybit.net/blog/2011/11/21/topology-cleaning-with-postgis/
"strk says:	
October 15, 2013 at 3:47 pm	

The PostGIS topology model follows the “Topology-Geometry” ISO model, which is not appropriate for route networks. Another ISO model “Topology-Network” is what you are after, which is not implemented in the core right now. Consider giving pg_routing a try. Or start work on a core implementation, it’d be fun ! :) "

**Comment by dkastl** [comment]
I think the PostGIS topology has other problems in mind, for example you want to simplify country boundaries, but you want to keep the borders correct.

I tried PostGIS Topology once to compute source and target columns. And even if the problems Steve mentioned would not exist, it just takes so much longer. Besides it's much harder to understand and the extension creates a different schema, adds a lot of functions ... and we just don't need to care about all this.

**Comment by cvvergara** [comment]
I feel flattered that the functions I made are better. tx guys. 
But I will have a look  anyway (not now, but later) even if we don't use it, just to see if it can give me ideas for an index based on topology.

**Comment by robe2** [comment]
I agree it would add a lot of overhead that in general is not worth it.   Might only make sense for someone already using topology (who actually has to manage the roads) or as a pre-cleaning routine before you apply pgrouting create topology functions.
