### ISSUE TITLE
Error within pgr_kdijkstraPath

### ISSUE THREAD

**Issue by micwimmer** [pgRouting/pgrouting#346]
I'm developing on a routing application which should route from 45.000
source nodes to several target nodes. Considering performance issues I
tried to use the pgr_kdijkstraPath function. It works really fast but
obviously there is a bug when calculating paths from several source nodes.

I tested with 1 source node and 2 target nodes. Result looks valid.
Then I increased the number of source nodes up to 100 and found out that
the target nodes in the result set wheren't 2 but 190! The function
internally decreased the node IDs.

This is the source:

CREATE OR REPLACE FUNCTION public.kdijkstra(in_from_node_id int,
in_to_node_ids int[]) RETURNS void AS $$
DECLARE

BEGIN

    INSERT INTO paths (seq, from_node_id, to_node_id, via_node_id, edge, cost)
    SELECT di.seq, in_from_node_id, di.id1, di.id2, di.id3, di.cost
    FROM pgr_kdijkstraPath (
        'SELECT id, source, target, cost, reverse_cost FROM osm_2po_4pgr',
        in_from_node_id, in_to_node_ids, true, true
    ) AS di
    ORDER BY seq;   
    
END;
$$ LANGUAGE plpgsql;

The function has been called 100 times (100 source node IDs) each with
the target node IDs 29730 and 60778. The result is valid for the first 7
calls, on call number 8 the target node IDs has been decreased and so on.

Here are all target node IDs found in the result set:

(29636,29637,29638,29639,29640,29641,29642,29643,29644,29645,29646,29647,29648,29649,29650,29651,29652,29653,29654,29655,29656,29657,29658,29659,29660,29661,29662,29663,29664,29665,29666,29667,29668,29669,29670,29671,29672,29673,29674,29675,29676,29677,29678,29679,29680,29681,29682,29683,29684,29685,29686,29687,29688,29689,29690,29691,29692,29693,29694,29695,29696,29697,29698,29699,29700,29701,29702,29703,29704,29705,29706,29707,29708,29709,29710,29711,29712,29713,29714,29715,29716,29717,29718,29719,29720,29721,29722,29723,29724,29725,29726,29727,29728,29729,29730,60684,60685,60686,60687,60688,60689,60690,60691,60692,60693,60694,60695,60696,60697,60698,60699,60700,60701,60702,60703,60704,60705,60706,60707,60708,60709,60710,60711,60712,60713,60714,60715,60716,60717,60718,60719,60720,60721,60722,60723,60724,60725,60726,60727,60728,60729,60730,60731,60732,60733,60734,60735,60736,60737,60738,60739,60740,60741,60742,60743,60744,60745,60746,60747,60748,60749,60750,60751,60752,60753,60754,60755,60756,60757,60758,60759,60760,60761,60762,60763,60764,60765,60766,60767,60768,60769,60770,60771,60772,60773,60774,60775,60776,60777,60778)

**Comment by woodbri** [comment]
Thank you for this report. We really need a test data and a query that reproduce the issue, so please send that to me directly.

**Comment by woodbri** [comment]
Thank you, here is the data file you sent: 
http://imaptools.com:8080/dl/issue346-pgrouting_test_case.zip

**Comment by monirul** [comment]
Hi,
I tried to generate the test case. but i faced two problem.
<strong>Problem One:</strong>
when i run the sql 
<pre>
	SELECT track_processing(); 
</pre>
it throws an error 
<pre>
	ERROR:  relation "osm_2po_4pgr" does not exist
</pre>

In the provided database, there is no table named 'osm_2po_4pgr'. but there is a table 'osm_2po_4pgr_excerpt'
so, i changed the line
<pre>
	'SELECT id, source, target, cost, reverse_cost FROM osm_2po_4pgr'
</pre>
to
<pre>
	 'SELECT id, source, target, cost, reverse_cost FROM osm_2po_4pgr_excerpt'
</pre>

<strong>Problem Two:</strong>

then i run the SELECT track_processing(); this time i got another error...
<pre>
	'ERROR:  One of the target vertices was not found or several targets are the same.'
</pre>
i tried to look into this and found that the following line causing the error.
<pre>
	PERFORM kdijkstra(tmprec.node_id, array[38759, 39012, 6149]); 
</pre>
this function was called with following params
<pre>
	kdijkstra(2848, array[38759, 39012, 6149]);
	kdijkstra(251, array[38759, 39012, 6149]);
	... [so on]
</pre>

where id: 2848, 39012, 251, are not in the database table.

i am interested to work on this bug. please let me know am i missing anything or is there any issue with the provided data.

thanks,
Monirul.

**Comment by cvvergara** [comment]
@micwimmer  @monirul 
I'am working on improvements, in this fork/branch:
https://github.com/cvvergara/pgrouting/tree/dd-develop
And I am working on the following Dijkstra functions (default value is indicated with "=" ):
```
pgr_dijkstra(sql, int source, int target, directed=true)
pgr_dijkstra(sql, arr[int] source, int target, directed=true)
pgr_dijkstra(sql, int source, arr[int] target, directed=true)
pgr_dijkstra(sql, arr[int] source, arr[int] target, directed=true)
```
I've made some basic tests, and maybe this one:
```
pgr_dijkstra(sql, int source, arr[int] target, directed=true)
```
can can be of help to what you need.
If you can give it a try, and tell me how it works for you on a real application, I would really appreciate it.

**Comment by micwimmer** [comment]
Sorry for the erroneous data. The target IDs are not in the data set. Try this call of kdijkstra within the function track_processing():

	PERFORM kdijkstra(tmprec.node_id, array[3581,4153,2328]);

The result will be written to the table paths. You can see all target IDs with

	select distinct to_node_id from paths order by to_node_id

Michael

**Comment by monirul** [comment]
Thanks for the update. I managed to regenerate the problem.

-Monirul.

**Comment by cvvergara** [comment]
Deprecating pgr_kdijkstraPath please use pgr_dijkstra
pgr_kdijkstraPath Its being fixed by wrapping it with the results of pgr_dijkstra

 Deprecating pgr_kdijkstraCost please use pgr_dijkstraCost
pgr_kdijkstraCost Its being fixed by wrapping it with the results of pgr_dijkstraCost
