### ISSUE TITLE
pgr_dijstra funtion 

### ISSUE THREAD

**Issue by noenest** [pgRouting/pgrouting#347]
Hello!!

I'm trying to pass to pgr_dijstra function the source field as a variable.
I have little experience and need help. Then I show the code of the function that I'm creating:

create or replace function path(p1 double precision, p2 double precision, f1 double precision, f2 double precision) returns void as $$
 Declare
  source1 integer;
  source2 integer;
 Begin
    select source into source1 from sp_2po_4pgr where x1=p1 and x2=p2;
    select source into source2 from sp_2po_4pgr where x1=f1 and x2=f2;

    select seq, id1 AS node, id2 AS edge, buf.geom_way from pgr_dijkstra('with buffered as (select * from sp_2po_4pgr where geom_way && (select ST_Buffer(ST_Collect(ARRAY[(select ST_AsText(geom_way) from sp_2po_4pgr where x1=p1 and x2=p2),(select ST_AsText(geom_way) from sp_2po_4pgr where x1=f1 and x2=f2)]),0.001))) select id, source, target, cost from buffered', source1, source2, false, false) as result INNER JOIN sp_2po_4pgr as buf ON result.id2 = buf.id;

 End;
$$ language plpgsql;

when I run the following query: select path(-4.5288132, -4.5275832, -4.5289673, -4.5295234);

I get: 

ERROR:  column "p1" does not exist
LINE 1: ...ect ST_AsText(geom_way) from sp_2po_4pgr where x1=p1 and x2=...
                                                             ^
QUERY:  with buffered as (select * from sp_2po_4pgr where geom_way && (select ST_Buffer(ST_Collect(ARRAY[(select ST_AsText(geom_way) from sp_2po_4pgr where x1=p1 and x2=p2),(select ST_AsText(geom_way) from sp_2po_4pgr where x1=f1 and x2=f2)]),0.001))) select id, source, target, cost from buffered
CONTEXT:  SQL statement "select seq, id1 AS node, id2 AS edge, buf.geom_way from pgr_dijkstra('with buffered as (select * from sp_2po_4pgr where geom_way && (select ST_Buffer(ST_Collect(ARRAY[(select ST_AsText(geom_way) from sp_2po_4pgr where x1=p1 and x2=p2),(select ST_AsText(geom_way) from sp_2po_4pgr where x1=f1 and x2=f2)]),0.001))) select id, source, target, cost from buffered', source1, source2, false, false) as result INNER JOIN sp_2po_4pgr as buf ON result.id2 = buf.id"
PL/pgSQL function path(double precision,double precision,double precision,double precision) line 10 at SQL statement

Thank you very much

**Comment by robe2** [comment]
This is better asked on pgrouting mailing list.  
https://lists.osgeo.org/mailman/listinfo/pgrouting-users

This is our bug ticket tracker, not a general support channel.
