### ISSUE TITLE
pgr_ksp not reliably returning k shortest paths!

### ISSUE THREAD

**Issue by alouis93** [pgRouting/pgrouting#350]
![shortest path](https://cloud.githubusercontent.com/assets/996681/8414310/2b03759c-1e65-11e5-99ca-f5f78c0d01e0.png)

So here, above is the very shortest path between 2179 and 2180, and as such it should show up in my result set when invoking `pgr_ksp`.

However, look at the following results from the `pgr_ksp` invocation: 

![pgr_ksp invocation](https://cloud.githubusercontent.com/assets/996681/8414339/573232d4-1e65-11e5-956a-d6ed580f0607.png)

And the edge shown in the first image clearly does not show up here. 

Is there a patch or anything of the sort I can use to fix this issue?

**Comment by woodbri** [comment]
Closing as duplicate. See #285, #246, #207 
Also please not that @cvvergara is reworking this code for a 2.1 or 3.0 release and you can help by testing this in her fork at https://github.com/cvvergara/pgrouting/

If you feel this is different from the above issues, please reopen and explain why. Thanks.

**Comment by cvvergara** [comment]
Can you give me results of: (including errors/notice messages if any)

```
pgr_version();
select * from pgr_dijkstra('select * from b_graph', 2179, 2180);
select * from pgr_dijkstra('select * from b_graph', 2179, 2180, true);
select * from pgr_dijkstra('select * from b_graph', 2179, 2180, false);
select * from pgr_dijkstra('select * from b_graph', 2179, 2180, true, false);
select * from pgr_dijkstra('select * from b_graph', 2179, 2180, false, false);

select * from pgr_ksp('select * from b_graph', 2179, 2180, 1, true);
select * from pgr_ksp('select * from b_graph', 2179, 2180, 1, false);
select * from pgr_ksp('select * from b_graph', 2179, 2180, 5, true);
select * from pgr_ksp('select * from b_graph', 2179, 2180, 5, false);
```

**Comment by cvvergara** [comment]
No response from the user, I am closing
