### ISSUE TITLE
Preparing for pgRouting  2.1.0

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#364]
The following two wiki pages present the development plan and the release process checklist.
[ pgRouting 2.1 Development plan ] (https://github.com/pgRouting/pgrouting/wiki/2.1-Development-Plan)
[ Release Process Checklist] (https://github.com/pgRouting/pgrouting/wiki/pgRouting-2.1.0-Release-Process-Checklist)

I would appreciate comments on the release process check list, (it is my first experience making a release) before I start filling the boxes

**Comment by woodbri** [comment]
Regarding: [ pgRouting 2.1 Development plan ] (https://github.com/pgRouting/pgrouting/wiki/2.1-Development-Plan)
* dropping support for postgresql version < 9.1 with create extension?
* dropping support for install without create extension?

[ Release Process Checklist] (https://github.com/pgRouting/pgrouting/wiki/pgRouting-2.1.0-Release-Process-Checklist)
* release process is alpha, beta, RCn, release. The listed order on the page is out of order.

Other than these minor questions, I think it looks good.

**Comment by cvvergara** [comment]
@woodbri I made the changes. thanks for commenting.

btw, about process step  "Winnie compiles and tests run" for develop branch is not working:
http://winnie.postgis.net:1500/view/pgRouting/job/pgRouting_matrix_branch_2.0/108/changes
So, I can not merge develop_2_1_0 into develop.

**Comment by cvvergara** [comment]
@robe2 Regina:
I would like to add the symbols that you use on jenkins to indicate the status (storm / cloud / sun) in the README.md file. (just like travis has its buttons)
is that possible?

**Comment by cvvergara** [comment]
@woodbri Steve
can you help me with this point of the checklist:
[ ] An appropriate tag has been created for this release

I think the owner has to do it.
This is the version I am getting:
```
                pgr_version                     
----------------------------------------------------
 (2.1.0,pgrouting-2.0.0,288,bbc96fc,develop,1.46.1)
```

Right now in the tests I get this failure:
```
'doc/test/utilities-any.test.sql' => 'FAILED: 1c1
< 2.1.0|pgrouting-2.1.0
---
> 2.1.0|pgrouting-2.0.0'
```

**Comment by cvvergara** [comment]
@sanak Nagase San:
For this point of the checklist:
[ ] Mac compiles and tests run

Can you please test "develop" branch on MAC and point out if any problem?

**Comment by sanak** [comment]
There seemed to be no typical problems on my Mac homebrew build environment.

By the way, I got the following warning at executing `cmake -DWITH_DD=ON ../`, but isn't "-DWITH-DD=ON" necessary anymore ?
<pre>
:
CMake Warning:
  Manually-specified variables were not used by the project:

    WITH_DD
</pre>

Also, I think that the following test fail is not so important,
but is it right ?
<pre>
           'doc/test/test.conf' => [
                                     {
                                       'comment' => 'documentation SQL tests for any versions.',
                                       'doc/test/alphashape-any.test.sql' => 'Passed',
                                       'doc/test/analyzeGraph-any.test.sql' => 'Passed',
                                       'doc/test/analyzeOneway-any.test.sql' => 'Passed',
                                       'doc/test/apspJohnson-any.test.sql' => 'Passed',
                                       'doc/test/apspWarshall-any.test.sql' => 'Passed',
                                       'doc/test/astar-any.test.sql' => 'Passed',
                                       'doc/test/bdDijkstra-any.test.sql' => 'Passed',
                                       'doc/test/bdstar-any.test.sql' => 'Passed',
                                       'doc/test/createTopology-any.test.sql' => 'Passed',
                                       'doc/test/createVertTab-any.test.sql' => 'Passed',
                                       'doc/test/dijkstra-v2.test.sql' => 'Passed',
                                       'doc/test/dijkstra-v3.test.sql' => 'Passed',
                                       'doc/test/kdijkstra-any.test.sql' => 'Passed',
                                       'doc/test/nodeNetwork-any.test.sql' => 'Passed',
                                       'doc/test/pointsAsPolygon-any.test.sql' => 'Passed',
                                       'doc/test/sampledata.test.sql' => 'Passed',
                                       'doc/test/trsp-any.test.sql' => 'Passed',
                                       'doc/test/tsp-any.test.sql' => 'Passed',
                                       'doc/test/utilities-any.test.sql' => 'FAILED: 1c1
< 2.1.0|pgrouting-2.1.0
---
> 2.1.0|pgrouting-2.0.0'
                                     }
                                   ],
</pre>

**Comment by cvvergara** [comment]
DD flag is no longer necessary
And only one library is generated.

**Comment by cvvergara** [comment]
The test fail is because the github tag is still for 2.0
So it will show until someone with permissions change it.

**Comment by sanak** [comment]
Oh, I see.
Thanks for confirmation!

**Comment by woodbri** [comment]
Created the tag for pgrouting-2.1.0 and pushed it and updated VERSION.

**Comment by cvvergara** [comment]
@woodbri Steve. Thanks for the tag, the 93 tests now are all ok
@sanak Nagase San, your tests must be all ok, now.
I will start closing issues related to this release

**Comment by sanak** [comment]
@cvvergara I confirmed that the 93 tests passed on Mac OSX homebrew environment.
Thanks,

**Comment by cvvergara** [comment]
@woodbri @dkastl @robe2 
The documentation for the alpha release can be found here:
http://docs.pgrouting.org/v2.1.0-alpha/doc/index.html

Based on the check list I think we can make an alpha release, but I don't know how to do that.

**Comment by dkastl** [comment]
Somewhere in the Wiki there should be a checklist.

**Comment by cvvergara** [comment]
@dkastl I am using the check list I found,
and acctually ading stuff to it, but it doesnt mention how to make the alpha release,
@woodbri please can you explain here or in the wiki?

**Comment by dkastl** [comment]
I'm still not yet back home.
I think I copied the checklist into a ticket. Then you can check the check
boxes.

**Comment by cvvergara** [comment]
@dkastl 
Updated the [ Release Process Checklist] (https://github.com/pgRouting/pgrouting/wiki/pgRouting-2.1.0-Release-Process-Checklist).
Can you put a comment on how to do the pre-release?

**Comment by dkastl** [comment]
I updated the original Wiki page: https://github.com/pgRouting/pgrouting/wiki/pgRouting-Release-Process-Checklist/_compare/7a0596db86cb6e0adaa4a0c8a33d8d17c36b552b...f9063f51256085eb7a187d3c05a8904aa53c1d98

Once you click "Draft new release" everything is pretty much self-explaining.

**Comment by robe2** [comment]
1) I saw missing is winnie tests 9.5alpha as well and PostGIS 2.2 which winnie did test so added that..  

2)  postgreSQL 9.4, boost 1.98, postGIS OK -- REALLY ther is a boost 1.98, thought we are only up to 1.58? I changed to 1.58 -- hope that was write

3) Regarding packager I added Devrim - he already said he'd be willing to help us out (that covers CentOS/EL).  I put Markus Wanner <markus at bluegap.ch> as ?  to see if we can get him interested in packaging pgRouting alongside PostGIS (in the apt.postgresql.org) .  Not sure how much more effort it would be for him or if you want to take on that role Daniel.  Would be nice if Ubuntu / Debian users have a single source to get both their PostGIS and pgRouting.

**Comment by cvvergara** [comment]
@robe2 1.98, might have been my dislexia showing up, where is that?

**Comment by cvvergara** [comment]
@robe2 now I am blind, thanks for the change

**Comment by robe2** [comment]
I changed it already - also added KingChaos for Mac.  I can't remember his email address.

**Comment by robe2** [comment]
Oh BTW I forwarded your announcement to postgis-dev and postgis-users.  I think that should be part of release procedure.

You probably also want to  submit to postgresql news -- https://www.postgresql.org/account/login/?next=/account/news/new/  (so it shows on front page).  

I would wait till official release for that one.

I'm testing out the beta builds made by winnie and then will post on my blog which gets shown on the postgresql.org (in the planet feed area), after I have tested a bit.

**Comment by dkastl** [comment]
Well, I'm not sure from which point it's OK to post this to other communities than pgRouting.
I would expect, that someone interested in pgRouting pre-releases would be subscribed to some pgRouting channel. So I thought it's enough to publish such news on other lists when the release is stable (or maybe a release candidate).

**Comment by cvvergara** [comment]
Closing for the release.
