### ISSUE TITLE
pgr_labelGraph

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#376]
This function is proposed by @Zia-

**Comment by dkastl** [comment]
What is the function supposed to do? Breaking a graph? ;-)
Maybe another name sounds more positive. 

Some idea: if you want to check a graph if it's valid or not, what about `pgr_isValidGraph()`? PostGIS has a few `ST_is...` as well.

**Comment by Zia-** [comment]
Yes. 'pgr_brokenGraph' sounds misnomer. The function is supposed to create one integer column in the edge table which will hold similar integer values for all those edges which are connected. Thus one will be able to see sub-graph within an edge table graph.
It's not breaking any geometry and is using source target columns to generate and populate above mentioned column.
I'll be working on the documentation and sample data testing soon

**Comment by woodbri** [comment]
Some better names might be:
```
pgr_colorGraphs
pgr_tagGraphs
pgr_tagSubGraphs
pgr_labelGraphs
pgr_labelSubGraphs
```
I think I like the word "label" best to describe what is happening.

**Comment by Zia-** [comment]
I would vote for `pgr_labelGraphs`.

**Comment by cvvergara** [comment]
Zia,
To be able to assign you to the issue, membership for the project has to be granted.
I recommend that you read the [git branching model](http://nvie.com/posts/a-successful-git-branching-model/), So, basically you will be working on your fork.

@dkastl 
Please can you give membership access to Zia.

**Comment by dkastl** [comment]
Working on a fork does not require to have write permissions.

**Comment by cvvergara** [comment]
But to put his name on assignee does.

**Comment by cvvergara** [comment]
@Zia- for your new function you have to use the underscored version of some functions. The documentation right now are in form of comments on the functions like here:
https://github.com/pgRouting/pgrouting/blob/develop/src/common/sql/utilities_pgr.sql#L24
By inspecting code you can see examples on how to use them. 
Please read #309

**Comment by Zia-** [comment]
@cvvergara Thanks for the git branching model link. Highly informative.

For underscored functions usage I'll go for the documentation review as of now till the final release of 2.1, and will do any further coding later.

**Comment by cvvergara** [comment]
@Zia- your function has a new name.
http://docs.pgrouting.org/v2.1.0-alpha2/doc/index.html#proposed-functions-proposed-by-zia-mohammed

**Comment by cvvergara** [comment]
@Zia- 
Your function now has a directory by itself. 
That will help to avoid any accidental modifications on the other files that are in src/common.
https://github.com/pgRouting/pgrouting/tree/develop/src/label_graph
Some of the file names I did change some of the remain with the same name.
so that you can practice:
`git mv <oldname> <newname>`
I like your idea that you will continue coding after the release is finish, then I can help you synchronize your fork with the main repository. (that includes: not to work on documentation, testing or moving files)

**Comment by Zia-** [comment]
I've been busy past few months, but will modify the documentation to use the sample data ASAP.

**Comment by cvvergara** [comment]
@Zia- Thanks for the information.

**Comment by cvvergara** [comment]
This function has being substituted with `pgr_lineGraph` and `pgr_lineGraphFuil` both experimental
