### ISSUE TITLE
pgRouting 2.1 testing on CentOS and Redhat Linux

### ISSUE THREAD

**Issue by robe2** [pgRouting/pgrouting#379]
@devrimgunduz  We are raring up for release of a pgRouting 2.1 alpha, can you help us out with regression testing on Yum PostgreSQL to make sure no surprises at release time.

Forgot to mention thread where this started discuss
https://github.com/pgRouting/pgrouting/issues/372#issuecomment-124936408

Thanks,
Regina

**Comment by devrimgunduz** [comment]
Hi Regina,

Sure, but I need a tarball to do that for easy packaging. What about I wait for Alpha 1?

Regards,

**Comment by robe2** [comment]
@devrimgunduz  Sure that's fine.  We'll let you know when that is ready.  Thanks for your support.

**Comment by robe2** [comment]
@devrimgunduz  Now that pgRouting 2.1 is released, would it be possible for you to add that to at least the PostgreSQL 9.5 yum offering? .  I see 9.5 when I installed, gave me pgrouting 2.0.1 and 9.4 gives me pgrouting 2.0.0.

Thanks,
Regina

**Comment by robe2** [comment]
I think this can be closed.  yum.postgresql.org is already shipping pgRouting 2.1.0 or we can change this ticket to be about 2.2.0.

**Comment by devrimgunduz** [comment]
2.2.0 is already out for 9.5 repo :)
