### ISSUE TITLE
Installation documentation outdated

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#380]
Some parts of the installation documentation seem to be outdated:
https://github.com/pgRouting/pgrouting/blob/develop/doc/src/installation/index.rst

Let's also drop the release(s) table and just provide a link to:
https://github.com/pgRouting/pgrouting/releases

**Comment by cvvergara** [comment]
Like this?
http://docs.pgrouting.org/v2.1.0-alpha2/doc/src/installation/index.html

**Comment by cvvergara** [comment]
@dkastl 
I am making changes here:
https://github.com/pgRouting/pgrouting/blob/develop_2_1_0/doc/src/installation/index.rst
And created a note saying that: its basic installation together with a reference to
https://github.com/pgRouting/pgrouting/wiki/Notes-on-Download%2C-Installation-and-building-pgRouting
wiki is easier to modify, and all the details can be placed there.
What do you think?

**Comment by dkastl** [comment]
Looks OK.

**Comment by robe2** [comment]
Can you change -- Winnie -- PostgreSQL 9.2-9.4beta1 32-bit, 64-bit  to read

Winnie PostgreSQL 9.2-9.5 32-bit/64-bit

I'm going to start building 9.5 this week so might as well just mention it now.

**Comment by cvvergara** [comment]
Moved to mileston 3.0 so that can give time to the experts of each plataform to fill it on their free time.

**Comment by cvvergara** [comment]
@robe2 
I also removed the word "experimental"
http://docs.pgrouting.org/v2.1.0-alpha2/doc/src/installation/index.html

**Comment by cvvergara** [comment]
I tried  travis with postgres 9.5, it didnt work.
https://travis-ci.org/pgRouting/pgrouting/builds/72871289
https://travis-ci.org/pgRouting/pgrouting/jobs/72871290

**Comment by cvvergara** [comment]
So, I am updating the installation documentation. using postgres PPA bt that is for ubuntu.
About other operative systems, I don't know.
And for experts on other operative systems they can use the wiki to put information in this wiki page:

https://github.com/pgRouting/pgrouting/wiki/Notes-on-Download%2C-Installation-and-building-pgRouting

**Comment by dkastl** [comment]
Well, I don't know, if we should maintain detailed instructions for each and every OS.
I think we should stick to the most popular ones.
