### ISSUE TITLE
Missing documentation for improved Alphashape function

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#383]
According to issue #235 the Alphashape function now can generate better polygons with holes and custom parameter, see merges #236  and #237.

But looking at the documentation, the updates have not been mentioned there. Or did I miss something?

**Comment by cvvergara** [comment]
@dkastl 
I just added information about the improvement in the [NEWS](https://github.com/pgRouting/pgrouting/blob/develop/NEWS#L22) and in the [changelog](https://github.com/pgRouting/pgrouting/blob/develop/doc/src/changelog/2_1_0.rst)

**Comment by sanak** [comment]
@dkastl, @cvvergara 
I updated `pgr_alphaShape` and `pgr_pointsAsPolygon` documents,
so, could you check my pull request (#388) ?
Thanks,

**Comment by cvvergara** [comment]
@sanak ありがとう
I am waiting for travis to finish, meanwhile I am reading :)
@robe2 can you also have a look:
https://github.com/sanak/pgrouting4w/blob/develop_2_1_0_issue383/src/driving_distance/doc/dd_alphashape.rst

**Comment by sanak** [comment]
@cvvergara 
No problem (どういたしまして).
And thanks for quick merge!
I close this issue, once.
