### ISSUE TITLE
Need a tar ball for next alpha or beta

### ISSUE THREAD

**Issue by robe2** [pgRouting/pgrouting#387]
I just noticed an alpha1 was tagged, but no tar ball was created.  We really need one of these if we want to encourage package maintainers to test them.  Most package maintainers won't without a fixed non-changing tar ball.

See for example - @devrimgunduz said in https://github.com/pgRouting/pgrouting/issues/379  he needs one for easy package testing.

**Comment by dkastl** [comment]
@robe2 it's not really clear to me how Github handles this, because when I look at the "Releases" page, then there is tarball for download: https://github.com/pgRouting/pgrouting/releases
It's just not "flagged" as a release with a green badge. Do we need to do this manually, so others get informed? Probably it's necessary, but I need to see how this is done properly.

**Comment by dkastl** [comment]
@cvvergara I think we should keep release and pre-release tags consistent. I just realized that we have various formats now. We're currently using some of the format `v2.0.0-rc1` and `pgrouting-2.1.0-alpha1`.

I don't remember anymore exactly why I choose the shorter format, and there was some comment by @devrimgunduz that a different format would be even better for him as a package maintainer. Though this was a bit difficult to achieve with Github.

I would prefer `v2.1.0-...` if there is no argument to include "pgrouting".

**Comment by dkastl** [comment]
OK, I just found out (again) how to do the "pre-release" using Github to make it look as it should.

**Comment by woodbri** [comment]
we should be using the tagging pattern of pgrouting-<version>[-<prerelease>] for the tag names so:
```
pgrouting-2.1.0-alphaN
pgrouting-2.1.0-betaN
pgrouting-2.1.0-RCn
pgrouting-2.1.0
```
where the trailing N or n is a number if we do multiple releases.

The reason for this naming scheme is that other processes pickup the tag and generate file names based on it. I think
```
pgrouting-2.1.0-alpha.tar.gz
vs:
v2.1.0-alpha.tar.gz
```
looks better. If every project did the later you would have a ton of files that you would have no idea what they were for.

I think the the code has been stable during alpha, 99% of the changes have been in the docs. It is safe to go to beta at this point.

**Comment by dkastl** [comment]
Here the pattern I tried to follow for the previous release: http://semver.org/
It seems to be very popular schema, but looking at the original author (see the end of the page) it's not a surprise that it looks good on Github ;-)

**Comment by cvvergara** [comment]
@dkastl Now that you are on the pre-release point, can you do it for beta?
https://github.com/pgRouting/pgrouting/releases/tag/pgrouting-v2.1.0-beta

@woodbri @robe2 
I also updated the documentation
http://docs.pgrouting.org/v2.1.0-beta/doc/index.html
Can you please have last glimpse before the informative mail is done?

**Comment by dkastl** [comment]
@cvvergara OK, I will update it ... and re-rename the tag of the alpha.

Let's try the following:

```
pgrouting-2.1.0-alpha
pgrouting-2.1.0-beta
pgrouting-2.1.0-rcN
pgrouting-2.1.0
```

I would say, that we are not going to release multiple alphas and betas ... let's try to make more stable releases ;-)

**Comment by cvvergara** [comment]
Exactly, no numbers. actually I asked @robe2 and they don't do alphas nor betas for minors, but a lot of installation issues are solved with this one, besides the internal library design.
Also we need to release before the release of postGIS and they in turn need to release before the release of postgres 9.5.

**Comment by cvvergara** [comment]
Forgot to mention we already tested it with postgis 2.2 and postgres 9.5

**Comment by dkastl** [comment]
@cvvergara just saw that you already created this tag for beta: `pgrouting-v2.1.0-beta`. But this is yet another variation, containing a `v`. I will rename it to `pgrouting-2.1.0-beta`.

**Comment by cvvergara** [comment]
@dkastl 
I did it before I saw this comments, sorry. please do the change.

**Comment by dkastl** [comment]
I have marked it as "pre-release": https://github.com/pgRouting/pgrouting/releases
So I think this ticket can be closed.
