### ISSUE TITLE
More VRP documentation is preferable for 

### ISSUE THREAD

**Issue by sanak** [pgRouting/pgrouting#393]
I think that more VRP documentation (at least, arguments and results) is preferable for v2.1 release.
Can I help something about those documentation ?
* pgr_vrpOneDepot: http://docs.pgrouting.org/v2.1.0-rc1/src/vrp_basic/doc/index.html
* pgr_vrppdtw: http://docs.pgrouting.org/v2.1.0-rc1/src/vrppdtw/doc/index.html

**Comment by robe2** [comment]
I agree too :)

**Comment by cvvergara** [comment]
@sanak 
It would be nice, yes please can you modify it?

**Comment by sanak** [comment]
@robe2, @cvvergara 
Okay, thanks for confirmation.
I will start to write it.

**Comment by cvvergara** [comment]
@sanak 
Did you write some documentation?
or can we move this issue to 2.2?

**Comment by sanak** [comment]
Sorry, I couldn't do this.
And yes, I think that we can move this to 2.2.

**Comment by cvvergara** [comment]
Moving to 2.3

**Comment by cvvergara** [comment]
there are two vrp proposed functions so, I am closing this issue, I suggest for 2.3 use the documented one
