### ISSUE TITLE
In general, don't use pgr_costResult, but use direct columns like new pgr_dijkstra

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#394]
Derived from comment:
https://github.com/pgRouting/pgrouting/issues/392#issuecomment-132586674
Use meaningful names in the return columns in the rest of the pgRouting functions

**Comment by sanak** [comment]
About result column naming, I think that `source`/`target` and `start`/`end` should not be mixed.
And I prefer `source`/`target` naming, because the naming are used historically (since v0.x).

**Comment by cvvergara** [comment]
@sanak 
Result column naming in V2.0 is seq, id1, id2, id3

**Comment by sanak** [comment]
> Result column naming in V2.0 is seq, id1, id2, id3

Oh, sorry.
Yes, result column naming is seq, id1, id2, id3 and cost in v2.0.
I meant that general naming which includes argument `sql` columns.

**Comment by cvvergara** [comment]
@sanak 
We need to think on a dictionary of terms, so we dont use the same term for 2 different things.
source is the source of an edge
source is the starting of a path

**Comment by cvvergara** [comment]
pgr_costResult is no longer available
