### ISSUE TITLE
cmake CONFIGURE_FILE error

### ISSUE THREAD

**Issue by antonpa** [pgRouting/pgrouting#4]
I get a cmake error with CONFIGURE_FILE - for all the *.sql install commands. I think it's because SQL_INSTALL_PATH is not getting set correctly, thus its sanity check that the destination exists fails.

It looks like the problem is:

IF(UNIX)
  SET(LIBRARY_OUTPUT_PATH ${LIB_DIR})
  SET(SQL_INSTALL_PATH /usr/share/postlbs)
ELSE(UNIX)
  SET(LIBRARY_OUTPUT_PATH ${PGROUTING_BINARY_DIR}/lib)
  SET(SQL_INSTALL_PATH ${PGROUTING_BINARY_DIR}/lib)
ENDIF(UNIX)

OSX appears to fall under the "UNIX" category (makes sense), and so it hardwires the SQL_INSTALL_PATH instead of using the configured PGROUTING_BINARY_DIR. /usr/share/postlbs does not exist on my system, and I don't want it to, I want the sql in the configured Postgres dir. If I comment out the UNIX block, leaving the set commands in the second block (else), cmake succeeds in configuring the build.

**Comment by woodbri** [comment]
Closing - Wont fix.
