### ISSUE TITLE
pgRouting develop 2_1_0 Windows crash on ksp on 9.4 32-bit run

### ISSUE THREAD

**Issue by robe2** [pgRouting/pgrouting#406]
```
---
> server closed the connection unexpectedly
> 	This probably means the server terminated abnormally
> 	before or while processing the request.
> connection to server was lost',
                                           'src/ksp/test/ksp-v3.test.sql' => 'CRASHED SERVER: 1,154c1,4
```

Just  noticed this  on

http://winnie.postgis.net:1500/job/pgRouting_PGVersionEDB/800/console

Seems to be a several ksp.

Checking to see if maybe its a result of my configurationg changes.

**Comment by cvvergara** [comment]
please have a look at this.
http://winnie.postgis.net:1500/view/pgRouting/job/pgRouting_PGVersionEDB/1204/console
was my fault.

**Comment by woodbri** [comment]
@cvvergara No problem, these things happen. Just fix it and turn out a rc3 as soon as you can.

**Comment by robe2** [comment]
yah seems fine now.  Feel free to close

**Comment by cvvergara** [comment]
closing.
