### ISSUE TITLE
Migrate Travic CI from "legacy" to container-based infrastructure

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#408]
It seems a lot has changed with Travis CI since we added it to pgRouting, so it's time to review what we have and update and improve the test where possible:
http://docs.travis-ci.com/user/migrating-from-legacy/

**Comment by cvvergara** [comment]
@strk 
I saw this [question about postgres matrix](https://github.com/travis-ci/travis-ci/issues/954#issuecomment-72829335) you made that wasn't answered back. 
I was wondering did you find out something about it?

**Comment by strk** [comment]
Not that I remember.

**Comment by cvvergara** [comment]
got travis working for Precise & Trusty.
I'll close this issue we already have an issue for OSX
which will not be done fore this release
