### ISSUE TITLE
pgr_dijkstra doesn't work with negative values

### ISSUE THREAD

**Issue by tiagoovieira** [pgRouting/pgrouting#417]
Hey, I'm trying to run the `pgr_dijkstra` function with a cost function that varies from -1 to 1, but it returns an empty result set. Is there a way to calculate a cost function with negative values?

**Comment by Zia-** [comment]
`Dijkstra` function, which is built on top of `Breadth First Search` algo. doesn't work for negative costs. You can use `Bellman-Ford` function, instead, which is also a case of `Breadth-First Search`.

**Comment by dkastl** [comment]
Negative values will cause `pgr_dijkstra` to ignore the way in this direction. It is common practice to describe one-way streets, so this is not going to change and you need to find a different way how to manage the costs without using negative values.
