### ISSUE TITLE
trsp and tsp name change to be more descriptive

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#427]
Change the names to be more descriptive for example:
pgr_travelingSalesman 
pgr_turnRestrictions
If someone likes short names they can wrap them on a function.
So, I can wrap it as:
pgr_vv    <--- hey in spanish is vendedor viajante

**Comment by dkastl** [comment]
`pgr_travelingSalesperson` is gender-neutral ;-)

**Comment by cvvergara** [comment]
@dkastl 
Wow, you got the hidden  vv = Vicky Vergara

**Comment by cvvergara** [comment]
currently TRSP and because of acronym usage, without looking at the documentation do you know what the acronym mean?
https://www.acronymfinder.com/TRSP.html

comparing with a well known acronym (TSP):
https://www.acronymfinder.com/TSP.html
you can find that TSP means Traveling Salesman Problem

So for TSP I am OK with using the acronym.

**Comment by cvvergara** [comment]
Vote for
pgr_turnRestrictionsPath

**Comment by cvvergara** [comment]
Vote for
pgr_turnRestrictions

**Comment by dkastl** [comment]
Since the result is a path, it should be part of the name in my opinion.

What about the little change to `pgr_turnRestrictedPath`?

**Comment by woodbri** [comment]
Daniel +1 on pgr_turnRestrictedPath

**Comment by robe2** [comment]
Sorry for the back and forth voting.  I was undecided between pgr_turnRestrictionsPath and pgr_turnRestrictedPath. I still sort of am.

It seems like "Turn Restricted Shortest Path" term is used slightly more than "Turn Restrictions Shortest Path"

e.g you have it here as that
https://github.com/pgRouting/pgrouting/wiki/Turn-Restricted-Shortest-Path-(TRSP)

The docs seem to be a mixed flavor of both, so should be standardized to whatever naming you decide on:

https://docs.pgrouting.org/latest/en/pgr_trsp.html#trsp

**Comment by manikanta-kondeti** [comment]
+1  pgr_turnRestrictedPath

**Comment by cvvergara** [comment]
`TRSP` remains.
Almost a decade with the acronym been used on pgRouting that I think it is the best choice.
See [TRSP family](https://docs.pgrouting.org/dev/en/TRSP-family.html)
For the new diversity of functions within this family

**Comment by cvvergara** [comment]
Forgot to mention, related to #2238
