### ISSUE TITLE
Shortest Path Shooting Star bug?

### ISSUE THREAD

**Issue by dzwarg** [pgRouting/pgrouting#43]
I encountered a bug with the Shortest Path Shooting Star algorithm during the FOSS4G tutorial sessions when using pgRouting with OSM data and GeoExt.

After loading the sample dataset for the routing tutorial, I created costs for the ways in my database with the following SQL:

```sql
update ways set class_id=199 where class_id=100;
update ways set to_cost = (199-class_id)*10;
```

I attempted to add rules to prefer more major roads (those with class_id of low 100's) over more minor roads (those with class_id of the high 100's). I found that I had to make the 'to_cost' attribute of each way much **higher** for the major roads to make the routing prefer the major roads. That is counter-intuitive to me -- wouldn't a higher cost introduce more penalty, and thus avoid the ways with higher costs?

With the weights set, and using the Denver.osm sample data, when I route from "-105.01770817195222 39.74944518305231" (~ exit 211 on I-25)[gid=13402] to "-105.01491867458083 39.72865495921035" (~ exit 209B on I-25)[gid=13564] using "SPS" method, the route seems to jump off the highway (a preferred way), onto residential streets, then back onto the highway. Both "SPA" and "SPD" follow the highway as expected. I can confirm that it is not a problem of routing the Northbound direction onto the Southbound direction.

Is this a problem with the way of calculating the "to_cost"?

**Comment by woodbri** [comment]
Closing - Wont fix.
