### ISSUE TITLE
pgtap test on pgr_trsp without restrictions vs pdr_dijkstra

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#431]
I am trying to make a comparison using pgtap of trsp (without restrictions)  with pgr_dijkstra (one to one)
Because the test doesn't include turn restrictions the results must be equivalent.
But it throws an ERROR, when it doesn't find a path.
That is not documented.
I don't think that not finding a path its an error when there is no path.
An error would be not finding a path when there is a path.

I  suggest that instead of an RAISE ERROR, RAISE NOTICE and return EMPTY SET when there is no path.

**Comment by cvvergara** [comment]
Trivial test strange result: Its finding a path on this [graph](http://docs.pgrouting.org/2.1/doc/src/developer/sampledata.html#fig1) when the starting location is the same as the ending location
```
SELECT * from pgr_trsp( 
   'SELECT id, source, target, cost, reverse_cost from edge_table ORDER BY id',
   1, 1, true, true);
 seq | id1 | id2 | cost 
-----+-----+-----+------
   0 |   1 |   1 |    1
   1 |   2 |   4 |    1
   2 |   5 |   8 |    1
   3 |   6 |   9 |    1
   4 |   9 |  16 |    1
   5 |   4 |   3 |    1
   6 |   3 |   2 |    1
   7 |   2 |   1 |    1
   8 |   1 |  -1 |    0
(9 rows)

SELECT * from pgr_trsp(
    'SELECT id, source, target, cost, reverse_cost from edge_table ORDER BY id',
    2, 2, true, true);
 seq | id1 | id2 | cost 
-----+-----+-----+------
   0 |   2 |   4 |    1
   1 |   5 |   8 |    1
   2 |   6 |   9 |    1
   3 |   9 |  16 |    1
   4 |   4 |   3 |    1
   5 |   3 |   2 |    1
   6 |   2 |  -1 |    0
(7 rows)
```

**Comment by sankepallyrohithreddy** [comment]
I think I solved the bug.There should be an if condition which checks whether the start and end vertices are the same.Let me know what to do next.

**Comment by sankepallyrohithreddy** [comment]
Whenever there is no path between the source and the target vertices,the code was returning,
"ERROR: Path Not Found".The function was returning -1(returned when there is an error),even in this case.So I made it return 0,in this case with the path being null.

**Comment by woodbri** [comment]
Thank you for the pull request. TRSP will likely get written in the 2.3 release to be based on the pgr_dijkstra code based and boost. at that time we will look at making it consistent with pgr_dijkstra return behavior. You should be able to wrap the call in a begin ... exception when others ... end; block to catch the error and continue with a null or empty result.

**Comment by cvvergara** [comment]
With pull #750 pgtap tests have being added:
comparing the results of pgr_trsp VS pgr_dijkstra when **no** restrictions are given.

https://travis-ci.org/pgRouting/pgrouting/jobs/182395398#L1449
