### ISSUE TITLE
add optionnal argument for cost only return  on pgr_kdijkstra

### ISSUE THREAD

**Issue by Remi-C** [pgRouting/pgrouting#435]
Hey,
sorrry to bother with a feature request, but I feel it may not be too much work.

The idea would be to add an argument to pgr_kdijkstra, something like "cost_only",
so it would return one row per shortest path, with the total cost, instead of K rows with the details of each shortest path.
As you see the return type would be the same, so no need to change any signature, the argumetn could have a default value to "false", so it doesn't break compatibility.

This way we can merge `pgr_kdijkstraCost` and `pgr_kdijkstraPath`

This would provide a key functionnality, because currently there is no efficient way to compute a lot of shortest path cost between nodes.

Having those cost is the key to a lot of much more complex network tools that could be used using plpython to perform much more subtle graph tasks.

Cheers,
Rémi-C

**Comment by cvvergara** [comment]
@Remi-C 
Hi Rémi @Remi-C 
Some topics about  `pgr_kdijkstraCost` and `pgr_kdijkstraPath`:
 - they only work for 1 to many
 - They code is faulty so for some cases the shortest path/cost is not returned

`pgr_kdijkstraPath` is going to be deprecated in favor of:
 - pgr_dijkstra( the one to many signature ) see the [signatures](http://docs.pgrouting.org/2.1/src/dijkstra/doc/dijkstra_v3.html#signatures)


`pgr_kdijkstraCost` is going to be deprecated in favor of the under development:
 - pgr_dijkstraCost( the one to many version ) see the [signatures](http://docs.pgrouting.org/dev/src/dijkstra/doc/dijkstraCost.html#signature-summary)

As they are different concepts, One is to find the shortest path an the other one is to find the costs of the shortest paths, by having the names separately it is easier to "debug" when making an application.

The output of [pgr_Johnson](http://docs.pgrouting.org/dev/src/allpairs/doc/johnson.html#pgr-johnson), [pgr_floydWarshall](http://docs.pgrouting.org/dev/src/allpairs/doc/floydWarshall.html#pgr-floydwarshall), and pgr_dijkstraCost family of functions will be the same:
```
RETURNS SET OF (start_vid, end_vid, agg_cost) or EMPTY SET
```

But don't be discouraged, the underlying code actually does what you are suggesting and uses the flag to retrieve the whole path or only the aggregate cost.

**Comment by Remi-C** [comment]
Hey,
I noticed the code works, I am very happy in fact, I achieved quit an advanced graph processing method using combination of pgpointcloud, postgis, pgrouting, networkx, scikit learn, postgis topology.

I put it here as example so other people using pgrouting may know that is can be used for adv

SO first I create a simplified network based on a lot of data from pgpointcloud. I do this using postgis functions. In blue is the network, in grey Paris building, for easier understanding.
![00_create_simplified_network](https://cloud.githubusercontent.com/assets/4725794/11838465/82df7c18-a3e7-11e5-908e-15349c0be495.png)

The goal is to reduce this network so it boils down to only a simple road network. For this I compute the topological distance from any node to any other node below a geometrical distance using postgis to create the node pairs, and the cool `pgr_dijkstraCost` function. In the image we plot a segment for each node-node pair, and color it according to pgrouting topological distance (notice top right edges are red, because topological distance is big)
![Uploading 01_compute_topological_from_all_to_neighborhood_2.png…]()

Then we use plpython , with networkx to create a graph from those segments, then we convert this graph into a distance matrix, then the distance matrix is converted to an affinity matrix, then we use spectral clustering on this

**Comment by Remi-C** [comment]
Hey,
I noticed the code works, I am very happy in fact, I achieved quit an advanced graph processing method using combination of pgpointcloud, postgis, pgrouting, networkx, scikit learn, postgis topology.

I put it here as example so other people using pgrouting may know that is can be used for advanced stuff, all within the database.

SO first I create a simplified network based on a lot of data from pgpointcloud. I do this using postgis functions. In blue is the network, in grey Paris building, for easier understanding.
![00_create_simplified_network](https://cloud.githubusercontent.com/assets/4725794/11838465/82df7c18-a3e7-11e5-908e-15349c0be495.png)

The goal is to reduce this network so it boils down to only a simple road network. For this I compute the topological distance from any node to any other node below a geometrical distance using postgis to create the node pairs, and the cool `pgr_dijkstraCost` function. In the image we plot a segment for each node-node pair, and color it according to pgrouting topological distance (notice top right edges are red, because topological distance is big)
![01_compute_topological_from_all_to_neighborhood_2](https://cloud.githubusercontent.com/assets/4725794/11838643/9f473e30-a3e8-11e5-85ec-755aa9ec9328.png)

Then we use plpython , with networkx to create a graph from those segments, then we convert this graph into a distance matrix, then the distance matrix is converted to an affinity matrix, then we use spectral clustering on this matrix ! 
To make it short, we automatically regroup the nodes of the original network into bigger groups containing nodes topologically close to each other.
![02_spectral_clustering_on_affinity_35_classes_morpho](https://cloud.githubusercontent.com/assets/4725794/11838675/d80f036a-a3e8-11e5-8297-081d7ecb1be0.png)

Then we rebuild a network using postgis topology
![03_rebuild_topology](https://cloud.githubusercontent.com/assets/4725794/11838679/e78eaf0c-a3e8-11e5-9ee3-1c9e2df2e770.png)

then we simplify again this network.
![04_clean_topology](https://cloud.githubusercontent.com/assets/4725794/11838690/f86f5b00-a3e8-11e5-87b2-a16ab5b2f1d5.png)

Voila, we go from several thousands nodes and edges to a few dozen, while retaining the original graph layout.

Thank you for your good working postgres extension!  
Cheers
Rémi-C

**Comment by cvvergara** [comment]
@Remi-C 
WOW, I am amazed on what it can be done with pgrouting. 
I would like to know if you have link to a page / repo or something that has what you did.

**Comment by woodbri** [comment]
@Remi-C Did you consider taking your original network of nodes and edges, and calling postgis build area function to generate a mesh of polygons, then union all the polygons together and use skeletonize to get the center lines of the road areas? These center lines can then be made into the network. I'm not sure if this would be a better or faster solution to what you have done, but it is another approach that might work.

**Comment by Remi-C** [comment]
Yep i also have tried that.
Problem with straight skeleton approach is that the necessary union doesn't
scale and that the straight skeleton result need a -lot- of cleaning, both
geometrical and topological.
Thé pro's are that when it works it looks nicier.
Oslandia is working on outputting more stuff from straight skeleton though,
which would help.

IRL there are much more advanced way to reconstruct road network (involving
inference and bayesian network for instance)
Le 25 févr. 2016 19:34, "Stephen Woodbridge" <notifications@github.com> a
écrit :

**Comment by cvvergara** [comment]
I close as its being "fixed" with the new functions.

**Comment by Remi-C** [comment]
Hey,
here are straight skeleton results:
failure is due to an error of polygonn simplification in my end
![straight_skeleton_failure](https://cloud.githubusercontent.com/assets/4725794/13348203/625b6ed4-dc72-11e5-90be-25abd0dae1ed.png)

![straight_skeleton_success](https://cloud.githubusercontent.com/assets/4725794/13348213/72ec94ee-dc72-11e5-9586-aa573410650e.png)

**Comment by Remi-C** [comment]
@cvvergara here is the code, depends on python functions in rc_lib:  
https://gist.github.com/Remi-C/85b32364a1e8b33af006

rc_lib : https://github.com/Remi-C/PPPP_utilities

Cheers !

**Comment by cvvergara** [comment]
@Remi-C 
I love your work, I am closing issues, as we are about to make a release, 
I would like to move all these comments to the wiki with your permission.
(actually to add images to the wiki its easier if they are added first to an issue)

**Comment by Remi-C** [comment]
yeah of course no problem,
thats kinda what I put htose here (I have the same issue with images, not
really practical to have a good wiki on github I find)
Cheers,
Remi-C

2016-02-26 14:28 GMT+01:00 Vicky Vergara <notifications@github.com>:

**Comment by cvvergara** [comment]
@Remi-C 
Please feel free to make edit the wiki, I made a copy/paste just as it is, but you might want to change things
https://github.com/pgRouting/pgrouting/wiki/Paris
