### ISSUE TITLE
small correction of the doc

### ISSUE THREAD

**Issue by Remi-C** [pgRouting/pgrouting#436]
Hey,
the [doc](http://docs.pgrouting.org/2.1/src/kdijkstra/doc/index.html#pgr-kdijkstra)
has the wrong signature for the function `pgr_kdijkstraCost` and `pgr_kdijkstraPath`,
the argument is called `has_reverse_cost` and not `has_rcost` as stated.

Same for the `source`and `targets` arguments
Easy to correct =)
Cheers,
Remi-C

**Comment by cvvergara** [comment]
@Remi-C 
Thanks for pointing that out.
I will not change the documentation, but I will make sure when wrapping the functions that they follow whatever is documented.
For example: I am wrapping the function function [pgr_kdijkstraCost](https://github.com/cvvergara/pgrouting/blob/cmake-improve-2.2/src/kdijkstra/sql/kdijkstra-V2.2.sql#L51)
(I still need to wrap `pgr_kdijkstraPath`)

**Comment by cvvergara** [comment]
Deprecating pgr_kdijkstraPath please use pgr_dijkstra
pgr_kdijkstraPath Its being fixed by wrapping it with the results of pgr_dijkstra

 Deprecating pgr_kdijkstraCost please use pgr_dijkstraCost
pgr_kdijkstraCost Its being fixed by wrapping it with the results of pgr_dijkstraCost
