### ISSUE TITLE
Clean main repository of outdated / unused branches

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#445]
I am preparing version 2.2 and I see a lot of unused / outdated branches

## BRANCH DELETIONS
Branch | Reasons | Last commit by
----------------- | ------------------------------- | ------
apsp_johnson | out-dated, pre version 2.0 |  @justjkk 
cmake-postgres | CMakelist.txt is user focus | @manikanta-kondeti 
~~darp~~ | ~~out-dated, pre version 2.0~~ | @dkastl 
~~darp3~~ | ~~out-dated, pre version 2.0~~ | @dkastl
devel-2.0-deprecated | deprecated, if used was never erased | @dkastl 
develop-2.2-old-travis | now we are using new travis | @cvvergara
 develop-trsp-fix |master is up to date with all commits from develop-trsp-fix. | @woodbri 
vrp_basic | Branch probably used to incorporate vrp_basic into pgRouting | @dkastl 
develop_2_1_0 | outdated | @cvvergara
doc-for-developers | Outdated, All changes are already in dev2.2 | @cvvergara 
feature-travis | dev-2.2 is up to date with all commits from feature-travis. | @cvvergara
new-travis-dev-2.2 | dev-2.2 is up to date with all commits from new-travis-dev-2.2. | @cvvergara
pgr-1.x. | dev-2.2 is up to date with all commits from pgr-1.x. | @dkastl 
trsp-improvements | outdated | @woodbri 
trsp | dev-2.2 is up to date with all commits from trsp. | @woodbri 
typefixI303 | outdated | @cvvergara

Non of the gsoc branches are going to be deleted. (maybe later the ones that are already merged into develop)

**Comment by cvvergara** [comment]
@woodbri, @robe2, @dkastl, and all the rest of the developers, please confirm this cleanup.
If you see a branch that needs to stay please state the reasons.

**Comment by woodbri** [comment]
Save darp and darp3 for Dial A Ride Program. Someone might want to resurrect it and get it running in 2.3+

**Comment by woodbri** [comment]
pgr-1.x can go with have a tag for the v1.05 which captures the code release prior to 2.0.

**Comment by woodbri** [comment]
trsp and trsp-improvements were already merged into develop and are now in 2.1 and 2.2 so they can be deleted.

**Comment by cvvergara** [comment]
Crossed out the darp, darp3 from the table as an indicator of not deleting them

**Comment by woodbri** [comment]
I think all these can be deleted unless someone else has an opinion.

**Comment by dkastl** [comment]
I also think deleting them is OK. Old versions are tagged, so we can find previous releases without the need to keep an extra branch.

**Comment by cvvergara** [comment]
Forgot to mention `unittests`  branch is also outdated

**Comment by cvvergara** [comment]
Deletion of branches has being made. except for `trap-improvements` mentioned above
I was looking at the code of `trsp-improvements` Is an idea of how to get rid of strtok that is not being used yet, so I will merge the code and delete the branch.

I will also merge `nodeNet-dev-2.2` to incorporate the changes in pgr_nodeNetwork and delete the branch.

**Comment by cvvergara** [comment]
`trsp-improvements` & `nodeNet-dev-2.2` have being merged and deleted.

**Comment by cvvergara** [comment]
If you have a clone in your computer, to cleanup your clone:
```
git branch -a
git remote prune origin
git branch -a
```

if you have a fork, I don't know if this will do:
```
git remote prune upstream
```

**Comment by dkastl** [comment]
Again, a good topic to post on the "developer" mailing list:
- We cleaned up old branches
- How to bring your repository in sync

I don't think many people follow Github issues. I just received a notification, because I was involved (and mentioned).

**Comment by dkastl** [comment]
Oh, sorry. I first answered the Github issues before seeing, that you actually wrote to the DEV list ;-)

**Comment by cvvergara** [comment]
All branches mentioned in this issue have being deleted, closing
