### ISSUE TITLE
Documentation Index

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#450]
Related to #449 
I changed the index so that:
Proposed, experimental, deprecated & dicontinued functions are on a second level.
I made the section Proposed for 2.3 which contains functions that basically are working and ready (except for the documetation) but I must mention that some "bug fixes" of other functions are being fixed by calling some of this functions.

In the Proposed for 2.3 there might be some documentation, but for the moment is a copy/paste of some other files.

The intention of the change is to keep  focus on the official functionality of pgRouting.
Probably the index needs more work after the documentation of the new functions is finished, but and any comment would be very much appriciated.

**Comment by cvvergara** [comment]
This comes from a conversation with @dkastl 

A comment about "the future" So the appropriate names can be placed in the present:
I am making what I call "Family of functions"

For example the withPoints family of functions proposed for 2.3: (even though they are ready and some are used in 2.2 to patch some bugs in other functions)
pgr_withPoints   (includes one-one, one-many, many-one, many-many)
pgr_withPointsCost (includes one-one, one-many, many-one, many-many)
pgr_withPointsKSP
pgr_withPointsDD 
pgr_withPointsVia

So lets imagine in the future a turnRestricted family of functions:
pgr_turnRestricted   (includes one-one, one-many, many-one, many-many)
pgr_turnRestrictedCost (includes one-one, one-many, many-one, many-many)
pgr_turnRestrictedKSP
pgr_turnRestrictedDD 
pgr_turnRestrictedVia

and what about a turnRestrictedWithPoints family of functions:
pgr_turnRestrictedWithPoints   (includes one-one, one-many, many-one, many-many)
pgr_turnRestrictedWithPointsCost (includes one-one, one-many, many-one, many-many)
pgr_turnRestrictedWithPointsKSP
pgr_turnRestrictedWithPointsDD 
pgr_turnRestrictedWithPointsVia

So, the issue here is with the naming, that is one of the reasons the withPoints family of functions are marked as proposed. They are Dijsktra Based.

as of 2.1:
pgr_dijkstra
pgr_KSP
pgr_drivingDistance 

for exmple:
pgr_dijkstra
pgr_dijkstraCost  (replaces pgr_kdisjkstraCost)
pgr_dijkstraKSP  (would replace pgr_KSP)
pgr_dijkstraDD (replaces pgr_drivingDistance)
pgr_dijkstraVia   (proposed)

I wonder if it would remain clear that by making more overlading of `pgr_dijkstra ` to include the withPoints would be clear that with points are being used.

for example:
Lets take one to many signature summary of pgr_dijkstra
```
pgr_dijkstra(edges_sql, start_vid,  end_vids, directed:=true)
RETURNS SET OF (seq, path_seq , end_vid, node, edge, cost, agg_cost)
    OR EMPTY SET
```

using the same name for the withPoints one ot many:
Instead of:
```
pgr_withPoints(edges_sql, points_sql, start_pid, end pids, driving_side :='b', details := false, directed:=true)
```
Have:
```
pgr_dijkstra(edges_sql, points_sql, start_pid, end pids, driving_side :='b', details := false, directed:=true)
RETURNS SET OF (seq, path_seq, end_pid, node, edge, cost, agg_cost)
    OR EMPTY SET
```

I am about to do the documentation of the "withPoints" family of functions, and I would like your point of view. Name change relatively fast, (I have to modify the tests to use the new name also), right now I have it as withPoints.

I need feedback before I start doing that documentation.

**Comment by dkastl** [comment]
If you need feedback, you probably better ask on the mailing list. ;-)
I think it's a good question for the list.

**Comment by cvvergara** [comment]
The index I chose was never complained about so I am closing this issue.
