### ISSUE TITLE
 dev-2.2 error: ISO C does not support ‘__int128’ type 

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#453]
mentioned on #430 by @theRealDashu.
@theRealDashu, can you please post in this issue:
operative system gcc version, and the piece of compile errors.

**Comment by TheRealDashu** [comment]
gcc version 4.9.2 (Debian 4.9.2-10)

postgres@nic-int3:/tmp/pgrouting-test/build$ make install
[  1%] Building C object src/vrppdtw/src/CMakeFiles/vrppdtw.dir/pdp.c.o
In file included from /usr/include/postgresql/9.5/server/c.h:53:0,
                 from /usr/include/postgresql/9.5/server/postgres.h:47,
                 from /tmp/pgrouting-test/src/vrppdtw/src/pdp.c:23:
/usr/include/postgresql/9.5/server/pg_config.h:725:24: error: ISO C does not support ‘__int128’ type [-Werror=pedantic]
 #define PG_INT128_TYPE __int128
                        ^
/usr/include/postgresql/9.5/server/c.h:298:9: note: in expansion of macro ‘PG_INT128_TYPE’
 typedef PG_INT128_TYPE int128;
         ^
/usr/include/postgresql/9.5/server/pg_config.h:725:24: error: ISO C does not support ‘__int128’ type [-Werror=pedantic]
 #define PG_INT128_TYPE __int128
                        ^
/usr/include/postgresql/9.5/server/c.h:299:18: note: in expansion of macro ‘PG_INT128_TYPE’
 typedef unsigned PG_INT128_TYPE uint128;
                  ^
cc1: all warnings being treated as errors
src/vrppdtw/src/CMakeFiles/vrppdtw.dir/build.make:54: recipe for target 'src/vrppdtw/src/CMakeFiles/vrppdtw.dir/pdp.c.o' failed
make[2]: *** [src/vrppdtw/src/CMakeFiles/vrppdtw.dir/pdp.c.o] Error 1
CMakeFiles/Makefile2:804: recipe for target 'src/vrppdtw/src/CMakeFiles/vrppdtw.dir/all' failed
make[1]: *** [src/vrppdtw/src/CMakeFiles/vrppdtw.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by TheRealDashu** [comment]
Hey just wanted to ask when 2.2 dev will become stable ?

**Comment by cvvergara** [comment]
I am thinking you are trying branch dev-2.2 because master branch does not have -pedantic flag
The problem is in postgres C files, which we can not modify, so look at this [line](https://github.com/pgRouting/pgrouting/blob/dev-2.2/CMakeLists.txt#L583)
First try removing -Werror (that makes all warnings into errors)
```
[-Werror=pedantic]
```
if it doesnt work remove -pedantic

Anyway when the code gets moved onto master branch only this flags will be there:
```
-Wall -frounding-math
```

**Comment by cvvergara** [comment]
Could finally reproduce the error on branch jenkins.
https://travis-ci.org/pgRouting/pgrouting/builds/108638201
-Werror 
converts any warning to error, 
so delete that flag, as we can not do anything on the postgresql included files

**Comment by cvvergara** [comment]
Got an aswer about this, this is not in our control, except that for the release we will not use flags that reflect that warning/error
http://www.postgresql.org/message-id/5543.1455306323@sss.pgh.pa.us
