### ISSUE TITLE
pgRouting home page still says 2.0

### ISSUE THREAD

**Issue by robe2** [pgRouting/pgrouting#459]
The pgRouting home page is a bit misleading and only talks about 2.0 which would lead people to believe 2.0 is the latest stable release.

http://pgrouting.org/

**Comment by cvvergara** [comment]
@dkastl 
Where is that home page?

**Comment by dkastl** [comment]
@cvvergara 
The website is here and works similar to the documentation: https://github.com/pgRouting/website (see Readme).
I thought I had checked for updating text to 2.1, but I actually only did so for the Download block, it seems. 

Well, we should probably make the text independent from particular information about releases.

**Comment by cvvergara** [comment]
The down load block is in gh-pages of pgRouting

**Comment by dkastl** [comment]
The whole website is generated with Sphinx (see the Readme).
So when you checkout `master`, make the changes and generated the static HTML, then you switch to the `gh-pages` branch, copy the files from the `build` directory, commit & push and it should be all done.

**Comment by dkastl** [comment]
I can update the website, just not today.

**Comment by cvvergara** [comment]
I created the issue in the correct issue list for pgRouting/website repository
Closing here
