### ISSUE TITLE
memleak in dijkstra sp?

### ISSUE THREAD

**Issue by mfortini** [pgRouting/pgrouting#46]
I'm having issues with Dsp on a fairly large graph.
If I run several rounds of dsp with different sources and targets in the same session, the postgresql process memory keeps growing, until the OOM killer gets rid of it.
If I just close the session everytime, memory stays at a reasonable level.
I tried looking at the source code, but maybe I need some guidance in where to look at.
I can provide some sort of dataset, if it helps.

TIA

**Comment by woodbri** [comment]
Closing - Wont fix.
