### ISSUE TITLE
pgr_ksp problem

### ISSUE THREAD

**Issue by jaksitst** [pgRouting/pgrouting#481]
Hi,

I met the following problem during the testing algorithm KSP.
I made a mini database, which would show the problem.

Details of the following PDF document:
[ksp_algorithm_test.pdf](https://github.com/pgRouting/pgrouting/files/117456/ksp_algorithm_test.pdf)

Where the error???

**Comment by cvvergara** [comment]
That is pgr_ksp from version 2.0, can you pelase try with [pgr_ksp v 2.1](http://docs.pgrouting.org/2.1/src/ksp/doc/ksp_v3.html#pgr-ksp-v3)

**Comment by jaksitst** [comment]
In version 2.1 working properly

**Comment by cvvergara** [comment]
I'll close this issue. pgr_ksp was fixed in version 2.1
