### ISSUE TITLE
TRSp results costs do not include turn restriction costs

### ISSUE THREAD

**Issue by woodbri** [pgRouting/pgrouting#491]
Daniel Urda wrote on the list:

As far as I understand, when using TRSP, the cost column in the results only includes the cost for traversing the respective edge, without taking into account the cost for actually arriving on that edge (e.g. the cost of a restriction which has the current edge as to and the previous one as from).

 Is there a way to get such costs (besides the obvious, but rather inefficient way, of querrying the restriction table for each pair of consecutive edges in the computed way) ?

**Comment by cvvergara** [comment]
yeah, trsp has quite some bugs, this relese I am wrapping it with some good code for the casses where no restrictions are given, but I hope to fix the cases where restrictions are used in the near future.

**Comment by cvvergara** [comment]
This query takes a restricted U turn:
```
SELECT * FROM pgr_dijkstra(
  $$SELECT id, source, target, cost, reverse_cost
    FROM edge_table WHERE id != 16$$,
  4, 9);
 seq | path_seq | node | edge | cost | agg_cost
-----+----------+------+------+------+----------
   1 |        1 |    4 |    3 |    1 |        0
   2 |        2 |    3 |    5 |    1 |        1
   3 |        3 |    6 |    9 |    1 |        2
   4 |        4 |    9 |   -1 |    0 |        3
(4 rows)
```
Keeping the graph with those edges only then:
```
SELECT * FROM pgr_trsp(
  $$SELECT id, source, target, cost, reverse_cost
    FROM edge_table WHERE id in (3,5,9)$$,
  $$SELECT * FROM restrictions$$,
  4, 9);
 seq | path_seq | start_vid | end_vid | node | edge |  cost   |      agg_cost      
-----+----------+-----------+---------+------+------+---------+--------------------
   1 |        1 |         4 |       9 |    4 |    3 |   1.009 |                  0
   2 |        2 |         4 |       9 |    3 |    5 |   1.025 |              1.009
   3 |        3 |         4 |       9 |    6 |    9 | 101.081 |              2.034
   4 |        4 |         4 |       9 |    9 |   -1 |       0 | 103.11500000000001
(4 rows)
```
It so happens that the cost has the restriction cost incorporated.

**Comment by cvvergara** [comment]
Work has been done for TRSP on develop branch for version 3.4 (due to be released on September/October 2022:
https://github.com/pgRouting/pgrouting/issues/2238
Please check the documentation
https://docs.pgrouting.org/dev/en/TRSP-family.html
and the migration guide:
https://docs.pgrouting.org/dev/en/trsp_migration.html

For further similar problems with TRSP functions please open a new issue with the specific function name.
