### ISSUE TITLE
pgr_pointsaspolygon first argument select with text

### ISSUE THREAD

**Issue by opessoa** [pgRouting/pgrouting#493]
Hi guys, I'm using pgr_pointsaspolygon to generate a polygon from my points, but, I have a select with date comparison, something like this:

`select st_astext(pgr_pointsaspolygon('select id, st_x(the_geom) as x,st_y(the_geom) as y from rota_destino where date(dt_hr) = ''17/02/2016'' and id_rota = 0 order by ordem'));`

This results in:

`ERROR:  syntax error at or near "17"
LINE 1: ...geom) as y from rota_destino where date(dt_hr) = '17/02/2016...
                                                             ^
QUERY:  SELECT x, y FROM pgr_alphashape('select id, st_x(the_geom) as x,st_y(the_geom) as y from rota_destino where date(dt_hr) = '17/02/2016' and id_rota = 0 order by ordem', 0)
CONTEXT:  PL/pgSQL function pgr_pointsaspolygon(character varying,double precision) line 17 at FOR over EXECUTE statement ... `

How can I solve it?

**Comment by opessoa** [comment]
Hi guys, maybe this is a solution:

`FOR vertex_result IN EXECUTE 'SELECT x, y FROM pgr_alphashape('''|| replace( query, '''', '''''') || ''', ' || alpha || ')' `

In function `pgr_pointsaspolygon`.

**Comment by dkastl** [comment]
Thank you for providing a solution!
If you think you found one, that works for you and still works with the example data from the documentation, feel free to submit a patch (Pull Request) to the `develop` branch.

At the moment I'm exactly seeing, what you propose. Escaping quotations in pgpsql lacks a bit of readability ;-)
What exactly solved your problem?

**Comment by robe2** [comment]
At a glance I think it would be better to use a parameterized query

    FOR vertex_result IN EXECUTE 'SELECT x, y FROM pgr_alphashape($1) ' USING query


Didn't test so might have typos

**Comment by opessoa** [comment]
@dkastl, @robe2 I will try the Regina's solution at monday! 

Thanks guys.

**Comment by opessoa** [comment]
@dkastl, @robe2 parameterized query solves the problem... (In my solution I had use replace to insert double ').

How can I submit a patch to the develop branch?

**Comment by dkastl** [comment]
As far as I know you need to fork the repository, make the changes (you can probably do this also in the browser), then initiate a pull request: https://help.github.com/articles/using-pull-requests/

Please use the `develop` branch as a base for changes. The `develop` branch should be also the branch to reference as target for the pull request.

**Comment by woodbri** [comment]
I think that Vicky is using branch 'dev-2.2' as her base branch for the current release and the pull request should be made against that.

**Comment by dkastl** [comment]
@woodbri I know about Vicky's 2.2 branch and I thought, if I should mention it or not. I decided to propose the `develop` branch, because otherwise we have to adjust our "how-to-contribute" guideline all the time. If the branch name changes again for whatever reason, comments in tickets may get invalid again.
I think we should be able to pull patches into `develop` and then update our custom development branches .

**Comment by opessoa** [comment]
It's done guys! I need to do something else?

**Comment by dkastl** [comment]
Hmm, if successful, the pull request should show up here: https://github.com/pgRouting/pgrouting/pulls
Can you check if you missed some step?

**Comment by opessoa** [comment]
Sorry... now it's ok.

**Comment by cvvergara** [comment]
Hi,  sorry for a delay response from me.
This case from @opessoa  it can be done against develop.
