### ISSUE TITLE
pgRouting 2.2.0 alpha includes micro and -- in library name

### ISSUE THREAD

**Issue by robe2** [pgRouting/pgrouting#515]
### Expected behavior and actual behavior
The pgRouting library that gets built on Windows (under mingw64) is called
libpgrouting--2.2.0.dll

I was expecting it to follow the same naming convention as the pgRouting 2.1 which was named

libpgrouting-2.1.dll

(for contrast - pgRouting 2.0 was not versioned -- was call librouting.dll (with librouting_*.dll files (bd,dd, ksp, tsp accompanying them) 

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System

pgRouting 2.2.0-alpha, PostgreSQL 9.5, Windows

Also there should be no -- in the name, should just be a single dash.  I think -- is very non-standard to have in a library name.

The micro version number should also be stripped.  The reason being is that micros are supposed to be stability and security patches and generally require just a drop in replacement for any of that version so people generally just install over and library replacement is generally sufficient to get the benefits.

**Comment by cvvergara** [comment]
So, instead of
```
libpgrouting--2.2.0.dll    (for windows)
libpgrouting--2.2.0.so    (for linux)
```
is
```
libpgrouting-2.2.dll
libpgrouting-2.2.so
```

As soon as I fix it I'll release 2.2 alpha1

**Comment by cvvergara** [comment]
@robe2 
I am getting this now, is that correct?
please confirm so I can make the alpha1
```
-- Install configuration: ""
-- Installing: e:/jenkins/postgresql/rel/pg9.5w64gcc48/lib/libpgrouting-2.2.dll.a
-- Installing: e:/jenkins/postgresql/rel/pg9.5w64gcc48/lib/libpgrouting-2.2.dll
-- Installing: e:/jenkins/postgresql/rel/pg9.5w64gcc48/share/extension/pgrouting--2.2.0.sql
-- Installing: e:/jenkins/postgresql/rel/pg9.5w64gcc48/share/extension/pgrouting.control
-- Installing: e:/jenkins/postgresql/rel/pg9.5w64gcc48/share/extension/pgrouting--2.0.0--2.2.0.sql
-- Installing: e:/jenkins/postgresql/rel/pg9.5w64gcc48/share/extension/pgrouting--2.1.0--2.2.0.sql
```
[jenkins link](http://winnie.postgis.net:1500/view/pgRouting/job/pgRouting_PGVersionEDB/3696/console)

**Comment by cvvergara** [comment]
in travis:
```
Install the project...
-- Install configuration: ""
-- Installing: /usr/lib/postgresql/9.1/lib/libpgrouting-2.2.so
-- Installing: /usr/share/postgresql/9.1/extension/pgrouting--2.2.0.sql
-- Installing: /usr/share/postgresql/9.1/extension/pgrouting.control
-- Installing: /usr/share/postgresql/9.1/extension/pgrouting--2.0.0--2.2.0.sql
-- Installing: /usr/share/postgresql/9.1/extension/pgrouting--2.1.0--2.2.0.sql
```
[travis link](https://travis-ci.org/pgRouting/pgrouting/jobs/113028928#L1002)

**Comment by robe2** [comment]
You are missing a 2.0.1--2.2.0.sql

**Comment by cvvergara** [comment]
@robe2 like this?:
```
-- Installing: /usr/share/postgresql/9.3/extension/pgrouting--2.2.0.sql
-- Installing: /usr/share/postgresql/9.3/extension/pgrouting.control
-- Installing: /usr/share/postgresql/9.3/extension/pgrouting--2.0.0--2.2.0.sql
-- Installing: /usr/share/postgresql/9.3/extension/pgrouting--2.0.1--2.2.0.sql
-- Installing: /usr/share/postgresql/9.3/extension/pgrouting--2.1.0--2.2.0.sql
```

**Comment by robe2** [comment]
Yes much better.
