### ISSUE TITLE
pgRouting 2.2.0 beta1 issue, can't upgrade from pgrouting 2.1.0

### ISSUE THREAD

**Issue by robe2** [pgRouting/pgrouting#521]
### Expected behavior and actual behavior
It should upgrade, but instead I get - 

ERROR:  syntax error at or near "text"
********** Error **********

ERROR: syntax error at or near "text"
SQL state: 42601
Character: 2712

### Steps to reproduce the problem
CREATE EXTENSION postgis;
CREATE EXTENSION pgrouting VERSION "2.1.0";
ALTER EXTENSION pgrouting UPDATE TO "2.2.0";

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System
Upgrading from released pgRouting 2.1 - (2.1.0,pgrouting-2.1.0,1,b38118a,master,1.59.0)

POSTGIS="2.3.0dev r14740" GEOS="3.5.0-CAPI-1.9.0 r4090" PROJ="Rel. 4.9.1, 04 March 2015" GDAL="GDAL 2.0.1, released 2015/09/15" LIBXML="2.7.8" LIBJSON="0.12" RASTER PostgreSQL 9.5.1, compiled by Visual C++ build 1800, 64-bit

**Comment by cvvergara** [comment]
pgr_version                   
-------------------------------------------------
I could reproduce this error, I will debug the upgrader

**Comment by robe2** [comment]
This is fixed in develop.  Do you want to wait till you release another beta (or final) before closing this out?

**Comment by cvvergara** [comment]
I'll close when releasing beta2

**Comment by cvvergara** [comment]
fixed in Tag pgrouting-2.2.0-RC1
