### ISSUE TITLE
pgr_gsoc_vrppdtw crashes on 2nd usage within the same connection

### ISSUE THREAD

**Issue by Illedran** [pgRouting/pgrouting#528]
### Expected behavior and actual behavior
pgr_gsoc_vrppdtw crashes when used the 2nd time within the same database connection.
I tested it on the data provided within the test directory.

### Steps to reproduce the problem
1) Create a connection to the database.
2) Run pdp-any-00.data to create the schema and import data.
3) Run pdp-any-01.test.sql twice.

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System
PostgreSQL 9.5.1
PostGIS 2.2.1
pgRouting 2.1.0
ArchLinux: Linux 4.1.19-1-lts

**Comment by cvvergara** [comment]
@Illedran 
Thanks for your report.
pgr_gsoc_vrppdtw is a proposed function and needs work.
