### ISSUE TITLE
_pgr_startpoint, _pgr_endpoint make more efficient

### ISSUE THREAD

**Issue by robe2** [pgRouting/pgrouting#529]
I was looking at these functions that are currently plpgsql and on some tests, I noticed performance seems a lot better if they are sql functions.

I propose changing them to this - I think they haven't changed in a while

`
CREATE OR REPLACE FUNCTION _pgr_startpoint(g geometry)
  RETURNS geometry AS
$$
SELECT CASE WHEN  geometrytype($1) ~ '^MULTI'  THEN st_startpoint(st_geometryn($1,1))
   ELSE st_startpoint($1)
    END;
$$
  LANGUAGE sql IMMUTABLE;

CREATE OR REPLACE FUNCTION _pgr_endpoint(g geometry)
  RETURNS geometry AS
$$
SELECT CASE WHEN  geometrytype($1) ~ '^MULTI'  THEN st_endpoint(st_geometryn($1,1))
   ELSE st_endpoint($1)
    END;
$$
  LANGUAGE sql IMMUTABLE;

`

To test I was running a portion from pgr_nodenetwork.  With the functions are they are in plpgsql:(testing on pgRouting 2.2.0)

-- this query take 2.9-3.0 seconds 1470 rows created (I ran 5 times)
-- if change to use the SQL variant time drops to 1.6-1.7 seconds
`
create temp table intergeom on commit drop as (
        select l1.gid as l1id, 
               l2.gid as l2id, 
           l1.the_geom as line,
          _pgr_startpoint(l2.the_geom) as source,
         _pgr_endpoint(l2.the_geom) as target,
               st_intersection(l1.the_geom, l2.the_geom) as geom 
        from (SELECT \* FROM ospr.ways) as l1 
             join (SELECT \* FROM ospr.ways) as l2 
             on (st_dwithin(l1.the_geom, l2.the_geom, 1e-005))
where l1.gid <> l2.gid and st_equals(_pgr_startpoint(l1.the_geom),_pgr_startpoint(l2.the_geom))=false and 
    st_equals(_pgr_startpoint(l1.the_geom),_pgr_endpoint(l2.the_geom))=false and 
    st_equals(_pgr_endpoint(l1.the_geom),_pgr_startpoint(l2.the_geom))=false and 
    st_equals(_pgr_endpoint(l1.the_geom),_pgr_endpoint(l2.the_geom))=false 
     )

`

The only danger I think with making this an sql function is that it then becomes transparent to the planner so it's possible pgrouting could fail install if postgis and pgrouting aren't installed in same schema.  I haven't tested that out yet.  So consider this food for thought for future.

**Comment by cvvergara** [comment]
didnt have time in 2.3
