### ISSUE TITLE
pgr_withPoints not working correctly

### ISSUE THREAD

**Issue by xarbau** [pgRouting/pgrouting#541]
Hi, I’ve tried this function and it seems not to work correctly. When it calculates the route between vertex it does well, but when using the pointsofinterest, it confuses the ids of the points and the result is incorrect.
If we take a look at the example:

Example:	From point 1 to point 3
SELECT * FROM pgr_withPoints(
        'SELECT id, source, target, cost, reverse_cost FROM edge_table ORDER BY id',
        'SELECT pid, edge_id, fraction, side from pointsOfInterest',
        -1, -3);
seq | path_seq | node | edge | cost | agg_cost 
-----+-------------+-------+-------+------+----------
   1 |        1 |         -1 |       1 |     0.6 |        0
   2 |        2 |          2 |       4 |        1 |      0.6
   3 |        3 |          5 |       7 |        1 |      1.6
   4 |        4 |          8 |       6 |     0.7 |      2.6
   5 |        5 |         -3 |      -1 |        0 |      3.3
(5 rows)
If we follow the edges, we’ll see that it begins from the point 1 but ends at point 4. Edges sequence(1,4,7,6)

![img](https://cloud.githubusercontent.com/assets/18477948/14553355/341567e2-02e6-11e6-91a5-eaf53530359a.png)

These are the correspondences of the points

(‘Pointsofinterest’)->(Point used by pgr_withpoints)
1->1
2->5
3->4
4->2
5->3
6->6

Pgrouting version :(2.2.0,pgrouting-2.2.0,afc622e,master,1.59.0)

postgis version: "POSTGIS="2.2.2 r14797" GEOS="3.5.0-CAPI-1.9.0 r4090" PROJ="Rel. 4.9.1, 04 March 2015" GDAL="GDAL 2.0.2, released 2016/01/26" LIBXML="2.7.8" LIBJSON="0.12" RASTER"

postgres version: "PostgreSQL 9.5.2, compiled by Visual C++ build 1800, 32-bit"

**Comment by cvvergara** [comment]
@xarbau 
Can you please test this branch and see that it fixes the issue?
https://github.com/pgRouting/pgrouting/tree/hotFix/issue541

**Comment by xarbau** [comment]
Hi Vicky,
I’m using Windows and I have to compile this branch and I’m not sure how to do it. Do you know any tutorial?

Salutacions.

Josep López Xarbau | R+D+i - Projectes de Transferència Tecnològica – Centre Coneixement Urbà | jlopez@tecnocampus.cat<mailto:jlopez@tecnocampus.cat>
[Descripción: signatura_mail_TCM]
TecnoCampus Mataró-Maresme | Edifici Universitari TCM 1 Planta 2 | Avinguda Ernest Lluch, 32 (Porta Laietana)
08302 Mataró (Barcelona) | Tel. 93 169 65 00 | Fax 93 169 65 05 | www.tecnocampus.cat<http://www.tecnocampus.cat/>

De: Vicky Vergara [mailto:notifications@github.com]
Enviado el: viernes, 15 de abril de 2016 9:07
Para: pgRouting/pgrouting
CC: Josep Lopez Xarbau
Asunto: Re: [pgRouting/pgrouting] pgr_withPoints not working correctly (#541)


@xarbau<https://github.com/xarbau>
Can you please test this branch and see that it fixes the issue?
https://github.com/pgRouting/pgrouting/tree/hotFix/issue541

**Comment by cvvergara** [comment]
@xarbau 
Sorry, I am not the Windows expert. @robe2 might be able to help.
PD. looks like you replied directly using the mail, and a lot of personal data was added into the issue comment.
At the bottom of the mail there is a link  "view it on GitHub", please click the link edit the comment to delete the personal info from comment.
(and maybe you should always use the GitHub page to post comments so that no personal info is posted there.)
