### ISSUE TITLE
pgRouting docs for 2.2.0 say UPDATE to 2.1.0

### ISSUE THREAD

**Issue by robe2** [pgRouting/pgrouting#543]
You should probably just make this a variable.  That's what we do in PostGIS docs so we don't need to change it all the time.

http://docs.pgrouting.org/2.2/en/doc/src/installation/installation.html

(way at the bottom says)

To upgrade pgRouting to version 2.1.0 use the following command:

ALTER EXTENSION pgrouting UPDATE TO "2.1.0";

**Comment by cvvergara** [comment]
I am working on this #544 for version 2.2, when I finish I will be making a micro 2.2.1,
what if:

To upgrade pgRouting to version 2.2.x use the following command:
ALTER EXTENSION pgrouting UPDATE TO "2.2.x";
