### ISSUE TITLE
pgr_drivingDistance equicost = true is missing nodes (regression bug)

### ISSUE THREAD

**Issue by robe2** [pgRouting/pgrouting#552]
### Expected behavior and actual behavior

These two queries should return the same count since all nodes within my limit should be accounted for in both with the only difference that a node could appear more than ones when equicost = false

```

SELECT COUNT(DISTINCT dd.node)  
FROM pgr_drivingDistance(
    'SELECT gid As id, source, target,                                   

    cost_s AS cost, reverse_cost_s AS reverse_cost 

    FROM ospr.ways',
    ARRAY[1003,1130]
    , 5*60, true, equicost := false                                                             
) AS dd  ;

SELECT COUNT(DISTINCT dd.node)  
FROM pgr_drivingDistance(
    'SELECT gid As id, source, target,                                   

    cost_s AS cost, reverse_cost_s AS reverse_cost 

    FROM ospr.ways',
    ARRAY[1003,1130]
    , 5*60, true, equicost := true                                                             
) AS dd  ;


```

### Steps to reproduce the problem

In pgRouting 2.1.0 they do.  In pgRouting 2.2.0 I lose nodes.  Both pgr 2.1.0 and 2.2.0 give same answer for the equicost = false case.  So it seems issue is only for equicost = true.

 I gave @cvvergara  my dataset from the book that exhibits this issue since its hard to replicate the issue with test data.

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System

Use the commands:
```
PostgreSQL 9.5.2, compiled by Visual C++ build 1800, 64-bit POSTGIS="2.3.0dev r14810" GEOS="3.5.0-CAPI-1.9.0 r4090" PROJ="Rel. 4.9.1, 04 March 2015" GDAL="GDAL 2.0.2, released 2016/01/26" LIBXML="2.7.8" LIBJSON="0.12" RASTER (2.2.0,pgrouting-2.2.0,afc622e,master,1.59.0)

```

**Comment by cvvergara** [comment]
Reproduced the issue.

**Comment by cvvergara** [comment]
@robe2 
can you test this branch with your data (also on jenkins)
https://github.com/pgRouting/pgrouting/tree/hotFix/issue552
If it does, I need to prepare a release 2.2.2.
The tests for driving distance didn't catch that error, I need to find a query using the sample data of the documentation that catches the error.
[travis build](https://travis-ci.org/pgRouting/pgrouting/builds/125659819)

**Comment by robe2** [comment]
that branch fixes the issue.

**Comment by cvvergara** [comment]
Going to fix a documentation about pgr_drivingDistance that says it's not coded yet, but actually is coded & a parameter name that is wrong, using this same issue

**Comment by cvvergara** [comment]
parameter name:
eid 
should be:
edge_id
