### ISSUE TITLE
pgr_analyzeGraph is spelled as pgr_analizeGraph in outputs and pgr_create_topology

### ISSUE THREAD

**Issue by robe2** [pgRouting/pgrouting#555]
http://docs.pgrouting.org/2.2/en/src/topology/doc/pgr_analyzeGraph.html#pgr-analyze-graph

In examples -- all pgr_analizeGraph should be changed to pgr_anlayzeGraph.

also on that page the data has:

``  SELECT  pgr_create_topology('edge_table',0.001); ``

Should be 

``  SELECT  pgr_createTopology('edge_table',0.001); ``

**Comment by cvvergara** [comment]
So, two things need to be considered,
* the documentation for 2.2
* the documentation for 2.3-dev

@dkastl 
I would like @Illedran to fix the documentation on 2.2, and @sankepallyrohithreddy to fix the documentation on 2.3

They will have to write documentation for their functions, in I feel its an opportunity for them to see how documentation is handled in pgRouting. It will give them a chance to practice creating branches, merge, delete branches, change branches, pull request, etc.

The difference will be:
In documentation for 2.2:
* change the misspelling by substitution.

In documentation for 2.3-dev:
* change the examples to be auto-generated
* change misspelling on the non examples text if any

The commonality is:
1. create a working branch departing from master & develop respectively:
* hotFix/issue555  for 2.2 from master
* fix/issue555  for 2.3-dev from develop
2. update the documentation on the gh-pages
* 2.2 directory
* dev directory
3. merge the changes into master & develop respectively.
4. delete the branch used to work the issue

of course I'll guide them all the way.
