### ISSUE TITLE
Performance of pgr_dijkstra() in pgRouting v2.2.0 is not good

### ISSUE THREAD

**Issue by heleyboo** [pgRouting/pgrouting#556]
I have been used pgRouting in my project to find shortest path with Dijkstra algorithm. I had intended to use pgr_dijkstra function in pgRouting 2.2 instead of pgr_kdijkstraPath(pgRouting v2.0) in my source code. Then I have made a performance comparison between two those functions but the result is pretty bad for pgr_dijkstra.

My database has more than 1 million records. When I use pgr_kdijkstraPath to find shortest path between two nodes, it just take 550 ms, but it take about 800 - 1200 ms for pgr_dijkstra. 

I think the performance for pgr_dijkstra need to improve.

**Comment by cvvergara** [comment]
@heleyboo 
this is the same as #526 
there is this comment https://github.com/pgRouting/pgrouting/issues/526#issuecomment-203203021

can you pleas post the results of:
select pgr_version();

**Comment by heleyboo** [comment]
> can you pleas post the results of:
> select pgr_version();
@cvvergara Below are results of pgr_version()
(2.2.0,pgrouting-2.2.0-RC1,1d42557,develop,1.41.0)

**Comment by cvvergara** [comment]
can you upgrade to version 2.2.2?

**Comment by heleyboo** [comment]
Thanks @cvvergara, I will upgrade to version 2.2.2.

**Comment by heleyboo** [comment]
Hi @cvvergara, I have upgraded pgRouting to version 2.2.2 but when I execute performance test, the performance results still bad.

With v2.0.0(2.0.0,pgrouting-2.0.0,0,f26831f,master,1.41.0), I execute the following queries
`explain analyze select count(*) FROM pgr_dijkstra('SELECT gid as id, source, target, length as cost FROM ways_walk', 132542, 7515, false, false);`

`explain analyze select count(*) FROM pgr_kdijkstraPath('SELECT gid as id, source, target, length as cost FROM ways', 132542, ARRAY[7515], false, false);`
It takes average 1137ms for both pgr_dijkstra and pgr_kdijkstraPath

And with v2.2.2(2.2.2,pgrouting-2.2.2,544044b,master,1.41.0), it takes about 2000ms for query use pgr_dijkstra
`explain analyze select count(*) FROM pgr_dijkstra('SELECT gid as id, source, target, length as cost FROM ways', 132542, 7515, false);`

**Comment by cvvergara** [comment]
@heleyboo did you made some progress on this topic?

**Comment by heleyboo** [comment]
@cvvergara Thanks for your information. According to your suggestion, I have executed performance test on my database and the result is so good when I use a bounding box to limit search area. It's a little bit faster than v2.0.0. Thank a lot.

**Comment by cvvergara** [comment]
Glad to hear.
I'll close this issue
