### ISSUE TITLE
Error on building docs with Sphinx & python3

### ISSUE THREAD

**Issue by Illedran** [pgRouting/pgrouting#559]
### Expected behavior and actual behavior

CMake should build the docs regardless of the python version. It currently fails when the python version is >=3.0. 
### Steps to reproduce the problem

``` bash
cd build/
cmake -DWITH_DOC=ON ..
make doc
```
### Proposed Fix

The error happens at this line:
https://github.com/pgRouting/pgrouting/blob/master/cmake/FindSphinx.cmake#L55
it can be fixed by modifying the python statement to

``` python
from __future__ import print_function; import sphinx; print(sphinx.__version__)
```

**Comment by cvvergara** [comment]
didnt have time in 2.3

**Comment by cvvergara** [comment]
Leaving this issue for later

**Comment by cvvergara** [comment]
Right now it is done with python >=3
Closing issue.
