### ISSUE TITLE
Astar new code approval

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#560]
pgr-astar uses an inner query different  of pgr_dijkstra:
In pgr_astar
```
SELECT id, source, target, cost[, reverse_cost], x1,y1,x2,y2 FROM edge_table
```

In pgr_dijkstra
```
SELECT id, source, target, cost[, reverse_cost] FROM edge_table
```
So internally a different traits for Vertices/Edges on boost::graph have to be used. (in pgr_astar case the vertex also needs the location x,y)
Additionally the GSoC projects might need, specially GSoC contraction, different  traits for Vertices/Edges. 
A modification on the general graph has being made to facilitate the boost library usage for different graph definitions. I used pgr_astar to test these modifications, (of course all the other functions that already use it had to be adjusted to the new general graph modifications)
 A new signature to cover #36 has being added, and the current pgr_astar has being wrapped based on the current behaviour, comparative tests vs pgr_dijkstra (using the sample data of the documentation) have being made.
https://github.com/cvvergara/pgrouting/tree/rewrite/astar
There are still things to do, like rewrite the documentation, or make performance tests to evaluate the claim: "pgr_astar is faster than pgr_dijkstra" and answer questions like how much faster?
But the urgency of merging the code is because this new general graph is going to be used.
As the GSoC projects advance, I will have to add functionality that I couldn't foresee.

Note 1: up till now contraction has its own "general graph" because of the lack of the functionality I just added
Note 2: with this functionality it was a fast rewrite of pgr_astar.

So the next two comments in this issue, is for making a community vote for the following options:
* merge into develop now
* merge into develop later

P.D.
* Please use the thumbs up or thumbs down to make your vote,
* If you have a different alternative, feel free to open a new comment with the new alternative.
* if you feel you need to state why you chose an alternative, please mention the alternative and your reasons in a comment
* to see all issues related to pgr_astar, look for the label astar

**Comment by woodbri** [comment]
Not clear what the ramifications of these options are!
* why would one want to delay merging?
* does merging now disrupt any current activities?
* beyond AStar and GSoC activities that need this, are there other developers actively doing work on the code base?
* does this merge impact the existing code base other than AStar and GSoC activities?

In general, I'm of the belief that sooner is better than later unless it causes someone major heartburn because it gives us more opportunity for people to test it and report potential issue.

Without more information, I'm +1 on merge now.

**Comment by dkastl** [comment]
@cvvergara Do you think there could be a backwards compatibility issue?
If there is a risk, that current users of pgRouting must adjust their applications when they upgrade, why don't we target then this change for a pgRouting 3.0 release?

There are projects, that do major releases very often, like web browsers or Node.js now does as well.
And there are projects that do small releases for ages and sometimes even don't get to the point to release 1.0 ;-)

I think, for pgRouting it's OK to do a new major release (3.0), if we feel that we carry too much burden with us to guarantee backwards compatibility. For such a new major release, it's probably better to start with `develop-3.0` branch to.

It will probably take at least until the end of 2016 to have CH and the Max Flow be released with pgRouting, so there should be enough time.

**Comment by dkastl** [comment]
Maybe adding, that CH and Max Flow will introduce new ideas and type of algorithms, which could be also a good reason for a new major release.

**Comment by cvvergara** [comment]
@dkastl 
what backwards compatabiity are you talking about???
pgr_astar as it is returns wrong values.
Rewriting Astar does not affect the other functions that use the general internal library code.
About major release, not yet, the internal library needs more refinement, and there are still lots of existing functions that return wrong results that need to be rewritten.

**Comment by dkastl** [comment]
@cvvergara your issues sounded like "serious" changes, but if it does not really affect existing users, then I don't see any problem to merge into `develop`.

**Comment by cvvergara** [comment]
Merge done, I will propagate changes to other branches.
