### ISSUE TITLE
TSP

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#565]
coding:
 * pgr_eucledianDMatrix,
 * pgr_dijkstraDMatrix
 * pgr_withPointsDMatrix
 * pgr_astarDMatrix (coded for the future)
Took me 1 day.... (the 10th) and that includes that I had to go to my mom's house, so I really didn't work a full day (was mother's day in Mexico.)

I've being trying to make the wrappers of:
* _pgr_makeDistanceMatrix... yesterday and I got stuck (mainly because I am making changes that can be used with ids of type BIGINT)
* pgr_vidsToDMatrix... today and I am stuck, (https://github.com/pgRouting/pgrouting/issues/564)

I would like to make this kind of calls work:
```
SELECT * FROM pgr_TSP( 'select * FROM pgr_fooDMatrix(...)', from_vid)
SELECT * FROM pgr_TSP( 'select * FROM  pgr_fooDMatrix(...)', from_vid, to_vid)
SELECT * FROM pgr_TSP('select * FROM myTempTable', from_vid, to_vid)
```
the signature might look like be:
```
SELECT * FROM pgr_TSP( matrix_row_sql::TEXT, start_vid::BIGINT);
SELECT * FROM pgr_TSP( matrix_row_sql::TEXT, start_vid::BIGINT, end_vid::BIGINT);
```
matrix_row_sql has the following columns: (start_vid, end_vid, agg_cost);
(curiously are the columns in the results of pgr_fooDMatrix)

This new signatures would not  need any of: pgr_vidsToDmatrix, pgr_vidsToDMatrix, _pgr_makeDistanceMatrix, pgr_pointsToDmatrix

**Comment by woodbri** [comment]
Just a thought, why not make NEW signatures for TSP that do not use the array/matrix interface and just leave the old ones for backwards compatibility. And when 3.0 comes along the old signature can go away and be replaced by the new ones. I'm not sure it makes sense long term so carry the array/matrix signatures forward.

**Comment by cvvergara** [comment]
working branch:
https://github.com/cvvergara/pgrouting/tree/newSignature/TSP
working directory:
newTSP

**Comment by cvvergara** [comment]
I want to add more control on the way tsp works, so for example:
```
CREATE OR REPLACE FUNCTION pgr_eucledianTSP(
    coordinates_sql TEXT,
    start_id BIGINT DEFAULT -1,
    end_id BIGINT DEFAULT -1,
    randomize BOOLEAN DEFAULT true,
    initial_temperature FLOAT DEFAULT 100,
    final_temperature FLOAT DEFAULT 0.1,
    cooling_factor FLOAT DEFAULT 0.9,
    tries_per_temperature INTEGER DEFAULT 500,
    change_per_temperature INTEGER DEFAULT 60,
    OUT seq integer,
    OUT node integer,
    OUT cost FLOAT,
    OUT agg_cost FLOAT)
RETURNS SETOF record
AS '$libdir/${PGROUTING_LIBRARY_NAME}', 'eucledianTSP'
LANGUAGE c VOLATILE STRICT;
```

**Comment by dkastl** [comment]
What is "temperature" for TSP?

**Comment by cvvergara** [comment]
yeah, I will need to document it a lot :)

**Comment by cvvergara** [comment]
you can see all those parameters as cycle controls.

**Comment by woodbri** [comment]
The parameters pertain to the specific solver being used. In this case the algorithm is simulated annealing and the solver simulates annealing of metal, where you heat it up and which allows for a lot of random changes, then you cool it down and the atoms align (ie the solution is optimized) and this is repeated multiple times and each time you lower the amount of randomness that is allow so you iterate to a better solution.

**Comment by dkastl** [comment]
See, now I learned a new English noun "annealing" ;-)

**Comment by woodbri** [comment]
https://en.wikipedia.org/wiki/Simulated_annealing

**Comment by cvvergara** [comment]
hmm, so it wasn't "Anne" doing "a ling" ;)

**Comment by cvvergara** [comment]
Sample execution using the data from western sahara to adjust default values
http://www.math.uwaterloo.ca/tsp/world/countries.html#WI
```
SET client_min_messages TO DEBUG1;
SELECT * FROM pgr_eucledianTSP($$select * FROM wi29$$);
```
the results I get:
```
DEBUG:  Elapsed time for  reading coordinates:: 0.000674sec = (14212.000000 - 13538.000000) / CLOCKS_PER_SEC 
NOTICE:  Total 29 coordinates:
DEBUG:  Elapsed time for  processing eucledianTSP: 0.071441sec = (85717.000000 - 14276.000000) / CLOCKS_PER_SEC 
NOTICE:  LOG = Initializing tsp class --->OK
tsp.greedyInitial --->OK
tsp.annealing --->OK

Cycle(100) total changes =100 = 18      14 were because  delta energy < 0
Cycle(90) total changes =90 = 8 6 were because  delta energy < 0
Cycle(81) total changes =81 = 1 1 were because  delta energy < 0
Cycle(72.9) total changes =72.9 = 5     2 were because  delta energy < 0
Cycle(65.61) total changes =65.61 = 4   2 were because  delta energy < 0
Cycle(59.049) total changes =59.049 = 2 0 were because  delta energy < 0
Cycle(53.1441) total changes =53.1441 = 5       2 were because  delta energy < 0
Cycle(47.8297) total changes =47.8297 = 1       0 were because  delta energy < 0
Cycle(43.0467) total changes =43.0467 = 1       0 were because  delta energy < 0
Cycle(38.742) total changes =38.742 = 0 0 were because  delta energy < 0
Total swaps: 32
Total slides: 10
Total reverses: 35
Times best tour changed: 45
Best cost reached = 28777.5

 seq | node |       cost       |     agg_cost     
-----+------+------------------+------------------
   1 |    6 |                0 |                0
   2 |    2 | 900.617093380362 | 900.617093380362
   3 |    1 |  74.535614157127 | 975.152707537489
   4 |    5 | 2266.91173136004 | 3242.06443889753
   5 |    8 | 1188.01888359478 | 4430.08332249231
   6 |    4 | 994.708187806297 |  5424.7915102986
   7 |    3 | 1172.36699411442 | 6597.15850441303
   8 |    7 | 891.004385199336 | 7488.16288961236
   9 |    9 |  650.85409697993 | 8139.01698659229
  10 |   16 |  4088.0585364911 | 12227.0755230834
  11 |   24 | 1243.87392358622 | 13470.9494466696
  12 |   27 | 559.016994374947 | 14029.9664410446
  13 |   25 |  74.535658878487 | 14104.5020999231
  14 |   20 | 1330.83095428717 | 15435.3330542102
  15 |   26 | 509.901951359278 | 15945.2350055695
  16 |   28 | 648.288376333318 | 16593.5233819028
  17 |   29 | 592.939989005405 | 17186.4633709082
  18 |   21 | 440.456596290771 |  17626.919967199
  19 |   23 | 197.926372783442 | 17824.8463399824
  20 |   22 | 220.141999627513 |   18044.98833961
  21 |   19 | 697.666150054665 | 18742.6544896646
  22 |   15 | 772.082339448903 | 19514.7368291135
  23 |   18 | 1108.05137466134 | 20622.7882037749
  24 |   17 | 683.333268292684 | 21306.1214720675
  25 |   14 | 1202.91366735569 | 22509.0351394232
  26 |   13 | 1321.76283931305 | 23830.7979787363
  27 |   12 | 1314.23824873744 | 25145.0362274737
  28 |   11 | 1411.95293791574 | 26556.9891653895
  29 |   10 | 106.718669615254 | 26663.7078350047
  30 |    6 | 2113.77757765045 | 28777.4854126552
(30 rows)
```

**Comment by cvvergara** [comment]
![western-sahara](https://cloud.githubusercontent.com/assets/5035290/15509326/bbd418d8-2198-11e6-84d4-e604311ff726.png)

**Comment by cvvergara** [comment]
what if...
I put a time_limit parameter also?

**Comment by cvvergara** [comment]
per cycle or total?

**Comment by cvvergara** [comment]
I'll make it total

**Comment by cvvergara** [comment]
another smaller signature for the people that work with time, and have the controlling parameters automatically based on the size of the data.
``
CREATE OR REPLACE FUNCTION pgr_eucledianTSP(
    coordinates_sql TEXT,
    start_id BIGINT DEFAULT -1,
    end_id BIGINT DEFAULT -1,
    randomize BOOLEAN DEFAULT true,
    max_execution_time FLOAT default '+infinity'::FLOAT
   OUT ....
)
```

**Comment by cvvergara** [comment]
I want to refine the ordering of the parameters
choice (1) What I have right now
```
CREATE OR REPLACE FUNCTION pgr_eucledianTSP(
    coordinates_sql TEXT,
    start_id BIGINT DEFAULT -1,
    end_id BIGINT DEFAULT -1,
    randomize BOOLEAN DEFAULT true,
    max_processing_time FLOAT DEFAULT '+infinity'::FLOAT,
    initial_temperature FLOAT DEFAULT 100,
    final_temperature FLOAT DEFAULT 0.1,
    cooling_factor FLOAT DEFAULT 0.9,
    tries_per_temperature INTEGER DEFAULT 500,
    max_changes_per_temperature INTEGER DEFAULT 60,
    max_consecutive_non_changes INTEGER DEFAULT 200,
```

choice (2) What I think might be better because the 
tries_per_temperature, max_changes_per_temperature and max_consecutive_non_changes
control when to  **break** the cycles.
```
CREATE OR REPLACE FUNCTION pgr_eucledianTSP(
    coordinates_sql TEXT,
    start_id BIGINT DEFAULT -1,
    end_id BIGINT DEFAULT -1,
    randomize BOOLEAN DEFAULT true,
    max_processing_time FLOAT DEFAULT '+infinity'::FLOAT,
    tries_per_temperature INTEGER DEFAULT 500,
    max_changes_per_temperature INTEGER DEFAULT 60,
    max_consecutive_non_changes INTEGER DEFAULT 200,
    initial_temperature FLOAT DEFAULT 100,
    final_temperature FLOAT DEFAULT 0.1,
    cooling_factor FLOAT DEFAULT 0.9,
```

**Comment by cvvergara** [comment]
shall I change?  put thumbs up.
shall I keep? put thumbs down

**Comment by cvvergara** [comment]
some documentation about how tsp annealing with the parameters I mention
https://github.com/cvvergara/pgrouting/blob/newSignature/TSP/src/newTSP/doc/tsp.rst
https://github.com/cvvergara/pgrouting/blob/newSignature/TSP/src/newTSP/doc/tsp_parameters.txt

**Comment by cvvergara** [comment]
mad some documentation for pgr_eucledianTSP
https://github.com/cvvergara/pgrouting/blob/newSignature/TSP/src/newTSP/doc/pgr_eucledianTSP.rst
the three examples are in:
https://github.com/cvvergara/pgrouting/blob/newSignature/TSP/src/newTSP/doc/doc-pgr_eucledianTSP.queries

**Comment by cvvergara** [comment]
Documentation can be viewed here:
http://docs.pgrouting.org/dev-tsp/en/src/tsp/doc/tsp.html
http://docs.pgrouting.org/dev-tsp/en/src/fooDmatrix/doc/dmatrix.html

It still needs some clean up, maybe some grammar??
please consider that English is not my first language, so comments are very appreciated.

**Comment by dkastl** [comment]
@cvvergara just found Sphinx Spellchecker: http://sbkro.hatenablog.jp/entry/2014/11/18/224001
It's a Japanese blog post, but not much to read, mostly code snippets, so I guess you can manage that.
Not sure it works, but if it does, maybe it helps.
