### ISSUE TITLE
Build error on Fedora 24 + GCC 6.0

### ISSUE THREAD

**Issue by devrimgunduz** [pgRouting/pgrouting#576]
Hi,

I'm getting this on Fedora 24, with GCC 6.0. Not getting this on Fedora 23, so I assume that this is a GCC issue. This is pgrouting 2.2.3 against PostgreSQL 9.5:
```
+ /usr/bin/make
/var/lib/pgsql/rpm/BUILD/pgrouting-pgrouting-2.2.3/src/common/src/get_check_data.c: In function 'pgr_SPI_getText':
/var/lib/pgsql/rpm/BUILD/pgrouting-pgrouting-2.2.3/src/common/src/get_check_data.c:230:12: warning: function returns address of local variable [-Wreturn-local-addr]
     return value;
            ^~~~~
/var/lib/pgsql/rpm/BUILD/pgrouting-pgrouting-2.2.3/src/common/src/get_check_data.c:226:11: note: declared here
     char* val = NULL;
           ^~~
/var/lib/pgsql/rpm/BUILD/pgrouting-pgrouting-2.2.3/src/vrp_basic/src/VRP_Solver.cpp: In member function 'bool CVRPSolver::updateTourCosts(CTourInfo&)':
/var/lib/pgsql/rpm/BUILD/pgrouting-pgrouting-2.2.3/src/vrp_basic/src/VRP_Solver.cpp:760:59: error: 'ceil' was not declared in this scope
  vecStartTimes.push_back(static_cast<int>(ceil(dTravelTime)));
                                                           ^
make[3]: *** [src/vrp_basic/src/CMakeFiles/vrp_basic.dir/VRP_Solver.cpp.o] Error 1
make[2]: *** [src/vrp_basic/src/CMakeFiles/vrp_basic.dir/all] Error 2
make[1]: *** [all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.RIJtrb (%build)
    Bad exit status from /var/tmp/rpm-tmp.RIJtrb (%build)
rpmsign: no arguments given
../../../common/Makefile.global:58: recipe for target 'build' failed
make: *** [build] Error 1

```

> 

```

**Comment by cvvergara** [comment]
Hello,
there was this pull request,
https://github.com/pgRouting/pgrouting/pull/573
In linux & windows it didnt cause problem the missing line in the code
This is the change:
https://github.com/pgRouting/pgrouting/pull/573/files
Maybe that fixes it, can you try please.
Vicky


On Sun, May 22, 2016 at 3:19 PM, Devrim Gündüz <notifications@github.com>
wrote:

> Hi,
>
> 0I'm getting this on Fedora 24, with GCC 6.0. Not getting this on Fedora
> 23, so I assume that this is a GCC issue. This is pgrouting 2.2.3 against
> PostgreSQL 9.5:
>
>    - /usr/bin/make
>    /var/lib/pgsql/rpm/BUILD/pgrouting-pgrouting-2.2.3/src/common/src/get_check_data.c:
>    In function 'pgr_SPI_getText':
>    /var/lib/pgsql/rpm/BUILD/pgrouting-pgrouting-2.2.3/src/common/src/get_check_data.c:230:12:
>    warning: function returns address of local variable [-Wreturn-local-addr]
>    return value; ^~~~~
>    /var/lib/pgsql/rpm/BUILD/pgrouting-pgrouting-2.2.3/src/common/src/get_check_data.c:226:11:
>    note: declared here char* val = NULL; ^~~
>    /var/lib/pgsql/rpm/BUILD/pgrouting-pgrouting-2.2.3/src/vrp_basic/src/VRP_Solver.cpp:
>    In member function 'bool CVRPSolver::updateTourCosts(CTourInfo&)':
>    /var/lib/pgsql/rpm/BUILD/pgrouting-pgrouting-2.2.3/src/vrp_basic/src/VRP_Solver.cpp:760:59:
>    error: 'ceil' was not declared in this scope
>    vecStartTimes.push_back(static_cast(ceil(dTravelTime))); ^ make[3]: ***
>    [src/vrp_basic/src/CMakeFiles/vrp_basic.dir/VRP_Solver.cpp.o] Error 1
>    make[2]: *** [src/vrp_basic/src/CMakeFiles/vrp_basic.dir/all] Error 2
>    make[1]: *** [all] Error 2 error: Bad exit status from
>    /var/tmp/rpm-tmp.RIJtrb (%build) Bad exit status from
>    /var/tmp/rpm-tmp.RIJtrb (%build) rpmsign: no arguments given
>    ../../../common/Makefile.global:58: recipe for target 'build' failed make:
>    *** [build] Error 1
>
>  —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pgRouting/pgrouting/issues/576>
>



-- 

Georepublic UG (haftungsbeschränkt)
Salzmannstraße 44,
81739 München, Germany

Vicky Vergara
Operations Research

eMail: vicky@georepublic.de
Web: https://georepublic.info

Tel: +49 (089) 4161 7698-1
Fax: +49 (089) 4161 7698-9

Commercial register: Amtsgericht München, HRB 181428
CEO: Daniel Kastl

**Comment by cvvergara** [comment]
@devrimgunduz 
I changed branch master, soon to be 2.2.4
I suppose I fixed this issue, but I don't have Fedora,
Can you please try master branch so I can close with the certainty that was fixed.

**Comment by cvvergara** [comment]
Made the change in master, then its going for the next minor 2.2.4
