### ISSUE TITLE
assign_vertex_id function error with PostGIS 2.0

### ISSUE THREAD

**Issue by pdcc** [pgRouting/pgrouting#58]
Hello,

I'm trying to work with pg routing on postgis 2.0 and postgres 9.1.3, in windows 7 64 bits.
I'm loaded the binaries from here:

https://github.com/sanak/pgrouting/downloads

The pgrouting was succed installed but when i run the assign_vertex function i get this error:

ERROR:  find_srid() - couldnt find the corresponding SRID - is the geometry registered in the GEOMETRY_COLUMNS table?  Is there an uppercase/lowercase missmatch?
CONTEXT:  PL/pgSQL function "assign_vertex_id" line 17 at assignment

Anybody can help to fix that?If someone have an idea i can try....

**Comment by woodbri** [comment]
Closing - Wont fix.
