### ISSUE TITLE
How to build the pgrouting2.2.3 by the Microsoft's Visual Studio 2010 or later in the windows?

### ISSUE THREAD

**Issue by HongbiaoMiao** [pgRouting/pgrouting#583]
How to build the pgrouting2.2.3 by the Microsoft's Visual Studio 2010 or later in the windows? And can you tell me what third party libraries i needs and their version number？

Thanks！

**Comment by dkastl** [comment]
Would you mind to ask question on the mailing list or GIS Stackexchange?
You can find the links on this website: http://pgrouting.org/support.html

The Github issue tracker is used for development and reporting bugs for example. In general not many pgRouting users will read issues.

Regarding your question: why don't you use Windows binaries from PostGIS, that also contains pgRouting? http://postgis.net/windows_downloads/
