### ISSUE TITLE
ST_startpoint and geometry type with PostGIS may return "null"

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#59]
Check geometry type for "LINESTRING"/"MULTILINESTRING" as ST_startpoint might not work anymore with PostGIS 2.0: 

> Changed: 2.0.0 no longer works with single geometry multilinestrings. In older versions of PostGIS -- a single line multilinestring would work happily with this function and return the start point. In 2.0.0 it just returns NULL like any other multilinestring. The older behavior was an undocumented feature, but people who assumed they had their data stored as LINESTRING may experience these returning NULL in 2.0 now.

**Comment by woodbri** [comment]
Closing - Wont Fix.
