### ISSUE TITLE
updating to latest stable 

### ISSUE THREAD

**Issue by Revo86** [pgRouting/pgrouting#591]
What am I supposed to do, if I want to update from 2.0.0 to 2.2.0? (I hope this is the correct place to ask this question)

I tried 

```
psql -d routing_test

ALTER EXTENSION pgrouting UPDATE TO "2.2.0";
```

and error is the following:
`ERROR:  extension "pgrouting" has no update path from version "2.0.0" to version "2.2.0"`

**Comment by woodbri** [comment]
On 6/9/2016 5:38 AM, Revo86 wrote:
> What am I supposed to do, if I want to update from 2.0.0 to 2.2.0? (I
> hope this is the correct place to ask this question)
>
> I tried |psql -d routing_test
> ALTER EXTENSION pgrouting UPDATE TO "2.2.0";|
>
> and error is the following:
> |ERROR: extension "pgrouting" has no update path from version "2.0.0" to
> version "2.2.0"|

It should be safe to do the following:

drop extension pgrouting;
create extension pgrouting;



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by cvvergara** [comment]
the latest is 2.2.3

On Fri, Jun 10, 2016 at 9:08 AM, Stephen Woodbridge <
notifications@github.com> wrote:

> On 6/9/2016 5:38 AM, Revo86 wrote:
> > What am I supposed to do, if I want to update from 2.0.0 to 2.2.0? (I
> > hope this is the correct place to ask this question)
> >
> > I tried |psql -d routing_test
> > ALTER EXTENSION pgrouting UPDATE TO "2.2.0";|
> >
> > and error is the following:
> > |ERROR: extension "pgrouting" has no update path from version "2.0.0" to
> > version "2.2.0"|
>
> It should be safe to do the following:
>
> drop extension pgrouting;
> create extension pgrouting;
>
>
>
> ---
> This email has been checked for viruses by Avast antivirus software.
> https://www.avast.com/antivirus
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pgRouting/pgrouting/issues/591#issuecomment-225191647>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEzVGtFqzyq9-jIEGkzdiiqTF8SbXwsKks5qKW_MgaJpZM4IxyuH>
> .
>



-- 

Georepublic UG (haftungsbeschränkt)
Salzmannstraße 44,
81739 München, Germany

Vicky Vergara
Operations Research

eMail: vicky@georepublic.de
Web: https://georepublic.info

Tel: +49 (089) 4161 7698-1
Fax: +49 (089) 4161 7698-9

Commercial register: Amtsgericht München, HRB 181428
CEO: Daniel Kastl

**Comment by dkastl** [comment]
@woodbri @cvvergara the PostgreSQL documentation says:

```
UPDATE
    This form updates the extension to a newer version. The extension must supply a suitable 
    update script (or series of scripts) that can modify the currently-installed version into the 
    requested version.
```

So if we would provide a script, that drops pgRouting extension and creates it again, the `UPDATE` extension command would work, right?
Do you know, where to place such a script? Not a good idea?

**Comment by woodbri** [comment]
The update script is not a drop/create script. This is just a workaround for the problem to get the user going again.

The scripts need to be like the postgis scripts. See: ``ls /usr/share/postgresql/9.4/extension/postgis--*`` but ours will be a lot simpler and smaller because we have less functions.

**Comment by cvvergara** [comment]
I could replicate the error
```
doc_dat_20=# select * from pgr_version();
 version |       tag       | build |  hash   | branch | boost  
---------+-----------------+-------+---------+--------+--------
 2.0.0   | pgrouting-2.0.1 | 5     | 40ad51f | master | 1.54.0
(1 row)

doc_dat_20=# ALTER EXTENSION pgrouting UPDATE TO "2.2.3";
ERROR:  cannot change return type of existing function
DETAIL:  Row type defined by OUT parameters is different.
HINT:  Use DROP FUNCTION pgr_version() first.
doc_dat_20=# DROP FUNCTION pgr_version();
ERROR:  cannot drop function pgr_version() because extension pgrouting requires it
HINT:  You can drop extension pgrouting instead.
```

Then I went to inspect the signature files
https://github.com/pgRouting/pgrouting/blob/master/tools/sigs/pgrouting--2.0.0.sig#L36
https://github.com/pgRouting/pgrouting/blob/master/tools/sigs/pgrouting--2.0.1.sig#L36
and pgr_version() is missing

I remember that there was a bug in the https://github.com/pgRouting/pgrouting/blob/master/tools/mk-signature-file
But the pgrouting-2.0.0.sql and pgrouting-2.0.1.sql where never regenerated.

By adding the missing lines:
```
doc_dat_20=# ALTER EXTENSION pgrouting UPDATE TO "2.3.0";
ALTER EXTENSION
doc_dat_20=# 
```
It will fix the problem.
but, 2.0.0 and 2.0.1 will never be able to be upgraded to

* 2.1.0
* 2.2.0
* 2.2.1
* 2.2.2
* 2.2.3

I think a 2.2.4 will be necessary so that 2.0.0 and 2.0.1 be upgradable

**Comment by dkastl** [comment]
> I think a 2.2.4 will be necessary so that 2.0.0 and 2.0.1 be upgradable
But let's not just make a release for this issue only.
It's pretty easy to first DROP and then CREATE the extension again.
