### ISSUE TITLE
What is file "#.gitignore#" for?

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#594]
In the following commit a new file `#.gitignore#` made it into the repository.
https://github.com/pgRouting/pgrouting/commit/18c6058ac07cbe7fa956249e7725f4e31ab024b0

@robe2 was this a mistake, or does this file have any purpose?

**Comment by woodbri** [comment]
.gitignore allows you to ignore files in the src tree so git status and and other git commands ignore those. This is helpful to ignore things like MacOS specific cruft or a build directory that should never get committed to the repository.

**Comment by dkastl** [comment]
@woodbri yes, I know that. I probably even created it many years ago.
There is another file that starts and ends with `#`. Have you seen it?
It looks like accidentally copied.

**Comment by robe2** [comment]
You can delete it.  When I am in the middle of an edit my editor renamed the file #.whateverfilename#

So I must have hit commit at an inopportune time.

**Comment by dkastl** [comment]
I see. I just didn't want to delete something, that maybe Winnie needs ;-)
