### ISSUE TITLE
Cast Issue in dijkstra_sp_delta_directed function

### ISSUE THREAD

**Issue by Pinpin31** [pgRouting/pgrouting#60]
I have got a cast issue in dijkstra_sp_delta_directed function :

    2012-06-19 18:14:34 CEST STATEMENT:  SELECT gid, the_geom FROM dijkstra_sp_delta( 'routes', $1, $2, $3 )
    2012-06-19 18:14:39 CEST ERROR:  type of parameter 33 (numeric) does not match that when preparing the plan (integer)
    2012-06-19 18:14:39 CEST CONTEXT:  PL/pgSQL function "dijkstra_sp_delta_directed" line 83 at assignment
        PL/pgSQL function "dijkstra_sp_delta" line 19 at FOR over EXECUTE statement

This error occurs when a number with no decimal is used in the function line 83 :

    FOR rec IN EXECUTE 'SELECT CASE WHEN '||source_x||'<'||target_x||
           ' THEN '||source_x||' ELSE '||target_x||
           ' END as ll_x, CASE WHEN '||source_x||'>'||target_x||
           ' THEN '||source_x||' ELSE '||target_x||' END as ur_x'
        LOOP
	END LOOP;

I think that source_x or target_x is considered as integer instead of numeric when values are concatenated.
Same error occurs line 92.

Versions :
"PostgreSQL 9.1.4 on i686-pc-linux-gnu, compiled by gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3, 32-bit"
Postgis "1.5 USE_GEOS=1 USE_PROJ=1 USE_STATS=1"
PgRouting 1.0.5

I resolve the problem with this modification in dijkstra_sp_delta_directed function :

       # Cast in Float to prevent plan error in PostgreSQL
	FOR rec IN EXECUTE 'SELECT CASE WHEN CAST('||source_x||' as float8)< CAST('||target_x||
           ' as float8) THEN CAST('||source_x||' as float8) ELSE CAST('||target_x||
           ' as float8) END as ll_x, CASE WHEN CAST('||source_x||' as float8)>CAST('||target_x||
           '  as float8) THEN CAST('||source_x||' as float8) ELSE CAST('||target_x||' as float8) END as ur_x'
        LOOP
	END LOOP;

	ll_x := rec.ll_x;
	ur_x := rec.ur_x;

        # Cast in Float to prevent plan error in PostgreSQL
	FOR rec IN EXECUTE 'SELECT CASE WHEN CAST('||source_y||' as float8)<CAST('||
            target_y||' as float8) THEN CAST('||source_y||' as float8) ELSE CAST('||
            target_y||' as float8) END as ll_y, CASE WHEN CAST('||
            source_y||' as float8)>CAST('||target_y||' as float8) THEN CAST('||
            source_y||' as float8) ELSE CAST('||target_y||' as float8) END as ur_y'
        LOOP
	END LOOP;

**Comment by woodbri** [comment]
Closing - Wont fix.
