### ISSUE TITLE
Index in the documentation

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#601]
### Actual Index:
For example:
http://docs.pgrouting.org/2.2/en/genindex.html#D
Has for Dijkstra:
```
dijkstra(edges_sql, start_vid, end_vid)
dijkstra(edges_sql, start_vid, end_vid, directed:=TRUE)
dijkstra(edges_sql, start_vid, end_vids, directed:=TRUE)
dijkstra(edges_sql, start_vids, end_vid, directed)
dijkstra(edges_sql, start_vids, end_vids, directed)
dijkstra(sql, source, target, directed, has_rcost) -- deprecated 
```
### What if...  Index:

- Not even mention in the index the deprecated signature.
- And use "One to One" etc (when applicable)
- Have an entry to the general Information of the function (when applicable).

```
dijkstra(General Information)
dijkstra(Minimal Use)
dijkstra(One to One)
dijkstra(One to Many)
dijkstra(Many to One)
dijkstra(Many to Many)
```

**Comment by cvvergara** [comment]
Thumbs up or Down for:

- Not even mention in the index the deprecated signature.

**Comment by cvvergara** [comment]
Thumbs up or down for:

- Use "One to One" etc (when applicable)

**Comment by cvvergara** [comment]
Thumbs up or down for:

- Have an entry to the general Information of the function (when applicable).

**Comment by woodbri** [comment]
I think all of these are excellent ideas. I really like the idea of presenting the functionality it is often very hard to understand the functionality by reading the signatures and this will make it easier for people to fiind the commands they need.

**Comment by cvvergara** [comment]
http://docs.pgrouting.org/dev/en/genindex.html
