### ISSUE TITLE
Proposed functions for 2.3

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#609]
There are these proposed functions in section *proposed functions for 2.3*
http://docs.pgrouting.org/2.2/en/src/proposedNext.html#proposednext
Are they going to be officially included on version 2.3?

**Comment by woodbri** [comment]
I think proposed functions should be proposed for the next major release not for a point release. So in this case all proposed function should be for 3.0 not 2.3 or 2.4, etc. There is no reason to make a commitment for when we will officially release new functionality. We can always release something sooner if we decide it needs to be.

Also the main purpose for the 2.x series of releases was to improve our infrastructure and to fix the existing code to work correctly. I think 3.x will be able new functionality. the proposed functions are giving people a preview of the new functions we will be adding.

**Comment by cvvergara** [comment]
So, I shall rename the section instead of:
```
Proposed Functions for version 2.3
```
to be
```
Proposed Functions for next major version 3.0
```
And keep proposed Functions that most likely:
* Name might not change.
* Signature might not change.
* Functionality might not change.
* pgTap tests have being done.
* Documentation is complete.
In that section?

**Comment by cvvergara** [comment]
In the main index can I do this:

pgr_tsp - Traveling Sales Person
  - pre-processing:
  pgr_dijkstraCostMatrix - proposed
  pgr_withPointsCostMatrix - proposed

Or,
In the documentation of tsp, is where I mention the proposed functions

**Comment by woodbri** [comment]
Please make a demo of documentation with changes for review.

**Comment by dkastl** [comment]
I would just name it "Proposed Functions", so we decided, when they should be made "official".

I also don't think, that we need to wait for a new major release too long.
There are already so many changes and new things, that we could get rid of some old stuff, that we carry with us and make 2.3 the last release of the 2.x series.

**Comment by woodbri** [comment]
We need to do a 3.0 release!

**Comment by woodbri** [comment]
I think we should consider doing 3.0 release instead of a 2.4 with the release containing:

- turn restrictions
- all the proposed functions
- probably need to also add restrictions to osm2pgrouting
- some other stuff I'm forgetting

The turn restrictions piece is big effort and I think it if key to pgRouting defending its position as general routing solution. I will work with Vicky on looking into the turn restriction issues.

**Comment by cvvergara** [comment]
Then, if that is the case for 2.3:

 I would like to include the code for:
- flow algorithms (the one to one version) 
- the contraction function

as part of the "proposed".
So that we can start getting feedback from the community.

**Comment by dkastl** [comment]
Sounds good to me. 2.3 could be some sort of "preview release", and then for 3.0 we can introduce new functions and get rid of deprecated things.

**Comment by cvvergara** [comment]
@Illedran @sankepallyrohithreddy 
How much time do you feel you get your code ready for the 2.3 release?
code freeze: (no more functionality is added)
July 15, 2016

Documentation fixes: (bugs might also be fixed)
July 15 to July 30

Alpha release:
Agust 1st

Release:
is for September 1st.

**Comment by sankepallyrohithreddy** [comment]
I finished coding the framework.
Current work : Adjusting the pgtap tests to the latest signature. 
Next week : User documentation
Later I would like to test the contraction and expansion on OSM data.

**Comment by cvvergara** [comment]
Ok, so lets meet on Wednesday so I can start a preview merge for testing on jenkins and appveyor

**Comment by cvvergara** [comment]
@woodbri 
Develop documentation current structure.
http://docs.pgrouting.org/dev/en/doc/index.html
