### ISSUE TITLE
Add AppVeyor badge

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#624]
Similar to Travis CI there is also a badge available  for AppVeyor, that can be added to the `README`, so we can visualize the build status.
https://ci.appveyor.com/project/Georepublic/pgrouting/settings/badges

Maybe good to use this opportunity to reorganize and cleanup the badges a bit.

**Comment by cvvergara** [comment]
like this ones?
https://github.com/pgRouting/pgrouting/tree/test/appveyor

**Comment by dkastl** [comment]
Yes, like this one! :-)
Thanks!
