### ISSUE TITLE
FSF address is wrong

### ISSUE THREAD

**Issue by volter** [pgRouting/pgrouting#63]
Please update the FSF's postal address in COPYING and various other files. See http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt

**Comment by cvvergara** [comment]
@dkastl @woodbri 
Not all the files have licences. like:
https://github.com/pgRouting/pgrouting/blob/develop/src/vrp_basic/src/VRP.h
How do I proceed?

**Comment by cvvergara** [comment]
Added a licence to the vrp Gsoc code, with the name of the students
