### ISSUE TITLE
I am receiving the error listed in issue #210 in pgrouting 2.0.1, although it is supposed to be fixed?

### ISSUE THREAD

**Issue by SurfaceThought** [pgRouting/pgrouting#652]
As said, I am running into the exact same issue as enumerated in issue #210. 

I get "ERROR: Condition is not correct, please execute the following query to test your condition" when trying to run pgr_createtopology, although the query:

select * from streets.walknetwork WHERE true AND (true) limit 1;

Runs without issue. It appears to me from issue #210 that this was an issue with 2.0.0 that was supposed to be fixed for 2.0.1. Am I incorrect about that?

I am running Fedora 24, postgres 9.5.3, postgis 2.2.1. The reason I am not using the most recent version of pgrouting is because it is currently broken in Fedora 24.

Thanks for any help!

**Comment by cvvergara** [comment]
Latest release is 2.2.3
branch develop-2_0_1 was never released
but probably got fixed on 2.1.0
Sorry to hear that about fedora, but I don't know how to make tests on fedora, I don't have a fedora.
So I try to make things work for trusty and precise, also for the packager on windows, and recently I am making tests for vs2013. (So, if it works for fedora is just by chance)
Soon I will be making a release 2.3.0, based on develop (but right now lots of changes are going on)
if you can build pgRouting from develop on your fedora and see if its not broken it would be nice.

**Comment by SurfaceThought** [comment]
Thank you,

Unfortunately, I am only a GIS analyst and not really a Computer Science guy. I don't really know the first thing about compiling software.

I did try to build 2.3.0, but I got an error that it couldn't find the postgres bin... I imagine because it is stored in a different place in the directory than it is stored in Debian...

**Comment by SurfaceThought** [comment]
Closing issue as 2.2 is now working on Fedora 24.
