### ISSUE TITLE
Bogus uses of extern "C"

### ISSUE THREAD

**Issue by jwakely** [pgRouting/pgrouting#653]
Several headers have broken C++ code of the form:

    #ifdef __cplusplus
    extern "C"
    #endif
    void some_function();
    #ifdef __cplusplus
    extern "C"
    #endif

The second occurrence of `extern "C"` does not close the block, it just means that whatever happens to come after that header is included gets unintentionally given "C" language linkage.

It should be:

    #ifdef __cplusplus
    extern "C" {
    #endif
    void some_function();
    #ifdef __cplusplus
    }
    #endif

Also, several files use `extern C" { ... }` around the `#include` for `pgr_types.h` which is (1) odd, why not just put it in the header itself? (2) inconsistent, because some files don't do it, (3) unnecessary because that header only defines types not functions, so the language linkage is irrelevant. That isn't actually a bug, just poor style.

**Comment by cvvergara** [comment]
I will leave this open until I check on develop

**Comment by cvvergara** [comment]
### TODO in develop

Review all code (old & new) to fix this issue(s) in develop.

### Task 1
- [ ] check `extern` in  *_driver.h files.
  - [ ] allpairs     
  - [ ] alpha_shape  
  - [ ] apsp_warshall  
  - [ ] apsp_johnson   
  - [ ] astar     
  - [ ] bd_astar  
  - [ ] bd_dijkstra     
  - [ ] common       
  - [ ] convenience  
  - [ ] contraction  
  - [ ] costMatrix   
  - [ ] dijkstra          
  - [ ] driving_distance  
  - [ ] internalQueryTests  
  - [ ] ksp        
  - [ ] kdijkstra  
  - [ ] label_graph  
  - [ ] linecommand   
  - [ ] pickDeliver      
  - [ ] topology  
  - [ ] tsp        
  - [ ] trsp      
  - [ ] vrp_basic  
  - [ ] vrppdtw           
  - [ ] withPoints
### Task 2
- [ ] eliminate `extern` when including pgr_types.h
  - [ ] allpairs     
  - [ ] alpha_shape  
  - [ ] apsp_warshall  
  - [ ] apsp_johnson   
  - [ ] astar     
  - [ ] bd_astar  
  - [ ] bd_dijkstra     
  - [ ] common       
  - [ ] convenience  
  - [ ] contraction  
  - [ ] costMatrix   
  - [ ] dijkstra          
  - [ ] driving_distance  
  - [ ] internalQueryTests  
  - [ ] ksp        
  - [ ] kdijkstra  
  - [ ] label_graph  
  - [ ] linecommand   
  - [ ] pickDeliver      
  - [ ] topology  
  - [ ] tsp        
  - [ ] trsp      
  - [ ] vrp_basic  
  - [ ] vrppdtw           
  - [ ] withPoints

**Comment by cvvergara** [comment]
Merged the fixes to develop.
