### ISSUE TITLE
error trying to build 2.2.3 from vrp_basic

### ISSUE THREAD

**Issue by saultdon** [pgRouting/pgrouting#662]
### Steps to reproduce the problem
On linux, I run
```
cmake -L ../

make
```

and the output error is:
```
Scanning dependencies of target vrp_basic
[ 95%] Building C object src/vrp_basic/src/CMakeFiles/vrp_basic.dir/VRP.c.o
[ 96%] Building CXX object src/vrp_basic/src/CMakeFiles/vrp_basic.dir/VRP_core.cpp.o
[ 98%] Building CXX object src/vrp_basic/src/CMakeFiles/vrp_basic.dir/VRP_Solver.cpp.o
/tmp/makepkg/pgrouting/src/pgrouting-2.2.3/src/vrp_basic/src/VRP_Solver.cpp: In member function ‘bool CVRPSolver::updateTourCosts(CTourInfo&)’:
/tmp/makepkg/pgrouting/src/pgrouting-2.2.3/src/vrp_basic/src/VRP_Solver.cpp:760:59: error: ‘ceil’ was not declared in this scope
  vecStartTimes.push_back(static_cast<int>(ceil(dTravelTime)));
                                                           ^
make[2]: *** [src/vrp_basic/src/CMakeFiles/vrp_basic.dir/build.make:111: src/vrp_basic/src/CMakeFiles/vrp_basic.dir/VRP_Solver.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:920: src/vrp_basic/src/CMakeFiles/vrp_basic.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
```

I have the following installed:
PostgreSQL - 9.5.3
PostGIS - 2.2.2

**Comment by cvvergara** [comment]
@saultdon 
I just pushed what I think is going to be a new micro version on master that I think fixes that problem.
Can you download again "master" and try it again?

**Comment by saultdon** [comment]
Works great. Thanks for the prompt fix!

I'll update the package for Arch Linux.

**Comment by dkastl** [comment]
@saultdon it would be nice to add a notice and link to the manual, where the packages are available.
I think this is the best page in the manual: https://github.com/pgRouting/pgrouting/blob/master/doc/src/installation/installation.rst
For us it would be best, if the person in charge also keeps the information updated, so if you can make the changes and submit a pull request, this would be great.
