### ISSUE TITLE
Error, columns 'source', 'target' must be of type int4, 'cost' must be of type float8

### ISSUE THREAD

**Issue by adantart** [pgRouting/pgrouting#677]
I followed [this](https://blog.openshift.com/add-map-navigation-to-your-app-with-pgrouting-on-openshift/) tutorial about 6 months ago and it worked well.
Now, following from scratch, I think versions have changed and have some problem.

The thing is when I try to do this:

pgrouting=# SELECT seq, id1 AS node, id2 AS edge, cost FROM pgr_dijkstra('
pgrouting'#     SELECT gid AS id, source::integer, target::integer, length::double precision AS cost FROM ways',
pgrouting(#                 747, 311, false, false);

it responses:

NOTICE:  Deprecated function
ERROR:  Error, columns 'source', 'target' must be of type int4, 'cost' must be of type float8
CONTEXT:  PL/pgSQL function pgr_dijkstra(text,integer,integer,boolean,boolean) line 7 at assignment

I don't have big knowledge about pgrouting ... so I'm a little bit lost ;-)

thank you !

```
pgrouting-workshop=# SELECT version();
 PostgreSQL 9.5.4 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609, 64-bit

pgrouting-workshop=# SELECT postgis_full_version();
 POSTGIS="2.2.1 r14555" GEOS="3.5.0-CAPI-1.9.0 r4084" PROJ="Rel. 4.9.2, 08 September 2015" GDAL="GDAL 1.11.3, released 2015/09/16" LIBXML="2.9.3" LIBJSON="0.11.99" RASTER

pgrouting-workshop=# SELECT pgr_version();
 (2.2.3,pgrouting-2.2.3,6d05b9b,master,1.58.0)
```

**Comment by cvvergara** [comment]
Probably the tutorial yo are mentioning was for version 2.0:
As you are reading a tutorial that is not for the latest version, I suggest you have at hand the latest [documentation](http://docs.pgrouting.org) for the version your are using.


version 2.0 had a bug about not checking the type of `id` that is to be integer (your gid is not integer)
try this one.
```
SELECT seq, id1 AS node, id2 AS edge, cost FROM pgr_dijkstra('
SELECT gid::integer AS id, source::integer, target::integer, length::double precision AS cost FROM ways',
 747, 311, false, false);
```

Starting from Version 2.1 you can do this with pgr_dijkstra
```
SELECT * FROM pgr_dijkstra('
SELECT gid AS id, source, target, length AS cost FROM ways',
 747, 311, false);
```

I also suggest that you start with the [workshop](http://workshop.pgrouting.org/),  its not exactly a tutorial, but its from the official pgRouting team. 

If you have problem with the workshop, use this issues: https://github.com/pgRouting/workshop/issues
right now the latest version of the workshop is under development, (the one for FOSS4G Bonn event).

We can not fix non official pgRouting tutorials.

**Comment by adantart** [comment]
Yeah, it's working !!!  
Anyway I found an installation of 9.1 psql and 2.0 pgrouting just to workaround ...
But I document this if I need to upgrade in the future (I'll do ;-)
THANK you again !
