### ISSUE TITLE
Random direction of routing

### ISSUE THREAD

**Issue by adantart** [pgRouting/pgrouting#678]
I create a query to make a routing but I get random direction in each section.
I have data exported from OSM directly (with osm2pgrouting)
I have for example:

With these 2 queries I get the id's of the points:
```
$node_from :  select id from ways_vertices_pgr order by st_distance(the_geom, st_setsrid(st_makepoint($lng1, $lat1), 4326)) limit 1;
$node_to :  select id from ways_vertices_pgr order by st_distance(the_geom, st_setsrid(st_makepoint($lng2, $lat2), 4326)) limit 1;
```

Then I do the big select:
`SELECT y2, x2, y1, x1, name, length FROM ways JOIN (SELECT seq, id1 AS node, id2 AS edge_id, cost FROM pgr_dijkstra('SELECT gid AS id, source::integer, target::integer, length::double precision AS cost FROM ways', $node_from, $node_to, false, false) )  AS route ON ways.gid = route.edge_id  ORDER BY seq;`

When I have the route and put each marker in a map animated, some sections are OK, but others the "man" walked backwards.

I have checked the output and it's really the output ... some sections are "backwards" direction :-(
And I don't know any rule to know which one are backwards.

You can check it in this video: http://imgur.com/a/XVHHW
The big orange street (I mark it with the mouse) and some other small streets are in the right direction, but other sections have the information backwards, so it seems it's jumping and coming back ;-)

Any ideas ?
Thank you !

**Comment by woodbri** [comment]
On 8/23/2016 8:42 AM, Alex wrote:
> I create a query to make a routing but I get random direction in each
> section.
> I have data exported from OSM directly (with osm2pgrouting)
> I have for example:
>
> With these 2 queries I get the id's of the points:
>
> |$node_from : select id from ways_vertices_pgr order by
> st_distance(the_geom, st_setsrid(st_makepoint($lng1, $lat1), 4326))
> limit 1; $node_to : select id from ways_vertices_pgr order by
> st_distance(the_geom, st_setsrid(st_makepoint($lng2, $lat2), 4326))
> limit 1; |
>
> Then I do the big select:
> SELECT y2, x2, y1, x1, name, length FROM ways JOIN (SELECT seq, id1 AS
> node, id2 AS edge_id, cost FROM pgr_dijkstra('SELECT gid AS id,
> source::integer, target::integer, length::double precision AS cost FROM
> ways', $node_from, $node_to, false, false) ) AS route ON ways.gid =
> route.edge_id ORDER BY seq;
>
> When I have the route and put each marker in a map animated, some
> sections are OK, but others the "man" walked backwards.
>
> I have checked the output and it's really the output ... some sections
> are "backwards" direction :-(
> And I don't know any rule to know which one are backwards.
>
> Any ideas ?
> Thank you !

pgRouting only returns the list of edge ids, for any given route, some 
of the edges might have been traveled in the reverse direction. You need 
to check which direction you are traveling along any give edge and may 
be reverse the edge before animating it.

-Steve


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by adantart** [comment]
Thank you @woodbri  ... any ideas how to do that ?
maybe comparing "bearing" of the street with bearing of the total route ?

**Comment by woodbri** [comment]
On 8/23/2016 9:55 AM, Alex wrote:
> Thank you @woodbri <https://github.com/woodbri> ... any ideas how to do
> that ?
> maybe comparing "bearing" of the street with bearing of the total route ?
>
The results give something like seq|nodeid|edgeid|cost

So you should be able to do something like:

select a.*, case when nodeid != b.source then st_reverse(geom) else geom 
end as geom
   from pgr_dijkstra(...) a, edges b
  where b.id=a.edgeid;

So if the nodeid == source then the geom is ok and if it is not then it 
must be equal to the target so reverse the geometry.

Anyway that is the idea, you'll have to adjust it to your queries and 
tables.

-Steve

---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by adantart** [comment]
I don't have that "edge" relation ... :-(

```
pgrouting-workshop=# SELECT a.* FROM pgr_dijkstra('SELECT gid AS id, source::integer, target::integer, length::double precision AS cost FROM ways', 1590, 6347, false, false) a, edge b where b.id=a.edgeid;
ERROR:  relation "edge" does not exist
```

**Comment by woodbri** [comment]
On 8/23/2016 12:07 PM, Alex wrote:
> I don't have that "edge" relation ... :-(
>
> |pgrouting-workshop=# SELECT a.* FROM pgr_dijkstra('SELECT gid AS id,
> source::integer, target::integer, length::double precision AS cost FROM
> ways', 1590, 6347, false, false) a, edge b where b.id=a.edgeid; ERROR:
> relation "edge" does not exist |

As mentioned you need to adjust this to your tables and queries. Your 
ways table is the edge table I referenced and a.edgeid is whatever the 
column name for the edge id is in the pgr_* results, etc.


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by cvvergara** [comment]
@adantart 
You are using not the latest version of pgRouting.
- the version you are using returns seq, id1, id2, cost
- if you want to flip the geometries there is this [howto](http://talks.vicky.georepublic.info/howto/flipGeometries.html#/) but it is based on the latest version of pgRouting. 

I remember you are following a tutorial for an older version #677 
So, this #issuecomment-241785688 happens because @woodbri is giving you suggestions based on a more recent version of pgRouting.

**Comment by adantart** [comment]
Thank you @cvvergara 
I've updated everything:

```
pgrouting-workshop=# SELECT version();
                                                     version                                                     
-----------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.5.4 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609, 64-bit
(1 row)

pgrouting-workshop=# SELECT postgis_full_version();
                                                                           postgis_full_version                                                                            
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 POSTGIS="2.2.1 r14555" GEOS="3.5.0-CAPI-1.9.0 r4084" PROJ="Rel. 4.9.2, 08 September 2015" GDAL="GDAL 1.11.3, released 2015/09/16" LIBXML="2.9.3" LIBJSON="0.11.99" RASTER
(1 row)

pgrouting-workshop=# SELECT pgr_version();
                  pgr_version                  
-----------------------------------------------
 (2.2.3,pgrouting-2.2.3,6d05b9b,master,1.58.0)
(1 row)

```

But sincerely, I'm a little lost with the OSM data and I don't know how to apply what @woodbri suggested me to my query.

I have now this query working:

```
SELECT y2, x2, y1, x1, name, length, seq
	FROM ways 
	JOIN (
		SELECT seq, id1 AS node, id2 AS edge_id, cost FROM pgr_dijkstra('SELECT gid::integer AS id, source::integer, target::integer, length::double precision AS cost, reverse_cost FROM ways', 3245, 193, false, false)
	) AS route ON ways.gid = route.edge_id
ORDER BY seq;
```

I will **appreciate** a lot any help ...

THANK YOU !

**Comment by cvvergara** [comment]
@adantart 
try our [workshop](http://workshop.pgrouting.org/2.1.0-dev/en/index.html), it uses OSM data (and has an example about getting the flipped geometries)

about the query, with the 2.2 version, you dont need to write the type, and also you dont need the second false

```
SELECT y2, x2, y1, x1, name, length, seq
    FROM ways 
    JOIN (
        SELECT * FROM pgr_dijkstra('SELECT gid AS id, source, target, length AS cost, reverse_cost FROM ways', 3245, 193, false) 
    ) AS route ON ways.gid = route.edge_id
ORDER BY seq;
```

Glad to be of help.
(please close)

**Comment by adantart** [comment]
Ok, thank you, I did it !
