### ISSUE TITLE
1.05 compile error with boost-1.51 on OSX in boost_wrapper.cpp

### ISSUE THREAD

**Issue by 2bits** [pgRouting/pgrouting#68]
Hey now, trying to build pgrouting-1.05 on OSX 10.8 [for Homebrew][1].

I get a build error compiling with either clang or llvm-gcc, where I guess boost changed its API.  I am trying to compile against boost-1.51. 

```
In file included from /tmp/pgrouting-9esZ/pgrouting-1.05/core/src/boost_wrapper.cpp:25:
In file included from /usr/local/include/boost/graph/adjacency_list.hpp:245:
/usr/local/include/boost/graph/detail/adjacency_list.hpp:2652:56: error: no type named 'type' in 'boost::property_value<Vertex, boost::edge_weight_t>'
        typedef typename property_value<Property,Tag>::type value_type;
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
```
Before configure, I apply four of the recent patches you've committed:

https://github.com/pgRouting/pgrouting/commit/8574864fcce8f37acabe40b985b36c6c3e8c7bdd.patch
https://github.com/pgRouting/pgrouting/commit/27e5ccd4da4f8ddd2b7b59c5a10e03d93eeb766b.patch
https://github.com/pgRouting/pgrouting/commit/dc6bff6b6923a565986eb4e314351299dc101f9a.patch
https://github.com/pgRouting/pgrouting/commit/1be144ec4cc11f9748eca881a44668a4bdf3343b.patch

The [full build log is here][2]
My [CMakeCache.txt is here][3]
And [my system config is here][4]

I'd offer a patch, but I'm not up to it. So thanks for any ideas.

[1]: https://github.com/mxcl/homebrew
[2]: https://gist.github.com/3807281
[3]: https://gist.github.com/3807484
[4]: https://gist.github.com/3807500

**Comment by woodbri** [comment]
Closing - Wont fix.
