### ISSUE TITLE
Tag: Stale & GSoC branches

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#680]
From the [tag documentation](https://git-scm.com/book/en/v2/Git-Basics-Tagging)
there is a [Light weight tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging#Lightweight-Tags)

> This is basically the commit checksum stored in a file – no other information is kept.

These branches would not be deleted because the link was sent recently to the gsoc program:
- [x] gsoc-flow    -----tag & dont delete branch ---->   gsoc/flow-lw
- [x] gsoc-ch    -----tag & dont delete branch ---->   gsoc/contraction-lw

Besides tag also delete the branches. if needed a checkout from the tag can be done.  
- [x]  gsoc-vrppdtw    -----tag---->   gsoc/vrppdtw-lw
- [x] gsoc-cvrptw    -----tag---->   gsoc/cvrptw-lw
- [x] gsoc-vrp    -----tag---->    gsoc/vrp-lw
- [x] gsoc-partition    -----tag---->    gsoc/partition-lw
- [x] gsoc-two_q    -----tag---->    gsoc/two_q-lw
- [x] gsoc-multimodal    -----tag---->   gsoc/multimodal-lw
- [x] gsoc-tdsp    -----tag---->   gsoc/tdsp-lw
- [x] darp3    -----tag---->   unstable/darp3-lw
- [x] darp    -----tag---->   unstable/darp-lw

- [x] wait a week before deleting branches
- [x] delete branches

This would leave only these branches:
master
gh-pages
develop 
release/2.3.0  -- (right now is alpha) once moved to master, can be used for the micro releases (if any), and when the next minor comes out it can be deleted
gsoc-ch     -- if accidentally modified the tag has the commit of the gsoc program code
gsoc-flow   -- if accidentally modified the tag has the commit of the gsoc program code

**Comment by woodbri** [comment]
I think that what I would do with all these branches is to create a new respository like http://github.com/pgrouting/gsoc-projects/ and then fork them into that to keep them around but not in the pgrouting repository then new gsoc projects can also go into that and this would keep the main pgrouting repository much cleaner. Another benefit of this is that all the gsoc wiki pages would go into that repository's wiki and not the pgrouting wiki.

**Comment by woodbri** [comment]
Here is the process to move the branches:
http://stackoverflow.com/questions/2227062/how-do-i-move-a-git-branch-out-into-its-own-repository

**Comment by cvvergara** [comment]
I prefer the tags. Can't change the name of the branch like I wanted with the "/" instead of the "-" but works form me 
```
git checkout gsoc-foo
git tag gsoc-foo-lw
git push --tags
git push origin --delete gsoc-foo
```
gsoc-foo  ---- tag ---> gsoc-foo-lw

**Comment by woodbri** [comment]
ok- works for  me.

**Comment by dkastl** [comment]
I also prefer the tags and keep them in the same repository. 
I would also like to move to some branch naming schema, following the one of "Git Flow": http://danielkummer.github.io/git-flow-cheatsheet/

When you run `git flow init`, it will ask you for naming preferences, with the following defaults:
```
$ git flow init
No branches exist yet. Base branches must be created now.
Branch name for production releases: [master] 
Branch name for "next release" development: [develop] 

How to name your supporting branch prefixes?
Feature branches? [feature/] 
Bugfix branches? [bugfix/] 
Release branches? [release/] 
Hotfix branches? [hotfix/] 
Support branches? [support/] 
Version tag prefix? []
```

Maybe we could add our custom "GSoC" branch with `[gsoc/]`.

**Comment by cvvergara** [comment]
Actually, In the main repository I want to keep the least branches possible.
`master`
`develop`
`release/< version >`  where to make the changes before merging into master.

As master, Has the latest release, any merge, push, change etc that modifies code and or documentation must me released, and that implies change version, change files, etc. I want master to be untouched. so that is why keep the release/< version >.

I use the The [branching model](http://nvie.com/posts/a-successful-git-branching-model/) ideas with the "/" in my fork, And use prefix I like. ;) 
https://github.com/cvvergara/pgrouting/branches/yours

Any way, I'll figure out how to make the tags (with "/")
gsoc-foo --- tag --> gsoc/foo-lw

**Comment by dkastl** [comment]
Yes, the least possible branches is also my goal.
I think there are only the `release/...` branches that may remain for a longer time (beside `master` and `develop`). Because these release branches are there to fix issues with previous releases.

`bugfix/` and similar branches should be removed, when the code has been merged and the issue has been resolved. In case of `feature/` branches they should be also merged and removed afterwards, but maybe there will remain some features, that don't make it into a release ... like the `darp` branch. I think it's OK to keep them, until they will be replaced someday with equivalent functionality maybe,

**Comment by cvvergara** [comment]
having like the:
darp ---tag--->  unstable/darp-lw
when time comes:
```
git checkout -b feature/darp unstable/darp
```
will create a working branch for `darp` from the tag

**Comment by cvvergara** [comment]
Created the tags
Tested on my fork's clone:
```
git fetch upstream 
```
```
From https://github.com/pgRouting/pgrouting
 * [new tag]         gsoc/contraction-lw -> gsoc/contraction-lw
 * [new tag]         gsoc/cvrptw-lw -> gsoc/cvrptw-lw
 * [new tag]         unstable/darp-lw -> unstable/darp-lw
 * [new tag]         unstable/darp3-lw -> unstable/darp3-lw
 * [new tag]         gsoc/flow-lw -> gsoc/flow-lw
 * [new tag]         gsoc/multimodal-lw -> gsoc/multimodal-lw
 * [new tag]         gsoc/multimodal-pure-scheduled-lw -> gsoc/multimodal-pure-scheduled-lw
 * [new tag]         gsoc/partition-lw -> gsoc/partition-lw
 * [new tag]         gsoc/tdsp-lw -> gsoc/tdsp-lw
 * [new tag]         gsoc/two_q-lw -> gsoc/two_q-lw
 * [new tag]         gsoc/vrp-lw -> gsoc/vrp-lw
 * [new tag]         gsoc/vrppdtw-lw -> gsoc/vrppdtw-lw
```
