### ISSUE TITLE
cmakelists hardwires optimization and debug flags

### ISSUE THREAD

**Issue by kyngchaos** [pgRouting/pgrouting#686]
Cmakelists hardwires -O2 and -g compilation flags.  This should be left to the standard Cmake option CMAKE_BUILD_TYPE.

**Comment by cvvergara** [comment]
@kyngchaos 
Unfortunately,  pgr_bdDijkstra has some problems when not compiled without optimization (planned to fix in 2.4) See here:
https://travis-ci.org/cvvergara/pgrouting/jobs/157331579#L1807
and I have it as a TODO
https://github.com/pgRouting/pgrouting/blob/master/CMakeLists.txt#L402

It will not be hard coded on 2.4
pgr_bdDijkstra will be rewriten as its not the only bug it has.

**Comment by cvvergara** [comment]
pull request on develop #705 does fixes this problem.
pgr_bdDijkstra has being rewritten
