### ISSUE TITLE
Build error on RHEL 6, pgRouting 2.3.0

### ISSUE THREAD

**Issue by devrimgunduz** [pgRouting/pgrouting#687]
Hi,

I'm getting the errors below while building pgrouting 2.3.0 on RHEL 6. This is against postgis 2.3.0, with gcc 4.4.7 , boost 1.41:

`[  6%] Building CXX object src/withPoints/src/CMakeFiles/withPoints.dir/pgr_withPoints.cpp.o
cd pgrouting-pgrouting-2.3.0/build/src/withPoints/src && /usr/lib64/ccache/c++    -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -std=c++0x -frounding-math -fPIC  -O3 -DNDEBUG -I/usr/pgsql-9.6/include/server -Ipgrouting-pgrouting-2.3.0/src/common/src -Ipgrouting-pgrouting-2.3.0/src/dijkstra/src    -o CMakeFiles/withPoints.dir/pgr_withPoints.cpp.o -c pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp
In file included from pgrouting-pgrouting-2.3.0/src/withPoints/src/./pgr_withPoints.hpp:34,
                 from pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:44:
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp: In function 'size_t collapse_paths(General_path_element_t**, const std::deque<Path, std::allocator<Path> >&)':
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp:125: error: expected initializer before ':' token
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp:129: error: expected primary-expression before 'return'
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp:129: error: expected ';' before 'return'
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp:129: error: expected primary-expression before 'return'
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp:129: error: expected ')' before 'return'
In file included from pgrouting-pgrouting-2.3.0/src/withPoints/src/./pgr_withPoints.hpp:34,
                 from pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:44:
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp: In function 'void equi_cost(std::deque<Path, std::allocator<Path> >&)':
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp:151: error: expected primary-expression before '[' token
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp:151: error: expected primary-expression before ']' token
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp:151: error: expected primary-expression before 'const'
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp:151: error: expected primary-expression before 'const'
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp:151: error: expected unqualified-id before 'bool'
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp:156: error: expected initializer before ':' token
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp:203: error: expected primary-expression at end of input
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp:203: error: expected ';' at end of input
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp:203: error: expected primary-expression at end of input
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp:203: error: expected ')' at end of input
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp:203: error: expected statement at end of input
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp:203: error: expected '}' at end of input
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp: In function 'size_t count_tuples(const std::deque<Path, std::allocator<Path> >&)':
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp:207: error: expected initializer before ':' token
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp:210: error: expected primary-expression before 'return'
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp:210: error: expected ';' before 'return'
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp:210: error: expected primary-expression before 'return'
pgrouting-pgrouting-2.3.0/src/withPoints/src/././../../common/src/basePath_SSEC.hpp:210: error: expected ')' before 'return'
In file included from pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:45:
pgrouting-pgrouting-2.3.0/src/withPoints/src/./msg_logger.hpp: In function 'void PGR_LOG_POINTS(std::ostringstream&, const std::vector<Point_on_edge_t, std::allocator<Point_on_edge_t> >&, const std::string&)':
pgrouting-pgrouting-2.3.0/src/withPoints/src/./msg_logger.hpp:41: error: expected initializer before ':' token
pgrouting-pgrouting-2.3.0/src/withPoints/src/./msg_logger.hpp:47: error: expected primary-expression before '}' token
pgrouting-pgrouting-2.3.0/src/withPoints/src/./msg_logger.hpp:47: error: expected ';' before '}' token
pgrouting-pgrouting-2.3.0/src/withPoints/src/./msg_logger.hpp:47: error: expected primary-expression before '}' token
pgrouting-pgrouting-2.3.0/src/withPoints/src/./msg_logger.hpp:47: error: expected ')' before '}' token
pgrouting-pgrouting-2.3.0/src/withPoints/src/./msg_logger.hpp:47: error: expected primary-expression before '}' token
pgrouting-pgrouting-2.3.0/src/withPoints/src/./msg_logger.hpp:47: error: expected ';' before '}' token
pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp: In function 'int check_points(std::vector<Point_on_edge_t, std::allocator<Point_on_edge_t> >&, std::ostringstream&)':
pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:60: error: expected primary-expression before '[' token
pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:60: error: expected primary-expression before ']' token
pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:60: error: expected primary-expression before 'const'
pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:60: error: expected primary-expression before 'const'
pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:61: error: expected unqualified-id before 'bool'
pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:69: error: expected primary-expression before '[' token
pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:69: error: expected primary-expression before ']' token
pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:69: error: expected primary-expression before 'const'
pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:69: error: expected primary-expression before 'const'
pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:74: error: unable to deduce 'auto' from '<expression error>'
pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:82: error: expected primary-expression before '[' token
pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:82: error: expected primary-expression before ']' token
pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:82: error: expected primary-expression before 'const'
pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:82: error: expected primary-expression before 'const'
pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp: In function 'void eliminate_details_dd(Path&)':
pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:104: error: expected initializer before ':' token
pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:435: error: expected primary-expression at end of input
pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:435: error: expected ';' at end of input
pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:435: error: expected primary-expression at end of input
pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:435: error: expected ')' at end of input
pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:435: error: expected statement at end of input
pgrouting-pgrouting-2.3.0/src/withPoints/src/pgr_withPoints.cpp:435: error: expected '}' at end of input
make[3]: *** [src/withPoints/src/CMakeFiles/withPoints.dir/pgr_withPoints.cpp.o] Error 1
make[3]: Leaving directory `pgrouting-pgrouting-2.3.0/build'
make[2]: *** [src/withPoints/src/CMakeFiles/withPoints.dir/all] Error 2
make[2]: Leaving directory `pgrouting-pgrouting-2.3.0/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `pgrouting-pgrouting-2.3.0/build'
error: Bad exit status from /var/tmp/rpm-tmp.FQNGRq (%build
`

Any comments?

Regards, Devrim

**Comment by cvvergara** [comment]
@devrimgunduz 
The first error is in a Range Loop [link] (https://github.com/pgRouting/pgrouting/blob/master/src/common/src/basePath_SSEC.hpp#L125): 

```
for (const Path &path : paths) {
```

And again the "official" but not enforced g++ is 4.6 (didn't try with something less than that version)
About the flag:
 -std=c++0x 
http://www.stroustrup.com/what-is-2009.pdf
Says that it supports range loops.

Is it possible for you to change the compiler to be at least g++4.6

**Comment by devrimgunduz** [comment]
@cvvergara 

Hi,

Unfortunately that is the GCC in RHEL 6 :-( I'm not a C or C++ or whatever guy, so any compiler switch that can help?

Thanks!

**Comment by woodbri** [comment]
http://stackoverflow.com/questions/25433142/installing-gcc-4-8-2-on-red-hat-enterprise-linux-6-5

See the comments related to devtoolset that offers more recent compilers.

**Comment by devrimgunduz** [comment]
Hi @woodbri ,

Changing the compiler will cause more troubles, I assume, as we build around 150 packages for PostgreSQL yum repo there, so I'm inclined to keep it with the default one.

Regards, Devrim

**Comment by cvvergara** [comment]
@devrimgunduz 
what about RHEL 7 ?
https://access.redhat.com/solutions/19458

**Comment by woodbri** [comment]
On 9/29/2016 2:14 PM, Devrim Gündüz wrote:
> Hi @woodbri <https://github.com/woodbri> ,
>
> Changing the compiler will cause more troubles, I assume, as we build
> around 150 packages for PostgreSQL yum repo there, so I'm inclined to
> keep it with the default one.
>
> Regards, Devrim

Check and see if it replaces or just adds another compiler that you can 
optionally use. If it adds a new one, then you should be able to set the 
GCC and/or CPP variables to point to the new compilers.

I totally understand the mess you can potentially get into using mixing 
and matching packages with a package manager.

If you can't move to the new compiler, then pgRouting 2.3 will probably 
require EL7 releases because that is where the new compiler is released. 
Vicky has done a lot of work to rewrite a lot of code to fix bugs and 
move the source forward to the newer and cleaner compiler idioms and I'm 
sure that there will not be much interest to make the new code also 
support the older compilers once again.

-Steve

---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by devrimgunduz** [comment]
@cvvergara No issues with RHEL 7. I can leave RHEL6 with older pgrouting (2.2) in this case.

Thanks!

**Comment by devrimgunduz** [comment]
@woodbri Right, I'll stick with older pgrouting for RHEL 6, it has more problems already anyway.

Thanks!

**Comment by cvvergara** [comment]
@devrimgunduz 
which 2.2.x ?

**Comment by devrimgunduz** [comment]
2.2.latest?

**Comment by cvvergara** [comment]
2.2.4 is the latest
¿did you re open? or was a miss click?

**Comment by devrimgunduz** [comment]
I'll close it, as I noticed something else now. Thanks!
