### ISSUE TITLE
not find path by pgr_dijkstra

### ISSUE THREAD

**Issue by tanyuabc** [pgRouting/pgrouting#703]
### Expected behavior and actual behavior

SELECT r.id, r.geom, r.name,r.source,r.target, r.length FROM pgr_dijkstra('SELECT id ,source,target,length::double precision as cost,reverse_cost::double precision as reverse_cost FROM vietnamroads',224614,201212,false,false) pd,vietnamroads r where id2=r.id order by pd.seq
### Steps to reproduce the problem

line_locate_point: 1st arg isnt a line ,the   geometry type is MULTILINESTRING and srid is 4326
### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System

Use the commands:
```
"PostgreSQL 9.3.13, compiled by Visual C++ build 1600, 32-bit"
"POSTGIS="2.1.5 r13152" GEOS="3.4.2-CAPI-1.8.2 r3924" PROJ="Rel. 4.8.0, 6 March 2012" GDAL="GDAL 1.11.1, released 2014/09/24" LIBXML="2.7.8" LIBJSON="UNKNOWN" TOPOLOGY RASTER"
"(2.0.0,pgrouting-2.0.0,0,d6ed2cb,master,1.53.0)"
```

i' dot know that data issues ?

**Comment by cvvergara** [comment]
You are using an old pgRouting version 2.0.0.
http://docs.pgrouting.org/2.0/en/src/dijkstra/doc/index.html#pgr-dijkstra
issues on pgr_dikstra were fixed on version 2.1

The latest is version 2.3.1 and has slightly a different signature:
http://docs.pgrouting.org/latest/en/src/dijkstra/doc/pgr_dijkstra.html#pgr-dijkstra
The old Signature is still supported:
http://docs.pgrouting.org/latest/en/src/dijkstra/doc/pgr_dijkstra_v2.html#pgr-dijkstra-v2
