### ISSUE TITLE
Code not available at github gsoc-tdsp branch

### ISSUE THREAD

**Issue by ritwikraj1** [pgRouting/pgrouting#725]
I am trying to install TDSP functionality in pgRouting on my Linux 14.04 system. I was following the steps mentioned in the link:
https://github.com/pgRouting/pgrouting/wiki/TDSP-Tutorial-and-Example

It says we have to install the code from the github gsoc-tdsp branch. But when I look it up on the following link:
https://github.com/pgRouting/pgrouting/tree/gsoc-tdsp

It says "page not found". Could you please help me in that where I can find the code for gsoc-tdsp branch?

Thank you,
Ritwik

**Comment by woodbri** [comment]
On 2/8/2017 11:27 AM, ritwikraj1 wrote:
> I am trying to install TDSP functionality in pgRouting on my Linux 14.04
> system. I was following the steps mentioned in the link:
> https://github.com/pgRouting/pgrouting/wiki/TDSP-Tutorial-and-Example
>
> It says we have to install the code from the github gsoc-tdsp branch.
> But when I look it up on the following link:
> https://github.com/pgRouting/pgrouting/tree/gsoc-tdsp
>
> It says "page not found". Could you please help me in that where I can
> find the code for gsoc-tdsp branch?
>
> Thank you,
> Ritwik

The repository has been reorganized and many of the branches were 
removed, but we kept them as tags. Clone the repository and then you can do:

# list the tags
git tag -l

# checkout the gsoc/tdsp-lw tag
git checkout gsoc/tdsp-lw

-Steve W

---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus
