### ISSUE TITLE
Libraries for Postgresql 9+ on Windows

### ISSUE THREAD

**Issue by djq** [pgRouting/pgrouting#74]
Would it be possible to have libraries built for Postgresql 9+ on Windows? When I tried running the SQL files I got the following error:

>ERROR:  incompatible library "C:/Program Files (x86)/PostgreSQL/9.1/lib/librouting.dll": version >mismatch
>DETAIL:  Server is version 9.1, library is version 8.4.

On Linux, PgRouting is working with Postgresql 9+ and PostGIS 2+. 

Also, I'm not sure where the best location to download windows binaries is. The most recent version on the website http://pgrouting.org/download.html are from two years ago.

Thank you.

**Comment by woodbri** [comment]
Closing - Wont fix.
