### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#749]
Installation and Download instructions are available on more than one place consistency is hard to maintain.

README file
https://github.com/pgRouting/pgrouting/wiki/Notes-on-Download,-Installation-and-building-pgRouting
http://docs.pgrouting.org/2.4/en/doc/src/installation/installation.html
http://docs.pgrouting.org/2.4/en/doc/src/installation/build.html
http://docs.pgrouting.org/2.4/en/doc/src/installation/install-dependencies.html

**Comment by cvvergara** [comment]
Hello @SunveerSingh 
Where did you find these links?
http://docs.pgrouting.org/2.4/en/doc/src/installation/installation.html
http://docs.pgrouting.org/2.4/en/doc/src/installation/build.html
http://docs.pgrouting.org/2.4/en/doc/src/installation/install-dependencies.html

The documentation changed format on 2.4 So those links do not exist on versions >=2.4
https://docs.pgrouting.org/2.4/en/pgRouting-installation.html

**Comment by cvvergara** [comment]
@dkastl 
I like the idea of the wiki page
what do you think?

@SunveerSingh can you check if you can edit the pgrouting wiki?
If not, tell me so I can add you as colaborator

**Comment by cvvergara** [comment]
So, ah I see, where you got the links from
yes they changed, trying to keep a better maintenance
and we are still working on them.

**Comment by SunveerSingh** [comment]
HI @cvvergara I was able to edit the wiki page, and added all the stuff at a single place:
https://github.com/pgRouting/pgrouting/wiki/Notes-on-Download,-Installation-and-building-pgRouting

And now, what we will do with these pages?:
https://github.com/pgRouting/pgrouting/wiki/Download%3A-Debian-and-Ubuntu
https://github.com/pgRouting/pgrouting/wiki/Download%3A-Windows
https://github.com/pgRouting/pgrouting/wiki/Download%3A-RedHat-Fedora-Centos
https://github.com/pgRouting/pgrouting/wiki/Download%3A-FreeBSD-OS-X

**Comment by cvvergara** [comment]
Just leave them there, in case someone has links saved in their history
but, just in case add a line at the top
"This wiki page is no longer mantained, please go to <link to corresponding section> for latest information about the installation"

**Comment by SunveerSingh** [comment]
Done! Added the line on the top: " This wiki page is no longer mantained, please go to for latest information about the installation:https://github.com/pgRouting/pgrouting/wiki/Notes-on-Download,-Installation-and-building-pgRouting "

**Comment by cvvergara** [comment]
Thanks

**Comment by cvvergara** [comment]
lets do it :)
