### ISSUE TITLE
Can't upgrade from 2.3.2 to 2.4.0

### ISSUE THREAD

**Issue by robe2** [pgRouting/pgrouting#762]
### Expected behavior and actual behavior
Should be able to upgrade

but instead get error

```

ERROR:  cannot drop type contraction_vertex because other objects depend on it
DETAIL:  function pgr_fakecontraction(text,integer[]) depends on type contraction_vertex
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
********** Error **********

ERROR: cannot drop type contraction_vertex because other objects depend on it
SQL state: 2BP01
Detail: function pgr_fakecontraction(text,integer[]) depends on type contraction_vertex
Hint: Use DROP ... CASCADE to drop the dependent objects too.


```

### Steps to reproduce the problem
Install pgRouting 2.3.2
and then run:
```

ALTER EXTENSION pgrouting UPDATE TO "2.4.0";

```

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System

Use the commands:
```
SELECT version();
SELECT postgis_full_version();
SELECT pgr_version();
```

**Comment by cvvergara** [comment]
I think pgr_fakecontraction is a leftover of @sankepallyrohithreddy when he developed contraction:
he didn't delete the function
* its undocumented, 
* its useless,
* and its not in 2.4
* that function uses the leftover type he also made: contraction_vertex that
  * its undocumented, 
  * its useless,
  * and its not in 2.4

I'll cascade the dropping of the type

**Comment by cvvergara** [comment]
o maybe is first the function drop and then the type drop

**Comment by cvvergara** [comment]
Was the order of the droping

**Comment by cvvergara** [comment]
@robe2 made the order change on main repo's develop
(jenkins is running now)

**Comment by robe2** [comment]
just tested seems fine now.

**Comment by cvvergara** [comment]
ok, thanks for testing.
will start the release process now
