### ISSUE TITLE
Upgrade Travis CI to use trusty

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#770]
There seems to be a couple of improvements available for Travis CI, for example container-based builds.
Upgrading our `travis.yaml` may come with some advantages.
https://docs.travis-ci.com/user/trusty-ci-environment

See also OSX builds: #409

**Comment by cvvergara** [comment]
Besides precise, i'ts being using trusty from a long time
https://travis-ci.org/pgRouting/pgrouting/jobs/214659128/config
https://travis-ci.org/pgRouting/pgrouting/jobs/214659129/config

**Comment by dkastl** [comment]
Oh, I missed the second entries in the matrix, sorry.

I was mainly thinking to add the initial configuration for OSX as well, then read "precise" and about container-based builds. 
Someone with more knowledge about how to compile pgRouting on Mac (but no knowledge with Travis CI), could fill the missing gaps.

**Comment by cvvergara** [comment]
that is why #409 is pending.
