### ISSUE TITLE
DARP install

### ISSUE THREAD

**Issue by LisaB123** [pgRouting/pgrouting#86]
What a great project!

I have managed to get the project to run on Ubuntu 12.04.1 LTS using the instructions at http://pgrouting.org/docs/1.x/install_ubuntu.html

I am interested in trying out the extra DARP function. Are there instructions anywhere to help for this branch? Do I need to compile the DARP3 branch with any flags set etc?

I am compiling this with a view to trying out OpenVRP.

Thanks

Lisa

**Comment by dkastl** [comment]
DARP is discontinued.
