### ISSUE TITLE
Chinese Postman Problem solver

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#887]
There is an implementation of the Chinese Postman Problem solver available as QGIS plugin.
If this can be done with QGIS, it should also work with pgRouting:

Resources:
* https://plugins.qgis.org/plugins/chinesepostman/
* https://github.com/rkistner/chinese-postman
* https://github.com/rkistner/chinese-postman/blob/master/Algorithm.md

**Comment by dkastl** [comment]
Just adding a link to NetworkX, a Python package for the creation, manipulation, and study of the structure, dynamics, and functions of complex networks: https://networkx.github.io/

**Comment by cvvergara** [comment]
Chinese postman has been added as experimental function on v3.0
Closing the request
