### ISSUE TITLE
make[2]: *** [src/withPoints/src/CMakeFiles/withPoints.dir/many_to_many_withPoints_driver.cpp.o] Error 1 make[1]: *** [src/withPoints/src/CMakeFiles/withPoints.dir/all] Error 2 make: *** [all] Error 2

### ISSUE THREAD

**Issue by zhujunpengguizhou** [pgRouting/pgrouting#888]
[  0%] Built target ProcessSQLFiles
[  0%] Built target build-time-sql-directory
[  1%] Building CXX object src/withPoints/src/CMakeFiles/withPoints.dir/many_to_many_withPoints_driver.cpp.o
In file included from /home/pipelinedb/pipelinedb/include/pipelinedb/server/executor/executor.h:20:0,
                 from /home/pipelinedb/pipelinedb/include/pipelinedb/server/funcapi.h:21,
                 from /home/pipelinedb/pgrouting-2.4.1/src/withPoints/src/./../../common/src/./postgres_connection.h:62,
                 from /home/pipelinedb/pgrouting-2.4.1/src/withPoints/src/./../../common/src/pgr_alloc.hpp:38,
                 from /home/pipelinedb/pgrouting-2.4.1/src/withPoints/src/many_to_many_withPoints_driver.cpp:42:
/home/pipelinedb/pipelinedb/include/pipelinedb/server/nodes/relation.h:740:16: error: redefinition of ‘struct Path’
 typedef struct Path
                ^
In file included from /home/pipelinedb/pgrouting-2.4.1/src/dijkstra/src/./pgr_dijkstra.hpp:40:,
                 from /home/pipelinedb/pgrouting-2.4.1/src/withPoints/src/many_to_many_withPoints_driver.cpp:39:
/home/pipelinedb/pgrouting-2.4.1/src/dijkstra/src/././../../common/src/basePath_SSEC.hpp:42:7:error: previous definition of ‘struct Path’
 class Path {
       ^
In file included from /home/pipelinedb/pipelinedb/include/pipelinedb/server/executor/executor.h:20:0,
                 from /home/pipelinedb/pipelinedb/include/pipelinedb/server/funcapi.h:21,
                 from /home/pipelinedb/pgrouting-2.4.1/src/withPoints/src/./../../common/src/./postgres_connection.h:62,
                 from /home/pipelinedb/pgrouting-2.4.1/src/withPoints/src/./../../common/src/pgr_alloc.hpp:38,
                 from /home/pipelinedb/pgrouting-2.4.1/src/withPoints/src/many_to_many_withPoints_driver.cpp:42:
/home/pipelinedb/pipelinedb/include/pipelinedb/server/nodes/relation.h:756:7: error: invalid type in declaration before ‘;’ token
 } Path;
       ^
/home/pipelinedb/pipelinedb/include/pipelinedb/server/nodes/relation.h:756:7: error: conflicting declaration ‘typedef int Path’
In file included from /home/pipelinedb/pgrouting-2.4.1/src/dijkstra/src/./pgr_dijkstra.hpp:40:,
                 from /home/pipelinedb/pgrouting-2.4.1/src/withPoints/src/many_to_many_withPoints_driver.cpp:39:
/home/pipelinedb/pgrouting-2.4.1/src/dijkstra/src/././../../common/src/basePath_SSEC.hpp:42:7:error: ‘struct Path’ has a previous declaration as ‘struct Path’
 class Path {
       ^
make[2]: *** [src/withPoints/src/CMakeFiles/withPoints.dir/many_to_many_withPoints_driver.cpp.o] Error 1
make[1]: *** [src/withPoints/src/CMakeFiles/withPoints.dir/all] Error 2
make: *** [all] Error 2

how to solve the problem?

**Comment by zhujunpengguizhou** [comment]
In the pgrouting, CMakeList.txt include：
    set(CMAKE_INCLUDE_PATH ${CMAKE_INCLUDE_PATH} "/home/pipelinedb/CGAL-4.10")
    set(CMAKE_LIBRARY_PATH ${CMAKE_LIBRARIE_PATH} "/home/pipelinedb/CGAL-4.10/lib"

~/.bashrc include:
    BOOST_INCLUDE_DIRS="/home/pipelinedb/boost_1_60_0"
    BOOST_LIBRARYDIR="/home/pipelinedb/boost_1_60_0/stage/lib"
    BOOST_ROOT="/home/pipelinedb/boost_1_60_0"

    CGAL_INCLUDE_DIR="/home/pipelinedb/CGAL-4.10"
    CGAL_LIBRARIES="/home/pipelinedb/CGAL-4.10/lib"

cmake command:
    mkdir build
   cd build
   cmake  ..
   make
  sudo make install

dependency: boost-1.60.0 gdal-2.2.1 gmp-6.1.2 pgrouting-2.4.1 proj-4.9.3 CGAL-4.10 geos-3.6.2 json-c mpfr-3.1.5 postgis-2.3.3 pipelinedb-9.5(https://www.pipelinedb.com/)

**Comment by dkastl** [comment]
It seems you're using PipelinDB, a fork of PostgreSQL.
Can you test, if you have the same compile errors with an equivalent installation of PostgreSQL?

**Comment by zhujunpengguizhou** [comment]
may be .   thank you.

**Comment by dkastl** [comment]
PostgreSQL itslef provides binaries for various operating systems and pgRouting, also for CentOS.
I tried to find some build information, which is usually available as `spec` file. Here is one recent example: https://git.postgresql.org/gitweb/?p=pgrpms.git;a=blob;f=rpm/redhat/9.6/pgrouting/master/pgrouting.spec

Not sure this is helpful.

**Comment by zhujunpengguizhou** [comment]
Thank you for you response.
