### ISSUE TITLE
Add Two-Way Astar

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgrouting#89]
Initially received as a patch there is now also a Github repository for the original "Two Way A-Star" algorithm": https://github.com/sroycode/tway

And there is also a fork of pgRouting, which contains the algorithm: https://github.com/sroycode/pgrouting

**Comment by cvvergara** [comment]
I was looking at the code of the link, @woodbri is correct, its the bidirectional A* as we know it in pgRouting.
On I will label pgr_bdAstar for version 2.5  on the rewrite, also have the same options for the heuristics mentioned here:
http://docs.pgrouting.org/2.4/en/src/astar/doc/astar.html#heuristic
I'll close this issue: as it is pgr_bdastar,
and open a new issue mentioning the rewrite expectations.
