### ISSUE TITLE
pgr_ksp not providing all of the shortest paths

### ISSUE THREAD

**Issue by ivanmay** [pgRouting/pgrouting#919]
### Expected behavior and actual behavior

When presented with parallel paths between two nodes (x1, x2), I expect all of them provided that k is big enough to accommodate them all. 

If there are 4 edges between vertices x1 and x2 with a different cost, it appears to return the edge with the smallest cost.
### Steps to reproduce the problem
Create a small table with an id, start and end 
```
CREATE TABLE test(
	id SERIAL PRIMARY KEY,
	from_node int4 NOT NULL,
	to_node int4 NOT NULL
)

INSERT INTO test(from_node, to_node) VALUES
	(1, 2),
	(1, 2),
	(1, 2)
```

Query: 
```
SELECT * FROM pgr_ksp(
	'SELECT
		id,
		from_node as source,
		to_node as target,
		random() *9+ 1 AS cost
	FROM
		test',
	1,
	2,
	10,
	FALSE,
	TRUE
)
```

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System

POSTGRES = PostgreSQL 9.6.3 on x86_64-apple-darwin16.5.0, compiled by Apple LLVM version 8.1.0 (clang-802.0.42), 64-bit

POSTGIS="2.3.2 r15302" GEOS="3.6.2-CAPI-1.10.2 4d2925d6" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 1.11.5, released 2016/07/01" LIBXML="2.9.4" LIBJSON="0.12" RASTER

PGROUTING = (2.4.2,v2.4.2,fb7c27bfc,master,1.64.0)

Running on Mac OS x Sierra: 10.12.4

Use the commands:
```
SELECT version();
SELECT postgis_full_version();
SELECT pgr_version();
```

**Comment by cvvergara** [comment]
You might want to read this issue:
https://github.com/pgRouting/pgrouting/issues/285
and this wiki page:
https://github.com/pgRouting/pgrouting/wiki/Handling-parallels-after-getting-a-path-(pgr_ksp-focus)
Because of the exponential growth of parallel paths, it is left for the user of the function to handle parallel paths.

**Comment by ivanmay** [comment]
That makes sense.

Thanks for the response. Love this library!
