### ISSUE TITLE
Rename License topic in documentation

### ISSUE THREAD

**Issue by lvv83** [pgRouting/pgrouting#932]
Hello.
I spent a little time reading the [documentation](http://docs.pgrouting.org/latest/en/pgRouting-introduction.html#license).

I think that `License` topic may be renamed to `Licensing` or `Licenses`, cause there are many components with different licenses in pgRouting.

Thanks.

**Comment by dkastl** [comment]
@lvv83 , thanks for taking a time to read the documentation thoroughly!
If this was the only issue you had with the content, then we're very reliefed ;-)

`Licensing` sounds reasonable to me. 
@cvvergara , let's change it for the 2.5 RC.

**Comment by lvv83** [comment]
Well, I have yet one issue with license. There is no link to `MIT-X` license.
Should I create new issue about this?
