### ISSUE TITLE
cmake version required version number wrong

### ISSUE THREAD

**Issue by smathermather** [pgRouting/pgrouting#948]
### Expected behavior and actual behavior
When running cmake with version 2.8.12.2, it fails on "continue".

### Steps to reproduce the problem
Install cmake 2.8.12.2 on Ubuntu 14.04. Try to build pgRouting

### Other info
cmake 2.8.12.2 doesn't have "continue" per https://github.com/BioMedIA/MIRTK/issues/197 . README.md could be updates to reflect current minimum for cmake to fix issue.

**Comment by cvvergara** [comment]
cmake 3.2 would be the minimum version of cmake (I think)
That means modify readme, some docs, and the CMakeLists
probably it also needs a new micro release.
@robe2  doing these changes needs imply to make a new micro release?

**Comment by dkastl** [comment]
I agree with @robe2 : let's collect a few more issues until making a 2.5.1 release.

**Comment by smathermather** [comment]
👍
