### ISSUE TITLE
pgr_createtopology create vertex table with null values

### ISSUE THREAD

**Issue by AgrisNikitenko** [pgRouting/pgrouting#957]
### Expected behavior and actual behavior
I am using imported OSM data where tables start with planet_osm......
I am trying to generate topology, with pgr_createTopology, which produces vertexes table:
select pgr_createtopology('my_planet_osm_line',0.001, 'the_geom','id','source','target');
the edges table:
CREATE TABLE public.my_planet_osm_line
(
    id bigint,
    bicycle text COLLATE pg_catalog."default",
    bridge text COLLATE pg_catalog."default",
    highway text COLLATE pg_catalog."default",
    oneway text COLLATE pg_catalog."default",
    tunnel text COLLATE pg_catalog."default",
    the_geom geometry,
    source integer,
    target integer,
    cost double precision,
    reverse_cost double precision
)
The command produces Vertexes table:
CREATE TABLE public.my_planet_osm_line_vertices_pgr
(
    id bigint,
    cnt integer,
    chk integer,
    ein integer,
    eout integer,
    the_geom geometry
)
However in the vertex table all fields except id, and the_geom ar NULL.
Thereby the pgr_dijkstra() returns error - null values found.

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System

Use the commands:
```
SELECT version();
PostgreSQL 9.5.8 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit
SELECT postgis_full_version();
POSTGIS="2.2.1 r14555" GEOS="3.5.0-CAPI-1.9.0 r4084" PROJ="Rel. 4.9.2, 08 September 2015" GDAL="GDAL 1.11.3, released 2015/09/16" LIBXML="2.9.3" LIBJSON="0.11.99" RASTER
SELECT pgr_version();
(2.1.0,pgrouting-2.1.0,1,b38118a,master,1.58.0)

**Comment by dkastl** [comment]
You're using rather old version of pgRouting? Would you be able to upgrade to the latest release?

**Comment by AgrisNikitenko** [comment]
I am not sure since I have rather old version of PostGIS as well.

**Comment by dkastl** [comment]
I would recommend you this recent blog post, which also mentions pgRouting: http://www.bostongis.com/blog/index.php?/archives/268-Using-pg_upgrade-to-upgrade-PostGIS-without-installing-an-older-version-of-PostGIS.html
You usually can upgrade pgRouting just by dropping the extension and create them again.

**Comment by AgrisNikitenko** [comment]
Thanks I will try to do it.

**Comment by cvvergara** [comment]
Create topology does not break up osm geometries.
from the comment I think the importing was not done with osm2pgRouting so the lingsegments were not broken based on intersections.
Will tag as Question and close
