### ISSUE TITLE
Codacy configuration file

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#967]
Codacy tests are new,

Need to have a configuration file

Make codacy to ignore:
- SQL code on the test directory 
 - reason:  some non SQL commands that are posgreSQL commands are used like `\echo`
and because of that its marking merges with problems.

**Comment by dkastl** [comment]
Let's  drop Codacy, if it makes things more complicated.
However, if it's useful and motivates, then let's see how we can make use of it.
