### ISSUE TITLE
Improve code of Class Pgr_allpairs

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#969]
C++ Class Pgr_allpairs starts on Line 91 its a template class

https://github.com/pgRouting/pgrouting/blob/develop/include/allpairs/pgr_allpairs.hpp#L91
Right now it looks like this:
```
template < class G >
class Pgr_allpairs {
   ....
   void floydWarshall(
             G &graph,
             size_t &result_tuple_count,
   Matrix_cell_t **postgres_rows);
   ....
}

....

template < class G >
void Pgr_allpairs< G >::floydWarshall(
        G &graph,
        size_t &result_tuple_count,
        Matrix_cell_t **postgres_rows) {
     <code>
}
```

Change it to look like this:

```
template < class G >
class Pgr_allpairs {
   ....
   void floydWarshall(
             G &graph,
             size_t &result_tuple_count,
   Matrix_cell_t **postgres_rows) {
     <code>
}
```

Tasks: 

- [ ] work on your fork's clone, make sure that you are using the latest `develop` code
```
git checkout upstream/develop
git checkout -b issue969
```
Working per function:
- [ ] Move each function's code inside the Class as in the example above
- [ ] Make sure it compiles locally, and that the tests pass locally
- [ ] Commit (mentioning the function that you moved code) & push
- [ ] Make sure everything works on travis CI, and appveyor CI (you need an account on them)
- [ ] Once the function works go to the next one

Once done moving the code:
- [ ] Commit and make a PR to develop

If you are interested, write in a comment your interest and I will guide you on how to do it.

**Comment by prakashupes** [comment]
@cvvergara Yes, I am interested to improve code. But it looks like, already solved.
