### ISSUE TITLE
FreeBSD bot testing using Bessie and Bessie32

### ISSUE THREAD

**Issue by robe2** [pgRouting/pgrouting#970]
As I mentioned to @cvvergara I created two FreeBSD bots I'm now using for PostGIS testing (they are Virtual box VMs currently hosted on winnie) dubbed

bessie and bessie32.

Bessie is a 64-bit FreeBSD 11.1, cmake 3.9.3, PostgreSQL 10.1, CGAL 4.9_8, Boost 1.65.1, FreeBSD clang version 4.0.0 (tags/RELEASE_400/final 297347)
Bessie32 is same as Bessie except 32-bit FreeBSD 11.1

I'm planning to create folders under ci folder (bessie, bessie32) that will have the scripts they will run.

and trigger those first whenever any commit and then hopefully also in pull requests.

I'll close this out once I'm done.

**Comment by cvvergara** [comment]
@robe2  
Thanks

**Comment by cvvergara** [comment]
@dersvenhesse 
Do you know why we are getting this error?

```
/usr/home/jenkins/workspace/Test_Slave/develop/include/c_common/postgres_connection.h:31:32: warning: pragma diagnostic expected option name (e.g. "-Wundef") [-Wunknown-pragmas]
#pragma GCC diagnostic ignored "-pedantic"
```
Whole execution is here
https://debbie.postgis.net/view/PostGIS/job/Test_Slave/75/consoleFull

**Comment by dersvenhesse** [comment]
Not so spontaneously, I'm afraid. I can try to look into this, but unfortunately time is short at the moment.

**Comment by robe2** [comment]
@cvvergara see my pull request.  I also have it running the pgTap tests.

In order to put it in action, you need to install a github webhook on any pgrouting repo you want them to trigger on.  I'll send you the github webhook via skype since it involves a token secret.

I'm going to work on a job for handling pull requests as well.  The jenkins job I have only handles push requests at moment, though when you set up the webhook, you can go ahead and set it for pull/push/branch creation, since jenkins will just ignore the others for now.
