### ISSUE TITLE
arrays_input developers documentation

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#971]
Write the developers documentation of the following files

https://github.com/pgRouting/pgrouting/blob/develop/src/common/arrays_input.c
https://github.com/pgRouting/pgrouting/blob/develop/include/c_common/arrays_input.h

We use  Doxygen to generate the documentation
http://www.stack.nl/~dimitri/doxygen/

**Comment by codeSG** [comment]
@cvvergara Hi Ma'am, Please assign this to me. I had worked with doxygen a little. Some guidance would be helpful.

**Comment by codeSG** [comment]
Is this already done?? I found the doc for above-mentioned files here, http://docs.pgrouting.org/doxy/2.5/arrays__input_8c.html http://docs.pgrouting.org/doxy/2.5/arrays__input_8h.html 
Does it require any modifications?

**Comment by cvvergara** [comment]
@codeSG 
I have Doxygen set up so that is shows some documentation even if the function is not documented.
That one is not documented.
I will update develop branch soon, need to pump up the version, waiting for the final decision of what will be the next version.
It would be great if you can wait until I do this update to develop branch.

**Comment by codeSG** [comment]
Thanks, Ma'am!! for the information. 👍

**Comment by imshuv** [comment]
I want to work on this , I will be extremely thankful if someone can guide me through it.

**Comment by dkastl** [comment]
@imshuv , have you looked at https://github.com/pgRouting/pgrouting/wiki#development ?
