### ISSUE TITLE
bad lexical cast: source type value could not be interpreted as target

### ISSUE THREAD

**Issue by francot** [pgRouting/pgrouting#992]
### Expected behavior and actual behavior
osm2pgrouting --f /home/franco/workspace/osm/map.osm --dbname routing --username postgres --conf /home/franco/workspace/osm2pgrouting/mapconfig.xml

return:
Testing database connection: routing
database connection successful: routing
Connecting to the database
connection success

Creating tables...
TABLE: ways_vertices_pgr already exists.
TABLE: ways_vertices_pgr already exists.
TABLE: ways_vertices_pgr already exists.
TABLE: ways_vertices_pgr already exists.
Opening configuration file: /home/franco/workspace/osm2pgrouting/mapconfig.xml
    Parsing configuration

Exporting configuration ...
  - Done 
Counting lines ...
  - Done 
Opening data file: /home/franco/workspace/osm/map.osm	total lines: 188862
    Parsing data

bad lexical cast: source type value could not be interpreted as target

### Steps to reproduce the problem:
osm data I use:
(directly download from https://www.openstreetmap.org/)
https://www.dropbox.com/s/z77wrxinbyojiau/map.osm?dl=0

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System
"PostgreSQL 9.5.10 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit"

"POSTGIS="2.2.1 r14555" GEOS="3.5.0-CAPI-1.9.0 r4084" PROJ="Rel. 4.9.2, 08 September 2015" GDAL="GDAL 1.11.3, released 2015/09/16" LIBXML="2.9.3" LIBJSON="0.11.99" TOPOLOGY RASTER"

"(2.1.0,pgrouting-2.1.0,1,b38118a,master,1.58.0)"

**Comment by cvvergara** [comment]
Hello, looks that your issue is about:
osm2pgrouting 
Can you post the issue in https://github.com/pgRouting/osm2pgrouting/issues
Also, make sure that you are using the latest osm2pgrouting version

**Comment by francot** [comment]
Sorry a lot of  tab open!
